### ISSUE TITLE
Calculator : Change the UI of calculator !!

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#10]

**Comment by urvashi-code1255** [comment]
Hi @Vishal-raj-1 I have changed the UI of the calculator. Is there anything more you want to do?

**Comment by Vishal-raj-1** [comment]
Hey @urvashi-code1255, I want scientific calculator !!

**Comment by urvashi-code1255** [comment]
But that's the functionality and this issue has a label of style

**Comment by Vishal-raj-1** [comment]
Yep !! We will do this issue later, once our calculator is ready !!

**Comment by bitaashna** [comment]
Hey @Vishal-raj-1  I would like to contribute to this PR..I will work on turning the given calculator into scientific calculator? Can I start working on it?

**Comment by nandini7637** [comment]
Hey I would like to contribute to this issue, please assign me this . I am a GSSOC participant

**Comment by raveena69** [comment]
I would like to contribute to this issue

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?

**Comment by sarala-2210** [comment]
I would like to contribute to this issue, @Vishal-raj-1 please assign me this . I am a GSSOC participant. Thank you!!

**Comment by Asmita-si** [comment]
I want to work on this issue. Can you please assign it to me? @Vishal-raj-1  @urvashi-code1255
