### ISSUE TITLE
Modify UI of Todo App

### ISSUE THREAD

**Issue by Vedant-Rahane** [Vishal-raj-1/Awesome-JavaScript-Projects#1001]
I would like to modify UI of Todo app and also make it well responsive.

![todo-old](https://user-images.githubusercontent.com/71424483/114751724-23104200-9d73-11eb-8476-545ff214b8b2.png)

@urvashi-code1255 Please assign me this.

**Comment by harshgupta20** [comment]
@Vedant-Rahane Whats the update ?

**Comment by Vedant-Rahane** [comment]
I am working on it. Will make PR today.

**Comment by Vedant-Rahane** [comment]
Sorry, Some work is remaining. I will make PR ASAP.
