### ISSUE TITLE
Fix Calendar project

### ISSUE THREAD

**Issue by Vedant-Rahane** [Vishal-raj-1/Awesome-JavaScript-Projects#1002]
Issues :
- Some part of calendar is hidden and not scrollable. Also background image is not visible.

![calender-full](https://user-images.githubusercontent.com/71424483/114752466-ef81e780-9d73-11eb-8a48-ef8f0ddf1c0d.png)

- Not responsive.

![calender-res](https://user-images.githubusercontent.com/71424483/114752514-ff013080-9d73-11eb-9b2a-1cdaf1fad26f.png)

**Comment by Vedant-Rahane** [comment]
@urvashi-code1255 Please review and assign me this.

**Comment by AnshikaAgrawal5501** [comment]
Hey @Vedant-Rahane I was the one who enhanced its CSS part. Just for your knowledge, the images are already present in the image folder in assets. Someone has changed their names from lower case to upper case and all the images' names start from calendar_  and there are a total of 3 images - logo, back cover, and background.

**Comment by Vedant-Rahane** [comment]
Okay, I will check. Thanks.
I am making this project responsive.

**Comment by harshgupta20** [comment]
@AnshikaAgrawal5501 thankyou so much for this detail, it would help other participants to understand projects better, we appretiate.
