### ISSUE TITLE
Guessing word (Puzzle game)

### ISSUE THREAD

**Issue by Aarti002** [Vishal-raj-1/Awesome-JavaScript-Projects#1006]
This is a kind of puzzle game, in which player would be provided with few attempts for guessing the word .
About game :  -
 - whenever player will click any word from keyboard which must lie in whole statement then their number of  attempts will be decreased but not for any other alphabet which is not in statement
 - when player guesses correct alphabet then it automatically gets filled up at all the places it lies
 
Please assign this project to me!

**Comment by harshgupta20** [comment]
This project is looks similar to word scramble game which is already exist in our project, If you project is different then kindly describe about it more with some screenshot so that we can better understand.

**Comment by Aarti002** [comment]
just now viewed word scramble project, but mine is completely different , basically my project won't provide any hint player has to guess random words which must lie in it, let me share a screenshot

**Comment by Aarti002** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/70666307/114971999-2a326f80-9e9b-11eb-928c-f95201a8bd94.png)
i already guessed few words in this , i hope u get it :) @harshgupta20 
Thank you!

**Comment by harshgupta20** [comment]
@Aarti002 go ahead with it :)

**Comment by harshgupta20** [comment]
PR got merged successfully, thanks for contributing.
