### ISSUE TITLE
DrumKit project feature update - Play Audio on Pressing key

### ISSUE THREAD

**Issue by shivanshugarg12800** [Vishal-raj-1/Awesome-JavaScript-Projects#1011]
## Describe the bug
To play the audio in the DrumKit project on pressing the respective key on the keyboard.

## To Reproduce
1.  By adding the addEventListener functionality on the keys

## Expected behavior
The audio will play when we press the respective key on the keyboard 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Windows
 - Browser: Chrome

**Comment by shivanshugarg12800** [comment]
@Vishal-raj-1 @ridsuteri @urvashi-code1255 Please assign this issue to me under GSSOC'21

**Comment by harshgupta20** [comment]
@shivanshugarg12800 Yes, You can send the PR for this issue.
