### ISSUE TITLE
GIF Image Bug

### ISSUE THREAD

**Issue by Rohan27s** [Vishal-raj-1/Awesome-JavaScript-Projects#1012]
## Describe the bug
The GIF image of Text to Voice Generator is not visible in the Projects section

## Expected behavior
There must be the GIF shown instead of the alt text

## Environment (please complete the following information):
 - OS:Windows-10
 - Browser:Google Crome

## Additional context

I want to solve this issue under GSSOC21.
Please assign me this issue
The Error is as shown in the screenshot:-
![image](https://user-images.githubusercontent.com/74227860/114864817-14776880-9e0f-11eb-9853-498016640060.png)

**Comment by Rohan27s** [comment]
Admins please me this issue I have already solved this issue

**Comment by Rohan27s** [comment]
@harshgupta20 Can you check my Pull request

**Comment by harshgupta20** [comment]
Sure.
