### ISSUE TITLE
Toggle button Error

### ISSUE THREAD

**Issue by Rohan27s** [Vishal-raj-1/Awesome-JavaScript-Projects#1014]
## Describe the bug
The Dark/Light toggle button is not scrolling down while we scroll down through the page and the borders of the buttons are not sticking to the toggle button

## Expected behavior
The toggle button must scroll down while we scroll the page and also the borders of the toggle button must stick to the button

## Environment (please complete the following information):
 - OS: Windows-10
 - Browser: Google Crome

## Additional context
The Problem is mentioned in the screenshot
![image](https://user-images.githubusercontent.com/74227860/114869227-5f47af00-9e14-11eb-9270-0c1e594564d7.png)

I want to work on this issue under GSSOC21 please assign me this issue

**Comment by Rohan27s** [comment]
Admins i have already solved this issue please assign me this issue

**Comment by harshgupta20** [comment]
@Rohan27s Great, You can send the PR for it.

**Comment by Rohan27s** [comment]
@harshgupta20 I have already sent the PR can you check it please. I have solved two issues in one PR #1013

**Comment by harshgupta20** [comment]
@Rohan27s Sure.
