### ISSUE TITLE
About us has gramatically incorrect content. Content needs to be improvised for about us.

### ISSUE THREAD

**Issue by aastha621** [Vishal-raj-1/Awesome-JavaScript-Projects#1015]
## Describe the bug
About us has grammatically incorrect and repetitive content. Content needs to be improvised for about us.

## To Reproduce
I have experience in curating content, I can give a better, crisp and concise content  for About Us section.

## Expected behavior
Grammatically correct and impactful about us content.

**Comment by harshgupta20** [comment]
@aastha621 Go ahead and start working on it.

**Comment by aastha621** [comment]
@harshgupta20 sure, thanks!

**Comment by aastha621** [comment]
> @aastha621 Go ahead and start working on it.

@harshgupta20 I have made the PR. Pls review it. PR #1063
