### ISSUE TITLE
I would like to add "Pickle Rick Raze" game

### ISSUE THREAD

**Issue by Raj142** [Vishal-raj-1/Awesome-JavaScript-Projects#1017]
I will also include difficulty levels such as Easy , Medium , Hard ..
please assign it to me as i am a participant of GSoC'21.

**Comment by 991rajat** [comment]
Add something for reference please I'm not able to get it.

**Comment by Raj142** [comment]
I want to add a project name "Pickle Rick Raze".
in which player has to find the way to solve puzzle and result shows number of step taken by user. 

![jKBaoN](https://user-images.githubusercontent.com/52609526/114983266-06c4f000-9eae-11eb-9d44-d5156e9c8923.jpg)

**Comment by harshgupta20** [comment]
@Raj142 this project already exist. Is there any specific you want to add.

**Comment by Furquan712** [comment]
I would like to work on this issue, will you assign me ?

**Comment by harshgupta20** [comment]
@Furquan712 Since this project already exist, so I have to close this issue.
