### ISSUE TITLE
JavaScript Interest Calculator - Enhancement

### ISSUE THREAD

**Issue by AnshikaAgrawal5501** [Vishal-raj-1/Awesome-JavaScript-Projects#1023]
## Is your feature request related to a problem? Please describe.
No its not a problem. I want to enhance the complete look of the JavaScript Interest Calculator to make it look more attractive.
## Describe the solution you'd like
Currently, the calculator looks too old-fashioned and it's not at all attractive. I would like to change its complete look. **Most importantly, I will make it responsive. Currently, not suitable for small devices.**

Few things I would like to do :
- Add some bootstrap
- Add icons if feel the need (icons give a good look)
- Change the colors 
- Change the font-family
- Will give it a proper background

## Screenshot
![InterestCalculator](https://user-images.githubusercontent.com/56653257/114947123-2b977400-9e6a-11eb-91a1-25a5c364cf33.png)

## Additional context
I am a GSSOC'21 participant and would love to work on this issue.
@Vishal-raj-1 @urvashi-code1255 @ridsuteri @harshgupta20

**Comment by ridsuteri** [comment]
@AnshikaAgrawal5501 go ahead with it :)
