### ISSUE TITLE
Adding styles to Coin-Toss Game

### ISSUE THREAD

**Issue by SilverGraph** [Vishal-raj-1/Awesome-JavaScript-Projects#1024]
Greetings! I am a GSSOC'21 and I would request you to assign me the task of adding styles to the Coin-toss game page.

**Comment by harshgupta20** [comment]
@SilverGraph you send the PR,
Kindly send it within 7days.

**Comment by SilverGraph** [comment]
@harshgupta20 I have opened the PR.
