### ISSUE TITLE
Add paint clone

### ISSUE THREAD

**Issue by rupal11** [Vishal-raj-1/Awesome-JavaScript-Projects#1025]
I would like to add a project similar to paint made using HTML, CSS, and javascript. I have named it Colora. In this we can draw, change brush color, brush size, background color. It also provides features such as undo, redo, delete, save.

**Comment by harshgupta20** [comment]
@rupal11 you can send the PR for the issue, kindly send the PR within 7 days.

**Comment by harshgupta20** [comment]
Your PR has been merged thanks for contributing :)
