### ISSUE TITLE
Two github links in navbar

### ISSUE THREAD

**Issue by vedant-jain03** [Vishal-raj-1/Awesome-JavaScript-Projects#1027]
![bandicam 2021-04-16 10-33-57-271](https://user-images.githubusercontent.com/76901313/114974105-649e0b80-9e9f-11eb-8ebe-670dfeac03ac.jpg)

There are 2 github icon in navbar

**Comment by harshgupta20** [comment]
@vedant-jain03 you send the PR for it, and Kindly send the PR within 7days. or else we need to assign it to another.

**Comment by Krishnapro** [comment]
Hello, 
I am Krishna, participant in GSSoC'21. There are 2 github icon in navbar so please assign me this issue to fixed.
