### ISSUE TITLE
Found duplicate of "Drum kit"

### ISSUE THREAD

**Issue by Raj142** [Vishal-raj-1/Awesome-JavaScript-Projects#1035]
Please assign it to me as a part of GSSoC.

![drum1](https://user-images.githubusercontent.com/52609526/115024414-b1083c00-9edd-11eb-8d70-6c0a695784e5.PNG)
![drum2](https://user-images.githubusercontent.com/52609526/115024417-b2d1ff80-9edd-11eb-98cf-748c4e1bdefc.PNG)

**Comment by 991rajat** [comment]
Already fixed.
