### ISSUE TITLE
Make signup/login page responsive And add validations

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [Vishal-raj-1/Awesome-JavaScript-Projects#1042]
I want to make signup/login page responsive and also want to add validations to it.

[GSSOC'21]

Screenshots:

![login](https://user-images.githubusercontent.com/66208607/115037994-b620b780-9eec-11eb-9516-745051600c33.png)

@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @ridsuteri @991rajat Please assign me this issue.

**Comment by harshgupta20** [comment]
@Bhavya-Sehgal Any Update? Kindly reply within 2 days else I have to close this issue.
