### ISSUE TITLE
Add Lorem Ipsum Generator

### ISSUE THREAD

**Issue by sohini3062** [Vishal-raj-1/Awesome-JavaScript-Projects#1047]
GSSOC 2021
I want to add a lorem ipsum generator which generates a number of paragraphs as needed by the user.
The project I am working on currently looks like this:
![1](https://user-images.githubusercontent.com/64258756/115047864-8ecee800-9ef6-11eb-967c-bbd7450eb6e6.JPG)

**Comment by harshgupta20** [comment]
Merged : )
