### ISSUE TITLE
duplicates of same project

### ISSUE THREAD

**Issue by Muskan-creator** [Vishal-raj-1/Awesome-JavaScript-Projects#1049]
## Describe the bug
Love calculator and live code editor projects are created twice.

## To Reproduce

1. remove duplicate files from projects
2. change html file,add css and javascript

## Expected behavior
remove duplicated projects from html ,css and javascript files.

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

![image](https://user-images.githubusercontent.com/59757988/115055647-57b10480-9eff-11eb-92c0-235c37b31a23.png)

**Comment by Muskan-creator** [comment]
@urvashi-code1255 please assign me this issue

**Comment by 991rajat** [comment]
Already fixed. If you found new one create a new issue.
