### ISSUE TITLE
Add E-commerce items to cart Project

### ISSUE THREAD

**Issue by K-jais** [Vishal-raj-1/Awesome-JavaScript-Projects#1051]
This Project will have some items of the e-commerce website and from that we can add the items to the cart and then place it by getting the total price of all the items.

**Comment by K-jais** [comment]
Please @ridsuteri  review this issue

**Comment by ridsuteri** [comment]
i guess it's similar to issue #792 .. and that's is already assigned !

**Comment by K-jais** [comment]
But sir It's been 13 days and he hasn't come up with a PR.

**Comment by K-jais** [comment]
So if u can assign that issue to me?

**Comment by ridsuteri** [comment]
@K-jais he'll come up with a PR by tomorrow.. and if not we have @Amit366 after him !

**Comment by K-jais** [comment]
Okk

**Comment by ridsuteri** [comment]
since this issue is already present , hence i am closing this now :(
