### ISSUE TITLE
Add Bookmark of sites Project

### ISSUE THREAD

**Issue by K-jais** [Vishal-raj-1/Awesome-JavaScript-Projects#1052]
This project will have the bookmark of the sites and saves that particular website in the home page for that particular user.

**Comment by K-jais** [comment]
Please @ridsuteri  review this issue

**Comment by ridsuteri** [comment]
@K-jais is it similar to issue #492 ?
if not please provide a brief description and gif/screenshots

**Comment by K-jais** [comment]
![Screenshot (2264)](https://user-images.githubusercontent.com/75881393/115345592-a646f300-a1cc-11eb-80f7-9ea1ce6d2c7d.png)

@ridsuteri

**Comment by ridsuteri** [comment]
@K-jais this looks similar to #579 , which is already merged into main ,hence i don't think it's available now :(
