### ISSUE TITLE
[GSSOC'21] Adding a java script slider animator

### ISSUE THREAD

**Issue by anushree71199** [Vishal-raj-1/Awesome-JavaScript-Projects#1054]
I would like to add a project in which there are animations of a navigation bar from all four directions. This navigation bar animation will get called using API. Whenever user clicks the button an animation will take place you can check a sample of this project down below:

https://user-images.githubusercontent.com/59678817/115063181-da8a8d00-9f08-11eb-8b67-78bf9debe64a.mp4

This is slider animation plugin which will have the installation process in it and the brief of what it will do if one includes this in their web pages. Please assign me this project under GSSOC'21 , I would love to contribute in this project. [javascript][gssoc'21]

**Comment by harshgupta20** [comment]
@anushree71199 Any Update? Kindly reply within 2 days else I have to close this issue.

**Comment by anushree71199** [comment]
@harshgupta20 yeah I have created the project but due to my end semester exams it's getting delayed to create a PR. Will create a pull request soon, please try to  understand that due to my exams I am just a bit inactive here. But I will make a PR till 30th april. Thanks

**Comment by anushree71199** [comment]
This issue is almost over, I have created the project and will request a PR soon.
