### ISSUE TITLE
Hexadecimal to RGB colour converter

### ISSUE THREAD

**Issue by Amit366** [Vishal-raj-1/Awesome-JavaScript-Projects#1055]
## Is your feature request related to a problem? Please describe.
No its not a problem. I will add a Hexadecimal to RGB colour converter.
## Describe the solution you'd like
I will be using HTML and JavaScript. 

## Additional context
I am a participant of GSSOC. Please assign it to me

**Comment by Amit366** [comment]
@ridsuteri please assign

**Comment by ridsuteri** [comment]
@Amit366 go ahead with it :)
