### ISSUE TITLE
Sidenav Enhancement

### ISSUE THREAD

**Issue by AnshikaAgrawal5501** [Vishal-raj-1/Awesome-JavaScript-Projects#1057]
## Is your feature request related to a problem? Please describe.
No its not a problem. I wish to enhance the look of sidenav.
## Describe the solution you'd like.
- I feel that sidenav should have some different icons like instead of youtube and google icons we should better use Instagram and Mail icons since they are the means of social connectivity. 
- One more thing I feel to change that when we scroll down the banner area the sidenav still remains in that colour only which makes it look less attractive. 
- I have also noticed that sidenav is not responsive to the theme swapper. Will make it.

![Untitled](https://user-images.githubusercontent.com/56653257/115071768-47575480-9f14-11eb-849c-07639704b989.png)

I think we should make it work something like this.
![screen-capture](https://user-images.githubusercontent.com/56653257/115071825-5b02bb00-9f14-11eb-88ce-f9b4cf9169a5.gif)

Also, the hover effect can be made a little better.

## Additional context
I am a GSSoc'21 participant and would love to work on this issue. Kindly assign me.
@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @ridsuteri

**Comment by AnshikaAgrawal5501** [comment]
@Vishal-raj-1 @urvashi-code1255 @Harshal0902 @ridsuteri 
Please check this issue and assign this to me.
Thanks.

**Comment by ridsuteri** [comment]
@AnshikaAgrawal5501 go ahead with it :)
