### ISSUE TITLE
UI of currency converter

### ISSUE THREAD

**Issue by Ankita297** [Vishal-raj-1/Awesome-JavaScript-Projects#1074]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to enhancing the look of  currency converter
## Additional context
Add any other context about the feature request here.

![Herry Potter _ All charecter - Google Chrome 18-04-2021 08_14_37](https://user-images.githubusercontent.com/67833077/115132776-cb96fe00-a020-11eb-892f-f4cabfe98459.png)
It is not much appealing .

**Comment by Ankita297** [comment]
Can i work on this @ridsuteri @Vishal-raj-1 @urvashi-code1255 ?

**Comment by ridsuteri** [comment]
@Ankita297 similar issue ( #1044 ) is assigned to @Bhavya-Sehgal 
this issue is not available now and hence i am closing it :(
