### ISSUE TITLE
3 github logo issue

### ISSUE THREAD

**Issue by iamabhii1** [Vishal-raj-1/Awesome-JavaScript-Projects#1075]
hii ,i wanted to updated /correct the issue with github logo on index.html file .
and slightly UI change .
please assign this to me .
this contribution is for gssoc21

**Comment by 991rajat** [comment]
What you would like to change please specify.

**Comment by iamabhii1** [comment]
actually there is two link of github on the index.html file 
that i want to correct.

**Comment by harshgupta20** [comment]
@iamabhii1 I haven't found this issue to exist, maybe I couldn't recognize that, it would be better if attach any screenshot of it. Kindly reply within 2 days else I have to close this issue.

**Comment by iamabhii1** [comment]
![Screenshot (16)_LI](https://user-images.githubusercontent.com/68424960/116657520-2e3ab300-a9ac-11eb-89e2-0838305a25ba.jpg)
this part three github link for same repo.

**Comment by abhijeet141** [comment]
@991rajat @harshgupta20  Is anyone working on this issue ? I would like to fix this bug.

**Comment by 991rajat** [comment]
Looks Like Abhimanyu fixed it. Will try to assign you different issue.

**Comment by 991rajat** [comment]
@iamabhii1 Try to find different bug or project.Let any maintainer know, will assign you asap.

**Comment by abhijeet141** [comment]
> @abhijeet141 Try to find different bug or project.Let any maintainer know, will assign you asap.

Okay :)
