### ISSUE TITLE
wanted to remove the redundancy from script file 

### ISSUE THREAD

**Issue by iamabhii1** [Vishal-raj-1/Awesome-JavaScript-Projects#1076]
hi , i wanted to remove the redundancy from script.js  file in this project .
i saw there is repetition in script .js file kindly allow to me correct this issue .
i saw there are some project data that are repeating many times which is causing redundancy in the project and confusion .

please kindly assign this issue to me.
this contribution is for gssoc21

**Comment by 991rajat** [comment]
Already fixed.
