### ISSUE TITLE
Geolocation app

### ISSUE THREAD

**Issue by Sloth-Panda** [Vishal-raj-1/Awesome-JavaScript-Projects#108]
## Is your feature request related to a problem? Please describe.
Yes
## Describe the solution you'd like
Would like to add a geolocation app with proper error handling that will display ur location on a google map
## Additional context
Add any other context about the feature request here.
No

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 would like to work this under cwoc plz assign me

**Comment by abhinav5481** [comment]
Hi,
I would like to work on this issue. Please assign it to me.
