### ISSUE TITLE
Meme Soundboard not producing any sound

### ISSUE THREAD

**Issue by SrishtiArya07** [Vishal-raj-1/Awesome-JavaScript-Projects#1082]
## Describe the bug
No sound is produced when the buttons on the soundboard are clicked.

## Expected behavior
The meme soundboard should play music when the buttons are clicked.

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome

## Additional context
I can fix this issue. Please assign it to me under GSSOC 21.

**Comment by 991rajat** [comment]
It works, when keys are pressed. You could add mouse event to it
Would you like to work on it.

**Comment by SrishtiArya07** [comment]
> It works, when keys are pressed. You could add mouse event to it
> Would you like to work on it?

Yes, I will work on it.  Please assign it to me under gssoc 21.

**Comment by harshgupta20** [comment]
@SrishtiArya07 Go ahead : )

**Comment by Ankita297** [comment]
Can i work on this  @ridsuteri @harshgupta20 @991rajat ?

**Comment by harshgupta20** [comment]
@SrishtiArya07 Any update? Kindly reply within 2 days or else I have to assign it to @Ankita297 .

**Comment by Ankita297** [comment]
Can i work on this now @harshgupta20 @ridsuteri ?

**Comment by Ankita297** [comment]
@ridsuteri @harshgupta20 Can i work on this ?

**Comment by Ankita297** [comment]
@ridsuteri @harshgupta20 Can i work on this ?

**Comment by harshgupta20** [comment]
@Ankita297 Yes, You can work on this :)
