### ISSUE TITLE
Local-Storage

### ISSUE THREAD

**Issue by Meghag5** [Vishal-raj-1/Awesome-JavaScript-Projects#109]
## Describe the solution you'd like
In this project it will help us to create menu and add items in this list.

## Additional context
Add any other context about the feature request here.
It is very useful for daily routine if we are going to do shopping and have long list to remember.

**Comment by Meghag5** [comment]
@urvashi-code1255 pls add the tags and assign it to me.

**Comment by urvashi-code1255** [comment]
@Meghag5 go for it!!
