### ISSUE TITLE
Duplicate images in Javascript Drumkit project 

### ISSUE THREAD

**Issue by tend2infinity** [Vishal-raj-1/Awesome-JavaScript-Projects#1092]
## Describe the bug
The same image is used twice in that project which seems misleading.

## Expected behavior
There should be only one image in that and I will remove the duplicate image from the DOM

## Screenshot
![awesome-javascript-bug3](https://user-images.githubusercontent.com/61948033/115152931-00429e00-a091-11eb-8c72-65b159863f79.JPG)

**Comment by 991rajat** [comment]
@tend2infinity This is good starter problem, I already assigned you 1-2 issue I think,
Are you okay  with this If I assign this to someone new, He is first time contributor.
If not let me know I'll assign it to you.

**Comment by tend2infinity** [comment]
@991rajat If you think its a level 1 issue then sure, you can assign that to a beginner. But if you feel its a level 2 kindly assign that to me, I'm in search of some valuable points!

**Comment by 991rajat** [comment]
It's a level 0 issue  
Just need to remove the duplicate section I think. So that's why

**Comment by 991rajat** [comment]
I'm assigning this you @codDoc98.

**Comment by codDoc98** [comment]
> I'm assigning this you @codDoc98.

yay!!! will do @991rajat

**Comment by codDoc98** [comment]
> I'm assigning this you @codDoc98.

but how do we find the project in which this bug is?

**Comment by 991rajat** [comment]
It's drumkit project. Look out in script.js Then find the html file. @codDoc98

**Comment by 991rajat** [comment]
@codDoc98 An updates? If not want work will assign to someone else let me know

**Comment by codDoc98** [comment]
@991rajat  doing it nowwwwwwwww

**Comment by codDoc98** [comment]
@991rajat  i don't know if this is the way we do pull and merge in gitHub .   GitHub guided me all these steps and i did it . Please check and let me see myself in leaderboard too.

**Comment by 991rajat** [comment]
Good Work No worries. You did good.
