### ISSUE TITLE
Netflix clone UI fix

### ISSUE THREAD

**Issue by tend2infinity** [Vishal-raj-1/Awesome-JavaScript-Projects#1093]
## Describe the bug
The movie cards shown in this project are aligned vertically which does not seem good for UI.

## Expected behavior
I will align them horizontally with proper responsiveness

## Screenshot
![awesome-javascript-bug4](https://user-images.githubusercontent.com/61948033/115153072-9eceff00-a091-11eb-9dfc-a88bcc9eee83.JPG)

**Comment by 991rajat** [comment]
It is fixed. If you want to improve or modify create a new issue will be happy to assign you.
