### ISSUE TITLE
Enhancement in URL Shortner

### ISSUE THREAD

**Issue by yashikabhargava** [Vishal-raj-1/Awesome-JavaScript-Projects#1105]
**Is your feature request related to a problem? Please describe.**
URL Shortner

**Describe the solution you'd like**

change in size and font-style of the text.
Change in shape of button.
Change in the background color, alignment to the center.
Addition of theme.
Improvement in UI.

**Additional Context**
I want to work on this issue, can you please assign this issue to me as a part of gssoc21.
@urvashi-code1255 @Vishal-raj-1  @991rajat @harshgupta20

**Comment by yashikabhargava** [comment]
@urvashi-code1255  @991rajat @ridsuteri  I want to work on this issue, can you please assign this issue to me as a part of gssoc21.

**Comment by Ankita297** [comment]
Can i work on this @ridsuteri  @harshgupta20 @991rajat ?

**Comment by harshgupta20** [comment]
@yashikabhargava Any update? Kindly reply within 2 days or else I will assign it to @Ankita297 .

**Comment by yashikabhargava** [comment]
@harshgupta20 yes I'm working on it ,got delayed because of my exams.

**Comment by harshgupta20** [comment]
@yashikabhargava No problem, plz give any timeline so that it would good enough for the issue, to not to take too much time on this.

**Comment by ridsuteri** [comment]
> It's done. These are the improvements that I have done. Can I make a PR?
> 
> ![urlshortner](https://user-images.githubusercontent.com/76060661/119537804-0f132380-bda8-11eb-9add-7f3d3155fa6c.PNG)
> 
> ![url](https://user-images.githubusercontent.com/76060661/119537829-15a19b00-bda8-11eb-9327-1191476b9e31.PNG)

yes go ahead make a pr
