### ISSUE TITLE
Login Credential App

### ISSUE THREAD

**Issue by diptendunandi** [Vishal-raj-1/Awesome-JavaScript-Projects#111]
## App Description
It will add an authentication process so that anyone can not access the content which will increase the security of any system.

## Solution
Making of Login and Password App

**Comment by Vishal-raj-1** [comment]
@diptendunandi Go ahead !! Looking forward to your PR !!

**Comment by diptendunandi** [comment]
$ git push -u origin login
ssh: Could not resolve hostname github.com:Vishal-raj-1: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Can anyone please tell me where am I wrong?

**Comment by urvashi-code1255** [comment]
Hey @diptendunandi You haven't forked the repo!

follow the guidelines given in readme!

**Comment by diptendunandi** [comment]
Thanks, @urvashi-code1255. Login Feature is open for the pull request.

**Comment by diptendunandi** [comment]
I have done some changes to the code. Please pull the request @Vishal-raj-1 and @urvashi-code1255

**Comment by Vishal-raj-1** [comment]
@diptendunandi It contains merge conflicts, Please resolve it !! Rest is fine.

**Comment by harshgupta20** [comment]
@diptendunandi Any update ? Kindly reply within 2 days or I have to close this.
