### ISSUE TITLE
Mario-run project

### ISSUE THREAD

**Issue by Abhijay007** [Vishal-raj-1/Awesome-JavaScript-Projects#112]
Mario-run game project using vanilla javascript inspired by chorme dino-run game:

![mario-run](https://user-images.githubusercontent.com/64387054/108199945-be09e880-7143-11eb-9a87-84c51074c129.gif)

I made this project during hacktoberfest 2020, in this project I use javascript DOM and CSS keyframes(for animations) which may help a beginner to understand these concepts in more detail.

**Comment by TidbitsJS** [comment]
@Abhijay007, stupendous creation. Awesome!

**Comment by Abhijay007** [comment]
> @Abhijay007, stupendous creation. Awesome!

@TidbitsJS thanks!!
