### ISSUE TITLE
Enchancing the visual of TODO App

### ISSUE THREAD

**Issue by kanisshka** [Vishal-raj-1/Awesome-JavaScript-Projects#1122]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to enhancing the look of TODO APP.

## Additional context
Screenshot related to that stuff.
![image](https://user-images.githubusercontent.com/76627599/115447906-a7146f00-a236-11eb-881b-c32bcab3ad97.png)

**Comment by Vedant-Rahane** [comment]
Hey, @kanisshka I have modified the Todo app project. Please check PR #1069 
If you want to improve it further you can go ahead, just wanted to tell you that this visual is changed.

**Comment by kanisshka** [comment]
> Hey, @kanisshka I have modified the Todo app project. Please check PR #1069
> If you want to improve it further you can go ahead, just wanted to tell you that this visual is changed.

oh oky thank uh for this info.
