### ISSUE TITLE
New Project - Animated Background

### ISSUE THREAD

**Issue by AnshikaAgrawal5501** [Vishal-raj-1/Awesome-JavaScript-Projects#1144]
## Is your feature request related to a problem? Please describe.
No its not a problem. I would like to add a new project called Animated Background.
## Describe the solution you'd like
There will be colorful boxes and stars floating in the upward direction.

## Additional context
I am a gssoc21 participant and would like to work on this issue. Please assign me this.

@Vishal-raj-1 @urvashi-code1255 @ridsuteri @harshgupta20 @991rajat

**Comment by 991rajat** [comment]
Describe more, any preview you could show would be helpfull.

**Comment by AnshikaAgrawal5501** [comment]
Hey @991rajat ,
This is what I wish to add as a new Project. Please do let me know if you feel to change anything in the animation or add something more. Due to the blur screen recording, starts are not properly visible, sorry for that.
Thanks.

![screen-capture](https://user-images.githubusercontent.com/56653257/115967202-dc7ace80-a54e-11eb-8e07-10fed36e414c.gif)

**Comment by AnshikaAgrawal5501** [comment]
@Vishal-raj-1 @urvashi-code1255 @991rajat @harshgupta20 @ridsuteri 
Please assign me the issue.

**Comment by harshgupta20** [comment]
@AnshikaAgrawal5501 Go ahead :)
