### ISSUE TITLE
Add Custom Countdown Project

### ISSUE THREAD

**Issue by K-jais** [Vishal-raj-1/Awesome-JavaScript-Projects#1147]
This project will set a reminder for a particular date and then it will just get saved in local storage. And when it's time to give you the reminder, it will just give you the message.

Its working video,

https://user-images.githubusercontent.com/75881393/115790307-24311700-a3e4-11eb-8c97-9561ac87892f.mp4

**Comment by K-jais** [comment]
Please @ridsuteri @urvashi-code1255 review this issue.

**Comment by harshgupta20** [comment]
merged : )
