### ISSUE TITLE
Task list [GGSOC 21]

### ISSUE THREAD

**Issue by Deeksha-Rawat** [Vishal-raj-1/Awesome-JavaScript-Projects#1148]
please assign it to me under GGSOC'21.

![task list](https://user-images.githubusercontent.com/50552823/115826189-1f8e5200-a428-11eb-8684-3d5bb9c2c708.gif)

**Comment by 991rajat** [comment]
It's like to-do list right?
Which is already present. If you want to add new feature to it let me know will assign it to you.

**Comment by harshgupta20** [comment]
@Deeksha-Rawat Kindly reply within 2 days else I have to close this issue.
