### ISSUE TITLE
Let's draw

### ISSUE THREAD

**Issue by TidbitsJS** [Vishal-raj-1/Awesome-JavaScript-Projects#116]
### Drawing App
A simple yet elegant drawing app with three - colors & brushes with an eraser  

### Proposal
The goal is to learn how to draw with the mouse using Canva in JS

### Event
Participating as a part of GSSOC

### Demo
![draw](https://s2.gifyu.com/images/cinnamon-20210217-3.gif)

**Comment by TidbitsJS** [comment]
Let me create a PR for this. Do assign!

**Comment by Vishal-raj-1** [comment]
It will be great project @TidbitsJS 😃

**Comment by TidbitsJS** [comment]
> It will be great project @TidbitsJS

Thank you so much @Vishal-raj-1
