### ISSUE TITLE
Stopwatch isn't looking that much vibrant

### ISSUE THREAD

**Issue by kanisshka** [Vishal-raj-1/Awesome-JavaScript-Projects#1161]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to enhancing the look of stopwatch.

## Additional context

screenshot is attached.
![image](https://user-images.githubusercontent.com/76627599/115891898-3f4b6780-a474-11eb-99ed-c5b23909264d.png)

**Comment by 991rajat** [comment]
Yes you can change UI of it. Make it good.

**Comment by kanisshka** [comment]
> Yes you can change UI of it. Make it good.

sure
I'll try my best.

**Comment by kanisshka** [comment]
@991rajat hello sir i didn't know why but i'm not able to commit my changes to repo it's showing error
![image](https://user-images.githubusercontent.com/76627599/116124215-a1f56b00-a6e1-11eb-90f0-77dc2562f768.png)

**Comment by kanisshka** [comment]
@991rajat can you plz help on i tried multiple times still i didn't know why it's showing same error.

![image](https://user-images.githubusercontent.com/76627599/116132855-a9217680-a6eb-11eb-9322-94ed87bd9fa0.png)
