### ISSUE TITLE
Add a Brick Breaker game with sounds

### ISSUE THREAD

**Issue by Shivangi-ch** [Vishal-raj-1/Awesome-JavaScript-Projects#1164]
## Is your feature request related to a problem? Please describe.
No its not a problem. It is a new project.
## Describe the solution you'd like
I would like to add Brick breaker game with music  implemented in javascript. 

## Additional context
I am a GSSOC participant. 
Please assign this to me.
@Vishal-raj-1

**Comment by 991rajat** [comment]
Hey @Shivangi-ch It was implemented earlier but now its broken 
Name is Breakout.
What you could do is replace that one with yours new one.
