### ISSUE TITLE
Updating documentation

### ISSUE THREAD

**Issue by kumarankm** [Vishal-raj-1/Awesome-JavaScript-Projects#1167]
## Is your feature request related to a problem? Please describe.
Yes, I think we can add one more command in the contribution guideline to make individual repo be updated(forked repository).
## Describe the solution you'd like
By doing this, Even if the project gets deleted from the local computer, next time while we are cloning it will be easy for the contributor to get a flow.
![Untitled](https://user-images.githubusercontent.com/60292723/115948412-def80c80-a4eb-11eb-96b1-de1c054bb511.png)

## Additional context
Assign me this issue under GSSOC' 21!

**Comment by Furquan712** [comment]
i am Gssoc 21 participant . I would like to work on this , Will you assignee me

**Comment by harshgupta20** [comment]
@Furquan712 Go ahead :)

**Comment by harshgupta20** [comment]
Issue Closed
