### ISSUE TITLE
[GSSOC'21] Random name generator 

### ISSUE THREAD

**Issue by Tanya933** [Vishal-raj-1/Awesome-JavaScript-Projects#1180]
I would like to work on this issue .Please assign this issue to me .Thankyou

**Comment by 991rajat** [comment]
How would it work?
from where you would you get names?

**Comment by Tanya933** [comment]
I will hardcode a list of first and last names and then by using math function i will pick randoms indices of the lists.And by combining the those indices of first and last name ,will generate random names for the users.
User will have an option to generate upto 20 names at a time.
