### ISSUE TITLE
Adding Validations to contact form

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [Vishal-raj-1/Awesome-JavaScript-Projects#1185]
I want to work on this issue as  GSSOC'21 participant

[GSSOC'21] 

@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @ridsuteri Please assign me this issue

**Comment by ridsuteri** [comment]
@Bhavya-Sehgal can you explain the issue?

**Comment by Bhavya-Sehgal** [comment]
> @Bhavya-Sehgal can you explain the issue?
I want to add validations to the form in contact section so that the form is not going to submit until the user doesn't enter all the details.
