### ISSUE TITLE
Drum-kit using javascript 

### ISSUE THREAD

**Issue by bishalshaw-164** [Vishal-raj-1/Awesome-JavaScript-Projects#1199]
This is a simple project developed using javascript data-key, dom-manipulation and CSS animation In this project, seven button are there by clicking each button a sound would be played. This is an interesting project for listening to self-made drum tunes.

**Comment by 991rajat** [comment]
@bishalshaw-164 Drum Kit Already Present in our code base. Checkout out If you want to modify it. Let me know will assign it you.

**Comment by Ankita297** [comment]
Can i work on this  @ridsuteri @harshgupta20 . I will modify it further .

**Comment by harshgupta20** [comment]
@Ankita297 Can you describe the changes you want to make ?

**Comment by Ankita297** [comment]
@harshgupta20  right now there is only mouse clicking option we can key board event listener and also image is small we can enhnace the image and we can add some animation to button when it get clicked .

**Comment by Ankita297** [comment]
So can i work on this @ridsuteri ?

**Comment by Ankita297** [comment]
Can i work on this @ridsuteri Sir ?

**Comment by ridsuteri** [comment]
@Ankita297 keypress events are active on this project so if you want to improvise the project on any other basis please give a brief description of the changes you are going to make also if possible please share img/gifs :)

**Comment by Ankita297** [comment]
@ridsuteri Sir you can check previously if keypress event occurs there is no animation in button and also theme toggler button does not work and it is not mobile responsive 


https://user-images.githubusercontent.com/67833077/119236102-39b86e80-bb53-11eb-8685-9499b9fde1bd.mp4

**Comment by ridsuteri** [comment]
ok got it @Ankita297 , go ahead :)
