### ISSUE TITLE
ECOMMERCE WEBSITE WITH  (HTML,CSS AND JAVASCRIPT)

### ISSUE THREAD

**Issue by Mrinal81** [Vishal-raj-1/Awesome-JavaScript-Projects#1215]
Want to add a e-commerce website project....

PLEASE ASSIGN ME THIS ISSUE....

**Comment by Mrinal81** [comment]
@ridsuteri Hava a look on this issue...

**Comment by anushka-srivastava22** [comment]
Can I work upon this issue as I would love doing it. please assign me

**Comment by Mrinal81** [comment]
@anushka-srivastava22 currently I am working on it...

**Comment by Mrinal81** [comment]
@ridsuteri @991rajat I made a PR of ECOMMERCE WEBSITE........

Please have a look on it and Add Level Tag as well as GSSOC'21 Tag................

**Comment by Mrinal81** [comment]
@ridsuteri @991rajat  have a look on this PR #1335 ....
