### ISSUE TITLE
Add Brick Breaker game

### ISSUE THREAD

**Issue by K-jais** [Vishal-raj-1/Awesome-JavaScript-Projects#1227]
It's a brick breaker game with the scores and lives of the player.

Its working video,

https://user-images.githubusercontent.com/75881393/116279175-db42df00-a7a4-11eb-9bd6-27771587aec0.mp4

**Comment by K-jais** [comment]
Please @ridsuteri @urvashi-code1255 @991rajat review this issue.

**Comment by 991rajat** [comment]
Please don't create PR without assiging it you,
Someone else was also working, It's become difficult to manage

**Comment by K-jais** [comment]
@991rajat I haven't created the PR. Please check once again. It must be someone else.

**Comment by K-jais** [comment]
@991rajat I think this is an issue. Correct me if am wrong.

**Comment by 991rajat** [comment]
Ok Sorry for this, Actually someone is working on this too,
So once it resolves this will assign it to you.

**Comment by K-jais** [comment]
Sir @991rajat, can u please review issue #1239?

**Comment by 991rajat** [comment]
@K-jais Breakout is the name of the game, Just remove the old code add your new code there.
