### ISSUE TITLE
About us section is looking very bad

### ISSUE THREAD

**Issue by arpit456jain** [Vishal-raj-1/Awesome-JavaScript-Projects#1228]
## Describe the bug

It is looking like this.
<img width="960" alt="about currently" src="https://user-images.githubusercontent.com/55352601/116387863-e0516e00-a838-11eb-9cd5-a0a9a193e7b0.png">

which is very bad

## Expected behavior

It should look like this
<img width="960" alt="about must be" src="https://user-images.githubusercontent.com/55352601/116387949-f65f2e80-a838-11eb-8ce5-df08a1b6d5d5.png">

**Comment by 991rajat** [comment]
It's fixed by older issue.
