### ISSUE TITLE
bug in contact us page

### ISSUE THREAD

**Issue by arpit456jain** [Vishal-raj-1/Awesome-JavaScript-Projects#1229]
## Describe the bug

<img width="960" alt="bug in contact" src="https://user-images.githubusercontent.com/55352601/116388315-53f37b00-a839-11eb-99d4-d9e4e0939999.png">

**Comment by 991rajat** [comment]
Fix it please.

**Comment by arpit456jain** [comment]
@991rajat kindly review my PR and add suitable labels to issue and my PR

**Comment by arpit456jain** [comment]
@991rajat
