### ISSUE TITLE
sidenav project updation

### ISSUE THREAD

**Issue by shreyasingh7673** [Vishal-raj-1/Awesome-JavaScript-Projects#123]
#121  I
###
![SIDENAV](https://user-images.githubusercontent.com/72204395/108244667-713f0580-7175-11eb-8119-4a7879212105.png)
![Uploading ### ### `SIDENAV2.png…]()`
![SIDENAV2](https://user-images.githubusercontent.com/72204395/108244998-d09d1580-7175-11eb-9b4a-3dfe51bbe526.png)

I want to add animation to sidenav.

**Comment by shreyasingh7673** [comment]
can I do this as a cwoc and gssoc participant.

**Comment by asimaries** [comment]
I would like to work on this

**Comment by shreyasingh7673** [comment]
@urvashi-code1255  I have made PR. Do check and please give feedback.

**Comment by harshgupta20** [comment]
@shreyasingh7673 Any update ? Kindly reply within 2 days or I have to close this.
