### ISSUE TITLE
Project idea : Balloon and Brick game

### ISSUE THREAD

**Issue by AkanchhaBhadani** [Vishal-raj-1/Awesome-JavaScript-Projects#1232]
I want to design a game using javascript.
Game idea: Basically balloon type structures along with bricks would be drifting out from the bottom of the screen. There would be a dart present in one corner of screen which would move vertically only. Pressing a key would allow the dart to be shot. If it shoots a balloon then player gets point. If it hits the brick the brick gets collected at some other row on screen having a fixed height. Similarly, for all the balloons missed there would be a collection. If maximum number of hit bricks or left out balloons is reached the game is over.

I would like to work on this. @Vishal-raj-1  Please assign me this issue. I am GSSOC21 participant.  

![sample_image](https://user-images.githubusercontent.com/45426812/116424473-2c170e00-a85f-11eb-8387-ee67d9eb7a82.jpeg)

**Comment by AkanchhaBhadani** [comment]
@991rajat please see if I could work on it.

**Comment by 991rajat** [comment]
I remember this game. Nostalgia
 Go Ahead

**Comment by harshgupta20** [comment]
@AkanchhaBhadani Any update? Kindly reply within 2 days or else we have to close this issue due to inactivity.

**Comment by AkanchhaBhadani** [comment]
Yes, I am working on the issue. It's almost done. I will give updates by evening.
