### ISSUE TITLE
Add Budget App

### ISSUE THREAD

**Issue by K-jais** [Vishal-raj-1/Awesome-JavaScript-Projects#1239]
It's a budget app that takes care of your expenses and shows the details of the items on which you have to spend your money.

Its working video,

https://user-images.githubusercontent.com/75881393/116507299-a174f400-a8dc-11eb-9ae0-7df9dfb38290.mp4

**Comment by K-jais** [comment]
Please @ridsuteri @urvashi-code1255 @991rajat review this issue.

**Comment by ridsuteri** [comment]
@K-jais someone is already working on this issue,will  get back to you in couple of days!

**Comment by K-jais** [comment]
I am asking for this budget app.

**Comment by K-jais** [comment]
@ridsuteri not that brick breaker game as now I know someone is working on it. But please look into this budget app issue.

**Comment by K-jais** [comment]
@ridsuteri This is a budget app and I have attached the wokring video of it.

**Comment by ridsuteri** [comment]
> @ridsuteri This is a budget app and I have attached the wokring video of it.

@K-jais another budget app issue is also open! let's wait for it

**Comment by 991rajat** [comment]
Let's merge this one, will Tell other to replace it.
