### ISSUE TITLE
Character Counter in Javascript

### ISSUE THREAD

**Issue by neha07kumari** [Vishal-raj-1/Awesome-JavaScript-Projects#1245]
I would like to add a project which counts the character in JavaScript under GSSOC 2021.

**Comment by neha07kumari** [comment]
Please assign me this issue @ridsuteri @991rajat @Vishal-raj-1

**Comment by 991rajat** [comment]
@neha07kumari Already Present named word counter.
There's a PR if he didn't respond in 1 day I could assign it to you Look at it if you are able to work at it let me know
https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/1119

**Comment by 991rajat** [comment]
@neha07kumari This is already been resolved.I'm closing this one.
I'm assigning a new issue to you.
