### ISSUE TITLE
Currency Converter with HTML,CSS AND JAVASCRIPT 

### ISSUE THREAD

**Issue by Mrinal81** [Vishal-raj-1/Awesome-JavaScript-Projects#1250]
I AM A GSSOC'21 PARTICIPANT. I WANT TO MAKE CURRENCY CONVERTER WITH HTML,CSS AND JAVASCRIPT ...

PLEASE ASSIGN ME THIS ISSUE.....

**Comment by Mrinal81** [comment]
@ridsuteri @991rajat @harshgupta20  PLEASE HAVE A LOOK ON THIS ISSUE...

**Comment by ridsuteri** [comment]
@Mrinal81 there are already two currency converters available in the project ! and I don't think it's open now , hence closing it :(

**Comment by Mrinal81** [comment]
Ok
