### ISSUE TITLE
COVID-19 WEBSITE with HTML,CSS AND JAVASCRIPT 

### ISSUE THREAD

**Issue by Mrinal81** [Vishal-raj-1/Awesome-JavaScript-Projects#1257]
I am a GSSOC'21 Participant. I would like to add  COVID-19 WEBSITE on your project Page. This website aware us like what are the symptoms of Corona ..... How to fight with Corona......

@ridsuteri @991rajat @harshgupta20 PLEASE have a look on this issue..

PLEASE ASSIGN ME THIS ISSUE.....

**Comment by ridsuteri** [comment]
sounds great @Mrinal81 ! go ahead with it :)

**Comment by Mrinal81** [comment]
@ridsuteri kindly have a look on PR #1254

**Comment by Mrinal81** [comment]
I made a PR OF Restaurant website...kindly have a look on it..

**Comment by ridsuteri** [comment]
@Mrinal81 done :)

**Comment by Mrinal81** [comment]
@ridsuteri @991rajat @harshgupta20 ...... Please have a look on PR #1300 ...........

Please add Level Tag as well as GSSOC'21 Tag if everything is ok..........
