### ISSUE TITLE
Contact Now button is breaking, Three github icon.

### ISSUE THREAD

**Issue by RuchiGitHu** [Vishal-raj-1/Awesome-JavaScript-Projects#1262]
## Describe the bug
The Contact now button broken in two parts. Also in the landing page, right side of navbar, three github icon is there with same information.

## To Reproduce
1. Go to website.
2. Scroll down to "let's get started".
3. See the bug.

## Expected behavior
It should be in sequential format. And the Github icon should be one.

## Logs
Na

## Environment (please complete the following information):
 - OS: windows 10
 - Browser: Chrome

## Additional context
![image](https://user-images.githubusercontent.com/71754179/116814695-da7cc500-ab77-11eb-96c9-0ffbf5f4e040.png)
![image](https://user-images.githubusercontent.com/71754179/116814730-f1231c00-ab77-11eb-8c59-eefc35058df7.png)
![image](https://user-images.githubusercontent.com/71754179/116814747-fbddb100-ab77-11eb-821c-f2f815a9511c.png)

**Comment by RuchiGitHu** [comment]
Please assign this issue to me @ridsuteri 
Also please let me know if images is visible to you in PR.

**Comment by ridsuteri** [comment]
@RuchiGitHu i am able to see the images in your PR which seems a bug, but when i am checking site on my browser it looks normal to me...
![Screenshot (52)](https://user-images.githubusercontent.com/59795822/116815930-8543b200-ab7d-11eb-87d5-80bde55c37e3.png)

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu i am able to see the images in your PR which seems a bug, but when i am checking site on my browser it looks normal to me...
> ![Screenshot (52)](https://user-images.githubusercontent.com/59795822/116815930-8543b200-ab7d-11eb-87d5-80bde55c37e3.png)

Please let me clear if I am opening website in wrong manner.
I were opened https://vishal-raj-1.github.io/Awesome-JavaScript-Projects/ in Chrome and attached screenshots of bug. After your previous comment I Switched browser to bing and showing same error.
![image](https://user-images.githubusercontent.com/71754179/116816471-ab6a5180-ab7f-11eb-86ef-6928440450aa.png)

Note : Doing all this in Laptop.
Looking forward for your reply.
thanks in advance...

**Comment by ridsuteri** [comment]
> > @RuchiGitHu i am able to see the images in your PR which seems a bug, but when i am checking site on my browser it looks normal to me...
> > ![Screenshot (52)](https://user-images.githubusercontent.com/59795822/116815930-8543b200-ab7d-11eb-87d5-80bde55c37e3.png)
> 
> Please let me clear if I am opening website in wrong manner.
> I were opened https://vishal-raj-1.github.io/Awesome-JavaScript-Projects/ in Chrome and attached screenshots of bug. After your previous comment I Switched browser to bing and showing same error.
> ![image](https://user-images.githubusercontent.com/71754179/116816471-ab6a5180-ab7f-11eb-86ef-6928440450aa.png)
> 
> Note : Doing all this in Laptop.
> Looking forward for your reply.
> thanks in advance...

@RuchiGitHu this seems a bug !
maybe i am unable to see it bcz of my screen size or any other reason
hence i am assigning you the issue
