### ISSUE TITLE
Fix Images of project and remove duplicate

### ISSUE THREAD

**Issue by 991rajat** [Vishal-raj-1/Awesome-JavaScript-Projects#1269]
1. Remove Duplicate 
![image](https://user-images.githubusercontent.com/38184186/116890259-0d43bd80-ac4b-11eb-98a8-eb9afa420831.png)
2. Fix Images of Image Gallery and Document to Handwriting
![image](https://user-images.githubusercontent.com/38184186/116890361-26e50500-ac4b-11eb-9dfe-21b6ec274918.png)
![image](https://user-images.githubusercontent.com/38184186/116890448-42501000-ac4b-11eb-8489-62691ce033df.png)

**Comment by 991rajat** [comment]
@neha07kumari Would you like to work on this. Let me know will assign you

**Comment by 991rajat** [comment]
If Ok Go Ahead make a PR, I'll assign it to you later

**Comment by neha07kumari** [comment]
@991rajat  I'm not getting the issue , the images you have attached cannot be viewed properly.

**Comment by 991rajat** [comment]
Anyone interested Please GO Ahead Make a PR  if not available to assign.

**Comment by Amit366** [comment]
@991rajat so should I remove the duplicates and also add images to above mentioned projects??

**Comment by 991rajat** [comment]
Yes

**Comment by 991rajat** [comment]
Yes as you mentioned.
@Amit366 Do you want to work on this?

**Comment by Amit366** [comment]
Yes I want to work
