### ISSUE TITLE
Open every card on new tab

### ISSUE THREAD

**Issue by asimaries** [Vishal-raj-1/Awesome-JavaScript-Projects#127]
every card element should get a  target="_blank" in order to open in new tab and also other needed link should also get

**Comment by asimaries** [comment]
I would like to work on this issue

**Comment by urvashi-code1255** [comment]
@asimaries You can work on this issue!

Keep in mind to follow the PR template!

**Comment by urvashi-code1255** [comment]
Any updates @asimaries ?

**Comment by asimaries** [comment]
> Any updates @asimaries ?

sorry Urvashi di I forgot about this but I have completed it, you can check it please it's working 100% in my pc 🤞
ALSO PLEASE MERGE IT AND HELP ME TO MAKE MY FIRST CONTRIBUTION TO OPEN-SOURCE🤗

**Comment by asimaries** [comment]
let me know if something went wrong I'll try to fix that

**Comment by Vishal-raj-1** [comment]
@asimaries Learn how to squash commits and write good commit messages. I am sharing one video checkout this and let me know if you have any doubts after watching this [video](https://youtu.be/f1wnYdLEpgI).

**Comment by asimaries** [comment]
> @asimaries Learn how to squash commits and write good commit messages. I am sharing one video checkout this and let me know if you have any doubts after watching this [video](https://youtu.be/f1wnYdLEpgI).

OK Thanks

**Comment by asimaries** [comment]
![image](https://user-images.githubusercontent.com/75176367/109482534-1fb34680-7aa4-11eb-83b3-0d6e38323e24.png)
my profile is not showing their I want to show off that on LinkedIn "my first contribution"
😢😅😐
