### ISSUE TITLE
Linear Search Visualisation in JavaScript

### ISSUE THREAD

**Issue by shivammahajancse** [Vishal-raj-1/Awesome-JavaScript-Projects#1272]
I would like to add a project which visualizes the linear search in JavaScript under GSSOC 2021.

**Comment by shivammahajancse** [comment]
Please assign me this issue @ridsuteri @991rajat

**Comment by 991rajat** [comment]
@shivammahajancse Make Linear Search and Binary Search In One project. It will be great to see the searching speed.
Close the binary search issue. Change the name of this issue to Searching Algorithms
