### ISSUE TITLE
Ajax Type Ahead

### ISSUE THREAD

**Issue by Meghag5** [Vishal-raj-1/Awesome-JavaScript-Projects#128]
## Describe the solution you'd like
In this project it will show every single word that matches the name we will search.

## Additional context
Add any other context about the feature request here.

**Comment by Meghag5** [comment]
@urvashi-code1255 pls add tags and pls assign it to me.

**Comment by urvashi-code1255** [comment]
@Meghag5 go for it!

**Comment by harshgupta20** [comment]
@Meghag5 Kindly reply within 2 days or I have to close this.

**Comment by Meghag5** [comment]
@harshgupta20 pls give me time 5 days time.
I am not well i will not be able to work

**Comment by harshgupta20** [comment]
@Meghag5 No problem, Please take care of your health first, and come back stronger :)

**Comment by harshgupta20** [comment]
Hi @Meghag5 , How is your health?, Is everything fine?
