### ISSUE TITLE
Button generator -  html and css code generated

### ISSUE THREAD

**Issue by Ayushjain2205** [Vishal-raj-1/Awesome-JavaScript-Projects#1280]
## Idea 
Button generator - the user needs to input parameters like color, text, padding etc. And based on these parameters the button is shown as output and code is generated.

I want to work on this issue under GSSOC'21

**Comment by Ayushjain2205** [comment]
@991rajat I would like to work on this can you please assign this to me

**Comment by Furquan712** [comment]
I would like to work on this , Will you assignee me
