### ISSUE TITLE
[GSSOC'21] Adding a new project of JavaScript Hang-man app

### ISSUE THREAD

**Issue by anushree71199** [Vishal-raj-1/Awesome-JavaScript-Projects#1281]
I would like to add a JavaScript Hang-man app project under GSSOC'21. This project is called JavaScript Hang-man app and it is a word puzzle game. In this project one have to guess the correct letters that are forming a sentence. Five guesses will be given to you in order to try, this is totally random so that no one can predict a sentence from the source code. AJAX request is used for this JavaScript project where the client makes a request and the AJAX call fetches the required API.

Check this video to get an idea about what this project will do and how much fun this game would be:-

https://user-images.githubusercontent.com/59678817/116916305-c5349300-ac6a-11eb-86ac-e72fd1efd678.mp4

This project uses the Fetch API along with ASYNC/AWAIT, that works with promises.

If you are unfamiliar with JavaScript Promises, you can simply build the project with the XMLHttp Request object. 
[javascript][gssoc'21]

**Comment by Furquan712** [comment]
I would like to work on this , Will you assignee me

**Comment by anushree71199** [comment]
Please assign me this project under GSSOC'21 @ridsuteri @991rajat

**Comment by ridsuteri** [comment]
@anushree71199 hangman project already exists :( , you can try improving it or you can try adding any other awesome project
