### ISSUE TITLE
Add a flappy bird game with sounds in it.

### ISSUE THREAD

**Issue by Shivangi-ch** [Vishal-raj-1/Awesome-JavaScript-Projects#1288]
## Is your feature request related to a problem? Please describe.
No
## Describe the solution you'd like
I would like to add a more better flappy bird game with sounds in it implemented in vannila js.

## Additional context
I am GSSOC participant.
Please assign this to me.

**Comment by Shivangi-ch** [comment]
@Vishal-raj-1 Please assign this to me.

**Comment by 991rajat** [comment]
Already present. If you want to modify that start working on PR Let me know will assign you

**Comment by Shivangi-ch** [comment]
@991rajat Yes.I want to modify that .Please assign

**Comment by Amit366** [comment]
@991rajat @ridsuteri can I work??

**Comment by ridsuteri** [comment]
yes @Shivangi-ch , rajat has already assigned you the issue , you can start modifying the project
