### ISSUE TITLE
Adding a new project of Photo details displayer using JavaScript

### ISSUE THREAD

**Issue by Abhikr-git** [Vishal-raj-1/Awesome-JavaScript-Projects#1290]
In this project I would like to add a self-made JavaScript function which will display the details of  some images once the user hovers over the images. To use this code a developer just needs to have few images of their own and use this JavaScript function. 

I've have used basic HTML and CSS along with JavaScript. The main work is done in JavaScript, one will learn how mouse hover (over and out) events work through this project. 

Please assign me this under GSSOC'21 participation @ridsuteri  @991rajat . Thanks
[javascript][gssoc21]

**Comment by harshgupta20** [comment]
@Abhikr-git Can you attach any gif or image so that we see, how it will look like.
