### ISSUE TITLE
[GSSOC'21] Adding a Random User API Project

### ISSUE THREAD

**Issue by anushree71199** [Vishal-raj-1/Awesome-JavaScript-Projects#1291]
In this project I will be adding a JavaScript AJAX request which will fetch random user APIs from all over the world and display the Name, Last name, Location, Phone, Email (phone numbers and email are fake).

Basically this JavaScript project will use an AJAX request to create Random User Generator API which will retrieve a random user information and display that as the output in our DOM. I've tried to use concepts like JavaScript XMLHttpRequest Constructor, CSS Manipulation, DOM Manipulation. 

This project will look like this:

https://user-images.githubusercontent.com/59678817/117010453-72aab380-ad0a-11eb-9252-21aa8d837d8b.mp4

Please assign me this issue under GSSOC'21 participation @ridsuteri @991rajat. I would like to contribute to this project. Thanks.
[javascript] [gssoc21]

**Comment by ridsuteri** [comment]
sorry @anushree71199 , similar project is already present in the repo :( . Try to improve that or add any other awesome project
