### ISSUE TITLE
Changing the units from pxs to rems/ems

### ISSUE THREAD

**Issue by satcasm** [Vishal-raj-1/Awesome-JavaScript-Projects#1292]
While going through the ```index.html``` file , I noticed that there are some properties that uses ```px```, would like to change it to ```rems/ems``` such that the site remains responsive under GSSOC' 21.
Thanks!

**Comment by Furquan712** [comment]
I would like to work on this issue, will you assign me ?

**Comment by harshgupta20** [comment]
@satcasm Nice point , since the projects is already well responsive so It may cause of rising other issue as well, let me know if you found anything un-responsive.

**Comment by harshgupta20** [comment]
Closed due to inactivity
