### ISSUE TITLE
Adding a project of BBC news feed using JavaScript

### ISSUE THREAD

**Issue by anushree71199** [Vishal-raj-1/Awesome-JavaScript-Projects#1293]
In this project I would like to include a JavaScript feed reader where the main objective is to grab a series of RRS(Really Simple Syndication) news feed from BBC News or another feed and then display it on your web page. The main concepts that are added here is as follows:
1) fetchApi(): To fetch the information from BBC news feed and add that to this web-page. By using this api the web-page will fetch the real time data from the original website of BBC.
2) Date(): To keep the time and date updated so that real time information can be displayed on this page.

Normally, when you fetch content from a web page you use JSON, which turns the content into an object. The problem was to convert the XML data that came from an RSS feed into a JavaScript Object. In the past days, one can use the Google AJAX Feed Reader API to fetch this information, but it has been discontinued so now we use APIs to fetch data and feed them into our RSS BBC news feed. This project looks like this:

![bbc_rss_news_feed](https://user-images.githubusercontent.com/59678817/117027478-5b73c200-ad1a-11eb-90e1-10faf8459c77.png)

I would like to work on this issue please assign me this issue under GSSOC'21 participation @ridsuteri @991rajat. Thanks.
[javascript][gssoc21]

**Comment by Furquan712** [comment]
I would like to work on this issue, will you assign me ?
