### ISSUE TITLE
Background not visible in Infix Evaluator project

### ISSUE THREAD

**Issue by SilverGraph** [Vishal-raj-1/Awesome-JavaScript-Projects#1296]
## Describe the bug

- The background image is not visible when the page loads successfully

## To Reproduce
1. Go to `Awesome Javascript` homepage
2. Click on `Projects` in the navbar
3. Scroll through to find `Infix Evaluator` project and click on it

## Expected behavior

- Expected the background image to be visible

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Windows 10
 - Browser: Google Chrome

## Additional context
![Screenshot 2021-05-05 001730](https://user-images.githubusercontent.com/74287708/117054231-828cbc80-ad37-11eb-9441-ff033222d2c7.png)

**Comment by Ankita297** [comment]
Can i work on this  @ridsuteri @harshgupta20 @991rajat ?

**Comment by SilverGraph** [comment]
@Ankita297 It's already been resolved.
