### ISSUE TITLE
Add Guess My Number Game

### ISSUE THREAD

**Issue by aashi2912** [Vishal-raj-1/Awesome-JavaScript-Projects#1311]
## Is your feature request related to a problem? Please describe.
[GSSOC'21]
No its not a problem. I tried  to add one small project.
## Describe the solution you'd like
I want to add this little game (Guess my number) using basic JavaScript and html, CSS!

## Additional context
The game is about to guess the number until user guessed and got it right. It will also keep the highscore of your attempts and game along with it!

Do review this and if you like it give me permission to add this project and assign this issue to me.

@urvashi-code1255 @ridsuteri @Vishal-raj-1 @991rajat 

![game ss1](https://user-images.githubusercontent.com/52272710/117330563-7463ab00-aeb3-11eb-9adc-f09b5788a518.png)
![game ss2](https://user-images.githubusercontent.com/52272710/117330567-7594d800-aeb3-11eb-99e9-2c0c51f97461.png)
![game ss3](https://user-images.githubusercontent.com/52272710/117330569-762d6e80-aeb3-11eb-9727-6b2be3634e02.png)

**Comment by Furquan712** [comment]
I would like to work on this issue , will you assign me ?

**Comment by aashi2912** [comment]
Checked and game is already there added. closing this issue.
