### ISSUE TITLE
We can add code source github link (file) for that particular project

### ISSUE THREAD

**Issue by aashi2912** [Vishal-raj-1/Awesome-JavaScript-Projects#1312]
## Is your feature request related to a problem? Please describe.
[GSSOC'21]
No its not a problem. I tried to enhancing the feature of site.
## Describe the solution you'd like
The aim for this project and website is to help the user/people who visits it! While awesome and so many projects are there listed and live on site, but suppose if anyone wants to see that particular projects code and want to understand it or learn it or even use it. So, for that purpose I think we should add Github link of that project code source file for better understanding and how that project got implemented and it's logic.

## Additional context
We can work on this and add that source link under every projects particular page and user can find code direct.

If you like it or wanted to add something in it, let's discuss and assign it to me.

@urvashi-code1255 @991rajat @Vishal-raj-1 @ridsuteri

**Comment by ridsuteri** [comment]
@aashi2912 the project's source code is already available in the repository and the site has a link for the repository too, i guess if someone want's to view the source code of any project he/she can simple view it on the repository itself

**Comment by aashi2912** [comment]
Okay.
