### ISSUE TITLE
PainoApp 

### ISSUE THREAD

**Issue by Astrodevil** [Vishal-raj-1/Awesome-JavaScript-Projects#1314]
GSSoC 2021 contribution 
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to enhancing the look of sidenav.
## Describe the solution you'd like
I want to change colours of whole piano app
![Screenshot 2021-05-06 234430](https://user-images.githubusercontent.com/73425223/117346237-1e97fe80-aec5-11eb-92b3-66a8a76bd83c.png)

## Additional context
I want to change looks.

**Comment by 991rajat** [comment]
Make it look good.
Don't just stop with colors. Add something more so that it looks different.
