### ISSUE TITLE
Adding color options

### ISSUE THREAD

**Issue by kanisshka** [Vishal-raj-1/Awesome-JavaScript-Projects#1318]
## Is your feature request related to a problem? Please describe.
No, it's not a problem. I tried to enhance the look of the Dynamic quote generator.

## Describe the solution you'd like
Adding more color options.

![image](https://user-images.githubusercontent.com/76627599/117396549-cc33fd80-af17-11eb-9f17-7dfa06361e26.png)
There is only 3 colors conversions I want to add some more.

**Comment by harshgupta20** [comment]
@kanisshka Go ahead with the issue :)

**Comment by kanisshka** [comment]
> @kanisshka Go ahead with the issue :)
So sorry for the delay. I'll surely complete this shortly.
