### ISSUE TITLE
ONLINE EDUCATION  WEBSITE  WITH HTML,CSS  AND JAVASCRIPT 

### ISSUE THREAD

**Issue by Mrinal81** [Vishal-raj-1/Awesome-JavaScript-Projects#1334]
I am a GSSOC'21  Participant... I would like to add online education website on your Project Page.... The main motive of this online education website is to provide online courses to the students  during this pandemic situation.....

In INDIA all colleges, institutions are closed due to this pandemic... 
so students can build his skills through these online courses......

@ridsuteri @harshgupta20 @991rajat  Please have a look on this issue........

PLEASE ASSIGN ME THIS ISSUE.......

**Comment by harshgupta20** [comment]
Any update? Kindly reply within 2 days or else we have to close this issue due to inactivity.
