### ISSUE TITLE
Bulid up landing page with JavaScript 

### ISSUE THREAD

**Issue by WebVishal** [Vishal-raj-1/Awesome-JavaScript-Projects#1343]
Hi  @ridsuteri @991rajat @harshgupta20, I want to build up a Landing Page for  E-commerce website with help of Html CSS, and JavaScript  

Can I work on this idea as a Participant of GSSOC'21?

**Comment by ridsuteri** [comment]
@WebVishal can you share a ss/gif of what the output would look like

**Comment by WebVishal** [comment]
hey @ridsuteri  look it, I want to build up like this 

![Screenshot (121)](https://user-images.githubusercontent.com/76445546/117616929-71a1d800-b189-11eb-8b9b-63d37674794f.png)

![Screenshot (122)](https://user-images.githubusercontent.com/76445546/117616878-5c2cae00-b189-11eb-80af-9061d5023569.png)
![Screenshot (123)](https://user-images.githubusercontent.com/76445546/117616884-5d5ddb00-b189-11eb-9e10-b7be8bffbc6c.png)

**Comment by harshgupta20** [comment]
@WebVishal Any update? Kindly reply within 2 days or else we have to close this issue due to inactivity.

**Comment by WebVishal** [comment]
Hey bro I working on this project give me 2 day I create new pr for this project idea

**Comment by harshgupta20** [comment]
@WebVishal Kindly give update about this issue

**Comment by WebVishal** [comment]
> @WebVishal Kindly give update about this issue

Almost completed I create a pull request today late at night
