### ISSUE TITLE
Adding a Password Generator project

### ISSUE THREAD

**Issue by PritomDutta89** [Vishal-raj-1/Awesome-JavaScript-Projects#1348]
## Is your feature request related to a problem? Please describe.
No
## Describe the solution you'd like
I would like to add a project which generate a password on the user's choice in JavaScript 

## Additional context
Please assign me this issue under GSSOC'21 @ridsuteri @991rajat @harshgupta20

**Comment by PritomDutta89** [comment]
ok, thankyou

**Comment by ridsuteri** [comment]
@PritomDutta89 this project already exists in the repo :( you can either improve that or add any other awesome project :)
