### ISSUE TITLE
World Clock 

### ISSUE THREAD

**Issue by Priyadarshan2000** [Vishal-raj-1/Awesome-JavaScript-Projects#1350]
Hello 👋🏻 @Vishal-raj-1

This is a World clock application. world any city time show here. you change ta the time

Functionalities:
- Time change
- world any city time show

@Vishal-raj-1 I am a GSSoC'21 participant and I think this is an interesting javascript project. Kindly allow me to work on this issue and contribute to this project!

## Screenshot
![image](https://user-images.githubusercontent.com/62868878/117611564-56cb6580-b181-11eb-9838-8d875bf98cc9.png)

**Comment by harshgupta20** [comment]
@Priyadarshan2000 Go ahead and You can send the PR now :)

**Comment by Priyadarshan2000** [comment]
@harshgupta20 yes I send PR within 30 min

**Comment by harshgupta20** [comment]
@Priyadarshan2000 Thats Great👍👍
