### ISSUE TITLE
Github profiles

### ISSUE THREAD

**Issue by subhangi2731** [Vishal-raj-1/Awesome-JavaScript-Projects#1352]
I would like to add and build an Interactive Landing Page using JavaScript. Please assign me this issue under GSSOC'21 @ridsuteri @991rajat @harshgupta20 @Vishal-raj-1

**Comment by subhangi2731** [comment]
please assign me this issue

**Comment by subhangi2731** [comment]
@Vishal-raj-1 please assign me the issue

**Comment by ridsuteri** [comment]
@subhangi2731 is this issue regarding addition of landing page issue?

**Comment by ridsuteri** [comment]
> @subhangi2731 is this issue regarding addition of landing page issue?

if yes then i have already assigned that issue to you hence please close this one

**Comment by ridsuteri** [comment]
@subhangi2731 the description of this issue doesn't match with the heading . kindly provide a description of the issue along with any img/gif.
