### ISSUE TITLE
Adding a BookList App

### ISSUE THREAD

**Issue by PritomDutta89** [Vishal-raj-1/Awesome-JavaScript-Projects#1357]
## Is your feature request related to a problem? Please describe.
No 
## Describe the solution you'd like
I would like to add a project where you can add the books in JavaScript

## Additional context
Please assign me this issue under GSSOC'21 @ridsuteri @991rajat @harshgupta20

**Comment by ridsuteri** [comment]
@PritomDutta89 we already have a similar project by the name of library app  :( , is your project similar to that ? if not , please share a img/gif of your project
