### ISSUE TITLE
Add a SlingShot game

### ISSUE THREAD

**Issue by Shivangi-ch** [Vishal-raj-1/Awesome-JavaScript-Projects#1360]
## Is your feature request related to a problem? Please describe.
No its not a problem. 
## Describe the solution you'd like
I will Add A slingshot game.
![Screenshot from 2021-05-10 22-57-53](https://user-images.githubusercontent.com/57783826/117700846-2bc62d80-b1e4-11eb-972e-e62ea1a0445d.png)
![Screenshot from 2021-05-10 22-57-35](https://user-images.githubusercontent.com/57783826/117700855-2d8ff100-b1e4-11eb-9401-0a2c64bf1974.png)

## Additional context
Please assign this issue to me .
I am a GSSOC participant

**Comment by harshgupta20** [comment]
Any Update? Kindly Reply within 2 days or else I have to close it due to inactivity.

**Comment by Shivangi-ch** [comment]
Made a PR
