### ISSUE TITLE
Adding a finger pool game

### ISSUE THREAD

**Issue by anushree71199** [Vishal-raj-1/Awesome-JavaScript-Projects#1368]
I would like to add a finger pool game using JavaScript. Please assign me this issue under GSSOC'21 @ridsuteri @991rajat @harshgupta20 

This project would look like this:
![finger-pool](https://user-images.githubusercontent.com/59678817/117750329-dc5a1e80-b230-11eb-8b12-4fac090bed24.png)

**Comment by ridsuteri** [comment]
srry @anushree71199 , similar issue is already assigned ,hence this issue is not available to be assigned :(
