### ISSUE TITLE
Add a maze generator

### ISSUE THREAD

**Issue by Ananya-Misra** [Vishal-raj-1/Awesome-JavaScript-Projects#1373]
## Is your feature request related to a problem? Please describe.
No, it's not a problem.
## Describe the solution you'd like
I would like to add a maze generator app using JavaScript. Please assign me this issue under GSSOC'21 @ridsuteri @991rajat @harshgupta20

**Comment by harshgupta20** [comment]
Any Update? Kindly Reply within 2 days or else I have to close it due to inactivity.

**Comment by Ananya-Misra** [comment]
Yes, I have just made the PR for the issue. Sorry for the delay, due to my college lectures and assignments I was not able to give it sufficient time.
