### ISSUE TITLE
Add Face Detection App

### ISSUE THREAD

**Issue by Ananya-Misra** [Vishal-raj-1/Awesome-JavaScript-Projects#1374]
## Is your feature request related to a problem? Please describe.
No, it's not a problem.
## Describe the solution you'd like
I would like to add a real time face detection app using JavaScript. Please assign me this issue under GSSOC'21 @ridsuteri @991rajat @harshgupta20

**Comment by harshgupta20** [comment]
@Ananya-Misra Any Update? Kindly Reply within 2 days or else I have to close it due to inactivity.

**Comment by Ananya-Misra** [comment]
Yes, I am working on it. I will try to make the pr by tomorrow.
