### ISSUE TITLE
toggle bar is not working 

### ISSUE THREAD

**Issue by shreyasingh7673** [Vishal-raj-1/Awesome-JavaScript-Projects#138]
## Describe the bug
while decreasing the screen size the toggle bar is not working.
![Screenshot 2021-02-18 230457](https://user-images.githubusercontent.com/72204395/108400660-7c5f6780-7241-11eb-9265-e717b063726a.png)

## To Reproduce
Steps to reproduce the behaviour:
1. by setting an id to div of navbar section.

## Expected behaviour
toggle behaviour should work when the screen gets small.
like this
![Screenshot 2021-02-18 232829](https://user-images.githubusercontent.com/72204395/108400622-6c478800-7241-11eb-8ee8-196d57e14bf4.png)

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: windows 
 - Browser: google chrome

**Comment by shreyasingh7673** [comment]
please review the bug and assign me this as cwoc and gssoc participant to remove the bug.

**Comment by shreyasingh7673** [comment]
@urvashi-code1255

**Comment by urvashi-code1255** [comment]
@shreyasingh7673 I want to mention one thing! That your PR for gssoc will not be counted till 1 march. But I can surely assign this to you for crosswoc!

**Comment by shreyasingh7673** [comment]
okay

**Comment by shreyasingh7673** [comment]
I have sent  PR. please check

**Comment by harshgupta20** [comment]
Since the project has been updated, so this issue is invalid with respect to the updated project website.
