### ISSUE TITLE
Calculator: make it scientific calculator 

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#14]
Try to implement as many function as you can !!

![cal](https://user-images.githubusercontent.com/59874304/107146354-b42afd00-696d-11eb-90d6-7776427fae57.JPG)

**Comment by ArkajyotiChakraborty** [comment]
Good Evening sir, I want to contribute in this project, i have a build a basic calculator and working in web development.

**Comment by urvashi-code1255** [comment]
> Good Evening sir, I want to contribute in this project, i have a build a basic calculator and working in web development.

Hi @ArkajyotiChakraborty You can surely go for this issue. Assigning this to you

**Comment by ArkajyotiChakraborty** [comment]
Thanks, is there's any discord channel for this specific project or repo, and when is the deadline.

**Comment by urvashi-code1255** [comment]
> Thanks, is there's any discord channel for this specific project or repo, and when is the deadline.

You have 3 days to complete a particular issue. For now, you can ask any query in this issue thread only..

**Comment by ArkajyotiChakraborty** [comment]
ok thanks.

**Comment by ArkajyotiChakraborty** [comment]
Can i merged it on Wednesday, the basic part is ready i have to implement some advance functions, but having a test tomorrow.

**Comment by ArkajyotiChakraborty** [comment]
And do i have to merge the javascript file only.

**Comment by urvashi-code1255** [comment]
> Can i merged it on Wednesday, the basic part is ready i have to implement some advance functions, but having a test tomorrow.

Okay @ArkajyotiChakraborty No problem!

**Comment by urvashi-code1255** [comment]
> And do i have to merge the javascript file only.

You have to push all the files changed!! @ArkajyotiChakraborty

**Comment by ArkajyotiChakraborty** [comment]
ok thanks.

**Comment by ArkajyotiChakraborty** [comment]
I have added the changes, hope you like it, it was my first Open Source Contribution and made it in a very short time due to some exams. Thanks a lot to assign me with this opportunity.

**Comment by ArkajyotiChakraborty** [comment]
hey just to clarify it's done right, as the PR merged i guess no work is left for now.

thanks again.
