### ISSUE TITLE
Number Guessing Game

### ISSUE THREAD

**Issue by vanshikachokhani** [Vishal-raj-1/Awesome-JavaScript-Projects#1419]
I want to add a number guessing game where the user will have some predefined amount of tries to guess a random number in a given range.
Please assign me this issue under Gssoc'21 @ridsuteri @991rajat @harshgupta20

**Comment by ridsuteri** [comment]
sorry @vanshikachokhani, but this project has already been added to the repo , you can either try to improve that project or try adding any other awesome project :)
