### ISSUE TITLE
Missing Projects

### ISSUE THREAD

**Issue by TidbitsJS** [Vishal-raj-1/Awesome-JavaScript-Projects#143]
### Few projects missing
Not able to track down the "Drawing app", "Scientific Calculator", "Password Generator", "Mario", "URL Shortner"  etc app projects cards in the index file

As per mine project is considered, it had been merged properly ( Twice with the enhancement ) .. Files seem to be there in the public & assets folder. Cards are missing   

### Expected behavior
Projects cards have to be there. I am not able to see any mentioned projects card. 

Kindly, take a look!

### Event
Part of GSSOC

**Comment by Vishal-raj-1** [comment]
@TidbitsJS Please make the PR for the same !! Except that scientific calculator

**Comment by TidbitsJS** [comment]
Done with PR. 
If you want & no one is assigned for the scientific calculator project, then I am happy to work on that.
Let me know @Vishal-raj-1 

> @TidbitsJS Please make the PR for the same !! Except that scientific calculator
