### ISSUE TITLE
Add Image Filter Project

### ISSUE THREAD

**Issue by K-jais** [Vishal-raj-1/Awesome-JavaScript-Projects#1441]
This project will have features like brightness, contrast, blur, grayscale, invert, saturate, etc which you can implement on various images.

Its working video,

https://user-images.githubusercontent.com/75881393/118355373-4fdf9100-b58d-11eb-8b8e-059318d93ff4.mp4

**Comment by K-jais** [comment]
Please @ridsuteri @991rajat @urvashi-code1255 review this issue.

**Comment by 991rajat** [comment]
Hey @K-jais This Project Already Exist, Sorry Didn't know when I assigned You. I'm closing this one.
If you want to modify or improve it create an issue for the same
