### ISSUE TITLE
 Height Conversion Project

### ISSUE THREAD

**Issue by PritomDutta89** [Vishal-raj-1/Awesome-JavaScript-Projects#1449]
## Is your feature request related to a problem? Please describe.
No
## Describe the solution you'd like
I would like to add a project where you can convert feet into meter or meter into feet in JavaScript

## Additional context
Please assign me this issue under GSSOC'21 @ridsuteri @991rajat @harshgupta20

**Comment by 991rajat** [comment]
Length converter already exist. If you want to modify it create a new issue regarding that.
