### ISSUE TITLE
Photo Editing Web Application in Javascript

### ISSUE THREAD

**Issue by neha07kumari** [Vishal-raj-1/Awesome-JavaScript-Projects#1450]
I would like to add a project (Photo Editing Web Application ) in JavaScript under GSSOC 2021.

**Comment by neha07kumari** [comment]
Please assign me this issue @ridsuteri @991rajat @Vishal-raj-1 @harshgupta20

**Comment by 991rajat** [comment]
@neha07kumari Add the image for the refence please. TO check whether this project already exist or not.
