### ISSUE TITLE
Add a memory game

### ISSUE THREAD

**Issue by garvitgupta13** [Vishal-raj-1/Awesome-JavaScript-Projects#1456]
Add a memory game in which you have to flip cards such that the pictures of that 2 card matches
![image](https://user-images.githubusercontent.com/70805691/118371699-73c1c780-b5cb-11eb-9627-54c3f6d989b7.png)

You can see two cards at a time only

Plese assign me this issue under `gssoc21`

**Comment by garvitgupta13** [comment]
Please assign me this issue @ridsuteri @991rajat @Vishal-raj-1 @harshgupta20

**Comment by ridsuteri** [comment]
sorry @garvitgupta13 , this project already exists in the repo , you can either try to improve that or add any other awesome project :)
