### ISSUE TITLE
Add snow.js canvas

### ISSUE THREAD

**Issue by garvitgupta13** [Vishal-raj-1/Awesome-JavaScript-Projects#1457]
Add snow.js which is a great background template used in javascript

Please assign me this issue under `gssoc21`

**Comment by garvitgupta13** [comment]
Please assign me this issue @ridsuteri @991rajat @Vishal-raj-1 @harshgupta20

**Comment by ridsuteri** [comment]
@garvitgupta13 can you share a ss/gif of the project ?

**Comment by garvitgupta13** [comment]
> @garvitgupta13 can you share a ss/gif of the project ?

![20210517_151421_1 1](https://user-images.githubusercontent.com/70805691/118469016-f8732980-b722-11eb-839e-f348e9cfa792.gif)
