### ISSUE TITLE
Loan Calculator

### ISSUE THREAD

**Issue by garvitgupta13** [Vishal-raj-1/Awesome-JavaScript-Projects#1459]
A loan calculator which takes principal, interest and time as input and returns the monthly EMI

Please assign me this issue under `gssoc21`

**Comment by garvitgupta13** [comment]
Please assign me this issue @ridsuteri @991rajat @Vishal-raj-1 @harshgupta20

**Comment by ridsuteri** [comment]
sorry @garvitgupta13 , similar issue has already been assigned to someone else , hence i am closing this one :(
