### ISSUE TITLE
Tic Tac Toe Game

### ISSUE THREAD

**Issue by pranabprohit** [Vishal-raj-1/Awesome-JavaScript-Projects#148]
It's a multiplayer game and the players of this game have to position their marks(sign) so that they can construct a continuous line of three cells or box vertically, horizontally, or diagonally. An opponent can stop a win by blocking the end of the opponent's line.

**Comment by pranabprohit** [comment]
Hi @urvashi-code1255 , I would like to work on this issue.

**Comment by rohansharma4050** [comment]
HI, I am a GSSoC'21 participant and would like to work on this issue. Can you assign this to me?

**Comment by urvashi-code1255** [comment]
> Hi @urvashi-code1255 , I would like to work on this issue.

Sure @pranabprohit go for it!

**Comment by urvashi-code1255** [comment]
Hey @rohansharma4050 Welcome to the project! As @pranabprohit asked first so I assigned this issue to @pranabprohit . You can go for an issue which is not assigned to anyone yet.

**Comment by pranabprohit** [comment]
Hey @urvashi-code1255, I am part of CWOC so can you please add the required labels. And is their any group for discussion or for asking doubt related to project.

**Comment by urvashi-code1255** [comment]
@pranabprohit there is no group for now.

You can ask your doubts in this issue thread!

**Comment by pranabprohit** [comment]
Hii @urvashi-code1255, I think `index.html` file got changed earlier it was having more than 500 line of code but now it shows only 150 line. Can you please check.

**Comment by Vishal-raj-1** [comment]
@pranabprohit Yes, we have moved all the projects card from index.html to script.js. Now you have to add your project detail in script.js.
