### ISSUE TITLE
Add interactive colorful waves animation.

### ISSUE THREAD

**Issue by Shivangi-ch** [Vishal-raj-1/Awesome-JavaScript-Projects#1482]
## Is your feature request related to a problem? Please describe.
No its not a problem. 
## Describe the solution you'd like
I would like to add interactive colorful waves animation.
![Screenshot from 2021-05-18 01-21-35](https://user-images.githubusercontent.com/57783826/118548195-a6102800-b777-11eb-8fac-ec0a5a2f6d08.png)
![Screenshot from 2021-05-18 01-21-39](https://user-images.githubusercontent.com/57783826/118548202-a7415500-b777-11eb-83db-f99babd865ca.png)

## Additional context
Please assign me this under `gssoc21`

**Comment by Shivangi-ch** [comment]
@ridsuteri @991rajat Please assign .

**Comment by ridsuteri** [comment]
sorry @Shivangi-ch but this animation has already been applied to a project by the name "color flicker" :( you can either look for it's improvements or any other awesome js project
