### ISSUE TITLE
Expand and Collapse Card Used in FAQs

### ISSUE THREAD

**Issue by Muskan0** [Vishal-raj-1/Awesome-JavaScript-Projects#1488]
## Is your feature request related to a problem? Please describe.
No its not a problem. 
## Describe the solution you'd like
I would like to add the expand and collapse card mainly used in FAQ in websites.

## Additional context
Please assign me this under ```gssoc21```

https://user-images.githubusercontent.com/49088492/118615902-d343f100-b7de-11eb-8dc3-38adb4e7a983.mp4

**Comment by Vishal-raj-1** [comment]
@Muskan0 ?

**Comment by Amrutha1101** [comment]
I want to work on this issue under LGMSOC.

**Comment by Vishal-raj-1** [comment]
Go for it @Amrutha1101

**Comment by Amrutha1101** [comment]
May I know where is FAQ in the website?

**Comment by Ankita297** [comment]
you can search that in Projects section @Amrutha1101 .

**Comment by AmruthaCK** [comment]
It's already working fine . Shall I work on UI of the FAQ project?

**Comment by Amrutha1101** [comment]
It's already working fine. Shall I work on the UI of the FAQ project?

**Comment by Ankita297** [comment]
okay go ahead @Amrutha1101
