### ISSUE TITLE
Flash_card (short notes)

### ISSUE THREAD

**Issue by bitaashna** [Vishal-raj-1/Awesome-JavaScript-Projects#149]
In this students can make note of a particular topic in form of small Flashcards and thus making it easier for them to learn,memorize and revise.They can add as many flashcards they want!

**Comment by bitaashna** [comment]
Hi @urvashi-code1255 ! I would like to work on this issue.

**Comment by Vishal-raj-1** [comment]
I think it is same as our note app. Check it once !!

**Comment by bitaashna** [comment]
okay ! got it.. thanks
