### ISSUE TITLE
Color Guessing Game Using JavaScript DOM

### ISSUE THREAD

**Issue by prayas7102** [Vishal-raj-1/Awesome-JavaScript-Projects#1491]
## Is your feature request related to a problem? Please describe.
No its not a problem. 
## Describe the solution you'd like
I am suggesting to add a RGB color game using DOM.
In this game there are 6 blocks of random color and at the top there is a random RGB text indicating a color. The player have to guess which block corresponds to the color enclosed by the RGB at the top. The player can guess the right block by clicking on it.  Each time the player clicks on "play again" button the whole page would get refreshed, with new RGB color at top and new color of all the 6 blocks.
<img width="960" alt="color" src="https://user-images.githubusercontent.com/71717433/118637575-959d9300-b7f3-11eb-97c5-0d5bcbf7ade8.png">

## Additional context
This interactive game project  can enhance the DOM understanding of anyone who is a beginner in JavaScript.
I am also attaching the git hub link of my proposed project. ==>> https://github.com/prayas7102/Color-Guessing-Game-Using-Js-DOM

**Comment by ridsuteri** [comment]
sorry @prayas7102 , but this project already exists in the repo , you can either improve that or add any other awesome js project :)

**Comment by prayas7102** [comment]
Ok sir, I've created other issue #1690. Please have a look at it and let me
know if I can work on it.
