### ISSUE TITLE
Add Tic Tac Toe Game 

### ISSUE THREAD

**Issue by ainy-123** [Vishal-raj-1/Awesome-JavaScript-Projects#1494]
I want to add Tic-Tac-Toe game using HTML,CSS and Javascript.

I am GSSoC'21 participant and I want to work on this.
Kindly assign me this issue.

**Comment by Amit366** [comment]
@ridsuteri can I work on this??

**Comment by ainy-123** [comment]
> I want to add Tic-Tac-Toe game using HTML,CSS and Javascript.
> 
> I am GSSoC'21 participant and I want to work on this.
> Kindly assign me this issue.

/assign

**Comment by ridsuteri** [comment]
sorry @Amit366 and  @ainy-123 , but this project already exists :(
