### ISSUE TITLE
Note App : Implementation of more features

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#15]
## Features : 

- Add title for note app
- Add tags if required
- Add time stamp if required( will give notification )

## Searching 👍🏻 

- On the basis of tags
- On the basis of content (means title or notes)
- On the basis of time stamp(recent or older)

## Styling 👍🏻 

- You can come with your own design.

### Have more idea ? 

- Be creative, try to add as many features we can add to this app. Comment down your ideas

**Comment by Jyotsna555** [comment]
Hello Sir, I would like to contribute to this project. I have started learning Web development recently, and I will be able to add some styling to the note app.

**Comment by Mukta-Sawant** [comment]
@Vishal-raj-1 Can I work on this issue? I would like to solve this problem as a part of GirlScript Summer of code 2021.

**Comment by mirakiii** [comment]
Hey, @Vishal-raj-1 here I have worked on its styling and currently working on adding title to the note card would love add more functionality on the go!
![image](https://user-images.githubusercontent.com/68226051/108606626-101b6a00-73e1-11eb-8590-264f4d7246eb.png)

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?

**Comment by Siddharth1006** [comment]
Hey! My name is Siddharth S.  I am GSSOC'21 participant. I have a good understanding of HTML , CSS and Javascript. I also have couple of styling ideas for the design. If you can then please assign this issue to me. 
I am also ready to work with another participant if the other person agrees!

**Comment by Asmita-si** [comment]
I want to work on this issue. Can you please assign it to me? @Vishal-raj-1  @urvashi-code1255

**Comment by urvashi-code1255** [comment]
@mirakiii Are you working on this?

**Comment by mirakiii** [comment]
> @mirakiii Are you working on this?

yes @urvashi-code1255  ! I am would send PR by tommorow :) just want to ask if the styling showcased above OK ?

**Comment by SanskrutiRP** [comment]
Hey @urvashi-code1255 . I would like to improve styling part of this. Will you please assign this to me?

**Comment by urvashi-code1255** [comment]
> yes @urvashi-code1255 ! I am working on this, would send PR by tommorow :) just want to ask if the styling showcased above OK ?

@mirakiii Yeah design is looking good to me, Just change the yellow color.

**Comment by urvashi-code1255** [comment]
> Hey @urvashi-code1255 . I would like to improve styling part of this. Will you please assign this to me?

Sure @SanskrutiRP go for it!

**Comment by SanskrutiRP** [comment]
Thank You!!!
