### ISSUE TITLE
Fibonacci series generator in javascript

### ISSUE THREAD

**Issue by neha07kumari** [Vishal-raj-1/Awesome-JavaScript-Projects#1505]
I would like to add a project (Fibonacci series generator) in JavaScript under GSSOC 2021.

![Screenshot (289)](https://user-images.githubusercontent.com/47255445/118856146-425f3980-b8f4-11eb-906a-d0d440ebea0d.png)

![Screenshot (288)](https://user-images.githubusercontent.com/47255445/118856142-412e0c80-b8f4-11eb-9c36-0bd447a5b525.png)

**Comment by neha07kumari** [comment]
Please assign me this issue @ridsuteri @991rajat @Vishal-raj-1 @harshgupta20

**Comment by ridsuteri** [comment]
@neha07kumari fibonacci series as in , series generator?

**Comment by neha07kumari** [comment]
> @neha07kumari fibonacci series as in , series generator?

Yes, series generator.

**Comment by ridsuteri** [comment]
ok go ahead @neha07kumari :)
