### ISSUE TITLE
Dynamic Time message in Javascript

### ISSUE THREAD

**Issue by neha07kumari** [Vishal-raj-1/Awesome-JavaScript-Projects#1506]
I would like to add a project (Dynamic time message) in JavaScript under GSSOC 2021.
Description: This project will generate  messages according to the day time (as per morning , afternoon & evening) as and when you click the button "GET MESSAGE".

![Screenshot (287)](https://user-images.githubusercontent.com/47255445/118855378-56ef0200-b8f3-11eb-9c07-f0492a5444fa.png)

**Comment by neha07kumari** [comment]
Please assign me this issue @ridsuteri @991rajat @Vishal-raj-1 @harshgupta20

**Comment by ridsuteri** [comment]
@neha07kumari please elaborate the issue with a brief description and a image/gif :)

**Comment by neha07kumari** [comment]
> @neha07kumari please elaborate the issue with a brief description and a image/gif :)

done @ridsuteri .

**Comment by ridsuteri** [comment]
@neha07kumari ok go ahead with it :)
