### ISSUE TITLE
add projects using js

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#151]
## Description

Make one object add all projects details in it. Projects Details includes Project Name, Project link, Images/Gif. Use JS to iterate through these projects.

**Comment by TidbitsJS** [comment]
I will like to do this @Vishal-raj-1  ( I had even thought about this today itself ... The DRY )
Let's just make a separate JSON file for project info!

**Comment by sukhpreet-singh1** [comment]
can you please assign this issue to me ? 
i would love to solve it

**Comment by saaiswetha** [comment]
I would like to take up this issue. I'm a participant of GSSOC'21, could this be assigned to me?

**Comment by urvashi-code1255** [comment]
@TidbitsJS go for it. 

@sukhpreet-singh1 @saaiswetha As @TidbitsJS asked first so I m assigning this issue to her. please have a look at other issues which are kot assigned to anyone.
