### ISSUE TITLE
Adding Interactive Flashlight Project

### ISSUE THREAD

**Issue by anushree71199** [Vishal-raj-1/Awesome-JavaScript-Projects#1510]
I would like to add an interactive flashlight project made using JavaScript. Please assign me this issue under GSSOC'21 @ridsuteri @991rajat @harshgupta20 
[gssoc21][javascript]

**Comment by ridsuteri** [comment]
@anushree71199 can you elaborate the issue with images/gifs ?

**Comment by anushree71199** [comment]
This is what it will look like:
![flashlight](https://user-images.githubusercontent.com/59678817/118861350-07600480-b8fa-11eb-88be-39d01cf01deb.gif)
