### ISSUE TITLE
Project Idea: JavaScript vertical Timeline for a website

### ISSUE THREAD

**Issue by vanshikachokhani** [Vishal-raj-1/Awesome-JavaScript-Projects#1515]
I want to build a vertical timeline using javascript with animations for a website. This timeline will be different from the one already present in the repo. The timeline present in the repo is one for personal use but I want to build a timeline for a company website.
Please assign me this issue under Gssoc'21 @991rajat @ridsuteri @harshgupta20

**Comment by ridsuteri** [comment]
@vanshikachokhani can you please share an ss/gif of how your project would look like?

**Comment by vanshikachokhani** [comment]
> @vanshikachokhani can you please share an ss/gif of how your project would look like?

![Screenshot from 2021-05-20 16-42-15](https://user-images.githubusercontent.com/54857354/118969338-9157ae00-b98a-11eb-8603-89bd55088caa.png)
![Screenshot from 2021-05-20 16-42-53](https://user-images.githubusercontent.com/54857354/118969352-94eb3500-b98a-11eb-88a0-8335b8ada363.png)

**Comment by ridsuteri** [comment]
looks great @vanshikachokhani , go ahead with it :)
