### ISSUE TITLE
Add  Contributors Images in Readme

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#152]

**Comment by Mukta-Sawant** [comment]
@urvashi-code1255 @Vishal-raj-1 Can I work on this issue? Please assign it to me, I would like to solve this as a part of GirlScript Summer of code 2021.

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 @Vishal-raj-1 Can I work on this issue? Please assign it to me, I would like to solve this as a part of GirlScript Summer of code 2021.

Sure @Mukta-Sawant go for it :)
