### ISSUE TITLE
Project idea : step by step origami dog visualizer 

### ISSUE THREAD

**Issue by Ritika-Agrawal811** [Vishal-raj-1/Awesome-JavaScript-Projects#1520]
Hey I would like to add a small project I created using Js which is a step by step visualization of how to create an origami dog. I just need to work on its responsiveness. Please would you assign this issue to me. [Project on codepen ](https://codepen.io/RitikaAgrawal08/full/WNGbJyz)

**Comment by Ankita297** [comment]
@Ritika-Agrawal811 you want  to work on this  ?
