### ISSUE TITLE
Add Loan Calculator Project

### ISSUE THREAD

**Issue by K-jais** [Vishal-raj-1/Awesome-JavaScript-Projects#1522]
This project will calculate the amount and the principal amount which will be there for the particular rate of interest and time and it will show this with a pie graph and dynamic numbers.

Its working video,

https://user-images.githubusercontent.com/75881393/118973355-37a5b280-b98f-11eb-84dc-946e983c581c.mp4

**Comment by K-jais** [comment]
Please @ridsuteri @991rajat @urvashi-code1255 review this issue.

**Comment by ridsuteri** [comment]
sorry @K-jais but a loan calculator already exists, you can update the existing one if you want !

**Comment by K-jais** [comment]
@ridsuteri Ok then I will update that

**Comment by ridsuteri** [comment]
ok go ahead @K-jais :)
