### ISSUE TITLE
Bug in script.js file

### ISSUE THREAD

**Issue by vanshikachokhani** [Vishal-raj-1/Awesome-JavaScript-Projects#1528]
## Describe the bug
The factorial calculator proejct is included in the script.js file twice.

## To Reproduce
1. Remove the repeating

## Expected behavior
The project should be included only once.

Please assign me this under Gssoc'21 @991rajat @ridsuteri @harshgupta20

**Comment by ridsuteri** [comment]
@vanshikachokhani I am assigning you the issue, please make sure that you remove every duplicate entry of each project
