### ISSUE TITLE
Project idea: Scientific calculator

### ISSUE THREAD

**Issue by vanshikachokhani** [Vishal-raj-1/Awesome-JavaScript-Projects#1529]
I want to add a scientific calculator project using javascript.
Please assign me this issue under Gssoc'21 @991rajat @ridsuteri @harshgupta20

**Comment by ridsuteri** [comment]
@vanshikachokhani can you add the scientific calculator features to the existing calculator in the repo?

**Comment by vanshikachokhani** [comment]
> @vanshikachokhani can you add the scientific calculator features to the existing calculator in the repo?

Ok I will update the calculator proejct.

**Comment by ridsuteri** [comment]
that's great @vanshikachokhani , go ahead with the issue :)
