### ISSUE TITLE
About adding one project of JavaScript

### ISSUE THREAD

**Issue by sonalisonawane** [Vishal-raj-1/Awesome-JavaScript-Projects#153]
## Is your feature request related to a problem? Please describe.
This is a simple project in which all the events of drag and drop API are used like dragstart, dragend, dragover, dragleave, drop.etc and here we have to drag the object and drop it into its correct box for eg. cat should be drop into cat box.

**Comment by urvashi-code1255** [comment]
Hey @sonalisonawane Please add the full description of what your project is!!

**Comment by mirakiii** [comment]
Hey @sonalisonawane may I add a project of a video player that is solely made of javascript that contains play, pause, skip 10 sec, timeline features.. what say?

**Comment by sonalisonawane** [comment]
yes sure!

**Comment by urvashi-code1255** [comment]
Hey @sonalisonawane I like your idea

**Comment by sonalisonawane** [comment]
Thank you :) @urvashi-code1255 mam ,glad to add more projects in this repo onwards.
