### ISSUE TITLE
Pokemon pokedex

### ISSUE THREAD

**Issue by Ankita297** [Vishal-raj-1/Awesome-JavaScript-Projects#1545]
## Is your feature request related to a problem? Please describe.
it will be page of pokemon characters .
## Describe the solution you'd like
I have updated sidenav.html and added sidenav.css for changing current sidenav project into animated sidenav

## Additional context
Add any other context about the feature request here.

**Comment by Ankita297** [comment]
Can i work on this @ridsuteri @Vishal-raj-1 @harshgupta20 ?

**Comment by Ankita297** [comment]
@ridsuteri Sir ?

**Comment by ridsuteri** [comment]
@Ankita297 yes go ahead :)
