### ISSUE TITLE
Hover board 

### ISSUE THREAD

**Issue by Ankita297** [Vishal-raj-1/Awesome-JavaScript-Projects#1546]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to enhancing the look of sidenav.
## Describe the solution you'd like
I have updated sidenav.html and added sidenav.css for changing current sidenav project into animated sidenav

## Additional context
Add any other context about the feature request here.

**Comment by Ankita297** [comment]
Can i work on this  @ridsuteri @harshgupta20 ?

**Comment by ridsuteri** [comment]
@Ankita297 can you explain this  issue?

**Comment by Ankita297** [comment]
![hover board](https://user-images.githubusercontent.com/67833077/119234549-2229b780-bb4c-11eb-8722-f3094f62de26.png)
@ridsuteri  like this .

**Comment by ridsuteri** [comment]
@Ankita297 I guess it looks similar to an existing project in the repo, checkout etch sketch game in the repo, and let me know if your project is different from that one :)

**Comment by Ankita297** [comment]
@ridsuteri in etch sketch  the keyboard are used to drag  the lines trail  but in this we use mouse  and also the trail auto disappear after sometime .
So can i work on this ?

**Comment by ridsuteri** [comment]
> @ridsuteri in etch sketch the keyboard are used to drag the lines trail but in this we use mouse and also the trail auto disappear after sometime .
> So can i work on this ?

ohk sounds cool, go ahead :)
