### ISSUE TITLE
Add preloader Project

### ISSUE THREAD

**Issue by Ankita297** [Vishal-raj-1/Awesome-JavaScript-Projects#1548]
## Is your feature request related to a problem? Please describe.
I want to add diffrent preloaders 
## Describe the solution you'd like
I have updated sidenav.html and added sidenav.css for changing current sidenav project into animated sidenav

## Additional context
Add any other context about the feature request here.

**Comment by Ankita297** [comment]
Can i work on this @ridsuteri Sir ?

**Comment by ridsuteri** [comment]
@Ankita297 can you please share the preloader's ss/gif and how would the site look after adding it !

**Comment by Ankita297** [comment]
@ridsuteri  it is bascially going to be page which consist of different  types of preloader  , right now i have not started making it .

**Comment by ridsuteri** [comment]
> @ridsuteri it is bascially going to be page which consist of different types of preloader , right now i have not started making it .

ok go ahead, but do share gifs in the PR :)
