### ISSUE TITLE
Custom Range Slider

### ISSUE THREAD

**Issue by Muskan0** [Vishal-raj-1/Awesome-JavaScript-Projects#1549]
## Is your feature request related to a problem? Please describe.
No its not a problem. I want to add a Custom Range Slider using HTML, CSS and javascript.
## Additional context
Please assign this under ```gssoc```

**Comment by Atif0604** [comment]
@Ankita297 I want to work on this under LGMSOC-21

**Comment by Rizwan-S** [comment]
@Atif0604 go ahead
