### ISSUE TITLE
Double Vertical Slider

### ISSUE THREAD

**Issue by Muskan0** [Vishal-raj-1/Awesome-JavaScript-Projects#1550]
## Is your feature request related to a problem? Please describe.
No its not a problem. I want to add a double vertical slider using html, css and javascript.
## Additional context
Please assign this under ```gssoc```

**Comment by Atif0604** [comment]
@Rizwan-S @Ankita297 i want to work on this

**Comment by Rizwan-S** [comment]
@Atif0604 I have assigned you another issue. Please work on issues one at a time.

**Comment by Atif0604** [comment]
> @Atif0604 I have assigned you another issue. Please work on issues one at a time.

Now can i work on this? @Rizwan-S

**Comment by Rizwan-S** [comment]
@Atif0604 sure!
