### ISSUE TITLE
Ripple effect on clicking button

### ISSUE THREAD

**Issue by Muskan0** [Vishal-raj-1/Awesome-JavaScript-Projects#1551]
## Is your feature request related to a problem? Please describe.
No its not a problem. I want to add the feature of ripple effect when a button is clicked.
## Describe the solution you'd like
I will make it using html, css and javascript.
## Additional context
Please assign this under ```gssoc```

**Comment by RakeshCharpe** [comment]
can I work on this issue under LCM Soc21.

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by RiyaGupta89** [comment]
I am a participant of LGMsoc'21. May I please work under this issue?

**Comment by Ankita297** [comment]
@RiyaGupta89 you can go ahead .

**Comment by RiyaGupta89** [comment]
@Ankita297 Is this under LGMsoc'21?

**Comment by Ankita297** [comment]
@RiyaGupta89 any updates ?

**Comment by RiyaGupta89** [comment]
Yes @Ankita297, I am sorry. I thought you were not active. Also, I forgot about this issue too. I'll make the PR tomorrow for sure. Sorry again.

**Comment by Ankita297** [comment]
It's okay  @RiyaGupta89 ,make the PR as soon as possible .

**Comment by Ankita297** [comment]
@RiyaGupta89 any updates ?

**Comment by RiyaGupta89** [comment]
@Ankit0225 I tried resolving this issue but i dont know why my css is not working in the buttons. I am unable to solve this issue. Sorry.

**Comment by RakeshCharpe** [comment]
If this issue is still open so can I work on this issue under LGMSoc'21. I like to work on this issue.

**Comment by Ankita297** [comment]
@RakeshCharpe go for it .
