### ISSUE TITLE
Adding a Nebula Effect Sign Up Form 

### ISSUE THREAD

**Issue by anushree71199** [Vishal-raj-1/Awesome-JavaScript-Projects#1558]
I would like to add a sign up form where in the background there will be some cloud plus light effects and it will look something like this:

https://user-images.githubusercontent.com/59678817/119216540-e104b980-baf1-11eb-94e5-52af92aca1ad.mp4

Please assign me this issue under GSSOC'21 @ridsuteri @991rajat @harshgupta20 
[gssoc21][javascript]

**Comment by ridsuteri** [comment]
@anushree71199 how about adding this nebula effect to any of the existing forms-related projects from the repo?

**Comment by anushree71199** [comment]
@ridsuteri Yeah I can add it in other sign up forms too but I noticed that there aren't many good looking forms in the project so I just thought that adding it alone as a project will give others idea on how to use these kind of effects and make their sign up forms look better. If you want me to add this effect in other forms I'll make an issue for that too.

**Comment by ridsuteri** [comment]
> @ridsuteri Yeah I can add it in other sign up forms too but I noticed that there aren't many good looking forms in the project so I just thought that adding it alone as a project will give others idea on how to use these kind of effects and make their sign up forms look better. If you want me to add this effect in other forms I'll make an issue for that too.

ok go on with your idea :)
