### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by Harshal0902** [Vishal-raj-1/Awesome-JavaScript-Projects#156]
## Is your feature request related to a problem? Please describe.
Convert a link or text into QR Code.

## Describe the solution you'd like
I want to build a QR Code generator, through which the user just need to type text and it will convert that text into QR Code.

## Additional context
I want to build a QR Code generator.

**Comment by Harshal0902** [comment]
@Vishal-raj-1 Can you please assign this issue to me?
I would like to work on this issue.

**Comment by Vishal-raj-1** [comment]
@Harshal0902 Sure !!
