### ISSUE TITLE
Change the page brightness using a Range Slider

### ISSUE THREAD

**Issue by YasmineEl-shahat** [Vishal-raj-1/Awesome-JavaScript-Projects#1567]
I would like to add a brightness effect using JS 
![image_2021-05-22_152201](https://user-images.githubusercontent.com/58048543/119228062-7499b280-bb11-11eb-8b10-615f3f2477f7.png)

Please assign me this issue under GSSOC'21 participation @harshgupta20  @ridsuteri @991rajat @urvashi-code1255

**Comment by ridsuteri** [comment]
@YasmineEl-shahat  please checkout the **image editor** project in the repo and let me know if your issue is different from brightness feature of  that one :)

**Comment by YasmineEl-shahat** [comment]
Ooh I didn't see it . It uses the same feature.

**Comment by ridsuteri** [comment]
> Ooh I didn't see it . It uses the same feature.

yeah, and since it is already present, hence I am closing this issue :)
