### ISSUE TITLE
BirdLoader 

### ISSUE THREAD

**Issue by YasmineEl-shahat** [Vishal-raj-1/Awesome-JavaScript-Projects#1573]
when it comes to the right , the left half of bird's eye disappear .
![image](https://user-images.githubusercontent.com/58048543/119232338-33ab9900-bb25-11eb-911a-ccd471287271.png)
Please assign me this issue under GSSOC'21 participation @harshgupta20 @ridsuteri @991rajat @urvashi-code1255

**Comment by ridsuteri** [comment]
sorry @YasmineEl-shahat, but this issue already exists in the repo :(, you can either improve this one or add  any other awesome js project

**Comment by YasmineEl-shahat** [comment]
I know it needs to be improved cause when it comes to the right , the left half of bird's eye disappear .

**Comment by ridsuteri** [comment]
> I know it needs to be improved cause when it comes to the right , the left half of bird's eye disappear .

ok, so you want to work on its improvement?

**Comment by YasmineEl-shahat** [comment]
Yes, I will fix it

**Comment by ridsuteri** [comment]
> Yes, I will fix it
ok great then !
