### ISSUE TITLE
vanilla javascript Video player 

### ISSUE THREAD

**Issue by mirakiii** [Vishal-raj-1/Awesome-JavaScript-Projects#158]
## Description
hey ! @urvashi-code1255 I would like make a addition to this amazing list of projects by creating _Video Player_ that is solely made up of **vanilla javascript** and basic css, html .
## Features
* Play / Pause by clicking on screen
* 10 seconds skip button
* timeline feature
* appearance of dashboard only when hovering on screen
* And many more...

would love to get my hands over this project of javascript and make my contribution fruitful !

**Comment by urvashi-code1255** [comment]
Hey @mirakiii I like your idea. Do implement it :)

**Comment by Vishal-raj-1** [comment]
@mirakiii Waiting for your PR !!

**Comment by mirakiii** [comment]
👋 hey ! @Vishal-raj-1 , nice to hear from you as I am applying through GSSOC would it be ok if I send PR after march 1 by then I would add some aditional features to make it more exciting :sparkler: 
waiting to hear from you :)

**Comment by Vishal-raj-1** [comment]
@mirakiii Yeah no problem !!

**Comment by harshgupta20** [comment]
@mirakiii any update ? Kindly reply within 2 days or I have to close this.

**Comment by mirakiii** [comment]
Hey wait ! I was about to send the pull request if you let me ... Was busy with endsem stuff
