### ISSUE TITLE
Awesome Image Slider 

### ISSUE THREAD

**Issue by YasmineEl-shahat** [Vishal-raj-1/Awesome-JavaScript-Projects#1588]
I would like to add an image slider like this

![sliderVideo](https://user-images.githubusercontent.com/58048543/119243564-311e6300-bb68-11eb-9dc6-1264898ff594.gif)

Please assign me this  issue under GSSOC'21 participation @harshgupta20 @ridsuteri @991rajat @urvashi-code1255

**Comment by ridsuteri** [comment]
@YasmineEl-shahat a similar project by the name **click and drag image slider** already exists :(
