### ISSUE TITLE
Improve search box

### ISSUE THREAD

**Issue by YasmineEl-shahat** [Vishal-raj-1/Awesome-JavaScript-Projects#1591]
I wanna improve the search box in projects page so when I hit enter the results show
![image](https://user-images.githubusercontent.com/58048543/119249619-44e2bd00-bb9a-11eb-89f5-0ef4e6bf6c75.png)

Please assign me this issue under GSSOC'21 participation @harshgupta20 @ridsuteri @991rajat @urvashi-code1255

**Comment by ridsuteri** [comment]
@YasmineEl-shahat search box looks exactly like the above image, can you share the gif/img of how will it look after improvement ?

**Comment by YasmineEl-shahat** [comment]
I won't change it's style . I'll add a feature that when I hit enter the results is shown not only when I click on the search icon.

**Comment by ridsuteri** [comment]
ok go ahead @YasmineEl-shahat :)

**Comment by harshgupta20** [comment]
thanks for contributing, PR has been merged
