### ISSUE TITLE
Lyrics Search App

### ISSUE THREAD

**Issue by viraldevpb** [Vishal-raj-1/Awesome-JavaScript-Projects#1593]
## Feature Add
I found in this repository there is no app that searches the music and related it's lyrics so I came with idea to add lyrics search app in Javascript. I would like to add this files into your repository as an contributor.

## Additional context
Assign me this issue under GSSOC' 21!

**Comment by Amit366** [comment]
@ridsuteri can I work??

**Comment by viraldevpb** [comment]
I am Already Working on It

**Comment by viraldevpb** [comment]
@Amit366 You can work on this project!!

**Comment by harshgupta20** [comment]
@Amit366 You can send the PR now
