### ISSUE TITLE
Minesweeper

### ISSUE THREAD

**Issue by Amit366** [Vishal-raj-1/Awesome-JavaScript-Projects#1598]
## Is your feature request related to a problem? Please describe.
No its not a problem. I will add a minesweeper game
## Describe the solution you'd like
@991rajat @ridsuteri I am a GSSOC participant and would like to work in javascript.
Please assign this to me.

## Additional context
Add any other context about the feature request here.

**Comment by Amit366** [comment]
@991rajat @ridsuteri please assign this to me

**Comment by ridsuteri** [comment]
@Amit366 minesweeper game has already been added  through #1217 :(
if you want to work on it's improvement do open another issue !
