### ISSUE TITLE
Counter: Give style to button

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#16]

**Comment by khushi935** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by khushi935** [comment]
Can you specify which button style should I change?

**Comment by khushi935** [comment]
![button](https://user-images.githubusercontent.com/62712155/107181182-4da2ef00-6a00-11eb-991d-76fad6893ec0.png)

Does this look good? Or Should I add animation?
The button of "color flipper" is the effect after hover.

**Comment by Vishal-raj-1** [comment]
Hey @khushi935 thank you for showing your interest in this project. Yes you can do this & I guess it will be great if you align this button center. And Also change the button style of counter project. 
![counter](https://user-images.githubusercontent.com/59874304/107182457-ca36cd00-6a02-11eb-9141-14f8d5527a14.JPG)

**Comment by khushi935** [comment]
@Vishal-raj-1  I have a small doubt, I need to align text(ex calculator) as well as visit button in center?

**Comment by Vishal-raj-1** [comment]
@khushi935 YES !! You have to align both of them !!

**Comment by khushi935** [comment]
https://user-images.githubusercontent.com/62712155/107210236-dda95e80-6a29-11eb-8198-4edf12399c98.mp4

Does this look good?

**Comment by Vishal-raj-1** [comment]
@khushi935 This looks awesome !! Can you do one more thing ? Increase height of the project images. and give some fixed heights so that there would not be any extra white spaces.

Thanks

**Comment by khushi935** [comment]
okay, I will do it.

**Comment by khushi935** [comment]
![Screenshot (47)](https://user-images.githubusercontent.com/62712155/107212862-9624d180-6a2d-11eb-82ab-0584d4d36525.png)

Does this look good?

**Comment by Vishal-raj-1** [comment]
@khushi935 Perfect send the PR for the same !!

**Comment by Ruchip16** [comment]
Does this issue is resolved?

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?

**Comment by Asmita-si** [comment]
I want to work on this issue. Can you please assign it to me? @Vishal-raj-1  @urvashi-code1255

**Comment by urvashi-code1255** [comment]
> @Vishal-raj-1 Does this issue is resolved?

yes
