### ISSUE TITLE
Text to voice conversion

### ISSUE THREAD

**Issue by Sapna2001** [Vishal-raj-1/Awesome-JavaScript-Projects#160]
I would like to add the voice generator to the list of projects using HTML, CSS, JS.

In this mini-project, the text will be converted to voice.

Features:
1. Different accent
2. rate and pitch can be set
3. the speech can be stopped and restarted anytime

@urvashi-code1255 I would love to work on this issue as a part of GSSOC 2021 and I will start working on this when the contribution period starts. Please assign me this issue.

**Comment by Avnish5** [comment]
I am doing web dev from last 1 year.
I am also selected as a participant under GSSOC 2021.
Kindly assign this task to me...

**Comment by Vishal-raj-1** [comment]
@Sapna2001 Sure Sapna you can !! @Avnish5 You can check other issues

**Comment by Avnish5** [comment]
> @Sapna2001 Sure Sapna you can !! @Avnish5 You can check other issues

OKK

**Comment by Sapna2001** [comment]
Please add a label for GSSoC 21.
As mentioned on Discord, the points will be provided for GSSoC labels only
@urvashi-code1255
