### ISSUE TITLE
Project Idea: Relaxer application

### ISSUE THREAD

**Issue by vanshikachokhani** [Vishal-raj-1/Awesome-JavaScript-Projects#1606]
I want to contribute a relaxer application project in javascript.
This is a screenshot of the project.
![Screenshot from 2021-05-23 18-58-33](https://user-images.githubusercontent.com/54857354/119262445-e6006080-bbf8-11eb-8b84-9db9f52fb066.png)
Please assign me this issue under Gssoc'21 @ridsuteri @991rajat @harshgupta20

**Comment by harshgupta20** [comment]
Similar project already exist
