### ISSUE TITLE
addition of page scroll indicator

### ISSUE THREAD

**Issue by robin025** [Vishal-raj-1/Awesome-JavaScript-Projects#1611]
# Feature Add
I found in this repository there is no app having page scroll indicator project, i would like to work on this issue

# Additional context
Assign me this issue under GSSOC' 21!

**Comment by coding-geek21** [comment]
I would like to work on this @Ankita297 please assign me

**Comment by Ankita297** [comment]
@coding-geek21 go ahead

**Comment by Ankita297** [comment]
@coding-geek21 any updates ?

**Comment by coding-geek21** [comment]
> @coding-geek21 any updates ?

Sorry, My sem exams got over recently only , I will make PR by tomorrow for sure 👍
