### ISSUE TITLE
Portfolio page 

### ISSUE THREAD

**Issue by Ankita297** [Vishal-raj-1/Awesome-JavaScript-Projects#1625]
## Is your feature request related to a problem? Please describe.
I want to add a page for Portfolio .
## Describe the solution you'd like
I have updated sidenav.html and added sidenav.css for changing current sidenav project into animated sidenav

## Additional context
Add any other context about the feature request here.

**Comment by Amrutha1101** [comment]
I would like to work on this issue under LGMSOC.
Can you elaborate the issue pl?

**Comment by Atif0604** [comment]
Can i work on this @Rizwan-S

**Comment by Rizwan-S** [comment]
Sure!
