### ISSUE TITLE
Css gradient background animated

### ISSUE THREAD

**Issue by Ankita297** [Vishal-raj-1/Awesome-JavaScript-Projects#1626]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to enhancing the look of sidenav.
## Describe the solution you'd like
I have updated sidenav.html and added sidenav.css for changing current sidenav project into animated sidenav

## Additional context
Add any other context about the feature request here.

**Comment by Ankita297** [comment]
@ridsuteri @harshgupta20  can i work on this ?
https://user-images.githubusercontent.com/67833077/119321631-78a50c00-bc9a-11eb-9f8e-d45a725b24f0.mp4

**Comment by ridsuteri** [comment]
sorry @Ankita297, but a css gradient background generator already exists :(
