### ISSUE TITLE
URL Shortener

### ISSUE THREAD

**Issue by yashsehgal** [Vishal-raj-1/Awesome-JavaScript-Projects#163]
## Describe the solution you'd like
I want to contribute, one of the javascript-based projects of mine, which is a URL Shortner Application. I would love that you'll assign me to work and will merge my project into your codebase :)

## Additional context
Currently, This project is under the development phase, I am still working on the frontend part.

*If you want to take a look at the project code, here's the GitHub repository link*
https://github.com/yashsehgal/url.shrt

**Comment by Vishal-raj-1** [comment]
@yashsehgal We already have `url shortener`. Kindly improve that project.

**Comment by yashsehgal** [comment]
> @yashsehgal We already have `url shortener`. Kindly improve that project.

Okay, That's great too. I will work on that.
