### ISSUE TITLE
Drink Water App

### ISSUE THREAD

**Issue by bitaashna** [Vishal-raj-1/Awesome-JavaScript-Projects#1641]
Simple app to count intake of water.
In this we will be having a fixed goal of 2L and at a time we can drink 250 ml of water. So 8 glasses 250 ml each will be there which will act like buttons  to add or remove the number of drinks recorded.

@urvashi-code1255 @Vishal-raj-1 @ridsuteri I would like to contribute to it as a part of GSSOC'21 
Please assign it to me.

**Comment by harshgupta20** [comment]
Similar project already exist, can you plz describe it more, or attach some photos or gifs so that we can see

**Comment by bitaashna** [comment]
@harshgupta20  Please refer the below images
![Screenshot from 2021-05-30 01-22-49](https://user-images.githubusercontent.com/57864526/120083324-8ff25800-c0e5-11eb-9ca4-0188717c4f9a.png)
![Screenshot from 2021-05-30 01-22-46](https://user-images.githubusercontent.com/57864526/120083333-97196600-c0e5-11eb-869d-549cbef68b85.png)
![Screenshot from 2021-05-30 01-22-42](https://user-images.githubusercontent.com/57864526/120083334-997bc000-c0e5-11eb-9d78-ffe3451d1aee.png)
![Screenshot from 2021-05-30 01-22-30](https://user-images.githubusercontent.com/57864526/120083336-9c76b080-c0e5-11eb-8956-9f7ce15c3577.png)

**Comment by ridsuteri** [comment]
@bitaashna exactly similar project already exists :( hence i am closing this one
