### ISSUE TITLE
github-profiles

### ISSUE THREAD

**Issue by Ayush7614** [Vishal-raj-1/Awesome-JavaScript-Projects#165]
## Is your feature request related to a problem? Please describe.
github-profiles

## Describe the solution you'd like
This application gives your github profile statics like followers repo etc

## Additional context
Add any other context about the feature request here.

**Comment by Ayush7614** [comment]
@Vishal-raj-1 plss assign me this issue under crosswoc

**Comment by Vishal-raj-1** [comment]
@Ayush7614 This will be awesome project. Once you complete quiz app I will assign this issue to you as well.

**Comment by Ayush7614** [comment]
@Vishal-raj-1 now plss assign me under crosswoc

**Comment by JaveedYara72** [comment]
@Vishal-raj-1 can i work on this?

**Comment by Asmita-si** [comment]
I want to work on this issue. Can you please assign it to me? @Vishal-raj-1  @urvashi-code1255

**Comment by harshgupta20** [comment]
@Ayush7614 Any update ? Kindly reply within 2 days or I have to close this.
