### ISSUE TITLE
Image search project

### ISSUE THREAD

**Issue by Ankita297** [Vishal-raj-1/Awesome-JavaScript-Projects#1654]
## Is your feature request related to a problem? Please describe.
In this there will be search box user will type fill in it and imag related to it will be availbale .
## Describe the solution you'd like
I have updated sidenav.html and added sidenav.css for changing current sidenav project into animated sidenav

## Additional context
Add any other context about the feature request here.

**Comment by Ankita297** [comment]
Can i work on this @ridsuteri ?

**Comment by ridsuteri** [comment]
@Ankita297 please try to provide a brief description of the issue :) 
please share image/gif of the project,
also I think the issue template is also incorrectly filled , please correct it :)
