### ISSUE TITLE
Checkers game

### ISSUE THREAD

**Issue by Amit366** [Vishal-raj-1/Awesome-JavaScript-Projects#1656]
## Is your feature request related to a problem? Please describe.
No its not a problem. I will add checkers game
## Describe the solution you'd like
I am a GSSOC participant and would like to contribute in Javascript.
@ridsuteri please assign it to me

## Additional context
Add any other context about the feature request here.

**Comment by Amit366** [comment]
@harshgupta20 since it is a game won't it be a level 3??

**Comment by harshgupta20** [comment]
@Amit366 It not only about game but how complex it is and what are things you have used in this defines the level tag : )

**Comment by Amit366** [comment]
Ok
