### ISSUE TITLE
insect-catch-game

### ISSUE THREAD

**Issue by Ayush7614** [Vishal-raj-1/Awesome-JavaScript-Projects#166]
## Is your feature request related to a problem? Please describe.
insect-catch-game

## Describe the solution you'd like
This is insect catching game in javascript  when you catch the insect the score was increase

## Additional context
Add any other context about the feature request here.

**Comment by Ayush7614** [comment]
@Vishal-raj-1 plss assign me this issue under crosswoc

**Comment by Vishal-raj-1** [comment]
complete one issue first !!

**Comment by gaurav24072002** [comment]
Hey !! 
Can you assign this to me as I have made the same project once so I can solve any issue in it for sure.
please assign me this issue under GSSOC '21

**Comment by Ayush7614** [comment]
no @gaurav24072002 i have to work on the issue first i will ask to @Vishal-raj-1

**Comment by gaurav24072002** [comment]
Hey !! it's not a compitation any one can contribute that's the main aim of Open-Source..... lets work together in it.. ok.

**Comment by Vishal-raj-1** [comment]
@gaurav24072002 & @Ayush7614 I have assigned some projects to you already once you finished those project, Then both of you can work on this, till now we have more than 20+project but once the GSSOC open I will open more issues for every project because now they are looking only basic project. So dont worry you both of have many issues to solve.

**Comment by Ayush7614** [comment]
@Vishal-raj-1 now plss assign me this issue under gssoc

**Comment by Ayush7614** [comment]
@Vishal-raj-1 now plss assign me under gssoc

**Comment by Ayush7614** [comment]
@Vishal-raj-1 plss assigne me under gssoc i continuosuly msg you everyday plss respond it bro

**Comment by gaurav24072002** [comment]
Brother Please wait you will get reply from him have patience ...

**Comment by Ayush7614** [comment]
@urvashi-code1255 plss level it with gssoc

**Comment by urvashi-code1255** [comment]
@Ayush7614 there is no level tag yet for the gssoc.

**Comment by Ayush7614** [comment]
Plss level it for gssoc i see in many projects they can level for gssoc

**Comment by harshgupta20** [comment]
Hi @Ayush7614 since you have made created it before 8 march so it can't be tagged with gssoc21.
