### ISSUE TITLE
Active link : highlight which link is active in navbar

### ISSUE THREAD

**Issue by sheetalj2205** [Vishal-raj-1/Awesome-JavaScript-Projects#1668]
## Describe the bug
in the navbar which page is active is not visible now, I want to add active link feature
## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by RR-Sahoo** [comment]
can I work on this as I am a participant of LGM-SOC.

**Comment by Ankita297** [comment]
@sheetalj2205 any updates ?

**Comment by Amrutha1101** [comment]
Can I work on this issue under LGMSOC?

**Comment by Ankita297** [comment]
@Amrutha1101 go for it .
