### ISSUE TITLE
quiz-app

### ISSUE THREAD

**Issue by Ayush7614** [Vishal-raj-1/Awesome-JavaScript-Projects#167]
## Is your feature request related to a problem? Please describe.
quiz-app

## Describe the solution you'd like
This is quiz app made of javascript it will ask random question

## Additional context
Add any other context about the feature request here.

**Comment by Ayush7614** [comment]
@Vishal-raj-1 plss assign me this issue under crosswoc

**Comment by Vishal-raj-1** [comment]
Sure !!
