### ISSUE TITLE
Compound Interest Calculator

### ISSUE THREAD

**Issue by SrishtiArya07** [Vishal-raj-1/Awesome-JavaScript-Projects#1670]
## Is your feature request related to a problem? Please describe.
No its not a problem. I want to add a new feature called Compound Interest Calculator.
## Describe the solution you'd like
Compound interest is the interest on a loan or deposit calculated based on both the initial principal and the accumulated interest from previous periods. This tool will calculate the compound interest using HTML, CSS, and javascript.
## Additional context
Please assign this issue to me under GSSOC 21.

**Comment by harshgupta20** [comment]
Similar project already exist

**Comment by SrishtiArya07** [comment]
> Similar project already exist

I've checked. The project that already exists is of simple interest. I want to make Compound Interest Calculator

**Comment by 991rajat** [comment]
@harshgupta20
