### ISSUE TITLE
Chat bot Feature 

### ISSUE THREAD

**Issue by anjali1102** [Vishal-raj-1/Awesome-JavaScript-Projects#1677]
Simulates human-like conversations with users via text messages on chat. Its key task is to help users by providing answers

**Comment by anjali1102** [comment]
assign me with the required labels

**Comment by harshgupta20** [comment]
@anjali1102 Can you make this using pure vanilla JS ?

**Comment by anjali1102** [comment]
Yes sure

**Comment by harshgupta20** [comment]
Ok Great, you can send the PR for it : )
