### ISSUE TITLE
Adding Project Memory Game

### ISSUE THREAD

**Issue by ravireddy07** [Vishal-raj-1/Awesome-JavaScript-Projects#168]
## Is your feature request related to a problem? Please describe.

This is a Javascript game. There will be 16 cards, which hiding 8 different symbols/icons, where we have to flip two cards one after the other of same symbol/icon. If we fail to select same two cards, then the cards will get closed, but the symbol behind that cards will remain same in current game. We have to open all cards as soon as possible. There will be a timer which runs from your first move & you'll get rating based on the time you took to complete.

## Additional context
Add any other context about the feature request here.

This is one of my Udacity Nanodegree Project, I have written this code on my own from scratch. And i would like to add that project to this collection. Here is the [Original Repo of mine](https://github.com/Google-India-Scholarship/GoogleIndiaScholarship_PCC2_Project_Memory-Game).

Here is the Sample Output of the Project:  [Start Game](https://google-india-scholarship.github.io/GoogleIndiaScholarship_PCC2_Project_Memory-Game/)

And i would like to contribute as in Normal, i mean not a part of any program.
Pls, let me know you comments !

<img width="958" alt="download" src="https://user-images.githubusercontent.com/26524467/109296098-d4a3f400-7855-11eb-9848-6021a4f0ab10.png">

**Comment by urvashi-code1255** [comment]
Hey @ravireddy07 welcome to the project. I love your project. Go for it and add it. Eagerly waiting for your PR :)

**Comment by ravireddy07** [comment]
The initial PR was not complete that i forgotten to add this project in collection.

**Comment by ravireddy07** [comment]
Closing
