### ISSUE TITLE
Add Note Making App project

### ISSUE THREAD

**Issue by prayas7102** [Vishal-raj-1/Awesome-JavaScript-Projects#1690]
## Is your feature request related to a problem? Please describe.

No its not a problem. I am suggesting this Vanilla JavaScript project to add under the group of projects.

## Describe the solution you'd like

This project works similar to a Scribble pad. The web app can be used to create and store random notes.
This web app is responsive and uses bootstrap cards to show information stored in local web storage.
User can add and delete a note by just clicking a button.
Check the following git hub link to know more about this project : https://github.com/prayas7102/Note-Making-Web-App-using-JavaScript-and-Local-Storage.

## Additional context

This project would help students to explore about local web storage.
<img width="960" alt="notegssoc" src="https://user-images.githubusercontent.com/71717433/120020720-b9d54d00-c007-11eb-85d5-55062fc301bc.png">

**Comment by harshgupta20** [comment]
Similar project already exist
