### ISSUE TITLE
Adding show and hide password option in sign in form

### ISSUE THREAD

**Issue by kanishka8276** [Vishal-raj-1/Awesome-JavaScript-Projects#1694]
I will like to add Show and Hide password option in sign in form.
Please assign this to me.
GSSoC'21.

**Comment by mdinesh124** [comment]
@harshgupta20 Please assign me this issue under LGMSOC,

**Comment by Ankita297** [comment]
@mdinesh124 you can work on this .

**Comment by mdinesh124** [comment]
Ok, I will start my work.

**Comment by mdinesh124** [comment]
@Ankita297 I have added show hide feature in password
