### ISSUE TITLE
Talk with Banana : Javascript fun game

### ISSUE THREAD

**Issue by sheetalj2205** [Vishal-raj-1/Awesome-JavaScript-Projects#1698]
## Is your feature request related to a problem? Please describe.
No. I have made a fun game using vanilla js.  I want to add this in js projects.
## Describe the solution you'd like
![sug](https://user-images.githubusercontent.com/64475191/120068829-66fba400-c0a0-11eb-8b09-c5ae3c0418ba.JPG)
  
Currently It's UI look like this.

## Additional context
Add any other context about the feature request here.

**Comment by harshgupta20** [comment]
This project already exist.
