### ISSUE TITLE
Calculator: Allow typing on the keyboard

### ISSUE THREAD

**Issue by synox** [Vishal-raj-1/Awesome-JavaScript-Projects#17]
Either make the textfield editable, or mark it as readonly and setup keyboard listeners to react to the keypresses. 

Important to keep the code short and easy to understand.

**Comment by Vishal-raj-1** [comment]
Thanks for raising the issues !! You can work on this issue !!

**Comment by bitaashna** [comment]
Hey @Vishal-raj-1 !! I would like to contribute to it. I will setup keyboard listeners to react to the keypresses. 
Can u please assign this task to me.

**Comment by Vishal-raj-1** [comment]
@bitaashna Sure !!

**Comment by bitaashna** [comment]
@Vishal-raj-1 I have created a pull request to the issue. PLease check it and let me know.

**Comment by bitaashna** [comment]
@urvashi-code1255 please mention the labels.For this issue labels were not mentioned.
