### ISSUE TITLE
Panorama Cube

### ISSUE THREAD

**Issue by TidbitsJS** [Vishal-raj-1/Awesome-JavaScript-Projects#1709]
## Panorama Cube

Creating a panorama cube with Three JS in JavaScript

### Event

Part of gssoc21

**Comment by harshgupta20** [comment]
@TidbitsJS Spamming warning, You are creating multiple issue for same PR ( 3D Cube controls #1700 ), If we found this again we may need to close all your issues and PR. Right away

**Comment by TidbitsJS** [comment]
> @TidbitsJS Spamming warning, You are creating multiple issues for the same PR ( 3D Cube controls #1700 ), If we found this again we may need to close all your issues and PR. Right away

@harshgupta20, sorry, but I am not spamming. I have created different PRs for different issues. There are three different cube projects made using Three JS ( all of them created by me ). The cube projects are named as - 1) Simple Cube 2) Cube with texture & 3) Panorama effect cube. I was working on that. & if the concern is of creating multiple issues, then I think, I am clear in that as well. Everyone is doing the same, so am I. If you still find it as a violation or spamming, then kindly let me know.
