### ISSUE TITLE
3D Texture Cube Controls

### ISSUE THREAD

**Issue by TidbitsJS** [Vishal-raj-1/Awesome-JavaScript-Projects#1712]
## 3D Texture Cube Controls

Adding orbits controls effects so that the user can interact with the cube with Three Js in JavaScript.

### Event

Part of gssoc21

**Comment by harshgupta20** [comment]
@TidbitsJS Spamming warning, You are creating multiple issue for same PR ( 3D Cube controls #1700 ), If we found this again we may need to close all your issues and PR. Right away
