### ISSUE TITLE
Projects are not visible on the side.

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#1715]
## Describe the bug
While resolving some merge conflicts, this bug arises !!

## To Reproduce
1.  Check projects section of the website

## Expected behavior
Projects should be visible.

**Comment by Ankita297** [comment]
Can i work on this @Vishal-raj-1 ?

**Comment by Vishal-raj-1** [comment]
Yes @Ankita297

**Comment by Ankita297** [comment]
@Vishal-raj-1 the projects are now visible but there are some projects which are repeated or their image  in project section is not visible so can i work on this ?
![Projects _ Awesome JavaScript - Google Chrome 30-05-2021 21_44_01](https://user-images.githubusercontent.com/67833077/120111794-fb453400-c190-11eb-981d-106027038885.png)
![Projects _ Awesome JavaScript - Google Chrome 30-05-2021 21_44_49](https://user-images.githubusercontent.com/67833077/120111801-fda78e00-c190-11eb-8e1a-e26a7c463e03.png)
