### ISSUE TITLE
Animated Navigation

### ISSUE THREAD

**Issue by bitaashna** [Vishal-raj-1/Awesome-JavaScript-Projects#1722]
I would like to add a  new app for "Animated Navigation" as a GSSOC'21 participant.

![gif_20210530_042005 (1)](https://user-images.githubusercontent.com/57864526/120087063-70b5f380-c102-11eb-9d32-68aed864a77e.gif)
@991rajat @urvashi-code1255 @harshgupta20 @ridsuteri Please assign it to me.

**Comment by ridsuteri** [comment]
@bitaashna similar project already exists, hence i am closing this one :(
