### ISSUE TITLE
Blurry Loading Interface 

### ISSUE THREAD

**Issue by gaurav24072002** [Vishal-raj-1/Awesome-JavaScript-Projects#175]
#169
Blurry Loading Interface
A new project..

**Comment by urvashi-code1255** [comment]
Hey @gaurav24072002 I told you to follow the issue template and explain your project!!

Please do that

**Comment by medhavi11** [comment]
I would like to work on this issue, I am GSSOC 2021 participant.

**Comment by urvashi-code1255** [comment]
Hi @medhavi11 Welcome to the project! Please have a look at other issues in this project. As @gaurav24072002 has already made a PR for this one :)

**Comment by gaurav24072002** [comment]
Hey !! @urvashi-code1255 I have solved all the issues on #238 ... Please check it and merge it...

**Comment by subhangi2731** [comment]
can you please assign it to me?

**Comment by Vishal-raj-1** [comment]
It is already done. could you please check another issue @subhangi2731
