### ISSUE TITLE
Magic Note App: Replace alert box with bootstrap alert

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#176]
## Is your feature request related to a problem? Please describe.
Currently it show normal alert box, which is not look nice to me.

![bootstrap alert](https://user-images.githubusercontent.com/59874304/109396826-69dbe100-7959-11eb-8066-d783ce76238d.JPG)

## Describe the solution you'd like
Use bootstrap alert for styling

**Comment by mtwn105** [comment]
Hi @Vishal-raj-1  

I would like to work on this.

**Comment by tinchods93** [comment]
I could work on this also.

**Comment by urvashi-code1255** [comment]
Go for it @mtwn105

**Comment by tinchods93** [comment]
Were you able to solve this? If not, I can tackle it for you.
