### ISSUE TITLE
Overlap  and double icon

### ISSUE THREAD

**Issue by SamikshaSankar** [Vishal-raj-1/Awesome-JavaScript-Projects#1777]
## Describe the bug
1. Github icons are double
2. In top-button one circle are there 
3. theme changer and chatbot overlapping each other
 

## Expected behavior
1. outer-circle of top button will be removed (Not top-button  removed just extra circle will removed)
2. change the position of Chatbbot into right-bottom corner/ lower to top-button

## Environment (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox

![git2](https://user-images.githubusercontent.com/52104082/121056253-a4b4a700-c7db-11eb-809b-fdadfd226b86.jpg)

please assign me

**Comment by RakeshCharpe** [comment]
Can i work on this issue?

**Comment by SamikshaSankar** [comment]
@Vishal-raj-1 please assigned this issue...program has been started

**Comment by Ankita297** [comment]
The changes are done  . @SamikshaSankar  . So i am closing this issue . Kindly checkout other issues .
