### ISSUE TITLE
Wants to add date and time feature in Notes App!!

### ISSUE THREAD

**Issue by Kartikey0205** [Vishal-raj-1/Awesome-JavaScript-Projects#1778]
I want to add date and time feature in it , so that one who is adding notes keeps reference when he/she has added that note.
@Vishal-raj-1 , @urvashi-code1255  I will be thankful to you if you assign me under Lgm-Soc

/assign

**Comment by Kartikey0205** [comment]
Hey @Vishal-raj-1 when will you assign this to anyone??

**Comment by Kartikey0205** [comment]
@Vishal-raj-1 @urvashi-code1255 ???

**Comment by Ankita297** [comment]
@Kartikey0205 you can work on this .
