### ISSUE TITLE
Want to change the UI of the Dinosaur Game!!

### ISSUE THREAD

**Issue by mitali-1703** [Vishal-raj-1/Awesome-JavaScript-Projects#1779]
Hey @Vishal-raj-1 I would love to change the UI of the dinosaur game along with some background music when the dinosaur hits the obstacle. Could you please assign me this under LGM-SOC'21so that I can enhance its look?

**Comment by Kartikey0205** [comment]
Hey @Vishal-raj-1 I want to work on this issue please assign me if possible under Lgm-soc '21
