### ISSUE TITLE
Magic Note App: Mark as favorite

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#178]
## Is your feature request related to a problem? Please describe.
We can star some notes as well. 

## Describe the solution you'd like
Top Right side of the note card give star icon, and if user click on this icon, then mark this note as favorite/important. 

P.S: We have to also implement search functionality for it as well i.e, we can see all important notes in one place.

**Comment by tinchods93** [comment]
Hello! I would like to give this issue a try. Can you assign it to me?

**Comment by Vishal-raj-1** [comment]
@tinchods93 sure !!
