### ISSUE TITLE
New Project.

### ISSUE THREAD

**Issue by aktamoli0910** [Vishal-raj-1/Awesome-JavaScript-Projects#1780]
Can I contribute with a javascript project as a part of LGM-SOC-21?
It is a  TO-DO-LIST project with all the required features.

**Comment by aktamoli0910** [comment]
Can i work on this issue under LGM-SOC-21?

**Comment by Vishal-raj-1** [comment]
It's already there, if you want to improve that then you can otherwise try for other projects (don't need to work on already exist project from scratch)
