### ISSUE TITLE
Password Generator New Project

### ISSUE THREAD

**Issue by Veeresh-Rex** [Vishal-raj-1/Awesome-JavaScript-Projects#1784]
###  New Project
Hey,I am from LGM-SOC 21 .  I want to add password generator project .

**Comment by Veeresh-Rex** [comment]
@Vishal-raj-1  please assign me this issue.

**Comment by Veeresh-Rex** [comment]
> 
> 
> @Vishal-raj-1 please assign me this issue.

I'm LGM-SOC21 participant So please assign me labels of LGMSOC21.

**Comment by Veeresh-Rex** [comment]
There is already a "password generator project". should i make another password generator app.
@Vishal-raj-1

**Comment by Ankita297** [comment]
you can modify it @Veeresh-Rex  if you want ?

**Comment by Ankita297** [comment]
@Veeresh-Rex any updates ?

**Comment by 7JKaushal** [comment]
I'd love to contribute to this! is it still open?

**Comment by Ankita297** [comment]
@7JKaushal go for it .

**Comment by Ankita297** [comment]
@joshi-kaushal any updates ?

**Comment by joshi-kaushal** [comment]
yes my project is done i was waiting for Bar Char PR to get accepted. I guess we can't make multiple PRs at the same time

**Comment by Ankita297** [comment]
@joshi-kaushal  you should make different PR's from different branches .

**Comment by joshi-kaushal** [comment]
@Ankita297 Yeah got that, I have made a PR for Password generator too
