### ISSUE TITLE
Can I add a Quiz App in this project?

### ISSUE THREAD

**Issue by khushi-purwar** [Vishal-raj-1/Awesome-JavaScript-Projects#1785]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to enhancing the look of sidenav.
## Describe the solution you'd like
I am a LGM-SOC21 participent and I wanna add my javascript quiz app in this repo???

**Comment by Vishal-raj-1** [comment]
It's already there, if you want to improve that then you can go for it otherwise explore other project from the website.
