### ISSUE TITLE
Update the footer design and layout

### ISSUE THREAD

**Issue by Ciggzy1312** [Vishal-raj-1/Awesome-JavaScript-Projects#1788]
I would like to change the layout of the footer section
And add separate columns for About us section and links in the footer

Please assign this issue it to me under LGM-SOC tag

**Comment by Tulsi25** [comment]
Hii, I am a LGM-SOC'21 participants , would like to update the footer design and layout. 
I want to  update on footer with some columns and rows so that it would look symmetrical.

please assign this issue to me

**Comment by Vishal-raj-1** [comment]
is it done ? if yes then don't forget to mention issue number in your PR otherwise it will not be counted
