### ISSUE TITLE
Calculator: Bug 

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#179]
## Describe the bug
let say when we are doing `8*9 = 72` but now if want to do `72-6`, it show `8*9-6`.

## To Reproduce
Check the video

https://user-images.githubusercontent.com/59874304/109397160-5e89b500-795b-11eb-949f-2920a746c0b8.mp4

## Expected behavior
It should show final result only. Means it should show `72-6` instead of `8*9-6`

## Environment (please complete the following information):
 - OS: Window
 - Browser: chrome

**Comment by satcasm** [comment]
Hi, would like to work on this under GSSOC' 21.
Thanks.

**Comment by urvashi-code1255** [comment]
Go for it @satcasm

**Comment by satcasm** [comment]
Should I wait till 8th march ? As on that day GSSOC' 21 coding period starts or should I start now?
Thanks.

**Comment by urvashi-code1255** [comment]
> Should I wait till 8th march ? As on that day GSSOC' 21 coding period starts or should I start now?
> Thanks.

You can start working on it and send the PR. I will review it and will merge it after 8!
