### ISSUE TITLE
Simple calculator using javascript 

### ISSUE THREAD

**Issue by siddhi-244** [Vishal-raj-1/Awesome-JavaScript-Projects#1791]
## Is your feature request related to a problem? Please describe.
No its not a problem. I would like to add my project calculator. I am a lgmsoc participant

**Comment by siddhi-244** [comment]
Shall I add it?

**Comment by siddhi-244** [comment]
I haven't got any info regarding this issue !

**Comment by Vishal-raj-1** [comment]
Siddhi, there is already this project, you can make new project which haven't added yet or you can improve these projects because there's lot of improvement required.
