### ISSUE TITLE
Remove Extra Github Icon

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#1792]
## Describe the bug
Remove this extra github icon
![extra](https://user-images.githubusercontent.com/59874304/121728456-ebbbd880-cb0a-11eb-8158-0917f16cf0b3.JPG)

**Comment by RiyaGupta89** [comment]
I can work on this issue sir. Please assign me the issue.

**Comment by Vishal-raj-1** [comment]
Sure RIya go for it

**Comment by RiyaGupta89** [comment]
I have resolved this issue. Please review my code.
