### ISSUE TITLE
shift the theme changing button in navbar

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#1793]
![color](https://user-images.githubusercontent.com/59874304/121728974-903e1a80-cb0b-11eb-8bdc-0fc4e056a67f.JPG)

**Comment by jugeshraghav** [comment]
i would like to work on the issue. please assign it to me @Vishal-raj-1

**Comment by Vishal-raj-1** [comment]
sure

**Comment by Ankita297** [comment]
@jugeshraghav any updates ?
