### ISSUE TITLE
some projects are displayed twice.

### ISSUE THREAD

**Issue by jugeshraghav** [Vishal-raj-1/Awesome-JavaScript-Projects#1795]
## Describe the bug
Some projects are displayed twice.

## To Reproduce
some projects in the projects section are displayed twice. Prefix expression evaluator, random name generator , purple rain and re-create giphy are displayed twice in the project section.

![Screenshot (86)](https://user-images.githubusercontent.com/74092377/121784117-b4fbc600-cbcf-11eb-9da1-258cd10d0b71.png)
![Screenshot (87)](https://user-images.githubusercontent.com/74092377/121784119-b6c58980-cbcf-11eb-9daa-3741dc74303c.png)

**Comment by Vishal-raj-1** [comment]
Go for it

**Comment by jugeshraghav** [comment]
I am not able to clone this repository in my local machine. Every time i try to clone it shows some error.

**Comment by jugeshraghav** [comment]
can you help me out @Vishal-raj-1

**Comment by Ankita297** [comment]
@jugeshraghav  Please tell me the issue you are facing .

**Comment by Atif0604** [comment]
can i work on this @Ankita297 @Vishal-raj-1

**Comment by Ankita297** [comment]
@jugeshraghav  any updates ?

**Comment by jugeshraghav** [comment]
@Ankita297 This repository is not being cloned in my local environment

**Comment by Atif0604** [comment]
Please Assign it to me @Ankita297

**Comment by Ankita297** [comment]
@jugeshraghav can you share some screenshot or tell me the error

**Comment by Ankita297** [comment]
@jugeshraghav any updates ?

**Comment by Atif0604** [comment]
> @jugeshraghav any updates ?

Can i Work on this now @Ankita297 as the Participant isn't responding

**Comment by Ankita297** [comment]
go ahead  @Atif0604 .
