### ISSUE TITLE
Calculator: neumorphism css

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#180]
## Is your feature request related to a problem? Please describe.
Change background of the website/calculator, remove outline of the button. Currently it show square box on clicking the box.

## Describe the solution you'd like
Change the background , I prefer neumorphism css for this project.

**Comment by Mukta-Sawant** [comment]
@Vishal-raj-1 @urvashi-code1255 Can I work on this issue? I would like to solve this as a part of GSSOC'21. Please assign it to me.

**Comment by urvashi-code1255** [comment]
Sure go for it @Mukta-Sawant

**Comment by Mukta-Sawant** [comment]
![Screenshot (168)](https://user-images.githubusercontent.com/77935961/109697396-25984d00-7bb4-11eb-8f8b-eb0b7a2d27c5.png)
@urvashi-code1255 @Vishal-raj-1 please check this out and do let me know the changes.

**Comment by Mukta-Sawant** [comment]
> ![Screenshot (168)](https://user-images.githubusercontent.com/77935961/109697396-25984d00-7bb4-11eb-8f8b-eb0b7a2d27c5.png)
> @urvashi-code1255 @Vishal-raj-1 please check this out and do let me know the changes.

Or should I make buttons neumorphic too? like given in the picture?
![Screenshot (170)](https://user-images.githubusercontent.com/77935961/109702237-fe447e80-7bb9-11eb-832c-2bf94e5c1a9a.png)

**Comment by urvashi-code1255** [comment]
Yes @Mukta-Sawant make the buttons neumorphic too!

**Comment by Mukta-Sawant** [comment]
![ucCuz3rZTq](https://user-images.githubusercontent.com/77935961/110159305-891eb680-7e10-11eb-8e02-e90bc700ed29.gif)
@Vishal-raj-1 @urvashi-code1255 Please, check this!

**Comment by urvashi-code1255** [comment]
Its looking great @Mukta-Sawant . You can open a PR
