### ISSUE TITLE
Successful alert pop up feature for contact page "Send Message" button

### ISSUE THREAD

**Issue by ROHAN842** [Vishal-raj-1/Awesome-JavaScript-Projects#1801]
## Is your feature request related to a problem? Please describe.
As when user fills all the detail and clicks on "Send Message" button then site takes user 405 not allowed page.

## Describe the solution you'd like
 I want to add an alert which will pops up and will tell the user that message was delivered successfully with a green tick along with I would also like to add a feature without back end with which user would be sent to a fresh new page on clicking Send Message button where the message will be written, lets say "Thank you for your submission , Return back ".

## Additional context
Screenshots :-

![image](https://user-images.githubusercontent.com/61961107/122221621-12915a80-cecf-11eb-9b47-1f44d0ba23b4.png)

![image](https://user-images.githubusercontent.com/61961107/122221699-289f1b00-cecf-11eb-8253-956e99496dcb.png)

**Comment by Vishal-raj-1** [comment]
sure

**Comment by ROHAN842** [comment]
OK thanks

**Comment by ROHAN842** [comment]
Hey @Vishal-raj-1 after cloning in my desktop this error is coming I have tried every possible way to resolve this but was not successful can u help me in solving it,
![image](https://user-images.githubusercontent.com/61961107/122390244-65324b80-cf8f-11eb-8497-bd87bb92a153.png)

**Comment by ROHAN842** [comment]
@Vishal-raj-1 sir please review my PR
