### ISSUE TITLE
Project Section doesn't consists Signup/Login Option in the Navbar

### ISSUE THREAD

**Issue by ROHAN842** [Vishal-raj-1/Awesome-JavaScript-Projects#1808]
## Describe the bug
The Project page navbar doesn't have Signup/Login Option, I want to add this feature in the navbar.

## Additional context
![image](https://user-images.githubusercontent.com/61961107/122638574-72c40e80-d112-11eb-884e-b6a18f40c2b5.png)

**Comment by ROHAN842** [comment]
Hey @Vishal-raj-1 kindly assign this issue to me

**Comment by Ankita297** [comment]
![Awesome JavaScript _ Home - Google Chrome 21-06-2021 14_21_54](https://user-images.githubusercontent.com/67833077/122734854-155bc900-d29c-11eb-83a2-0a43bc43b3e6.png)
@ROHAN842  it is there Please see .

**Comment by ROHAN842** [comment]
@Ankita297 I am talking about projects.html page it doesn't have Sign/up Login option on the Navbar 

![image](https://user-images.githubusercontent.com/61961107/122742302-6f13c180-d2a3-11eb-8bae-977a5d6ece9a.png)

**Comment by Ankita297** [comment]
@ROHAN842 you can work on this .
