### ISSUE TITLE
Update the homeProjects Section

### ISSUE THREAD

**Issue by UJALA-TYAGI** [Vishal-raj-1/Awesome-JavaScript-Projects#1809]
I would like to make some changes in the homeProjects Section.
It will make the section look more organised and complement to the body section.

This is the current homeProjects Section.

![org](https://user-images.githubusercontent.com/69709596/122648477-192a0700-d147-11eb-8e22-519c52f02558.png)

After the changes it'll look more like:

![myedit](https://user-images.githubusercontent.com/69709596/122648542-5ee6cf80-d147-11eb-80bc-a78eff62e23d.png)

Please assign this issue to me.

Thankyou :)

**Comment by UJALA-TYAGI** [comment]
@Vishal-raj-1 
Sir, Please assign this issue to me.

**Comment by Ankita297** [comment]
@UJALA-TYAGI you can go ahead .

**Comment by UJALA-TYAGI** [comment]
Thank you so much ma'am.

**Comment by UJALA-TYAGI** [comment]
Ma'am done. Please check the code I've already made a PR.
