### ISSUE TITLE
color flipper: Styling required

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#181]
## Is your feature request related to a problem? Please describe.
Currently, Button color also changes as background color changes. 

## Describe the solution you'd like
Fixed background color of button to black. Align the text vertically.

**Comment by Ankita297** [comment]
I want to work on this issue under GSSOC . Please assign it to me.

**Comment by yashikabhargava** [comment]
@Vishal-raj-1 Hii there! I would love to work on this issue, Could you plz assign this issue to me as a part of Gssoc'21?

**Comment by urvashi-code1255** [comment]
@Ankita297 go for it!

@yashikabhargava Please look at some other issue as @Ankita297 asked for this first!

**Comment by yashikabhargava** [comment]
> @Ankita297 go for it!
> 
> @yashikabhargava Please look at some other issue as @Ankita297 asked for this first!

okay sure, thank you!

**Comment by Ankita297** [comment]
![Color Flipper - Google Chrome 03-03-2021 14_18_54](https://user-images.githubusercontent.com/67833077/109778980-7bf4a280-7c2b-11eb-9ce1-30cf977e9305.png)

**Comment by Ankita297** [comment]
Is it okay ?

**Comment by Ankita297** [comment]
![Color Flipper - Google Chrome 03-03-2021 14_17_37](https://user-images.githubusercontent.com/67833077/109779269-c83fe280-7c2b-11eb-8902-2caa1524849b.png)

**Comment by Ankita297** [comment]
Is it okay ?
