### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by ishitakapoor26** [Vishal-raj-1/Awesome-JavaScript-Projects#1810]
Design logo for website

**Comment by ishitakapoor26** [comment]
@Vishal-raj-1 pls assign this issue to me.

**Comment by Ankita297** [comment]
@ishitakapoor26 you can work on this .

**Comment by coding-geek21** [comment]
can i work on this?

**Comment by Ankita297** [comment]
issue is already assign to @ishitakapoor26 .Please look for another issues .

**Comment by Ankita297** [comment]
@ishitakapoor26 any updates ?

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 any updates ?

@Ankita297 yeah! will share all the designs by tomorrow morning.

**Comment by ishitakapoor26** [comment]
@Ankita297 pls check this design

![Awesome](https://user-images.githubusercontent.com/78542333/124722116-5a802c00-df27-11eb-9658-f786874aca04.gif)

**Comment by ishitakapoor26** [comment]
![Awesome (1)](https://user-images.githubusercontent.com/78542333/124722822-0de92080-df28-11eb-8224-35001ef1ca75.gif)

**Comment by Ankita297** [comment]
@Rizwan-S can you Please take a look into this and give your suggestions .

**Comment by Rizwan-S** [comment]
The second logo looks good. Can you remove the animation though?

**Comment by ishitakapoor26** [comment]
> The second logo looks good. Can you remove the animation though?

yeah sure!

**Comment by ishitakapoor26** [comment]
@Rizwan-S now pls have a look at it..

![Awesome](https://user-images.githubusercontent.com/78542333/124876426-9d093d80-dfe7-11eb-9201-36263f2cd557.png)

**Comment by Rizwan-S** [comment]
Excellent! @Ankita297 @Vishal-raj-1 we can continue with this logo if you don't have any suggestion.

**Comment by Ankita297** [comment]
It is very nice . 👍  . We can continue with this @Rizwan-S

**Comment by ishitakapoor26** [comment]
@Ankita297 may I open a pr?

**Comment by Ankita297** [comment]
Yes  @ishitakapoor26 go ahead .
