### ISSUE TITLE
Error 405 (Not allowed) after clicking send message button on Contact page

### ISSUE THREAD

**Issue by Ayonijakaushik19** [Vishal-raj-1/Awesome-JavaScript-Projects#1812]
## Describe the bug
#Error 405 Not allowed is showing after clicking send message button on the Contact page
## To Reproduce
1. 
2. 
3. 
4. 

## Expected behavior
It is should show "message sent successfuly and our support team will contact you soon"
## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by Ayonijakaushik19** [comment]
Hi @Vishal-raj-1, Please assign it to me.

**Comment by Vishal-raj-1** [comment]
Check it out may be it's done
