### ISSUE TITLE
Sign up with Linkedin redirecting to Vishal Raj's Linkedin profile.

### ISSUE THREAD

**Issue by Ayonijakaushik19** [Vishal-raj-1/Awesome-JavaScript-Projects#1816]
## Describe the bug
Sign up with the Linkedin button redirecting us to Vishal Raj's Linkedin profile.
## To Reproduce
1. 
2. 
3. 
4. 

## Expected behavior
It should redirect us to the Linkedin signup page.
## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by Ayonijakaushik19** [comment]
Hi @Vishal-raj-1, Please assign this to me I would like to work on this.

**Comment by Ankita297** [comment]
@Ayonijakaushik19 so what is the bug ?

**Comment by Ankita297** [comment]
@Ayonijakaushik19 ?

**Comment by Ayonijakaushik19** [comment]
Signup with LinkedIn taking me to Vishal Raj's LinkedIn profile, Instead of it should take me to the LinkedIn signup page.
