### ISSUE TITLE
Bug-2 in side Navbar

### ISSUE THREAD

**Issue by Ayonijakaushik19** [Vishal-raj-1/Awesome-JavaScript-Projects#1818]
## Describe the bug
The Twitter button on the side navbar is not redirecting us to the Twitter signup page.
## To Reproduce
1. 
2. 
3. 
4. 

## Expected behavior
It should redirect us to the Twitter signup page.
## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by Ayonijakaushik19** [comment]
Hi @Vishal-raj-1, Please assign this to me. I would like to work on this.

**Comment by Atif0604** [comment]
Can i work on this @Ankita297

**Comment by Vishal-raj-1** [comment]
@Ayonijakaushik19 & @Atif0604 anyone can work on this issue

**Comment by Atif0604** [comment]
yeah sure @Vishal-raj-1 
please give your twitter handle @Vishal-raj-1

**Comment by Vishal-raj-1** [comment]
Twitter handle : https://twitter.com/vishalraj_1
