### ISSUE TITLE
Bug-3 in Side Navbar

### ISSUE THREAD

**Issue by Ayonijakaushik19** [Vishal-raj-1/Awesome-JavaScript-Projects#1819]
## Describe the bug
The Linkedin button on the side navbar is redirecting us to Vishal raj's Linked profile.
## To Reproduce
1. 
2. 
3. 
4. 

## Expected behavior
It should redirect us to the LinkedIn sign-up page.
## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by Ayonijakaushik19** [comment]
Hi @Vishal-raj-1, I would like to work on this. Please assign this to me.

**Comment by Vishal-raj-1** [comment]
Sure @Ayonijakaushik19 !!

**Comment by Vishal-raj-1** [comment]
@Ayonijakaushik19 No it is directed to my profile so that anybody want's to connect with the owner of the project so they can connect !!
