### ISSUE TITLE
Add Hover effect to buttons in the contact Page.

### ISSUE THREAD

**Issue by UJALA-TYAGI** [Vishal-raj-1/Awesome-JavaScript-Projects#1820]
I would like to add hover effect to the buttons in the contact page. It'll make it look a lot nicer.

![hover](https://user-images.githubusercontent.com/69709596/122680822-e21f2880-d20e-11eb-8287-9d2484b47d6c.png)

Please assign me with this issue.

Thankyou :)

**Comment by Ankita297** [comment]
@UJALA-TYAGI you can go ahead .

**Comment by UJALA-TYAGI** [comment]
Thank you, ma'am.

**Comment by UJALA-TYAGI** [comment]
Ma'am I've made a PR. Please review it.

Thankyou.
