### ISSUE TITLE
Payment Integration gateway links are not working

### ISSUE THREAD

**Issue by siddhi-244** [Vishal-raj-1/Awesome-JavaScript-Projects#1823]
## Describe the bug
On your website when I try to click on payment gateway website it gives 404 error

## To Reproduce
1. I will change the folder name.
2. I will add the image in assets
3. I will change url in script.js

## Expected behavior
I expected it to show payment integration website

## Logs
404 error

**Comment by siddhi-244** [comment]
I would like to try it !

**Comment by Ankita297** [comment]
@siddhi-244  I  am assigning it you .

**Comment by siddhi-244** [comment]
Ok maam and also on my last pr there is no lgmsoc and level labels @Ankita297

**Comment by siddhi-244** [comment]
Plzz check it

**Comment by Ankita297** [comment]
Okay @siddhi-244  we will see it .

**Comment by siddhi-244** [comment]
Yes plzz it's already merged
