### ISSUE TITLE
Footer space

### ISSUE THREAD

**Issue by RiyaGupta89** [Vishal-raj-1/Awesome-JavaScript-Projects#1824]
![footer-correction](https://user-images.githubusercontent.com/72425181/122745367-8d2ef100-d2a6-11eb-88ca-6d52d7212142.png)
Footer has white space at the bottom.  If you think that needs to be removed then please assign me this issue. I'll resolve it.

**Comment by Ankita297** [comment]
@RiyaGupta89 Go ahead .

**Comment by RiyaGupta89** [comment]
@Ankita297  Ma'am done. Please check the code. I've push my code I've made one PR earlier and this code also got added to the previous PR. Please review it once.

**Comment by Ankita297** [comment]
@RiyaGupta89 Don't need to call mam . 
You should make the different PR's for different issues . So you can get the points

**Comment by RiyaGupta89** [comment]
@Ankita297 I tried making a different PR for this issue but I was not able to make a new PR. Maybe that PR first needs to be merged or declined but @Vishal-raj-1 is inactive. @Vishal-raj-1 Please if you are able to see this comment, please review it.

**Comment by Ankita297** [comment]
@RiyaGupta89 You should make a PR from different branches and if your PR get merged you can pull the changes to your main branch . Never make PR directly  from main branch .

**Comment by RiyaGupta89** [comment]
Okay I'll keep this in mind from now on. Now should I pull my changes or wait for @Vishal-raj-1 to review the code?

**Comment by Ankita297** [comment]
for now you should remove the code related to footer space issue and make a separate PR  for that and for other one will review it .

**Comment by RiyaGupta89** [comment]
@Ankita297 Done.
