### ISSUE TITLE
Social Icons bug needs to be resolved

### ISSUE THREAD

**Issue by RiyaGupta89** [Vishal-raj-1/Awesome-JavaScript-Projects#1827]
On the left side, there are social icons 
1-) When I click on twitter icon, nothing happens. 
2-) When I click on google icon, twitter page opens.
In the footer there are social icons too and none of them works when a user click on them.
Please assign me this issue if you think this needs to be solved.

**Comment by Vishal-raj-1** [comment]
@RiyaGupta89 Go for it !!

**Comment by RiyaGupta89** [comment]
@Vishal-raj-1 You mentioned no tags.
