### ISSUE TITLE
SignIn Page Bug

### ISSUE THREAD

**Issue by RiyaGupta89** [Vishal-raj-1/Awesome-JavaScript-Projects#1828]
![signin](https://user-images.githubusercontent.com/72425181/122784190-de9fa600-d2cf-11eb-86dd-e9dd4a6ee3a2.png)
In the signIn/login page, the main container that is present in the middle has its bottom submerged into the footer. Is this the design that you guys wanted or is it the bug? If this is something that needs to be solved, then please assign me the issue. I will resolve this. Otherwise you can close the issue.

**Comment by Ankita297** [comment]
@RiyaGupta89 the page is fine it is not submerged .

**Comment by RiyaGupta89** [comment]
Okay. @Ankita297
