### ISSUE TITLE
Mobile Size Padding

### ISSUE THREAD

**Issue by RiyaGupta89** [Vishal-raj-1/Awesome-JavaScript-Projects#1829]
![paddingleft](https://user-images.githubusercontent.com/72425181/122784730-5bcb1b00-d2d0-11eb-82fb-8f1c419f75d8.png)
![padding](https://user-images.githubusercontent.com/72425181/122784745-5ec60b80-d2d0-11eb-835e-92ce036d05ac.png)
Please look at both of the above pictures, "HELPING YOU IS OUR AIM" tagline does not have any left padding which does not look so nice. Also the "send message" button has its text being cut in the mobile view. I will resolve these minor issues, please allow me to work on this issue.

**Comment by Ankita297** [comment]
@RiyaGupta89 go ahead .

**Comment by RiyaGupta89** [comment]
@Ankita297 Done. Please have a look.
