### ISSUE TITLE
Contact page bug

### ISSUE THREAD

**Issue by RiyaGupta89** [Vishal-raj-1/Awesome-JavaScript-Projects#1831]
![contactbug](https://user-images.githubusercontent.com/72425181/122786612-1dcef680-d2d2-11eb-9a5e-dcd86b815f28.png)
Whether the form is empty or not, it displays this modal saying "Your message successfully delivered" which seems like a bug and also seems unprofessional. I can resolve this issue by asking users to first fill details then click on send message button.

**Comment by Ankita297** [comment]
@RiyaGupta89 go ahead
