### ISSUE TITLE
Seperate js and css files of payment gateway integration 

### ISSUE THREAD

**Issue by siddhi-244** [Vishal-raj-1/Awesome-JavaScript-Projects#1834]
## Describe the bug
The js and css files are not seperated

## To Reproduce
1. I would move the css and js files to their respective folders.
2. Also I  will change the path in respective html files 

## Expected behavior
That's the folder structure !

**Comment by siddhi-244** [comment]
Plzz let me try this

**Comment by Vishal-raj-1** [comment]
Go for it !!
