### ISSUE TITLE
About and Projects Link in the footer Section is not working properly

### ISSUE THREAD

**Issue by ROHAN842** [Vishal-raj-1/Awesome-JavaScript-Projects#1837]
## Describe the bug
About and Projects Section Link in the footer Section is not working properly.
It is just taking us to the top of the page.

## Expected behavior
It should redirect the user respectively  to the "About us" and "Projects" page.

## Additional context

https://user-images.githubusercontent.com/61961107/122912395-eb76d500-d375-11eb-9e3f-8374aa59bd76.mp4

**Comment by ROHAN842** [comment]
@Ankita297 could you please assign this issue to me under LGMSOC

**Comment by Ankita297** [comment]
@ROHAN842 go ahead .

**Comment by ROHAN842** [comment]
@Ankita297 I request you to kindly close this issue as the PR is merged for this issue
