### ISSUE TITLE
Quick Links Section doesn't consists Signup/Login option in Footer

### ISSUE THREAD

**Issue by ROHAN842** [Vishal-raj-1/Awesome-JavaScript-Projects#1840]
## Describe the bug
The Footer Section doesn't consists of Signup/Login option

## Expected behavior
I would like to add this feature in the footer section such that on clicking it user will be redirected to Signup/Login Page.

## Additional context
![image](https://user-images.githubusercontent.com/61961107/123150019-87d8ce80-d47f-11eb-80e6-ad78681627ba.png)

**Comment by ROHAN842** [comment]
@Ankita297 could you please assign this issue to me under LGMSOC

**Comment by Ankita297** [comment]
@ROHAN842 go ahead .

**Comment by ROHAN842** [comment]
Hey @Ankita297 kindly close this issue as the PR is already merged for this issue

**Comment by Ankita297** [comment]
done @ROHAN842
