### ISSUE TITLE
Repetition of sign-in,  sign-up div

### ISSUE THREAD

**Issue by supzi-del** [Vishal-raj-1/Awesome-JavaScript-Projects#1845]
## Describe the bug
There are two divs on sign-in and sign-up page (redundant) by mistake.
![image](https://user-images.githubusercontent.com/78655439/123558240-d2758600-d7b2-11eb-80ea-384173d44fbf.png)

## To Reproduce
1.  Remove one of the divs.
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Windows
 - Browser: Chrome

**Comment by supzi-del** [comment]
I would like to work on this under LGMSOC.

**Comment by Rizwan-S** [comment]
@supzi-del yeah sure!
