### ISSUE TITLE
Position of Dark Mode icon

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#1847]
## Describe the bug
Position of icon is overlap by the chat bot.

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by Atif0604** [comment]
Please assign it to me I will make changes to Positon in all pages
I'm a Participant of LGM-SOC'21

**Comment by Ankita297** [comment]
@Atif0604 go for it .
