### ISSUE TITLE
Bug in More Project Button on Home Page

### ISSUE THREAD

**Issue by Atif0604** [Vishal-raj-1/Awesome-JavaScript-Projects#1855]
## Describe the bug
Split Button Web view and Wrong Aligned in Mobile View

## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

## Additional context

##ScreenShots of the bugs
![image](https://user-images.githubusercontent.com/64218887/124186922-a3c11d80-dada-11eb-94eb-375761013503.png)
![image](https://user-images.githubusercontent.com/64218887/124186940-a91e6800-dada-11eb-875d-05b34b04c1fe.png)

**Comment by Atif0604** [comment]
@Ankita297 Please Assign this to me

**Comment by Atif0604** [comment]
@Rizwan-S can i work on this

**Comment by Rizwan-S** [comment]
Yeah! Go ahead.
