### ISSUE TITLE
Movie search app - feature

### ISSUE THREAD

**Issue by Rizwan-S** [Vishal-raj-1/Awesome-JavaScript-Projects#1858]
Add a feature to search movie by imdb rating in movie search app.

**Comment by Diksha02** [comment]
Please assign me this issue under LGMSOC-21

**Comment by Rizwan-S** [comment]
Sure!

**Comment by Diksha02** [comment]
Hey @Rizwan-S , sorry for the delay I wasn't able to access the API for some reason, I somehow worked my way around it. But now after reading the documentation I find that the API doesn't use imdb ratings and also there is no end-point to search by ratings...Can you please guide me on this?

**Comment by Rizwan-S** [comment]
Hi @Diksha02. Even I realized that there is no imdb rating in the data. As an alternative, you can show the recommended movies. Please use the attached link for reference.
https://developers.themoviedb.org/3/movies/get-movie-recommendations
Sorry for the inconvenience. Hope that helps.

**Comment by Diksha02** [comment]
> Hi @Diksha02. Even I realized that there is no imdb rating in the data. As an alternative, you can show the recommended movies. Please use the attached link for reference.
> https://developers.themoviedb.org/3/movies/get-movie-recommendations
> Sorry for the inconvenience. Hope that helps.

No problem, I can start working on that right away!
