### ISSUE TITLE
Create a bar chart

### ISSUE THREAD

**Issue by Rizwan-S** [Vishal-raj-1/Awesome-JavaScript-Projects#1864]
Create an app that takes a set of input and makes a bar chart.

**Comment by 7JKaushal** [comment]
I would love to contribute to this!

**Comment by Rizwan-S** [comment]
@7JKaushal go ahead!

**Comment by joshi-kaushal** [comment]
I have completed this and I will make a single pull request along with all other issues I am working on

**Comment by Rizwan-S** [comment]
@joshi-kaushal please make a separate PR for each issue.
