### ISSUE TITLE
Make a line chart

### ISSUE THREAD

**Issue by Rizwan-S** [Vishal-raj-1/Awesome-JavaScript-Projects#1867]
Create an app that takes data input and makes a line chart.

**Comment by 7JKaushal** [comment]
I would love to contribute to this!

**Comment by Amrutha1101** [comment]
Can I work on this issue under LGM-SOC?

**Comment by Rizwan-S** [comment]
@Amrutha1101 I already assigned you one issue. Please complete that first. Solve the issues one at a time :)

**Comment by RiyaGupta89** [comment]
@Rizwan-S  Can you provide a ui for that? It will be better that way to imagine.

**Comment by Rizwan-S** [comment]
@RiyaGupta89 , you are free to design the ui in any way you like. I am keeping it open ended to avoid restricting the creativity of contributors.

**Comment by RiyaGupta89** [comment]
Okay, i can work on this issue.

**Comment by joshi-kaushal** [comment]
Hey @RiyaGupta89 are you able to solve this issue? My code is ready...

**Comment by RiyaGupta89** [comment]
@joshi-kaushal You can push your code then if its ready.

**Comment by joshi-kaushal** [comment]
@RiyaGupta89 Made a PR, have a look.
@Rizwan-S please tell me what exactly to remove I am not getting it.
