### ISSUE TITLE
Position of Dark Mode icon 

### ISSUE THREAD

**Issue by Ankita297** [Vishal-raj-1/Awesome-JavaScript-Projects#1876]
## Describe the bug
In the project and contact section the dark mode icon is not placed properly 

![Contact _ Awesome JavaScript - Google Chrome 07-07-2021 22_48_20](https://user-images.githubusercontent.com/67833077/124802599-c4bfbd80-df75-11eb-962d-3b3c28f8b1f5.png)

**Comment by Diksha02** [comment]
I can work on this under LGMSOC'21

**Comment by Ankita297** [comment]
go ahead @Diksha02 .

**Comment by Diksha02** [comment]
Hey @Ankita297, can you guide me where is it supposed to appear. As of right now it appears as shown below.

![image](https://user-images.githubusercontent.com/18261935/124809467-c55c5200-df7d-11eb-8d5c-ced8dda382c7.png)
![image](https://user-images.githubusercontent.com/18261935/124809498-cdb48d00-df7d-11eb-8f55-d72512c247fd.png)

**Comment by Rizwan-S** [comment]
The dark mode icon has to be in top right corner.

**Comment by Diksha02** [comment]
> The dark mode icon has to be in top right corner. Try zooming in and out. You'll realize the mistake.

Oh I see it now, thanks
