### ISSUE TITLE
Whack a Mole Game is not Responsive

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#188]
Screenshot:

![Capture1](https://user-images.githubusercontent.com/63122133/109419491-bf64cc00-79f3-11eb-8e9c-f594e0902cbf.PNG)

Make it responsive for all screen sizes!

**Comment by flyingsonu122** [comment]
can I work on this?

**Comment by Vishal-raj-1** [comment]
@flyingsonu122 Sure !!

**Comment by flyingsonu122** [comment]
made it responsive for all screen sizes 
@Vishal-raj-1 please have a look [Here](https://flyingsonu122.github.io/Awesome-JavaScript-Projects/public/molegame.html) 

is it okay?

**Comment by urvashi-code1255** [comment]
Yes, Its looking good @flyingsonu122 . You can open a PR!!

**Comment by flyingsonu122** [comment]
> Yes, Its looking good @flyingsonu122 . You can open a PR!!

Alright

**Comment by flyingsonu122** [comment]
Done [PR here](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/201)
