### ISSUE TITLE
Our menu icon in restaurant website is not functionable .

### ISSUE THREAD

**Issue by myrishabh2312** [Vishal-raj-1/Awesome-JavaScript-Projects#1885]
## Describe the bug
Our menu icon is landing to unaccepted blank page and showing error.

## Expected behavior
After clicking to our menu icon it should land to the exact our menu section in the middle of restaurant website , where dishes are avaliable.

**Comment by myrishabh2312** [comment]
"Hello mentors i have created a new issue and would work on this , please assign it to me, under LGM SOC 21" .

**Comment by Ankita297** [comment]
@myrishabh2312 go for it .
