### ISSUE TITLE
Password Generator: Copied Alert

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#189]
For now after clicking on copy button an alert box is showing like this:

![Capture](https://user-images.githubusercontent.com/63122133/109419732-ef609f00-79f4-11eb-88dc-722efd8b24a7.PNG)

1. Change this alert box to a tooltip.
2. Change the text of copy button to copied after clicking on it. Also change its color after clicking.
3. Also for now the copy button is interfering in the password so apply some padding between them.

**Comment by ishani02** [comment]
Hello @urvashi-code1255 , I would like to work on this issue as a part of GSSOC'21.Could you please assign this to me ?

**Comment by urvashi-code1255** [comment]
Sure got for it @ishani02
