### ISSUE TITLE
email validation does not works in contact section

### ISSUE THREAD

**Issue by JongJianYi** [Vishal-raj-1/Awesome-JavaScript-Projects#1891]
## Describe the bug
The email validation doesn't works in CONTACT section (send message) :
Even though the email was typed in wrong format, it still able to deliver the message successfully (e.g., missing symbol @ )

## To Reproduce
1. disable the send button.
2. write an email validation function that will enable the send button, once the email has been correctly typed.
3. 
4. 

## Expected behavior
The send button should be disabled if the email is typed in wrong format, else it should be enabled and allows user to send the message.

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Windows
 - Browser: Google Chrome

**Comment by JongJianYi** [comment]
@Vishal-raj-1  I would like to resolve this issue.

**Comment by Rizwan-S** [comment]
@JongJianYi sure! Go ahead.

**Comment by Nirbhay1910** [comment]
@Vishal-raj-1 Can I work on this issue?

**Comment by Vishal-raj-1** [comment]
sure !!
