### ISSUE TITLE
Create a Knapsack Problem Project

### ISSUE THREAD

**Issue by wahfei** [Vishal-raj-1/Awesome-JavaScript-Projects#1893]
## Is your feature request related to a problem? Please describe.
No its not a problem. I wanted to add an additional project.
## Thoughts of the project
I wanted to create a knapsack problem project. Users will able to choose the weight that the knapsack can contain and the number of items to put into the knapsack along with their weight and profit.

The knapsack problem will be done using greedy algorithm/method. 

## Additional context
1. The items that can are chosen to put into the knapsack will be shown.
2. The maximum profit of the total knapsack problem will be shown.

**Comment by Ankita297** [comment]
@wahfei go ahead .
