### ISSUE TITLE
Todo List: Implementation

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#19]
Make a todolist from scratch 

## features
- Add task/remove task/ marks as done
![todolist](https://user-images.githubusercontent.com/59874304/107211287-58bf4480-6a2b-11eb-8609-f663cbc829e2.png)

- When all task is done do hurrah celebration like 

![star](https://user-images.githubusercontent.com/59874304/107211969-4691d600-6a2c-11eb-8912-1a60dbb26ea4.JPG)

**Comment by Meghag5** [comment]
I will like to work on this can we use react for this?

**Comment by urvashi-code1255** [comment]
Hi @Meghag5 , for now we are only using vanilla javascript

**Comment by urvashi-code1255** [comment]
Shall I assign this to you?

**Comment by Abhinav0909** [comment]
Hi, @ Vishal-rag -1 I would like to work on this issue

**Comment by urvashi-code1255** [comment]
Sure @Abhinav0909 you can take this issue!! Make sure to follow the PR template and show the video demo!! 

Also, What are the programs you are participating in?

**Comment by Abhinav0909** [comment]
@urvashi-code1255 thank you for assigning this issue to me.
what do you mean by other programs you are participating in?

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 thank you for assigning this issue to me.
> what do you mean by other programs you are participating in?

@Abhinav0909 Means Are you participating in gssoc or crosswoc?

**Comment by Abhinav0909** [comment]
@urvashi-code1255 I am participating in crosswoc.

**Comment by Mukta-Sawant** [comment]
@urvashi-code1255 @Vishal-raj-1  Can I work on this as a part of GSSOC'21?

**Comment by harshgupta20** [comment]
@Abhinav0909 Any Update? Kindly reply within 2 days or I have to assign this to some-else.
