### ISSUE TITLE
URL Shortner: Bug

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#190]
URL Shortner is not working properly. Its not showing short URL .

See the screenshot below:

![Capture](https://user-images.githubusercontent.com/63122133/109419993-2daa8e00-79f6-11eb-86b9-22a8a32e1232.PNG)

**Comment by kunal299** [comment]
@urvashi-code1255 I would love to solve this bug. Could you plz assign this issue to me as a part of Gssoc'21?

**Comment by urvashi-code1255** [comment]
Sure go for it @kunal299 :)

**Comment by kunal299** [comment]
@urvashi-code1255 But our coding period will start on 8th march.

**Comment by kunal299** [comment]
@urvashi-code1255 will it be fine?

**Comment by urvashi-code1255** [comment]
Yes you can send a PR and I will review and merge it after 8!

**Comment by kunal299** [comment]
> Yes you can send a PR and I will review and merge it after 8!

ok

**Comment by HarshMarolia** [comment]
@urvashi-code1255 I've solved the bug, can you please assign me the issue so that I can me my first PR.
