### ISSUE TITLE
Drawing App

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Vishal-raj-1/Awesome-JavaScript-Projects#1908]
## Is your feature request related to a problem? Please describe.
No its not a problem. I want to add an additional project.
## Describe the solution you'd like

I want to create a drawing app  that let user can create their small paintings. I also added a color picker for painting.

## Additional context
1. User can draw  anything.
2. There are four three buttons, one slider and color picker.

**Comment by Rizwan-S** [comment]
Sure! Go ahead.
