### ISSUE TITLE
Random Quote Generator

### ISSUE THREAD

**Issue by Kulshre142** [Vishal-raj-1/Awesome-JavaScript-Projects#1913]
## Is your feature request related to a problem? Please describe.
No, it's not a problem. I want to add a new javascript project.

## Describe the solution you'd like
I would like to add a random quote generator when anyone presses the generate quote button it triggers a change in the quote and the author who said it.

**Comment by Kulshre142** [comment]
@Rizwan-S ??

**Comment by Rizwan-S** [comment]
Go ahead!

**Comment by Rizwan-S** [comment]
Make sure that you make the pr by EOD for the project to be considered in LGMSoC.
