### ISSUE TITLE
ReadMe needs to fix

### ISSUE THREAD

**Issue by asimaries** [Vishal-raj-1/Awesome-JavaScript-Projects#192]
## Describe the bug
the main branch is named as "main" and not "master"

## To Reproduce
1. ReadMe file needs to update
2. 
3. 
4. 

## Logs
I was not able to run "git pull upstream master" instead "git pull upstream main" worked for me
if it's working for you then theirs no need for this issue to be raised

## Environment (please complete the following information):
 - OS:
 - Browser:

## Additional context
![image](https://user-images.githubusercontent.com/75176367/109421846-0b693e00-79ff-11eb-8c6e-4bb573038006.png)
![image](https://user-images.githubusercontent.com/75176367/109421967-91858480-79ff-11eb-8f03-648a5cfd1bf2.png)

**Comment by asimaries** [comment]
Can I work on This issue ?

**Comment by urvashi-code1255** [comment]
Sure go for it @asimaries . Also Can you please reduce the size and add some space between the open source programs logos as they are looking pretty awkward to me?

**Comment by asimaries** [comment]
yes I cn do that you

**Comment by asimaries** [comment]
> Sure go for it @asimaries . Also Can you please reduce the size and add some space between the open source programs logos as they are looking pretty awkward to me?

![image](https://user-images.githubusercontent.com/75176367/109426269-b6372780-7a12-11eb-8ec7-ad07e2e6ab4f.png)
you are talking about this .right?

**Comment by asimaries** [comment]
> Sure go for it @asimaries . Also Can you please reduce the size and add some space between the open source programs logos as they are looking pretty awkward to me?

yes I can do that

**Comment by urvashi-code1255** [comment]
> you are talking about this .right?

Yes @asimaries

**Comment by asimaries** [comment]
> > you are talking about this .right?
> 
> Yes @asimaries

sure

**Comment by asimaries** [comment]
please check the readme file should I add more space

**Comment by asimaries** [comment]
> > you are talking about this .right?
> 
> Yes @asimaries
https://github.com/asimaries/Awesome-JavaScript-Projects.github.io/tree/openInNewTab check this should I add more space

**Comment by asimaries** [comment]
I am not able to make a new PR for this, Please HELP 
and my all commits have been sent at https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/191 at this PR please check that  https://asimaries.github.io/Awesome-JavaScript-Projects.github.io/README.md here

**Comment by asimaries** [comment]
@urvashi-code1255 @Vishal-raj-1 this issue is also been solve via #191. PLease close this

**Comment by urvashi-code1255** [comment]
> ![image](https://user-images.githubusercontent.com/75176367/109430016-01f2cc80-7a25-11eb-82fb-49f22454c325.png)

Its looking perfect @asimaries . Thanks for your contribution!!
