### ISSUE TITLE
Socials Icons not visible in both Desktop and Mobile view

### ISSUE THREAD

**Issue by AbhayaShankar** [Vishal-raj-1/Awesome-JavaScript-Projects#1937]
## Describe the bug
Socials Icons not visible in both Desktop and Mobile view.

![issues2](https://user-images.githubusercontent.com/113185442/231445035-dd92ddbd-12f1-4065-9f4f-03e8eb84906f.png)

## To Reproduce
1. We can use React-icons or free svgs online and use it there and I will be happy to do so.

## Expected behavior
The svg or icons should be visible.

## Environment (please complete the following information):
 - OS: Android
 - Browser: Google chrome

**Comment by sahil003tech** [comment]
icons is visible.please check.

**Comment by AbhayaShankar** [comment]
Yes my bad
