### ISSUE TITLE
Projects Images are not shown

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#1946]
## Describe the bug
Projects Images are not shown

## To Reproduce
1. Go to /Projects.html

![image](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/assets/59874304/d35d7b73-c1f3-4073-b0b7-bc343132633d)

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by Anas-Rehberlik** [comment]
Hello,

I've investigated the problem and identified the cause of this issue. and it appears to be related to a minor typo in the image paths. I'm actively working on fixing it and and I'll submit a pull request with the correction shortly.
