### ISSUE TITLE
Doc: README

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#2]
We can do several changes in README. Like we can add the preview of the projects, website. We can add some gifs or images to make this readme more attractive.

**Comment by Vishal-raj-1** [comment]
Hey @urvashi-code1255 can you please add projects preview in readme.

**Comment by aditya28sarin** [comment]
Can you assign the issue to me? and also brief as to what exactly you want in the readme

**Comment by Vishal-raj-1** [comment]
@aditya28sarin Sure !! I want to add project images in readme in table form may be !! I am not sure you can try

**Comment by Sivyamkumar** [comment]
@Vishal-raj-1 can you please assign this task to me. I will do my best.

**Comment by Vishal-raj-1** [comment]
@Sivyamkumar Sure !! You can add GSSOC & CrossWOC as open source programs !! This repo is part of this two programs so you can add the logo of this two programs in README. Thanks !!

**Comment by urvashi-code1255** [comment]
Hey @aditya28sarin @Sivyamkumar Are you working on this issue?

**Comment by jainstuti** [comment]
Hi, I can add details to the readme as to what exactly the project is about. Can you please assign it to me as a part of gssoc21?

**Comment by aditya28sarin** [comment]
I am adding the images in table form @Vishal-raj-1

**Comment by codDoc98** [comment]
anything else left to add in readme? Let me do it. Desperate to be assigned first project issue.

**Comment by 991rajat** [comment]
Hey @codDoc98 Readme looks fine, Would you like to work on first good issues. like bugs
Let me know I'll assign it to you.

**Comment by codDoc98** [comment]
@991rajat yes I would like to sort those bug out if possible.

**Comment by 991rajat** [comment]
I'll try assign you a starter bug.
