### ISSUE TITLE
JavaScript Clock 

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#20]
Build Analog and digital clock both.

**Comment by khushi935** [comment]
I want to work on this.

**Comment by khushi935** [comment]
I have a small doubt I need to build digital and analog side by side? on the same page?

**Comment by urvashi-code1255** [comment]
> I have a small doubt I need to build digital and analog side by side? on the same page?

@khushi935 Please make them as a seperate projects.

**Comment by khushi935** [comment]
okay, thank you for the information. I will do it.

**Comment by urvashi-code1255** [comment]
@khushi935 Shall I assign this to you?

**Comment by khushi935** [comment]
Yes, please.

**Comment by urvashi-code1255** [comment]
@khushi935 Please send seperate PRs for both the clocks.

**Comment by khushi935** [comment]
okay 😊

**Comment by khushi935** [comment]
![Screenshot (75)](https://user-images.githubusercontent.com/62712155/107856785-a3d4bf80-6e50-11eb-96c3-8569ebc7f113.png)

How does this looking?

**Comment by TidbitsJS** [comment]
Hello, I have created these clocks. You can take a look ( Might help to improve or can be merged )

![Analog](https://i.ibb.co/6H0WdkT/Screenshot-from-2021-02-13-23-46-36.png)

![Digital](https://i.ibb.co/27hGZhY/Screenshot-from-2021-02-13-23-47-20.png)

**Comment by khushi935** [comment]
Thank you for the information, I will improve my clock😊

**Comment by khushi935** [comment]
![Screenshot (77)](https://user-images.githubusercontent.com/62712155/107871100-9f49ee80-6ec4-11eb-8009-0dfc8f585062.png)

please have l look, let me know if any changes required.

**Comment by Vishal-raj-1** [comment]
@TidbitsJS WoW !! Its looks awesome for me !! Can you raise the PR for the digital clock !!

@khushi935 Change color of the clock, It is not matching with background. Try to improve the color of the clock.

**Comment by khushi935** [comment]
https://user-images.githubusercontent.com/62712155/107877007-a2a69f80-6eef-11eb-8f24-ed418a26e497.mp4
 
How it's looking?

**Comment by urvashi-code1255** [comment]
Wow!! Its looking pretty cool @khushi935 !! You can raise a PR for it

**Comment by TidbitsJS** [comment]
Thank you @Vishal-raj-1. I will create the PR very soon

**Comment by supzi-del** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/78655439/108360696-87050700-7217-11eb-89e5-4b949b891741.png)

**Comment by Vishal-raj-1** [comment]
@supzi-del Analog clock is already made. You can improve its design.

**Comment by DEEPALI-SUK** [comment]
If we generate a PR right now , then would it be counted as GSSOC PROJECT 2021 valid pull request , as according to the  schedule it is starting from 1st March?

**Comment by Vishal-raj-1** [comment]
It will not counted !!

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?

**Comment by urvashi-code1255** [comment]
@Sakshi0401 You can work on it! We already have both the clocks. You can improve their UI.

**Comment by Sakshi0401** [comment]
> @Sakshi0401 You can work on it! We already have both the clocks. You can improve their UI.

Thanks @urvashi-code1255

**Comment by harshgupta20** [comment]
@Sakshi0401 Any update? Kindly reply within 2 days or I have to assign this to some-else.

**Comment by Amit366** [comment]
@harshgupta20 can I work??
