### ISSUE TITLE
Set Favicon

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#200]
Try out all the favicons present in the favicons folder and show me the pictures here. I will choose from them!!

**Comment by aniketsingh98571** [comment]
@urvashi-code1255  I can go with it as a part of GSSoC 2021

**Comment by urvashi-code1255** [comment]
@aniketsingh98571 go for it!

**Comment by aniketsingh98571** [comment]
![Screenshot (122)](https://user-images.githubusercontent.com/63097956/109600702-8471ae00-7b43-11eb-9daa-79ca439cb128.png)
![2](https://user-images.githubusercontent.com/63097956/109600705-85a2db00-7b43-11eb-9c56-cfe1220ab446.png)
![3](https://user-images.githubusercontent.com/63097956/109600706-86d40800-7b43-11eb-8044-38fa3ff384a0.png)
![4](https://user-images.githubusercontent.com/63097956/109600710-88053500-7b43-11eb-96df-7dd8f1b0f8d5.png)
![5](https://user-images.githubusercontent.com/63097956/109600716-8a678f00-7b43-11eb-90a8-657cf0778844.png)
![6](https://user-images.githubusercontent.com/63097956/109600719-8c315280-7b43-11eb-8785-90ed81c218fa.png)
@urvashi-code1255 Here is the screenshots of favicons from your project directory.

**Comment by Vishal-raj-1** [comment]
@urvashi-code1255 I like the first and the last one, what's about you ?

**Comment by urvashi-code1255** [comment]
@Vishal-raj-1 I like the first one. I think we can go for it.

@aniketsingh98571 Please make a PR for the first one.
