### ISSUE TITLE
URL Shortner : Alignment and hover

### ISSUE THREAD

**Issue by yashikabhargava** [Vishal-raj-1/Awesome-JavaScript-Projects#204]
**Is your feature request related to a problem? Please describe.**
URL Shortner

**Describe the solution you'd like**

alignment of text and button to the center, change in color of button while hovering and change in design of button.

**Additional context**
Add any other context about the feature request here.

**Comment by yashikabhargava** [comment]
can you please assign this issue to me as a part of Gssoc'21.

**Comment by urvashi-code1255** [comment]
@yashikabhargava you can go for it!

Show me the design here, before making a PR!

**Comment by yashikabhargava** [comment]
> @yashikabhargava you can go for it!
> 
> Show me the design here, before making a PR!

okay ,once its done I'll show it .

**Comment by yashikabhargava** [comment]
![url shortner 1](https://user-images.githubusercontent.com/76060661/109831494-7fa51b00-7c65-11eb-86b1-43cc905ee826.PNG)

**Comment by yashikabhargava** [comment]
Is it okay?

**Comment by yashikabhargava** [comment]
![URL Shortner 2](https://user-images.githubusercontent.com/76060661/109832739-a879e000-7c66-11eb-969d-76ded860510d.png)

**Comment by yashikabhargava** [comment]
button will look like this when hovering.

**Comment by urvashi-code1255** [comment]
Yes Looking good @yashikabhargava

**Comment by yashikabhargava** [comment]
hey! I created this issue under gssoc'21 but it does not have the label, can you please label it.
