### ISSUE TITLE
Image of the quiz app is not appearing.

### ISSUE THREAD

**Issue by Suhail-BW** [Vishal-raj-1/Awesome-JavaScript-Projects#206]
## Describe the bug
The card image of the Quiz App is not appearing.
<img width="372" alt="Screenshot 2021-03-02 at 10 52 42 PM" src="https://user-images.githubusercontent.com/76062078/109688317-275d1300-7baa-11eb-8f26-94ea3b21a34f.png">

## To Reproduce
1. Open the website
2. Navigate to the quiz app
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:Mac Os
 - Browser:Chrome

**Comment by Suhail-BW** [comment]
I am beginner with open source, if this is a genuine issue I would like to work on it.

**Comment by urvashi-code1255** [comment]
Yes @Suhail-BW I also noticed this! You can work on it !

**Comment by Suhail-BW** [comment]
@urvashi-code1255 there is no GIF regarding quiz app in assets/GIFs/. Where/How can I get this GIF to include there.

**Comment by urvashi-code1255** [comment]
@Suhail-BW you can make a GIF by your own

**Comment by Suhail-BW** [comment]
@Vishal-raj-1 By the way I am participating in GSSOC 2021
