### ISSUE TITLE
Currecy Convertor

### ISSUE THREAD

**Issue by Sapna2001** [Vishal-raj-1/Awesome-JavaScript-Projects#208]
I would be using HTML, CSS, JS to complete this task.
In this, the user will enter the amount, to currency and from currency, and according to the options chosen the value will be displayed.

@urvashi-code1255 @Vishal-raj-1 I would love to work on this issue as a part of GSSOC 2021 and I will make a PR for this when the contribution period starts. 

I have completed the earlier issue also and will make the PR for the same when the contribution period starts.

Please assign me this issue.

**Comment by urvashi-code1255** [comment]
@Sapna2001 go for it

**Comment by vasanthgk02** [comment]
Hii, I am interested to work on this project. So pls assign this to me !
