### ISSUE TITLE
Interest Calculator

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#21]
Ask Initial Amount, Rate, Time and print interest amount !!

P.S : Only for First Time User !!

**Comment by Sivyamkumar** [comment]
@Vishal-raj-1  can you assign this task to me and guide me to do this??

**Comment by Vishal-raj-1** [comment]
@Sivyamkumar Thanks for showing interest, You can go start  !!

**Comment by Vishal-raj-1** [comment]
Use this formula 

![formua](https://user-images.githubusercontent.com/59874304/107331780-574c5580-6ad9-11eb-93ff-7ce2f838cbf5.JPG)

Website something like this !!
![dsi](https://user-images.githubusercontent.com/59874304/107331788-59161900-6ad9-11eb-9800-85f7997530e6.JPG)

**Comment by archana-9430** [comment]
Please allow to work on this @Vishal-raj-1 and guide me for the same :)

**Comment by Vishal-raj-1** [comment]
@Sivyamkumar Are you working on this issue ? I will assign this issue to @archana-9430 if you haven't reply me !!

**Comment by archana-9430** [comment]
Since, @Sivyamkumar seems no longer be interested in resolving this issue, kindly @Vishal-raj-1 allow me to do the same.

**Comment by urvashi-code1255** [comment]
Sure @archana-9430 You go for it!!

**Comment by archana-9430** [comment]
![InterestCalculator](https://user-images.githubusercontent.com/78868726/107990570-b12dad80-6ffa-11eb-9fc9-46921f32b72b.png)
Please check this out. If there is some improvement needed , do let me know.

**Comment by archana-9430** [comment]
> ![InterestCalculator](https://user-images.githubusercontent.com/78868726/107990570-b12dad80-6ffa-11eb-9fc9-46921f32b72b.png)
> Please check this out. If there is some improvement needed , do let me know.

@urvashi-code1255 and @Vishal-raj-1  let me know the changes (if any).

**Comment by Vishal-raj-1** [comment]
@archana-9430 We can place this calculator in the middle, and decrease the size of the `input`. Also try to add some styling to buttons. Let me know if you need any help for the same.

**Comment by archana-9430** [comment]
> @archana-9430 We can place this calculator in the middle, and decrease the size of the `input`. Also try to add some styling to buttons. Let me know if you need any help for the same.

![SI](https://user-images.githubusercontent.com/78868726/108258198-c5ea7c80-7185-11eb-9517-63e1d26028ae.png)
check it and let me know if some improvements are needed :)

**Comment by urvashi-code1255** [comment]
> check it and let me know if some improvements are needed :)

I think the reset button should be at the right @archana-9430

**Comment by samfubuki** [comment]
I would like to work on this issue as a part of GSSOC 21

**Comment by archana-9430** [comment]
> > check it and let me know if some improvements are needed :)
> 
> I think the reset button should be at the right @archana-9430

![Screenshot (269)](https://user-images.githubusercontent.com/78868726/108536139-17b81180-7302-11eb-8e9d-4105f7a03ac6.png)
I made the necessary changes. Please let me know if some improvements are needed.

**Comment by archana-9430** [comment]
As a participant of GSSoC'21, can I work on this issue @Vishal-raj-1

**Comment by Vishal-raj-1** [comment]
@archana-9430 You are already working on this issue. Yes Design is fine but where is the answer ? Where we will see the output/calculated interest ? You can share your local website by enabling github pages on your local forked repo.

**Comment by archana-9430** [comment]
> As a participant of GSSoC'21, can I work on this issue @Vishal-raj-1

@Vishal-raj-1 , do check this out-   https://archana-9430.github.io/

**Comment by Vishal-raj-1** [comment]
Looks good to me, You can send the PR for the same.

**Comment by archana-9430** [comment]
> Looks good to me, You can send the PR for the same.

Sorry for the delay. Actually, I was busy in my semesters. I have send the PR for the same. Do check that out. Please merge this after 01/03/2021 , so that, I can get scores in GSSoC as well.

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?

**Comment by sarala-2210** [comment]
I would like to contribute on this issue as a part of gssoc-21 participant,  @Vishal-raj-1 please assign this to me.Thank you!!

**Comment by SanskrutiRP** [comment]
Heyy @urvashi-code1255.  I am GSSoC'21 participant. I would like to add some styling to this so it will be looking attractive and user friendly, will you please assign it to me?

**Comment by vaishnavig20** [comment]
Heyy @urvashi-code1255.I am GSSoc '21 participant. I would like to add more features to this project and improve the styling of this project so please assign it to me.

**Comment by Fab-Gaurav** [comment]
> As a GSSOC'21 participant I would like to contribute on this issue so can
> @Vishal-raj-1 can you please assigned me this.

Any Update or may I work on this issue?? @Vishal-raj-1 , @urvashi-code1255

**Comment by HelenEH0** [comment]
Hey @Vishal-raj-1 ,
 As a GSSOC'21 participant I would like to make some changes in the design of this project, Please assign this to me.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me. @Vishal-raj-1 @urvashi-code1255

**Comment by ashutosh-cusat** [comment]
Hey, I'm GSSOC'21 participant, I want to make some changes in the design of this project, Please assign this issue to me @Vishal-raj-1 @urvashi-code1255

**Comment by harshgupta20** [comment]
@archana-9430 Any update? Kindly reply within 2 days or I have to assign this to some-else.

**Comment by archana-9430** [comment]
> @archana-9430 Any update? Kindly reply within 2 days or I have to assign this to some-else.

@harshgupta20 , This issue has already been solved. I've already sent the PR and they've merged that too.

**Comment by archana-9430** [comment]
> @archana-9430 Any update? Kindly reply within 2 days or I have to assign this to some-else.

@harshgupta20 , see PR  #193 .
