### ISSUE TITLE
Animated eye follow mouse cursor

### ISSUE THREAD

**Issue by pranabprohit** [Vishal-raj-1/Awesome-JavaScript-Projects#211]
Minion animated eyes follow mouse cursor. wherever the cursor will move the animated eyes will follow it.

**Comment by pranabprohit** [comment]
@urvashi-code1255, I would like to work on this issue as a part of CWOC. Can you assign this issue to me.

**Comment by urvashi-code1255** [comment]
@pranabprohit go for it.

**Comment by pranabprohit** [comment]
Can you please add the CWOC required labels.
