### ISSUE TITLE
Whack A Mole Game suggestions

### ISSUE THREAD

**Issue by bilal-23** [Vishal-raj-1/Awesome-JavaScript-Projects#214]
This issue is regarding the whack a mole game.
#Issues:
1) No functionality to store Highscore.
2) Not responsive hence doesn't work properly on mobile devices.
3) Less number of holes, which makes it easier to play.

#Solutions
1) I would like to store the highscore in localstorage of browser and we can also reset the highscore.
2) Will make  it responsive.
3) Will add 3 more holes , so that it will be 3x3 and not a 2x3 matrix.

#Screenshots
![image](https://user-images.githubusercontent.com/71442068/109911739-9af94000-7cd0-11eb-8a97-8b850ee3bdd5.png)

**Comment by bilal-23** [comment]
@urvashi-code1255 @Vishal-raj-1 Let me know , if you are interested

**Comment by Vishal-raj-1** [comment]
@bilal-23 Sure You can implement it !!

**Comment by harshgupta20** [comment]
Any update ?
Reply within 2 days or else i have to close this issue.

**Comment by bilal-23** [comment]
I'll raise the PR by tomorrow @harshgupta20
