### ISSUE TITLE
Modify the looks of Website

### ISSUE THREAD

**Issue by chaitanyashimpi** [Vishal-raj-1/Awesome-JavaScript-Projects#215]
@urvashi-code1255 @Vishal-raj-1 

I would like to revamp the looks of the website as a part of **GSSOC 21.**
I am sure, it will help a lot.

**Comment by chaitanyashimpi** [comment]
@urvashi-code1255 
As a GSSOC participant, I would like to revamp the looks of the website.

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same.
Thank you.

**Comment by Simran2337** [comment]
I am GSSOC 2021 participant. I want to contribute

**Comment by Siddharth1006** [comment]
My name is Siddharth. I am a participant in GSSOC 2021. I am interested in this issue. If you can, then please assign the above issue to me! If not, then I am also ready to team up with another participant if he/she doesn't mind!

**Comment by chaitanyashimpi** [comment]
@urvashi-code1255 @Vishal-raj-1  I think you are a night owl at coding. Great :)

First of all, your project is fabulous, it will help many people in order to get the project ideas or can take these projects as a part of the project, It's awesome. You had done great work on your GUI of your website of your project. 

But I would like to give an attentive look to the website with proper navigation, with Home, Projects and Suggestion page, where On the home page we can show few projects and if the user wants to check more, he can navigate to the projects page and can explore a lot, with a search bar at the top. The suggestion page is the page where the user can suggest the projects for the website to add on.

While performing these changes I have a sutle color theme that will suit your website a lot. It will be great if you assign this issue to me as a part of GSSOC '21. This will be my second contribution to this project.

Anyway, I just checked your site there is some error, the projects are not available, check them.

Thank you.

**Comment by urvashi-code1255** [comment]
@chaitanyashimpi Yeah I have corrected the error in the website yesterday. Now its good,

I just love your idea @chaitanyashimpi You can go for it :)
