### ISSUE TITLE
Build a Analogue Clock with JavaScript

### ISSUE THREAD

**Issue by chaitanyashimpi** [Vishal-raj-1/Awesome-JavaScript-Projects#216]
It will be a great add-on JavaScript Project. 

I would like if you to assign this issue to me as a part of GSSOC.

**Comment by urvashi-code1255** [comment]
@chaitanyashimpi we already have an analog clock. You can modify it

**Comment by chaitanyashimpi** [comment]
@urvashi-code1255 Ok I will modify it. Can you assign it to me?

**Comment by chaitanyashimpi** [comment]
@urvashi-code1255 I have completed this issue under GSSOC '21. Can you please tag it with that. I hope this will also be counted on the leaderboard. 
Anyway, I am working on the Website Looks, it's going well. It will complete soon.
