### ISSUE TITLE
Visual Bubble sort

### ISSUE THREAD

**Issue by akshitadixit** [Vishal-raj-1/Awesome-JavaScript-Projects#217]
Hey i want to add visualisation for bubble sort and late work on all sorting algos.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.


My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by akshitadixit** [comment]
Hi @Vansh-Gupta4 and @Siddharth1006 please let me know what part do you wish to pickup :)

**Comment by Vansh-Gupta4** [comment]
I would help in implementation of algo

**Comment by akshitadixit** [comment]
@Vansh-Gupta4 sure thing. I'll design the layout and make a PR and leave the sorting function blank, so you can pull the changes and implement the algo inside the function, that works?

**Comment by akshitadixit** [comment]
Also @urvashi-code1255 if you could add the gssoc21 label please?

**Comment by akshitadixit** [comment]
@urvashi-code1255 for some reason this issue isn't being counted by gssoc, will be counted after it is closed?

**Comment by harshgupta20** [comment]
@akshitadixit Don't worry, we will sort it :)
