### ISSUE TITLE
Number System converter

### ISSUE THREAD

**Issue by WaderManasi** [Vishal-raj-1/Awesome-JavaScript-Projects#218]
Number system converter is a project in which we can easily convert decimal, binary, hexadecimal values into required number system. eg hex to binary or decimal to binary, etc.
Hello @urvashi-code1255 ,
I would like to contribute this project as a part of gssoc'21.

**Comment by urvashi-code1255** [comment]
@WaderManasi go for it :)

**Comment by harshgupta20** [comment]
Any update ?
Reply within 2 days or else i have to close this issue.
