### ISSUE TITLE
DNS Lookup

### ISSUE THREAD

**Issue by Sapna2001** [Vishal-raj-1/Awesome-JavaScript-Projects#219]
I would be using HTML, CSS, JS to complete this task.

@urvashi-code1255 @Vishal-raj-1 I would love to work on this issue as a part of GSSOC 2021 and I will make a PR for this when the contribution period starts.

Please assign me this issue.

**Comment by urvashi-code1255** [comment]
@Sapna2001 Can you please explain what your project will do?

**Comment by Sapna2001** [comment]
It will take the website name as input and run a DNS Lookup after which the IP address is displayed on the screen.

**Comment by harshgupta20** [comment]
Any update ?
Reply within 2 days or else i have to close this issue.
