### ISSUE TITLE
Day of the Week 

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#22]
![day](https://user-images.githubusercontent.com/59874304/107212787-7b525d00-6a2d-11eb-8c11-324521a689a9.JPG)

P.S : Only for First time User !!

**Comment by Aayushi-Mittal** [comment]
Hey! @Vishal-raj-1 Can I work on this issue?

**Comment by urvashi-code1255** [comment]
@Aayushi-Mittal Sure go for it!!

**Comment by Aayushi-Mittal** [comment]
Thanks! @urvashi-code1255 I am participating in GSSOC.

**Comment by Vishal-raj-1** [comment]
@Aayushi-Mittal You can contribute to this issue but it will not be counted for GSSOC'21 as it will be started from 1st march.

**Comment by Aayushi-Mittal** [comment]
Okay, No problem @Vishal-raj-1.
