### ISSUE TITLE
Dynamic Calendar

### ISSUE THREAD

**Issue by satyampgt4** [Vishal-raj-1/Awesome-JavaScript-Projects#220]
It will a Dynamic calendar you can go to any particular month or date
 In default it will show the calendar of current month with highlighting current date Dynamically
 I will Use HTML, CSS, JS to complete this task.

I would like to work on this issue as a part of GSSOC 2021 and I will make a PR for this when the contribution period starts.

@urvashi-code1255 @Vishal-raj-1 
Please assign me this issue.

**Comment by satyampgt4** [comment]
@urvashi-code1255 @Vishal-raj-1 Please assign me this issue.

**Comment by urvashi-code1255** [comment]
@satyampgt4 go for it.

**Comment by satyampgt4** [comment]
@urvashi-code1255 please add GSSOC 2021 label
