### ISSUE TITLE
Tetris game

### ISSUE THREAD

**Issue by Harshal0902** [Vishal-raj-1/Awesome-JavaScript-Projects#221]
## Is your feature request related to a problem? Please describe.
I want to make a Tetris game.

## Describe the solution you'd like
I want to make a Tetris game using HTML, CSS and Js

## Additional context
NA

**Comment by Harshal0902** [comment]
@urvashi-code1255 can you please assign this issue to me as a part of Cross WOC?

**Comment by urvashi-code1255** [comment]
@Harshal0902 go for it.
