### ISSUE TITLE
Image Slider 

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#23]
Build a carousel using vanilla javascript.

**Comment by Meghag5** [comment]
I will work on this.

**Comment by Vishal-raj-1** [comment]
@Meghag5 Sure you can start work on this issue !!

**Comment by jainh6148** [comment]
Hi, I would like to contribute to this project. Kindly assign it to me.

**Comment by urvashi-code1255** [comment]
> I will work on this.

Hi @Meghag5 Are you working on this issue?

**Comment by Meghag5** [comment]
> > I will work on this.
> 
> Hi @Meghag5 Are you working on this issue?

Yes

**Comment by urvashi-code1255** [comment]
> Hi, I would like to contribute to this project. Kindly assign it to me.

Hi @jainh6148 Welcome to the project!! As this issue is already assigned. I can't assign this to you.. There are more issues to work on in this repository. Have a look. Select an issue not having a label of "assigned". i will assign it to you :)

Thanks!
