### ISSUE TITLE
Randon Quotes Generator

### ISSUE THREAD

**Issue by Aayush-hub** [Vishal-raj-1/Awesome-JavaScript-Projects#230]
## Is your feature request related to a problem? Please describe.
Add a random quote generator, which can generate daily motivational quotes.

**Comment by Aayush-hub** [comment]
@Vishal-raj-1 @urvashi-code1255 Can I work on this for GSSoC21?

**Comment by vkassingh** [comment]
@Vishal-raj-1 @urvashi-code1255 i would like to contribute to the "AWESOME JAVASCRIPT PROJECTS". do we have a discord server or same for the further discussions?

**Comment by urvashi-code1255** [comment]
> @Vishal-raj-1 @urvashi-code1255 i would like to contribute to the "AWESOME JAVASCRIPT PROJECTS". do we have a discord server or same for the further discussions?

@vkassingh Discord Server link is in the readme

**Comment by urvashi-code1255** [comment]
@Aayush-hub Welcome to the Awesome Javascript Projects

We have a Random Quote Generator Project in our list.

You can modify it if you want.
