### ISSUE TITLE
Moving car animation

### ISSUE THREAD

**Issue by pranabprohit** [Vishal-raj-1/Awesome-JavaScript-Projects#232]
A project in which a car will move on road using animation.

**Comment by pranabprohit** [comment]
Hii @urvashi-code1255, I want to work on this issue as a part of GSSOC. Could you please assign this issue to me.

**Comment by urvashi-code1255** [comment]
@pranabprohit Sure go for it :)

**Comment by sandipswain** [comment]
Hi, @urvashi-code1255, I am a participant of GSSOC'21. I would like to work on this issue. Can you please assign me?

**Comment by pranabprohit** [comment]
@urvashi-code1255, Can you please add the required lables of GSSOC21 to this issue.
