### ISSUE TITLE
Typing Speed Tester app

### ISSUE THREAD

**Issue by Aayush-hub** [Vishal-raj-1/Awesome-JavaScript-Projects#234]
## Is your feature request related to a problem? Please describe.
Add a typing speed tester which can be used to test the typing speed of developers.

**Comment by Aayush-hub** [comment]
@Vishal-raj-1 @urvashi-code1255 Can I work on this?

**Comment by urvashi-code1255** [comment]
Sure @Aayush-hub Go for it :)
