### ISSUE TITLE
Light Switch on/off

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#24]
On clicking the light of bulb will be on/off.

**Comment by Meghag5** [comment]
I will work on this issue

**Comment by urvashi-code1255** [comment]
Go for it @Meghag5

**Comment by urvashi-code1255** [comment]
Hey @Meghag5 Will you work on this or shall I unassign you? As you are already assigned three issues!

**Comment by Meghag5** [comment]
> Hey @Meghag5 Will you work on this or shall I unassign you? As you are already assigned three issues!

Hey @urvashi-code1255 i am working on this

**Comment by urvashi-code1255** [comment]
> Hey @urvashi-code1255 i am working on this

Okay @Meghag5

**Comment by SanskrutiRP** [comment]
Hey @urvashi-code1255  I will like to work on this. Will you assign this to me??

**Comment by urvashi-code1255** [comment]
Hey @Meghag5 Are you working on this?

**Comment by ashutosh-cusat** [comment]
I will work on this issue please assign me @Vishal-raj-1 @urvashi-code1255

**Comment by mahesh-11102** [comment]
hello @Vishal-raj-1  sir @urvashi-code1255 mam, I'm a GGSOC participant,, I was the one who contacted  you in the discord , please assign me this issue , I can share you my prototype

**Comment by SalmaZakaria** [comment]
I am a GSSOC'21 Participant 
Could you please assign it to me?

**Comment by codDoc98** [comment]
> Hey @Meghag5 Are you working on this?

clearly, she isn't. Please assign me will do immediatey.

**Comment by Meghag5** [comment]
> > Hey @Meghag5 Are you working on this?
> 
> clearly, she isn't. Please assign me will do immediatey.

hey i am due to some health issues I was not able to do it

**Comment by codDoc98** [comment]
> > > Hey @Meghag5 Are you working on this?
> > 
> > 
> > clearly, she isn't. Please assign me will do immediatey.
> 
> hey i am due to some health issues I was not able to do it

ok, stay healthy.

**Comment by Ankita297** [comment]
can i work on this @urvashi-code1255 @ridsuteri @harshgupta20 @991rajat ?

**Comment by ashutosh-cusat** [comment]
can i also work on this @urvashi-code1255  by collabrate if anyone want.

**Comment by ridsuteri** [comment]
srry @Ankita297 @ashutosh-cusat this project is already implemented ,hence i am closing this issue :(
