### ISSUE TITLE
Javascript Login Authentication

### ISSUE THREAD

**Issue by codebuzzer01** [Vishal-raj-1/Awesome-JavaScript-Projects#244]
I want to add one more Javascipt project for login authentication using AngularJS. If no one is working on it then please assign it to me.

**Comment by vinayak0127** [comment]
As a GSSOC'21 participant i'd like to contribute this project in pure vanilla js ,
kindly assign this project to me @urvashi-code1255  @Vishal-raj-1

**Comment by cicada3006** [comment]
@urvashi-code1255 
Sure! I will work in vanilla js. Kindly assign it to me.

**Comment by codebuzzer01** [comment]
@urvashi-code1255  
Sure, I will work on vanilla js. Please assign it to me.

**Comment by urvashi-code1255** [comment]
Sure @codebuzzer01 go for it :)

**Comment by 991rajat** [comment]
Hey @codebuzzer01 are you still working on this issue?

**Comment by codebuzzer01** [comment]
@991rajat  Yeah!! I am working on it. Was quite busy in exams these days but sure I am working on it.

**Comment by harshgupta20** [comment]
@codebuzzer01 whats the update ?
Kindly reply within 2 days else i have to close this issue.

**Comment by harshgupta20** [comment]
@codebuzzer01 It is the last chance to send the PR for this issue, kindly reply in 24 hours.
