### ISSUE TITLE
[JavaScript] Fixed Header: The color of header changes based on how much the page has scrolled!

### ISSUE THREAD

**Issue by Nkap23** [Vishal-raj-1/Awesome-JavaScript-Projects#245]
I am a participant of Gssoc 21. I would love to contribute to this repo!

## The Idea

Basically a fixed header (which will remain at top of the page), but the color of the header will change based on how much the page has been scrolled. 

Example: Initially the color is blue, when the page scrolls by 20vh, the color changes to green, and so on. 
Live example (I implemented this in my portfolio website) 
https://nkap23.github.io/

If you try scrolling the page, you will see that initially, the header is black, but after scrolling, it changes to yellow. And if you scroll it back to the top, it returns to black again.

I request project admins/mentors to assign this issue to me. 
@Vishal-raj-1 
@urvashi-code1255

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021
Thank you.

**Comment by urvashi-code1255** [comment]
You can go for it @Nkap23 :)

Please look at other issues @shairanshrawat . As @Nkap23 asked first so I have assigned this issue to him
