### ISSUE TITLE
Text to speech

### ISSUE THREAD

**Issue by bitaashna** [Vishal-raj-1/Awesome-JavaScript-Projects#247]
A text to speech app for non-verbal conversations. Pre-made buttons and custom text speech.

**Project Specifications**

- Create a responsive UI (CSS Grid) with picture buttons
- Speaks the text when button clicked
- Drop down custom text to speech
- Speaks the text typed in
- Change voices and accents(in the language of your own choice)

I would like to contribute to it as a part of **GSSOC'21.**
Can you ( @urvashi-code1255 @Vishal-raj-1 )  please assign this work  to me.

**Comment by urvashi-code1255** [comment]
@bitaashna Please go for it :)

**Comment by bitaashna** [comment]
can u please label the issue as GSSOC'21

**Comment by bitaashna** [comment]
Hey @urvashi-code1255 ! I have created a pull request . Please check it :)

**Comment by bitaashna** [comment]
@urvashi-code1255 I have created the PR weeks ago .Please check it.Everytime someone commits to the repo, I have to resolve conflicts.Please review it as fast as u can
