### ISSUE TITLE
Drum Kit bug

### ISSUE THREAD

**Issue by Saatvik21** [Vishal-raj-1/Awesome-JavaScript-Projects#250]
**## Describe the bug
A clear and concise description of what the bug is.**

In the Drum Kit App, there's a mistake in the audio files of the drums. For the `data-key = "70"` ie the "Kick" button, the audio given to that button is of `data-key = "65"` ie the "Boom" button.  

As a participant of GSSOC'21 , I would like to work on this issue. 

Please assign me this issue @urvashi-code1255 @Vishal-raj-1 .

**Comment by Simran2337** [comment]
i want to contribute as a GSSOC participant

**Comment by urvashi-code1255** [comment]
@Saatvik21 go for it.

@Simran2337 Please look at other issues in this repository, as @Saatvik21 asked first I have assigned this issue to him.
