### ISSUE TITLE
Issue Tracker App built using pure JS.

### ISSUE THREAD

**Issue by dcs-soni** [Vishal-raj-1/Awesome-JavaScript-Projects#251]
Hi. I want to add an ISSUE TRACKER WebApp based on pure JS. This project will be very beneficial for the project maintainers of the Github as well. 

Description of the App - 

The project maintainer will be able to 
-> Add the description of the specific issue 
-> Add the security level of the issue for the existing project in which the issue is to be created.
-> To whom the project is assigned.
-> The status of the issue - whether it is open or closed.

More ideas to this simple app are appreciated. I would like to add this project as a participant of GSSoC'21. Share some thoughts on this and if everything goes well please assign it to me.

**Comment by urvashi-code1255** [comment]
@dcs-soni Welcome to the project :)

go for it.

**Comment by dcs-soni** [comment]
Hey! @urvashi-code1255 I am halfway through the project and some UI part is remaining with final touch. I am here to remind that **GSSoC'21** label is not present in this issue along with the level of the issue. Kindly note this..

This is what I have achieved upto this point

![image](https://user-images.githubusercontent.com/52232900/110886012-eb465280-830d-11eb-99f9-89c85e55b980.png)
