### ISSUE TITLE
Change the effect of navbar on hover

### ISSUE THREAD

**Issue by janvi01** [Vishal-raj-1/Awesome-JavaScript-Projects#252]
I would like to Change the effect of the navbar on hover, something like animation or background changes.

**Comment by janvi01** [comment]
Please assign this issue, I would like to contribute as a part of GSSOC.

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by 991rajat** [comment]
@janvi01 Could you please elaborate, In which project would you like to add this feat ?

**Comment by janvi01** [comment]
My idea was same as issue #599 .

**Comment by janvi01** [comment]
My idea was same as issue no 599

**Comment by 991rajat** [comment]
Hey @janvi01 Do not worry. Also no one is answering here so
I'm closing this duplicate issue for now as you are working on it
