### ISSUE TITLE
Speed Typing Game

### ISSUE THREAD

**Issue by bitaashna** [Vishal-raj-1/Awesome-JavaScript-Projects#253]
Game to beat the clock by typing random words

**Project Specifications**

- Create game UI including a difficuly setting(easy,medium,hard)
- Generate random word and place in DOM
- increasing the score after word is typed
- Implement timer
- Add of certain amount of time after word is typed based on difficulty
- Store difficulty setting in local storage

Hi @urvashi-code1255 @Vishal-raj-1 ! I would like to work on this issue as a participant of **GSSoC'21**
Can you please assign this task to me.

**Comment by Quickbeasts51429** [comment]
can I be assigned the task? Will be showing you the demo by tomorrow.

**Comment by bitaashna** [comment]
@urvashi-code1255 I have completed my previously assigned task..can I start working on this?
Please assign me this task 
#gssoc21

**Comment by urvashi-code1255** [comment]
Sure go for it @bitaashna :)

**Comment by bitaashna** [comment]
oops !! Somebody have already done it ! I haven't checked it...I will be closing this issue as it is already done
