### ISSUE TITLE
The navbar expansion button(hamburger) is not working

### ISSUE THREAD

**Issue by Suhail-BW** [Vishal-raj-1/Awesome-JavaScript-Projects#255]
## Describe the bug
The hamburger button of navbar is not expanding the navbar when screen size is minimised.

## To Reproduce
1. Minimize the main web-page, press the hamburger button of navbar.
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Mac-os
 - Browser: Chrome

**Comment by Suhail-BW** [comment]
@urvashi-code1255  Please look into the issue. If possible assign this to me as participant in GSSOC21.

**Comment by urvashi-code1255** [comment]
Yeah @Suhail-BW I noticed this too. Please go for it :)

**Comment by 991rajat** [comment]
Hey @Suhail-BW any updates ?
