### ISSUE TITLE
Stone paper scissors game 

### ISSUE THREAD

**Issue by sejalshri** [Vishal-raj-1/Awesome-JavaScript-Projects#257]
I would like to add javascript stone paper scissors game project as a participant of GSSOC,21 .
Kindly assign this issue to me.

**Comment by vinayak0127** [comment]
- As a GSSOC'21 participant i'd like to contribute this project rock , paper and scissor game in pure vanilla js:
- this will have following key features :-
  - Score Section
  - Winning message
  - Nice custom emojis to play
-Kindly assign this issue to me @urvashi-code1255  @Vishal-raj-1

**Comment by codDoc98** [comment]
please label it gssoc'21 and assign me this project, will be grateful to you.

**Comment by urvashi-code1255** [comment]
@vinayak0127 @codDoc98 @sejalshri @Riya764 There is a rock paper scissor already present in the project.
