### ISSUE TITLE
enhance the color flipper styling

### ISSUE THREAD

**Issue by gnikita432** [Vishal-raj-1/Awesome-JavaScript-Projects#258]
## Is your feature request related to a problem? Please describe.
No, it's not a problem. I am trying to enhance the styling of the color flipper.
## Describe the solution you'd like
I will modify the CSS file of the color flipper to enhance its styling
![jsissue1](https://user-images.githubusercontent.com/61223163/110448037-d50a7d80-80e6-11eb-9767-3e8dea4ce609.PNG)
![jsissue2](https://user-images.githubusercontent.com/61223163/110449049-cbcde080-80e7-11eb-86e9-cfbc8a41e651.png)

## Additional context
Please assign this task to me under GSSOC'21

**Comment by urvashi-code1255** [comment]
@gnikita432 @Quickbeasts51429 You both can divide the styling work. I am assigning this to both of you :)

**Comment by gnikita432** [comment]
@Quickbeasts51429 I have added hex colors in the color flipper. can you please share your idea?

**Comment by 991rajat** [comment]
Any Updates @gnikita432  and @Quickbeasts51429 ?

**Comment by Ankita297** [comment]
Can i work on this ?
@991rajat @urvashi-code1255

**Comment by Ankita297** [comment]
@ridsuteri

**Comment by ridsuteri** [comment]
@gnikita432 and @Quickbeasts51429 i am assigning this issue to @Ankita297 now ! 
since you haven't given any updates from a long time now
