### ISSUE TITLE
BMI-calculator-UI-changes

### ISSUE THREAD

**Issue by ishita-sehgal** [Vishal-raj-1/Awesome-JavaScript-Projects#259]
I would like to improve the styling of the BMI calculator UI. 
I would like to do following changes/rectify:
-after submitting, the fields should have automatically become clear or have a placeholder.
-on submitting on empty fields , the div content moves out.
-make the UI a little better looking .

@urvashi-code1255 , @Vishal-raj-1  Can you please assign this issue to me as a participant of GSSOC'21.

**Comment by srisatya1197** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by urvashi-code1255** [comment]
@srisatya1197 Please look at other issues in this repository which are opened by either me or @Vishal-raj-1
