### ISSUE TITLE
Insert margin-top in the project cards.

### ISSUE THREAD

**Issue by padmajabhol** [Vishal-raj-1/Awesome-JavaScript-Projects#260]
## Describe the bug
There isnt any top margin in the project cards and doesn't look good.
## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by Suhanii1214** [comment]
hello!! @padmajabhol 
I would like to work on this issue please assign it to me. I already have some experience in working with HTML & CSS

**Comment by padmajabhol** [comment]
> hello!! @padmajabhol 
> I would like to work on this issue please assign it to me. I already have some experience in working with HTML & CSS

I m not the project admin 😅

**Comment by urvashi-code1255** [comment]
@padmajabhol Do you want to work on it?

Or shall I assign this to @Suhanii1214

**Comment by padmajabhol** [comment]
> @padmajabhol Do you want to work on it?
> 
> Or shall I assign this to @Suhanii1214 

I want to work on it. Please assign this to me.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me. @padmajabhol

**Comment by 991rajat** [comment]
Hey @padmajabhol please elaborate I didn't get it?

**Comment by Vishal-raj-1** [comment]
@padmajabhol Could you please share screenshot. So that I can understand what you want to do ?

**Comment by urvashi-code1255** [comment]
@padmajabhol Any updates on this issue?
