### ISSUE TITLE
I would like to work on a todo javascript web project Please assign it to me under GsSOc'21

### ISSUE THREAD

**Issue by AakankshaShah** [Vishal-raj-1/Awesome-JavaScript-Projects#261]
## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by urvashi-code1255** [comment]
@AakankshaShah There is already an issue present on todo list. Please check that out #19
