### ISSUE TITLE
Color Code Converter and Color picker

### ISSUE THREAD

**Issue by AmeyaJain-25** [Vishal-raj-1/Awesome-JavaScript-Projects#265]
# Color Code Converter and Color picker
I would like to make an color code converter web page using javascript.

## Features:
1. HEX to RGB converter.
2. RGB to HEX converter.
3. Select a color by inputting the range using progress input.
4. Random color picker.

Please assign this to me under GSSoC 21'

**Comment by urvashi-code1255** [comment]
@AmeyaJain-25 go for it :)

**Comment by AmeyaJain-25** [comment]
Please add a label for GSSoC 21.
As mentioned on Discord, the points will be provided for GSSoC labels only
@urvashi-code1255

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by AmeyaJain-25** [comment]
I'm ready with the code @urvashi-code1255 
Please add the label of GSSoC 21' so that I can make the PR.

**Comment by AmeyaJain-25** [comment]
Made the PR #447 
Please review my PR
