### ISSUE TITLE
Random Password Generator

### ISSUE THREAD

**Issue by HarshMarolia** [Vishal-raj-1/Awesome-JavaScript-Projects#268]
## Features
Desired length Password.
Copy to clipboard feature.

Please assign this issue to me :)

**Comment by HarshMarolia** [comment]
Please assign this issue to me @urvashi-code1255

**Comment by sagunjaiswal** [comment]
hi,
I am a GSSOC'21 participant.
I would love to work on this issue can you assign this to me?

thanks in advance

**Comment by urvashi-code1255** [comment]
@HarshMarolia We already have a Random Password Generator App!!
