### ISSUE TITLE
ADD TrackerU web app Js

### ISSUE THREAD

**Issue by mohdjameel2412** [Vishal-raj-1/Awesome-JavaScript-Projects#269]
**hello greetings fellas** , I want to contribute a project that build on top of pure js HTML CSS
**Project** : TrackerU
**Features** : 
1. get users location info: **longitude &  latitude** **state** **country** **city**
2. get users device info : **os** **os type/version** **build info**
3. detect ip is exposed or not 
4. have a scale of venerability and for R&D purposes save users info 
i want to contribute my small project , is there any way i could do that?

**Comment by urvashi-code1255** [comment]
@mohdjameel2412 go for it!

**Comment by mohdjameel2412** [comment]
already  pull requested from @mohammedjameel24

i did not use this account to register with GSSOC21 that's the reason i created a account with my GSSOC registered account 
i apologies for confusions

**Comment by mohammedjameel24** [comment]
Please merge my pull request @urvashi-code1255 

Issue #370
