### ISSUE TITLE
RGB COLOR GUESSING GAME!

### ISSUE THREAD

**Issue by SHAGUN0312** [Vishal-raj-1/Awesome-JavaScript-Projects#270]
I would like to make a color guessing game using javascript.

**Features**
1. Button to choose between easy or Hard level.
2. Change in the background color, if the right color is chosen.
3. You'll be able to choose new colors, if you are not happy with the current shuffle of colors, just like it happens in spider solitaire, basically new game.
4. A 'try again', 'play again' and Correct alerts, based on the responses of the user.

PLease assign this to me under GSSoC 2021

**Comment by 0Faiz0** [comment]
I would like to make a color guessing game using javascript. as a GSSOC'21 participant

**Comment by urvashi-code1255** [comment]
@SHAGUN0312 @0Faiz0 You both can divide the work :)
