### ISSUE TITLE
impoved UI of calculator Webapp

### ISSUE THREAD

**Issue by mohdjameel2412** [Vishal-raj-1/Awesome-JavaScript-Projects#272]
## Is your feature request related to a problem? Please describe.
impoved UI of caculator Webapp
## Describe the solution you'd like
improve styling

## Additional context
please assign me

**Comment by urvashi-code1255** [comment]
@mohdjameel2412 go for it :)

**Comment by mohdjameel2412** [comment]
@urvashi-code1255  please assign this task to @mohammedjameel24 

the resason is this account of mine was not used to register in GSSOC and thats the reason i created a account with registered account 
I apologize for confusions 

thank you

**Comment by mohammedjameel24** [comment]
@urvashi-code1255 

Confirming both are my accounts 
Again sorry for confusions

**Comment by urvashi-code1255** [comment]
@mohammedjameel24 Please go for it :)

**Comment by khushi935** [comment]
Can I work on this?

**Comment by 991rajat** [comment]
@mohammedjameel24 Any Updates?

**Comment by mohammedjameel24** [comment]
pull req #700

**Comment by 991rajat** [comment]
You Don't have to link Here, Fill the PR description properly It will be linked automatically

Like 
Closes : #PR_NO

**Comment by Ankita297** [comment]
Can i work on this @991rajat @urvashi-code1255 ?

**Comment by Ankita297** [comment]
@ridsuteri ?

**Comment by ridsuteri** [comment]
@mohdjameel2412  has already raised a PR so i don't think this issue is available for now @Ankita297..

**Comment by Ankita297** [comment]
okay I thought that the PR was having some conflicts and  they had not been resolved ?

**Comment by ridsuteri** [comment]
@Ankita297 yes it has conflicts and  we have given him to resolve them

**Comment by mohammedjameel24** [comment]
Making a pr.
