### ISSUE TITLE
 bug:- the search bar is not working. 

### ISSUE THREAD

**Issue by kumarishalini6** [Vishal-raj-1/Awesome-JavaScript-Projects#275]
search bar;-
1. while searching someting like;- project... etc noting happens.
can you assign this to me under gssoc21

**Comment by Vishal-raj-1** [comment]
@kumarishalini6 Yeah Sure !! You can implement that feature

**Comment by harshgupta20** [comment]
Any update ?
Reply within 2 days or else i have to close this issue.
