### ISSUE TITLE
Task-Manager

### ISSUE THREAD

**Issue by AbhishekTiwari07** [Vishal-raj-1/Awesome-JavaScript-Projects#276]
I would like to add a task manager based on VanillaJS.

## Features
- Add new tasks
- Mark completed ones.
- Remove any task

## Additional Features
I'll try to add some animation :)

Please assign this to me under GSSoC'21

**Comment by urvashi-code1255** [comment]
@AbhishekTiwari07 go for it!

**Comment by harshgupta20** [comment]
Any update ?
Reply within 2 days or else i have to close this issue.
