### ISSUE TITLE
Weather App using Vanilla Javascript

### ISSUE THREAD

**Issue by sejalxz** [Vishal-raj-1/Awesome-JavaScript-Projects#277]
# Weather App
I would like to make a Weather app using JavaScript. I will be using darksky API to pull the necessary weather information.

## Features
1. Time zone
2. Temperature in Fahrenheit 
3. Temperature in Celsius  
4. SVG to represent weather condition (sunny/cloud..)

Please assign this to me under GSSoC 21'

**Comment by urvashi-code1255** [comment]
@sejalxz A weather app is already present in the project. Let me know if you can modify it :)

**Comment by sejalxz** [comment]
Sure, should I work on the same code base or work on this issue here?

**Comment by urvashi-code1255** [comment]
Sure go for it @sejalxz :)

**Comment by sejalxz** [comment]
@urvashi-code1255 I am actually stuck at a point. 
I have added the toggle feature when you click on the temperature. It works perfectly fine when the location is detected by browser (using latitude and longitude by allowing location) and toggles well. It's not working when I fetch details of temperature of the city using API it toggles only once for some cities. For some cities it works fine and for some cities it only shows in Fahrenheit. 

Could you help me around it?

**Comment by 991rajat** [comment]
@sejalxz Comment here what ever help needed.

**Comment by sejalxz** [comment]
@991rajat I have added the toggle feature from Celsius to Fahrenheit but it  not working when I fetch details of temperature of the city using API it toggles only once for some cities. I am not able to go around it

**Comment by 991rajat** [comment]
Is API working properly ? Are the responses you getting are correct? 
Send me the link of the branch I'll try to look into.

**Comment by sejalxz** [comment]
The API is working properly but the toggling is not working when you search for the cities but it works when the location is detected by the browser
