### ISSUE TITLE
Netflix Clone Search Bar and Logo Not Fixed On Top

### ISSUE THREAD

**Issue by Aanchal116** [Vishal-raj-1/Awesome-JavaScript-Projects#278]
Hii @Vishal-raj-1 ,
The topmost search bar containing the logo disappears if we scroll down, I would like to work on this issue and make the same fixed to the top. Please assign this issue to me as a part of GSSOC'21.

**Comment by urvashi-code1255** [comment]
@Aanchal116 Sure go for it :)

Make sure to follow the project guidelines and pattern.

**Comment by Aanchal116** [comment]
> @Aanchal116 Sure go for it :)
> 
> Make sure to follow the project guidelines and pattern.

Thanks @urvashi-code1255 , I'll get back to you as soon as possible.

**Comment by Aanchal116** [comment]
Hey @urvashi-code1255 , I completed my task and created a pull request for the same. Please have a look.
