### ISSUE TITLE
Adding a logo in the nav bar

### ISSUE THREAD

**Issue by shubhraagarwal** [Vishal-raj-1/Awesome-JavaScript-Projects#279]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to enhancing the look of navbar.
## Describe the solution you'd like
The navbar is missing a logo and that makes it look very dull, I would like to add a logo in the navabar, similar to the one in the title 
![image](https://user-images.githubusercontent.com/67220475/110584725-af887d00-8195-11eb-8a94-39e2cf8468e4.png)

I would to work on this issue under GS'SOC21

## Additional context
Add any other context about the feature request here.

**Comment by abhishek96k** [comment]
I would like to add a logo in the navbar.
so, can I go for it?
I am GSSoC'21 participant.
please /assign it to me.

**Comment by Aanchal116** [comment]
Hii,
I would like to work on this issue as a part of GSSOC'21. Please assign it to me.

**Comment by ORKO06** [comment]
I would like to work on this issue as a part of GSSOC'21. Please assign it to me.

**Comment by sagunjaiswal** [comment]
hi,

I would love to work on this issue can you assign this to me ?

thanks in advance

**Comment by 0Faiz0** [comment]
I Would like to work on this issue as a GSSOC'21 participant.

**Comment by urvashi-code1255** [comment]
@sagunjaiswal @shubhraagarwal  @Aanchal116 @0Faiz0 @ORKO06 @abhishek96k You all can suggest the logo designs.

**Comment by Vishal-raj-1** [comment]
Anybody interested or shall I close this issue !!
