### ISSUE TITLE
Space between Home and About Section

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#28]
Deliverables:
- Remove the extra space present between Home and About section(Reduce the space).

Screenshot of the bug
![Capture](https://user-images.githubusercontent.com/63122133/107220332-3aac1100-6a38-11eb-8378-28cb61bc95c7.PNG)

**Comment by shakmg** [comment]
@urvashi-code1255 Hi, I've submitted a first open source PR for this issue, please take a look, thanks.

**Comment by shakmg** [comment]
@urvashi-code1255 Can you please help me understand as I can't see my contribution to this repo even though my changes have been merged in?
