### ISSUE TITLE
Personal library app

### ISSUE THREAD

**Issue by ireneelizabethsabu** [Vishal-raj-1/Awesome-JavaScript-Projects#280]
Hi,
I am participant of GSSOC'21. I would like to contribute a simple **personal library website** using js.
Kindly assign this to me.

**Comment by urvashi-code1255** [comment]
@ireneelizabethsabu Sure go for it :)

**Comment by harshgupta20** [comment]
Any update ?
Reply within 2 days or else i have to close this issue.

**Comment by ireneelizabethsabu** [comment]
I apologize for the delay caused due to end sem exams.I am working on it and  will make the PR within 2 days.

**Comment by harshgupta20** [comment]
@ireneelizabethsabu update ?

**Comment by ireneelizabethsabu** [comment]
I have sent the PR already.Please look into it.
