### ISSUE TITLE
Typewriter effect using vanilla js

### ISSUE THREAD

**Issue by SanskaarPatni** [Vishal-raj-1/Awesome-JavaScript-Projects#282]
I would love to add a simple html page with a typerwriter effect.
@Vishal-raj-1 please assign me this issue as a part of GSSOC'21.

**Comment by urvashi-code1255** [comment]
@SanskaarPatni Sure go for it :)

Try to make it unique :)

**Comment by SanskaarPatni** [comment]
I tried squashing the commits but in the end always ran into problem.
I then created a new branch and later a new PR. 
Kindly merge the new PR #680 @Vishal-raj-1 @urvashi-code1255 .
The deletion of the earlier branch caused the old pull request to close by itself.
Thank you.
