### ISSUE TITLE
Text Formatter

### ISSUE THREAD

**Issue by poojitha2002** [Vishal-raj-1/Awesome-JavaScript-Projects#284]
Hi I am GSSOC participant. I would like to contribute this project. This is used to format the given text. Like converting text to upper case, lower case,  calculating frequency of each word, character count, number of lines in given text  and word count. The tech stack used is HTML,CSS,JS. Hope it will get assigned. Please assign this to me under GSSoC '21.

**Comment by urvashi-code1255** [comment]
@poojitha2002 Sure go for it :)

**Comment by poojitha2002** [comment]
Thank you for assigning!!

**Comment by poojitha2002** [comment]
Hello I have completed the project, please do verify it. 
https://github.com/poojitha2002/TextFormatter

**Comment by poojitha2002** [comment]
Hello can you please verify the project?

**Comment by poojitha2002** [comment]
Is my project validated?

**Comment by harshgupta20** [comment]
This project already exist.

**Comment by poojitha2002** [comment]
I think no, if existed why u have assigned :(
