### ISSUE TITLE
Dice Game

### ISSUE THREAD

**Issue by Manish-kasera** [Vishal-raj-1/Awesome-JavaScript-Projects#285]
I want to build a Dice game using Js and little bit CSS3 and HTML5 which can be simply play by refreshing the page..

**Comment by rk05-lenavo** [comment]
I'm the participant in GSSOC'21. i would love to work on this.Please assign me this issue.

**Comment by urvashi-code1255** [comment]
@Manish-kasera Sure go for it :)

**Comment by urvashi-code1255** [comment]
@rk05-lenavo Please look at other issues as we follow first ask first get rule!

**Comment by Ankita297** [comment]
Can i work on this ? @urvashi-code1255  @rk05-lenavo  @ridsuteri ?

**Comment by ridsuteri** [comment]
@Manish-kasera any updates?

**Comment by Manish-kasera** [comment]
Sorry for this... But please assign this to @Ankita297

**Comment by Ankita297** [comment]
@ridsuteri can i work on this as there has been two days and there is no response from @rk05-lenavo ?
@Vishal-raj-1 ?

**Comment by ridsuteri** [comment]
@rk05-lenavo i am assgining this issue to @Ankita297 !
