### ISSUE TITLE
UI Design and Text Formatting

### ISSUE THREAD

**Issue by Aanchal116** [Vishal-raj-1/Awesome-JavaScript-Projects#286]
Hii,
I'm a GSSOC'21 participant. I would like to edit the text style and few other things for UI on the text generator site to make it more attractive .Please assign this issue to me. Thankyou.

**Comment by urvashi-code1255** [comment]
Sure go for it @Aanchal116 :)

**Comment by 991rajat** [comment]
I'm Closing this for now since UI has been changed.
