### ISSUE TITLE
Javascript Drawing - Infinite Rainbow Maker

### ISSUE THREAD

**Issue by Praddyumn16** [Vishal-raj-1/Awesome-JavaScript-Projects#287]
This is a beginner friendly JS project which I would like to add in this set of awesome JS projects as a part of GSSoC'21. 
@Vishal-raj-1 I would recommend this project to be added because I myself started learning JS recently and this project was one of the initial projects I created.

**Comment by urvashi-code1255** [comment]
@Praddyumn16 Sure go for it :)

**Comment by harshgupta20** [comment]
Any update ?
Reply within 2 days or else i have to close it.
