### ISSUE TITLE
We can add the link to the website in readme.md This will be easy for new comers to get interacted with project 

### ISSUE THREAD

**Issue by rohank2502** [Vishal-raj-1/Awesome-JavaScript-Projects#288]
## Describe the bug
Not a Bug  but an update 
We can add the link of website ( github page ) in the read me file

## To Reproduce
1. Add the link in readme file 

## Expected behavior
This will help new comers to get interacted with the website in a better way 

I will like to work on this issue as a part of gssoc please let me know we can do this update or not !

**Comment by ayush461** [comment]
@rohank2502  Can u please assign this task to me,I am GSSOC 21 participant.

**Comment by urvashi-code1255** [comment]
@rohank2502 How will you add the link? Like in the form of badge or what? Can you show me the preview?

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 How will you add the link? Like in the form of badge or what? Can you show me the preview?

We can do both !! Which will look nice ? What you think ?

**Comment by rohank2502** [comment]
What to do please take a look here

**Comment by harshgupta20** [comment]
Hi @rohank2502 you can add whichever suits the site just make sure it should attractive and eye caching.

**Comment by rohank2502** [comment]
> hichever suits the site just make sure it should attractive and eye caching.
> i will suggest you to do it as soon as possible because it would be good for the project.

For Sure WIll get back to you with a PR today
