### ISSUE TITLE
[GSSoC '21] Adding pixels game

### ISSUE THREAD

**Issue by amrzaki2000** [Vishal-raj-1/Awesome-JavaScript-Projects#289]
Hello,
I'd like to create a mouse-click game in which pixels are falling from top of the screen and the user has to click them before  they reach bottom of the screen.

I'm a GSSoC participant. Can you assign this to me , please?

**Comment by amrzaki2000** [comment]
@Vishal-raj-1

**Comment by amrzaki2000** [comment]
@urvashi-code1255 @Vishal-raj-1  please assign this to me

**Comment by amrzaki2000** [comment]
@urvashi-code1255 @Vishal-raj-1

**Comment by urvashi-code1255** [comment]
@amrzaki2000 Sure go for it :)

**Comment by amrzaki2000** [comment]
@urvashi-code1255  
Hello,
I've raised PR regarding this issue.
Thank you
