### ISSUE TITLE
[GSSOC'21] Expense tracker app

### ISSUE THREAD

**Issue by vinayak0127** [Vishal-raj-1/Awesome-JavaScript-Projects#290]
id like to contribute this project as a gssoc'21 participant in pure vanilla js
please assign this project to me @urvashi-code1255  @Vishal-raj-1

**Comment by urvashi-code1255** [comment]
@vinayak0127 Sure go for it :)

**Comment by vinayak0127** [comment]
I was having conflicts that's why I closed previous pull requests
