### ISSUE TITLE
Glassmorphism UI effect

### ISSUE THREAD

**Issue by risingphoenixx** [Vishal-raj-1/Awesome-JavaScript-Projects#293]
We can add a Glassmorphism UI effect to the calculator web page. well, It looks really cool and the tilt effect will make this project more interesting.
 Solu:- we can add this effect by using the Vanilla tilt javascript library. 

I want to add this effect with calculator.html
I want to work on these things. could you pls assign it for me @Vishal-raj-1 @urvashi-code1255? Pls, reply.

**Comment by urvashi-code1255** [comment]
@risingphoenixx Sure go for it :)

**Comment by risingphoenixx** [comment]
Thank you @urvashi-code1255
