### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by machine-sg** [Vishal-raj-1/Awesome-JavaScript-Projects#294]
## Describe the solution you'd like
I want to add favicon in the header of the  home page. It will give a good outlook to the website. Please assign me this. I want to do it as a part of GSSoC'21 participant.

**Comment by sahilempire** [comment]
I want to work on this issue, please **aasign me** ,

Thanking you.

**Comment by sahilempire** [comment]
I want to work on this issue, I want to do it as a part of **GSSoC'21 participant**.

Thank You.

**Comment by urvashi-code1255** [comment]
Favicon is already present in the website @machine-sg

**Comment by sahilempire** [comment]
But, maybe they want better fevicon as compare to present one.

**Comment by Vishal-raj-1** [comment]
@sahilempire show me the better one !!

**Comment by sahilempire** [comment]
@Vishal-raj-1 **okay**, I will submit my pull request, with amazing fevicon **by tomorrow**!

Thank you.

**Comment by sahilempire** [comment]
@Vishal-raj-1  **okay**, I will submit my pull request, with amazing fevicon **by tomorrow**.

Thank you.

**Comment by sahilempire** [comment]
@Vishal-raj-1  **okay**, I will submit my pull request, with amazing fevicon **by tomorrow**.

And **please assign me**.

Thank you.

**Comment by sahilempire** [comment]
@Vishal-raj-1 I have created pull request #856  for the required fevicon.

Thank you.
