### ISSUE TITLE
Feature:  Simon Game

### ISSUE THREAD

**Issue by Ishikakhurana** [Vishal-raj-1/Awesome-JavaScript-Projects#295]
I can add Simon Game project built using HTML CSS Javascript jQuery .It is a memory game. The game detects if user got same sequence from start to end (most recent ) displayed key. It will have sound effects on click given as a pattern to follow.

**Comment by urvashi-code1255** [comment]
@Ishikakhurana This project is only build using vanilla js , so let me know if you can implement it using pure vanilla js

**Comment by Ishikakhurana** [comment]
yes it can be implemented using vanilla js

**Comment by Ishikakhurana** [comment]
@urvashi-code1255
