### ISSUE TITLE
Feature:DrumKit

### ISSUE THREAD

**Issue by Ishikakhurana** [Vishal-raj-1/Awesome-JavaScript-Projects#296]
The present Drum Kit project does not allow mouse click to select sound, only keypress is detected. if you allow, i can add the on click feature.

**Comment by urvashi-code1255** [comment]
@Ishikakhurana  Sure go for it!

Make sure to follow the project guidelines and pattern

**Comment by harshgupta20** [comment]
This issue already been resolved.
