### ISSUE TITLE
Filter Search (JavaScript)

### ISSUE THREAD

**Issue by Maitryee-Choudhary** [Vishal-raj-1/Awesome-JavaScript-Projects#297]
The project aims that it will have list of  items/images and based on user filter it will display the item/image that corresponds to required filter.
It will be easy for the user to have the content by filtering the items.
I will be displaying group of images and after applying filter, corresponding list of images will be display.

Hey @urvashi-code1255  can you please assign this issue to me?

**Comment by urvashi-code1255** [comment]
@Maitryee-Choudhary  Sure go for it!

Make sure to follow the project guidelines and pattern

**Comment by Maitryee-Choudhary** [comment]
> @Maitryee-Choudhary Sure go for it!
> 
> Make sure to follow the project guidelines and pattern

Yes,Thank you!

**Comment by harshgupta20** [comment]
Hi @Maitryee-Choudhary , you are working on the from 13 march any update ?
Reply within 2 days or else i have to close the issue.
