### ISSUE TITLE
Impossible Button Game (using HTML CSS and JavaScript)

### ISSUE THREAD

**Issue by guruc-134** [Vishal-raj-1/Awesome-JavaScript-Projects#298]
I would like to add a small web application in which the users will be challenged to click a button while it moves to a random location each time the user tries to click on it.
Some additional features
* button color changer
*  random button color option
*  background image changed for each new game

**Comment by urvashi-code1255** [comment]
@guruc-134  Sure go for it!

Make sure to follow the project guidelines and pattern

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by guruc-134** [comment]
@urvashi-code1255 I have added the necessary files and submitted a Pull Request[ here]( https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/361)
Please review it.
