### ISSUE TITLE
New Project: Markdown Previewer 

### ISSUE THREAD

**Issue by guruc-134** [Vishal-raj-1/Awesome-JavaScript-Projects#299]
I would like to add a web application that is built using HTML, CSS and  JavaScript along with some external libraries.
This comes with a text editor which provides a place to type the lines of text. then the previewer will translate those lines of text along with the syntax and semantics of markdown language and display it dynamically as the user is typing.

**Comment by urvashi-code1255** [comment]
@Avishake007 Sure go for it!

Make sure to follow the project guidelines and pattern

Make sure to use only vanilla js

**Comment by guruc-134** [comment]
@urvashi-code1255  I have added the necessary files and made a Pull Request. please review it from [here](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/333)

**Comment by guruc-134** [comment]
@urvashi-code1255 I have added the necessary files and made a Pull Request. please review it from [here](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/470)

**Comment by harshgupta20** [comment]
This project already exist.
