### ISSUE TITLE
Stopwatch

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#30]
Deliverables: 
- Make a decent stopwatch using Vanilla Javascript with start, stop and reset button.

**Comment by khushi935** [comment]
I would like to work on this .

**Comment by urvashi-code1255** [comment]
Sure go ahead @khushi935 :)

**Comment by Nagsenwaghmare** [comment]
Hey @urvashi-code1255  I also want to work on this issue can you please suggest UI you want or How should it look like.

**Comment by urvashi-code1255** [comment]
> Hey @urvashi-code1255 I also want to work on this issue can you please suggest UI you want or How should it look like.

hey @Nagsenwaghmare This issue can only be assigned to one person. There are many more issues to work on. Please have a look at those

**Comment by Nagsenwaghmare** [comment]
@urvashi-code1255 ok, fine

**Comment by khushi935** [comment]
https://user-images.githubusercontent.com/62712155/107261166-fd11ad00-6a64-11eb-81a5-ef3c8c4a3626.mp4

Does this look good?

**Comment by urvashi-code1255** [comment]
> Does this look good?

Looking pretty cool!! @khushi935 . Please make a PR for the same.

**Comment by khushi935** [comment]
I should add a photo and shotwatch heading in the project section(home page) as well?

**Comment by urvashi-code1255** [comment]
> I should add a photo and shotwatch heading in the project section(home page) as well?

Yes make a card similar to other cards and add image of stopwatch to it. Also add link of html file to href of a in the home page.
