### ISSUE TITLE
[GSSOC 21 ']Digital Clock Project 

### ISSUE THREAD

**Issue by Prajwal-ctrl** [Vishal-raj-1/Awesome-JavaScript-Projects#300]
Hi i am a GSSOC 21 participant i'm a newbie to web dev . Can i work on this project ,

**Comment by urvashi-code1255** [comment]
@Prajwal-ctrl We already have a digital clock, if you have any ideas to improve it then you can go for it .

**Comment by pritamkr1** [comment]
Hi! I want to work on this issue.

**Comment by Prajwal-ctrl** [comment]
Can change the Ui and improve it . Can I work on this issue

**Comment by urvashi-code1255** [comment]
Sure @Prajwal-ctrl go for it :)

**Comment by vasanthgk02** [comment]
I am very much interested to work on this project . So pls assign this to me😇

**Comment by 991rajat** [comment]
@Prajwal-ctrl  Any Updates?

**Comment by Vedant-Rahane** [comment]
@991rajat  I would like to modify UI of this project.

I will change from this : 

![clock](https://user-images.githubusercontent.com/71424483/114292637-7b162280-9aad-11eb-87f0-9637a6e6d84c.png)

to this :

![clockupdate](https://user-images.githubusercontent.com/71424483/114292649-8ff2b600-9aad-11eb-8bbd-01283fdef11e.png)

@Vishal-raj-1 @991rajat @urvashi-code1255 Can you assign me this ?

**Comment by 991rajat** [comment]
I'm closing this. @Vedant-Rahane  Someone is working on it If he didn't updates in 2 days. You will be assigned. Remind us by commenting here #820
