### ISSUE TITLE
[GSSOC'21] [IDEA] 2048 Game

### ISSUE THREAD

**Issue by midhun-b-m** [Vishal-raj-1/Awesome-JavaScript-Projects#301]
## Is your feature request related to a problem? Please describe.
I would like to develop 2048 Game using Javascript

## Describe the solution you'd like
Develop a 2048 game using javascript 

**Features**

- Different coloured tiles for different numbers
- A score indicator   
- Best score display

## Additional context
NA

**Comment by midhun-b-m** [comment]
@urvashi-code1255 I would like to work on this project idea.

**Comment by urvashi-code1255** [comment]
@midhun-b-m  Sure go for it!

Make sure to follow the project guidelines and pattern

**Comment by midhun-b-m** [comment]
**Status update** : project is almost done - will upload in a day or two
