### ISSUE TITLE
Maths Quiz Game

### ISSUE THREAD

**Issue by Saumya-07** [Vishal-raj-1/Awesome-JavaScript-Projects#302]
I would like to contribute to this project by adding a maths quiz game for fun, 
please assign this project addition to me @urvashi-code1255 @Vishal-raj-1
I am a GSSOC'21 participant and I am excited to contribute to this project

**Comment by urvashi-code1255** [comment]
@Saumya-07 I am assigning you two issues, so first complete those two, then ask for this :)

**Comment by balarka135** [comment]
@urvashi-code1255 I like to work on this issue. Please Assign me

**Comment by urvashi-code1255** [comment]
@Saumya-07 You have already assigned two issues so I am assigning this to @balarka135

**Comment by balarka135** [comment]
Thank you for assigning me. I will update you tomorrow about my project status.

**Comment by balarka135** [comment]
@urvashi-code1255 I build the math game already. But after several tries
![problem](https://user-images.githubusercontent.com/43699566/111038099-3915a480-844d-11eb-92fe-0d9e17306344.png)
 I am unable to link the image or gif with the Project section on the page. I attached a screenshot for your reference. pls, help me.Thank you
