### ISSUE TITLE
Github profile finder 

### ISSUE THREAD

**Issue by Saumya-07** [Vishal-raj-1/Awesome-JavaScript-Projects#303]
I would like to add a GitHub profile finder using GitHub API which can display various users name and their data
I would like @urvashi-code1255 @Vishal-raj-1 to please assign me this project.
I am a GSSOC'21 participant and looking forward to contributing to this project

**Comment by urvashi-code1255** [comment]
@Saumya-07 Can you please first show the demo here?

**Comment by Saumya-07** [comment]
It would be like we can enter Github username, and it would display the count of public repos, gists, followers, and following. Their bio can be displayed and the name of the followers

**Comment by urvashi-code1255** [comment]
@Saumya-07 go for it :)

**Comment by harshgupta20** [comment]
Any update ?
reply with in 2 days or else I have to close this issue.

**Comment by Saumya-07** [comment]
Sorry sir, I was not well, couldn't response
I had started working on the project only a day or two is required to complete it.
Can you please reopen the issue?
