### ISSUE TITLE
Movie search app

### ISSUE THREAD

**Issue by SatyaPrakash26** [Vishal-raj-1/Awesome-JavaScript-Projects#304]
I would like to add a movie search app using API and can display various movies with the word you searched
I would like @urvashi-code1255 @Vishal-raj-1 to please assign me this project.
I am a GSSOC'21 participant and want to contribute to this project

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by 991rajat** [comment]
@Dimple115 Are you still interested?

**Comment by Vishal-raj-1** [comment]
@SatyaPrakash26 or @Dimple115 Reply here are you interested or not !!

**Comment by SatyaPrakash26** [comment]
I am interested in this

**Comment by Vishal-raj-1** [comment]
@SatyaPrakash26 Okay assigned to you !! You can raise PR now.

**Comment by SatyaPrakash26** [comment]
Please add the level to it

**Comment by harshgupta20** [comment]
The tag has been added, you can send the PR now.

**Comment by harshgupta20** [comment]
@SatyaPrakash26 Kindly reply within 2 days or I have to close this.

**Comment by SatyaPrakash26** [comment]
I have almost completed my project.

**Comment by harshgupta20** [comment]
@SatyaPrakash26 , No problem you can take your time, but kindly inform us about the project you making so that your issue will not consider as inactive.

**Comment by SatyaPrakash26** [comment]
Sorry for that. Won't happen again

**Comment by SatyaPrakash26** [comment]
@harshgupta20  I have created the Pull Request 4 days ago. Please Look into this.

**Comment by harshgupta20** [comment]
@SatyaPrakash26 Kindly llink that PR with this issue.

**Comment by SatyaPrakash26** [comment]
please look into this

**Comment by Vishal-raj-1** [comment]
for this first you have to add & commits your changes then you have to pull changes

**Comment by Ankita297** [comment]
@SatyaPrakash26 are you working on this ?

**Comment by Atif0604** [comment]
Please assign this to me @Ankita297 
I'm a participant of LGMSOC'21

**Comment by Ankita297** [comment]
@Atif0604 go for it .
