### ISSUE TITLE
Fruit slicer game

### ISSUE THREAD

**Issue by SatyaPrakash26** [Vishal-raj-1/Awesome-JavaScript-Projects#306]
It is a simple fruit slicing game for fun, various fruits would drop, we have to slice each fruit and earn points, we will have three chances to continue the game if w a drop a fruit and timer also 
I would like to add this project and work on it
@urvashi-code1255 @Vishal-raj-1 to please assign me this project.
I am a GSSOC'21 participant and want to contribute to this project

**Comment by urvashi-code1255** [comment]
@SatyaPrakash26  Sure go for it!

Make sure to follow the project guidelines and pattern

**Comment by risingphoenixx** [comment]
I want to work on this issue. pls, Assign me @urvashi-code1255. I am a GSSOC'21 participent and want to contribute .

**Comment by 991rajat** [comment]
@SatyaPrakash26  Any Updates?

**Comment by SatyaPrakash26** [comment]
> @SatyaPrakash26 Any Updates?

Yes I am working on it
