### ISSUE TITLE
Add feature in Local Storage project

### ISSUE THREAD

**Issue by Saumya-07** [Vishal-raj-1/Awesome-JavaScript-Projects#307]
I am thinking I can add a button to delete the items added to the local storage project or strike the things done y clicking on the box,
I would like to work on this, please assign the issue to me  @urvashi-code1255 @Vishal-raj-1 
I am a GSSOC'21 participant and looking forward to contributing to this project

**Comment by urvashi-code1255** [comment]
@Saumya-07  Sure go for it!

Make sure to follow the project guidelines and pattern

**Comment by Saumya-07** [comment]
I can see all the older code is removed so should I make a local storage project from start then add changes 
I want to tell you I had forked the project before assigning it to me, so should I continue with that one and apply changes or make a new one @urvashi-code1255

**Comment by Saumya-07** [comment]
I am unable to create a pull request.
I have fixed the issue and added few functionalities.
