### ISSUE TITLE
3d cube effect

### ISSUE THREAD

**Issue by Avishake007** [Vishal-raj-1/Awesome-JavaScript-Projects#308]
I would  to add a 3d cube effect .
I would like @urvashi-code1255 @Vishal-raj-1 to please assign me this project.
I am a GSSOC'21 participant and want to contribute for this project.

**Comment by Avishake007** [comment]
@urvashi-code1255  and @Vishal-raj-1  here is what I have made . Do give your feedback.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/56298861/110737584-a4942200-8253-11eb-92f5-913577e4c590.gif)

**Comment by Avishake007** [comment]
@urvashi-code1255  please provide a label for gssoc21

**Comment by urvashi-code1255** [comment]
Its looking good to me @Avishake007 You can come up with a PR!!
