### ISSUE TITLE
Number System Calculator 

### ISSUE THREAD

**Issue by Amisha-here** [Vishal-raj-1/Awesome-JavaScript-Projects#309]
I would like to add a different calculator which will be converting decimal numbers to Binary,Ternary,Octal,Hexadecimal and vice versa.
I would like @urvashi-code1255 @Vishal-raj-1 to please assign me this project.
I am a GSSOC'21 participant and want to contribute to this project.

**Comment by urvashi-code1255** [comment]
@Amisha-here  Sure go for it!

Make sure to follow the project guidelines

**Comment by Amisha-here** [comment]
<img width="957" alt="Annotation 2021-03-14 131131" src="https://user-images.githubusercontent.com/66164747/111061012-132ce600-84c7-11eb-8eb0-40568e2a3859.png">

I have completed it.. please review it.. also add gssoc21 tag

**Comment by 991rajat** [comment]
@Amisha-here  Good Work
Create a PR.

**Comment by harshgupta20** [comment]
@Amisha-here it's a good project, you can send the PR : )

**Comment by harshgupta20** [comment]
@Amisha-here Its been month, you haven't replied, so you have to reply within 2 days, else I have to close it.
