### ISSUE TITLE
Change UI of the Project Section

### ISSUE THREAD

**Issue by Vishal-raj-1** [Vishal-raj-1/Awesome-JavaScript-Projects#31]
Remove Visit button from here and make image clickable which redirect to the project. Increase the Image size. 

![project](https://user-images.githubusercontent.com/59874304/107253323-34c82700-6a5c-11eb-8f80-9dff87c1d658.JPG)

**Comment by khushi935** [comment]
I want to work on this.

**Comment by urvashi-code1255** [comment]
> I want to work on this.

Sure Go Ahead @khushi935 . Looking forward to your PR :)

**Comment by khushi935** [comment]
Should I comment the button code or remove it?

**Comment by urvashi-code1255** [comment]
> Should I comment the button code or remove it?

Remove it @khushi935

**Comment by khushi935** [comment]
https://user-images.githubusercontent.com/62712155/107530850-40ddf100-6be2-11eb-8d16-acea0a1da695.mp4

Please have a look at once.

**Comment by urvashi-code1255** [comment]
> Please have a look at once.
Looking Nice @khushi935 . Please raise a PR :)

**Comment by urvashi-code1255** [comment]
Hey @khushi935 window.location is not working for github. So, projects are not opening on clicking on the images. Please find some other way to do it. 

![image](https://user-images.githubusercontent.com/63122133/107659284-ff664800-6cac-11eb-960b-76c5d74b259a.png)

**Comment by khushi935** [comment]
Okay I will try to do it in some other way. Please check this is bowser also. Is it working ?

**Comment by khushi935** [comment]
> Hey @khushi935 window.location is not working for github. So, projects are not opening on clicking on the images. Please find some other way to do it.
> 
> ![image](https://user-images.githubusercontent.com/63122133/107659284-ff664800-6cac-11eb-960b-76c5d74b259a.png)

How did you get this page? Means by clicking on which button did you get there?

**Comment by khushi935** [comment]
> Okay I will try to do it in some other way. Please check this is bowser also. Is it working ?

We can use window.location.href. I am not able to find another way. Please guide me.

**Comment by urvashi-code1255** [comment]
> Okay I will try to do it in some other way. Please check this is bowser also. Is it working ?

Hey @khushi935 Its working locally. But if you try to click on the projects from [this](https://vishal-raj-1.github.io/Awesome-JavaScript-Projects/) hosted link. You will get the error.

**Comment by urvashi-code1255** [comment]
> We can use window.location.href. I am not able to find another way. Please guide me.

@khushi935 You can simply use [this](https://www.daniweb.com/posts/jump/1968855). There's no need of javascript.

**Comment by khushi935** [comment]
okay got it. Thanks !!

**Comment by Vishal-raj-1** [comment]
@khushi935 You dont need to implement any javascript for this purpose. Just add put all code of card div in anchor tag (`<a href="...."> </a>`)

**Comment by khushi935** [comment]
> @khushi935 You dont need to implement any javascript for this purpose. Just add put all code of card div in anchor tag (`<a href="...."> </a>`)

I added a tag. Please check it.
