### ISSUE TITLE
AND , OR and XOR converter

### ISSUE THREAD

**Issue by Avishake007** [Vishal-raj-1/Awesome-JavaScript-Projects#312]
It will take take two decimal numbers as input and will produce the AND, OR and XOR of the two numbers.
I want to work on this project.
Please @urvashi-code1255 and @Vishal-raj-1  assign me for this project.
I am a GSSOC'21 participant and wants to contribute for this project

**Comment by urvashi-code1255** [comment]
@Avishake007 Sure go for it!

Make sure to follow the project guidelines

**Comment by Avishake007** [comment]
This is what I have developed. @urvashi-code1255  and @Vishal-raj-1 kindly give your feedback.  
![Uploading andorxor(1).PNG…]()

**Comment by Avishake007** [comment]
@urvashi-code1255  please provide a label for gssoc21

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by urvashi-code1255** [comment]
@Avishake007 Please reduce the border-radius of input boxes as its difficult to see the numbers entered

**Comment by Avishake007** [comment]
Sure @urvashi-code1255

**Comment by Avishake007** [comment]
@urvashi-code1255  I have made the necessary changes and also updated the PR. Kindly check if it is alright.
![andorxor(1)](https://user-images.githubusercontent.com/56298861/111018714-7728af00-83e0-11eb-88b8-e5ac88b4c329.PNG)

**Comment by vasanthgk02** [comment]
I am very much interested in this project. So pls assign this to me💪
