### ISSUE TITLE
A Simple Ballon Firing Game 

### ISSUE THREAD

**Issue by Amisha-here** [Vishal-raj-1/Awesome-JavaScript-Projects#313]
I would like to add a simple balloon firing game in which we have to fire the balloon and jump for obstacles. Score will be counted.
Adding a Image for the same.

<img width="959" alt="Annotation 2021-03-10 221408" src="https://user-images.githubusercontent.com/66164747/110665343-497c1400-81ee-11eb-8615-3703e2c25fc0.png">

I would like @urvashi-code1255 @Vishal-raj-1 to please assign me this project.
I am a GSSOC'21 participant and want to contribute to this project.

**Comment by urvashi-code1255** [comment]
@Amisha-here Sure go for it :)
