### ISSUE TITLE
project cards are not showing up due to missing comma in code [gssoc'21]

### ISSUE THREAD

**Issue by ishita-sehgal** [Vishal-raj-1/Awesome-JavaScript-Projects#314]
project cards are not showing up due to missing comma at correct place in code. Kindly assign this issue to me as a participant of gssoc 2021.

![Screenshot (649)](https://user-images.githubusercontent.com/78426468/110671640-c7431e00-81f4-11eb-9332-217b8a768b68.png)

**Comment by urvashi-code1255** [comment]
@ishita-sehgal Sorry to say and thanks for help but I have solved this issue!

**Comment by ishita-sehgal** [comment]
Okay :)
