### ISSUE TITLE
Contacts Search

### ISSUE THREAD

**Issue by TidbitsJS** [Vishal-raj-1/Awesome-JavaScript-Projects#315]
## Search Contacts
Creating an application to demonstrate searching.

## Event
Part of GSSOC'21

## Demo
![demo](https://s4.gifyu.com/images/cinnamon-20210309-2.gif)

**Comment by TidbitsJS** [comment]
@urvashi-code1255 assign this to me :)

**Comment by urvashi-code1255** [comment]
@TidbitsJS Sure go for it :)
