### ISSUE TITLE
Navbar Toggler not working

### ISSUE THREAD

**Issue by nikhil-Vaibhav** [Vishal-raj-1/Awesome-JavaScript-Projects#316]
## Describe the bug
I have found that when the window is resized the navigation menu gets hidden under a toggler which is not working when clicked.

## To Reproduce
1. 
2. 
3. 
4. 

## Expected behavior
When the toggler is clicked the navigation menu should open perfectly

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Windows
 - Browser: Chrome

## Additional context

#318

**Comment by vanshikapandey** [comment]
Sir I would like to take this issue and work on it as GSSOC'21 participant. Please assign it to me.

**Comment by urvashi-code1255** [comment]
@vanshikapandey Sure !!

**Comment by nikhil-Vaibhav** [comment]
Hey @urvashi-code1255  Please check the linked pull request which can close this issue as I have fixed this and tested on my system. Only few code lines have been finally changed but during testing many changes were tested. At the end final PR has been made. Thank you

**Comment by 991rajat** [comment]
Hey @nikhil-Vaibhav Sorry for this, Actually UI has been updated due to which this Issue becomes obsolete.
There are of plenty of things can be added or modified in our project feel free to checkout.
