### ISSUE TITLE
A stone paper scissor game 

### ISSUE THREAD

**Issue by barsha119** [Vishal-raj-1/Awesome-JavaScript-Projects#319]
This is a simple game of stone paper scissor where 2 players can play. Stone wins over scissor , scissor wins over paper and paper wins over stone.
Please @urvashi-code1255 and @Vishal-raj-1 assign me for this project.
I am a gssoc'21 participant and wants to contribute for this project

**Comment by urvashi-code1255** [comment]
@barsha119 There is already a stone paper sccissors game present in the website. Let me know if you can modify it :)

**Comment by Vishal-raj-1** [comment]
@barsha119 Do you want to improve already exist game ? Or shall I close this issue

**Comment by barsha119** [comment]
Actually , I think it's fine. I don't want make any changes . We may close it.
