### ISSUE TITLE
bug in counter app

### ISSUE THREAD

**Issue by Nagsenwaghmare** [Vishal-raj-1/Awesome-JavaScript-Projects#32]
![Counter - Google Chrome 08-02-2021 23_00_45](https://user-images.githubusercontent.com/64947831/107258371-b79fb080-6a61-11eb-8d0c-63b456e21e3b.png)

**Comment by Nagsenwaghmare** [comment]
when a user leave a site for some time  and starts Increamenting from where he left ,counter is not increamenting value but attaching '1'  and it goes on.

**Comment by TidbitsJS** [comment]
@Vishal-raj-1, I have solved the issue. Created PR as well. Take a look!
