### ISSUE TITLE
Quiz app

### ISSUE THREAD

**Issue by sneha-nitdgp** [Vishal-raj-1/Awesome-JavaScript-Projects#321]
It'll be an interactive quiz app, where users will have to answer a set of questions, and they'll be assigned points for it. At the end, their total scores would be displayed along with animation effects.
@urvashi-code1255 @Vishal-raj-1 please assign me this project. I'd like to work on it.

**Comment by urvashi-code1255** [comment]
@sneha-nitdgp There is a quiz app already present in the project! Let me know if you can modify it :)

**Comment by Aarti002** [comment]
hello @urvashi-code1255 under gssoc'21 can i add some modification to quiz app ?
Thank you!

**Comment by 991rajat** [comment]
@Aarti002 Are you interested?
Let me know I will assign it to you.

**Comment by Aarti002** [comment]
yes , please assign me
thank you

**Comment by Aarti002** [comment]
@991rajat i have made a PR please review it and let me know if something is wrong
Thank you!
