### ISSUE TITLE
Improve Footer

### ISSUE THREAD

**Issue by sneha-nitdgp** [Vishal-raj-1/Awesome-JavaScript-Projects#322]
I'd like to improve the footer and add social media icons. 
@Vishal-raj-1 Can you please assign this to me?

**Comment by 0Faiz0** [comment]
I would like to work on this issue as a GSSOC'21 participant.

**Comment by urvashi-code1255** [comment]
@sneha-nitdgp Sure go for it :)

**Comment by sneha-nitdgp** [comment]
@urvashi-code1255 Can I get some information regarding contact number, email id etc of creator or any social links apart from Github, which I can add in Footer?

**Comment by sneha-nitdgp** [comment]
@urvashi-code1255 Can I get some information regarding contact number, email id etc of creator or any social links apart from Github, which I can add in Footer?

**Comment by ridsuteri** [comment]
since @sneha-nitdgp is not responding to a PR made to this issue so it's open now , @0Faiz0 you want to work on this ?

**Comment by harshgupta20** [comment]
Since no one responding to this issue, so we are closing it
