### ISSUE TITLE
Improve navbar and make it fixed navbar at top.

### ISSUE THREAD

**Issue by aashi2912** [Vishal-raj-1/Awesome-JavaScript-Projects#324]
**[GSSOC'21]** No its not a problem. I tried to enhancing the look and make it more easier to jump on one page to another through navbar.
Navbar should be fixed at top. Right now It is not. When scrolling it's not getting displayed to user and have to go up again to navigate through another section.

@urvashi-code1255 @Vishal-raj-1  I need to make that update allow me to do it and add the label of GSSOC'21.

**Comment by urvashi-code1255** [comment]
@aashi2912 Check the website. This issue is already solved.
