### ISSUE TITLE
I want to add Contact Us feature in navbar.

### ISSUE THREAD

**Issue by aashi2912** [Vishal-raj-1/Awesome-JavaScript-Projects#326]
**[GSSOC'21]** Just wanted to add contact us section in navbar with one contact us form. It would be great and important feature need to be add for users for any query related to website and they can contact us.

@Vishal-raj-1 @urvashi-code1255 If you like it or wanted to add this, please assign it to me :) and add the label.

**Comment by urvashi-code1255** [comment]
@aashi2912 go for it!

**Comment by aashi2912** [comment]
Thank you!

**Comment by aashi2912** [comment]
@urvashi-code1255  I created one PR regarding this please check it.

**Comment by aashi2912** [comment]
@urvashi-code1255 I created PR again with recent changes. check that out.
