### ISSUE TITLE
A Typing Game 

### ISSUE THREAD

**Issue by cryptofox17** [Vishal-raj-1/Awesome-JavaScript-Projects#329]
I would like to contribute as a GSSOC participant by adding a typing game to this project. Please assign me this issue

**Comment by urvashi-code1255** [comment]
Can you show me the demo @cryptofox17 ?

**Comment by cryptofox17** [comment]
@urvashi-code1255  sure. So here is what i have worked on so far : https://cryptofox17.github.io/typingGame/ 
I will be using API to generate random words and also improve the UI to make to look more interactive

**Comment by urvashi-code1255** [comment]
@cryptofox17 That's why I asked for the demo!

A very similar typing speed tester game is already present in the project!
