### ISSUE TITLE
MusicBox using JS

### ISSUE THREAD

**Issue by DevrajDC** [Vishal-raj-1/Awesome-JavaScript-Projects#330]
I would like to contribute as a GSSOC participant by adding a musicbox to this project which has various sounds which can be played by either clicking on the boxes or pressing the keys on keyboard. Please assign me this issue.

**Comment by urvashi-code1255** [comment]
@DevrajDC go for it

**Comment by Ankita297** [comment]
can i work on this @urvashi-code1255 @ridsuteri @Vishal-raj-1 @harshgupta20 ?

**Comment by harshgupta20** [comment]
@DevrajDC Any update?
Kindly reply within 2 days or else i have to assign this to @Ankita297 .

**Comment by Ankita297** [comment]
@harshgupta20 @Vishal-raj-1 @urvashi-code1255 @ridsuteri can i work on this ?

**Comment by Ankita297** [comment]
@991rajat can i work on this ?

**Comment by Ankita297** [comment]
@harshgupta20 @Vishal-raj-1 @urvashi-code1255 @ridsuteri can i work on this ?
