### ISSUE TITLE
Progress bar 

### ISSUE THREAD

**Issue by pritamkr1** [Vishal-raj-1/Awesome-JavaScript-Projects#331]
I want to add a progress bar to this project

**Comment by urvashi-code1255** [comment]
@pritamkr1 Sure go for it :)

**Comment by vismitap** [comment]
May I work on this issue as a part of GSSoC'21?

**Comment by pritamkr1** [comment]
## Related Issue
  - Info about Issue or bug

Closes: #[331]

### Describe the changes you've made
I have added a project progress bar to this  **Awesome-JavaScript-Projects**  It contains three files that are  progressbar.html, progressbar.css, and prgressbar.js. It shows progress in % of HTML, CSS, JavaScript, React, and WordPress.
Basically, it shows progress in HTML, CSS, JavaScript, WordPress, and React, when you press their button one by one. it is a basic level VanilaJS project for a newbie.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented on my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
![Screenshot (27)](https://user-images.githubusercontent.com/77887792/111018945-b3630c00-83ee-11eb-83fe-ed13a9562155.png)
