### ISSUE TITLE
progress bar, giveaway,  countdown to new year, digital clock with best UI, review application to this project

### ISSUE THREAD

**Issue by pritamkr1** [Vishal-raj-1/Awesome-JavaScript-Projects#332]
Hello Sir! I'm Pritam Kumar. I'm a front-end developer. 
and I'm want to work on some vanillaJS  projects 
1. Progress bar
2. giveaway
3. countdown to the new year
4. digital clock with best UI
5. testimonial app

**Comment by urvashi-code1255** [comment]
@pritamkr1 Welcome to the Project :)

We already have new year countdown and Digital clock!

So youcan add others :)

**Comment by urvashi-code1255** [comment]
Make seperate issues for all

**Comment by Vishal-raj-1** [comment]
@pritamkr1 Did you made seperate issues ? Try to work on single project at a time

**Comment by pritamkr1** [comment]
@Vishal-raj-1  I quite form these issues already and I make separate for these

**Comment by pritamkr1** [comment]
@Vishal-raj-1  and I already done my side please look into it

**Comment by Vishal-raj-1** [comment]
So should I close this issue ?

**Comment by pritamkr1** [comment]
Yes! @Vishal-raj-1  you can close #332 and please look into others and merge it.

**Comment by Vishal-raj-1** [comment]
Okay sure
