### ISSUE TITLE
[GSSOC 21']Twitter-Clone using React.js and deploy using firebase 

### ISSUE THREAD

**Issue by Prajwal-ctrl** [Vishal-raj-1/Awesome-JavaScript-Projects#334]
Hey I'm GSSOC 21 Participant I want to make a clone of twitter . @tinchods93  @kishankr7979 @chaitanyashimpi can I work on this on please let me known

**Comment by urvashi-code1255** [comment]
@Prajwal-ctrl We are  using pure vanilla js in this project, so please tell me know if you can do this with vanilla js

**Comment by Vishal-raj-1** [comment]
Sorry @Prajwal-ctrl This project is only for vanilla JS projects. I am building one more repo for react one !! You can add it in that repo later on
