### ISSUE TITLE
Memory Cards project

### ISSUE THREAD

**Issue by nagasaisriya** [Vishal-raj-1/Awesome-JavaScript-Projects#337]
Memory Cards is a Flash card app for learning, features-display, add and remove memory cards with questions and answers.
I would like @urvashi-code1255 @Vishal-raj-1 to please assign me this issue.
I am a GSSOC'21 participant and want to contribute to this project.

**Comment by urvashi-code1255** [comment]
@nagasaisriya Go for it :)

**Comment by nagasaisriya** [comment]
Thank you! @urvashi-code1255
