### ISSUE TITLE
Random User Generator

### ISSUE THREAD

**Issue by WebVishal** [Vishal-raj-1/Awesome-JavaScript-Projects#339]
It will use Random User API as input and will get the random User when the Click Button with some Details
I want to work on this project.
Please @ urvashi-code1255 and @ Vishal-raj-1 assign me for this project.
I am a GSSOC'21 participant and wants to contribute to this project

**Comment by urvashi-code1255** [comment]
@WebVishal Random User project is already present in the project, let me know if you can modify it :)

**Comment by WebVishal** [comment]
@urvashi-code1255  It's not yet listed on Project Section how I can try to modify ;)

**Comment by 991rajat** [comment]
@WebVishal Are you interested?
Let me know I will assign it to you.

**Comment by WebVishal** [comment]
@991rajat  Sure sir 🥰, How long have I been waiting to work on this project, please assign me

**Comment by 991rajat** [comment]
Hey @WebVishal Go Ahead develop a new project for this  don't modify existing project.
