### ISSUE TITLE
Navbar Improvement

### ISSUE THREAD

**Issue by Anshika-Srivastava** [Vishal-raj-1/Awesome-JavaScript-Projects#342]
I would like to improve the navbar by adding a **search widget** and providing a **dropdown for projects** so that they can be segregated under easy, medium and hard.
I am a GSSOC'21 participant. Please assign this to me!
Thank you.

**Comment by urvashi-code1255** [comment]
@Anshika-Srivastava Sure go for it

**Comment by 991rajat** [comment]
Hey @Anshika-Srivastava Sorry for this, Actually UI has been updated due to which this issue becomes obsolete.
There are of plenty of things can be added or modified in our project feel free to checkout.
