### ISSUE TITLE
Project: JS Clock

### ISSUE THREAD

**Issue by Anshika-Srivastava** [Vishal-raj-1/Awesome-JavaScript-Projects#343]
I would like to contribute my code for JS clock having light and dark themes.
I am a GSSOC'21 participant. Please assign me this.
Thank You!

**Comment by urvashi-code1255** [comment]
@Anshika-Srivastava Js clock is already present in the project! Let me know if you can add dark theme to them

**Comment by Aarti002** [comment]
hey @urvashi-code1255 under gssoc'21 can i work on this issue using dark theme?
Thank you!
