### ISSUE TITLE
Meme sharing web app

### ISSUE THREAD

**Issue by mohammedjameel24** [Vishal-raj-1/Awesome-JavaScript-Projects#344]
## memeUrl

share memese using image url
edit delete memes 
add caption

**Comment by mohammedjameel24** [comment]
@urvashi-code1255  please assign me this under gssoc

**Comment by amritakesh** [comment]
hey
I'm a GSSoC participant, may i please work on this issue?

**Comment by ridsuteri** [comment]
@mohammedjameel24 can you please elaborate the issue

**Comment by mohammedjameel24** [comment]
Basic CRUD app . Like a todo app
But insted of making a txt column

User can input a image url instead 
And upload a meme out out of it an additional to it a caption and name field of author

**Comment by ridsuteri** [comment]
Ok go ahead with it @mohammedjameel24

**Comment by mohammedjameel24** [comment]
Making a pr

**Comment by mohammedjameel24** [comment]
pull request #687
