### ISSUE TITLE
Device info webapp

### ISSUE THREAD

**Issue by mohammedjameel24** [Vishal-raj-1/Awesome-JavaScript-Projects#345]
shows users device configuration 
location based map data 
pure javascript implementation

@urvashi-code1255  pls assign me this under gssoc

**Comment by urvashi-code1255** [comment]
@mohammedjameel24 go for it :)

Make sure to follow the project guidelines and pattern

**Comment by mohammedjameel24** [comment]
Started working 
✅

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by mohammedjameel24** [comment]
@urvashi-code1255 

#370 generated pull request successfully

**Comment by harshgupta20** [comment]
Congrats your contribution has been merged.
