### ISSUE TITLE
[GSSOC ' 21] Tip calculator 

### ISSUE THREAD

**Issue by Mainakroy050** [Vishal-raj-1/Awesome-JavaScript-Projects#347]
### Hello !!
i am Mainak Roy ,a front end developer
I want to add a _Tip calculator_ (it is a simple `html,` `css` and  `js` project )

Please @urvashi-code1255  and @Vishal-raj-1  assign me for this project.
I am a GSSOC'21 participant and wants to contribute for this project

**Comment by urvashi-code1255** [comment]
@Mainakroy050 Can you please show me the demo here!

**Comment by Mainakroy050** [comment]
**_Here is the link_** @urvashi-code1255 
[https://mainakroy050.github.io/Tip-Calculator/](url)
i can add some changes if you want me to do !

**Comment by urvashi-code1255** [comment]
@Mainakroy050 Its looking good, just remove the extra space and the vertical scroll bar.

**Comment by 991rajat** [comment]
@Mainakroy050 Any updates? Let me know

**Comment by 991rajat** [comment]
Anyone Interested comment here.
