### ISSUE TITLE
[GSSOC 21'] Date and Time Widget

### ISSUE THREAD

**Issue by Vedant-Rahane** [Vishal-raj-1/Awesome-JavaScript-Projects#348]
I am Vedant Rahane, GSSOC'21 participant.  
I would like to add this simple Javascript based project it will show current date and live time. 

![clock widget](https://user-images.githubusercontent.com/71424483/110770079-e5556080-827e-11eb-80fd-dae76203381c.png)

Please @urvashi-code1255 and @Vishal-raj-1 assign me this.

**Comment by pritamkr1** [comment]
I'm Pritam Kumar (P) GSSOC'21.
please assign me to these projects

**Comment by urvashi-code1255** [comment]
@Vedant-Rahane Sure go for it :)

**Comment by urvashi-code1255** [comment]
@pritamkr1 Please look at other issues in the project! We follow FCFS
