### ISSUE TITLE
Rock Paper Scissors: Responsiveness

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#349]
Make Rock paper scissors game responsive for all screen sizes.

**Comment by nagasaisriya** [comment]
Hello, would like to work on this issue

**Comment by nagasaisriya** [comment]
Hello @urvashi-code1255 , I've made some modifications and the page in mobile view looks like this, can you please guide me further on how to adjust the middle col-6 grid?
Thank you!
![2021-03-11 (3)](https://user-images.githubusercontent.com/63009472/110796654-33c62780-829e-11eb-9726-b53d59eeba2a.png)

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by urvashi-code1255** [comment]
@nagasaisriya You can adjust it to less columns like col-4 or 3

**Comment by nagasaisriya** [comment]
Yeah, would try it. Thank you

**Comment by nagasaisriya** [comment]
@urvashi-code1255 made a pr unknowingly i corrected the typo too, do check it out

**Comment by Ankita297** [comment]
Can i work  on this ?

**Comment by Ankita297** [comment]
@urvashi-code1255 @Vishal-raj-1 ?

**Comment by Ankita297** [comment]
@ridsuteri ?

**Comment by ridsuteri** [comment]
@Ankita297  a PR is already open corrosponding to this issue,i don't think this issue is available now

**Comment by Ankita297** [comment]
Can i work on this @ridsuteri @urvashi-code1255 @Vishal-raj-1 ?

**Comment by ridsuteri** [comment]
@nagasaisriya i am assigning this issue to @Ankita297 ?
