### ISSUE TITLE
Add a preloader to the website

### ISSUE THREAD

**Issue by Ankita297** [Vishal-raj-1/Awesome-JavaScript-Projects#352]
## Is your feature request related to a problem? Please describe.
As the site takes some time to load so it will be better if we will add a preloader to the website.
## Describe the solution you'd like
I want to implement a preloader.

## Additional context
Add any other context about the feature request here.

**Comment by urvashi-code1255** [comment]
Sure go for it @Ankita297 :)

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/111108475-f7851680-857e-11eb-832e-074dae52d46e.mp4

**Comment by Ankita297** [comment]
is it okay ? or need same changes ? 
like  background color or any other idea ?
If it is okay then i will make the PR .

**Comment by Ankita297** [comment]
I can also change the design if you want ?

**Comment by Ankita297** [comment]
Uploading Document - Google Chrome 2021-03-15 22-29-36.mp4…

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/111193826-9aba4800-85e0-11eb-8c77-967079a5c9fa.mp4
