### ISSUE TITLE
[GSSOC 21'] Drag Image Slider

### ISSUE THREAD

**Issue by Vedant-Rahane** [Vishal-raj-1/Awesome-JavaScript-Projects#353]
I am Vedant Rahane, GSSOC'21 participant.
I would like to add this Javascript based project in which we can drag image left or right like Slider or Carousel

You can see Demo here  - > [Image-Slider](https://vedant-rahane-touch-drag-slider.netlify.app/)

Please @urvashi-code1255 and @Vishal-raj-1 assign me this.

**Comment by urvashi-code1255** [comment]
@Vedant-Rahane Click and drag project is already present in this project!

Modify it to this!

**Comment by Vedant-Rahane** [comment]
> @Vedant-Rahane Click and drag project is already present in this project!
> 
> Modify it to this!

@urvashi-code1255 means to change previous Click and drag project with mine correct ?

**Comment by 991rajat** [comment]
Yes sure @Vedant-Rahane Make it Good One
