### ISSUE TITLE
Nav bar collapse/dropdown doesnt seem to work.

### ISSUE THREAD

**Issue by pri1311** [Vishal-raj-1/Awesome-JavaScript-Projects#354]
## Describe the bug
The navigation toggle button for small screen sizes to display nav-links doesn't work/ doesn't serve its purpose of showing nav links, in short nothing happens when the toggle button is clicked.

## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome

**Comment by Vedant-Rahane** [comment]
I am Vedant Rahane, GSSOC'21 participant.
I would like to work on this issue.
Please @urvashi-code1255 and @Vishal-raj-1, can you assign it to me.

**Comment by DPrinceKumar** [comment]
Hello There! I am Prince Kumar, GSSOC 2021  participant  I would like to work on this issue.
Please @urvashi-code1255 and @Vishal-raj-1, can you assign it to me.

**Comment by 991rajat** [comment]
Already resolved!
