### ISSUE TITLE
Reviews : Not well Responsive

### ISSUE THREAD

**Issue by Vedant-Rahane** [Vishal-raj-1/Awesome-JavaScript-Projects#355]
Reviews project is not well responsive, content is getting compressed.

![reviews](https://user-images.githubusercontent.com/71424483/110820636-4a2bad80-82b5-11eb-9e3b-38ead22f85c2.png)

I can fix this.
@urvashi-code1255 @Vishal-raj-1 Can you please assign this to me as GSSOC'21 participant.

**Comment by urvashi-code1255** [comment]
@Vedant-Rahane Sure go for it!
