### ISSUE TITLE
Want to Add live Code Editor in this project

### ISSUE THREAD

**Issue by LalitMishra1504** [Vishal-raj-1/Awesome-JavaScript-Projects#358]
I am Gssoc'21 participant and want to add live code editor in this project in which developer can make changes in html css javascript and see it live on the side of the screen they don't have to go to browser for this

So please assign me this project @urvashi-code1255 @Vishal-raj-1

**Comment by urvashi-code1255** [comment]
@LalitMishra1504 Sure go for it :)
