### ISSUE TITLE
typo error in rock paper scissor game

### ISSUE THREAD

**Issue by Ankita297** [Vishal-raj-1/Awesome-JavaScript-Projects#359]
## Describe the bug
the spelling of scissors is sessior  .
## To Reproduce
1. Rock Paper  Sessior game .

## Expected behavior
It should be scissors
## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by Ankita297** [comment]
![Rock Paper Sessior - Google Chrome 12-03-2021 08_41_46](https://user-images.githubusercontent.com/67833077/110886850-4dec1e00-830f-11eb-84b2-84b756582b96.png)

**Comment by urvashi-code1255** [comment]
@Ankita297 Sure correct it!
