### ISSUE TITLE
Project Idea : Simple Avatar Maker

### ISSUE THREAD

**Issue by jhamadhav** [Vishal-raj-1/Awesome-JavaScript-Projects#360]
# Simple Avatar Maker
A simple and useful API, microservice app to generate minimalistic profile pic using the username initials.

Example : for username = John Doe 
![example pic (John Doe)](https://user-images.githubusercontent.com/37475140/110887065-a4595c80-830f-11eb-8a40-bc33c8ed6d09.png)

## Main goal
1. Using node.js make an API to fetch the avatar image when passed username name and other details as parameters
2. make the API a microservice, so that it can be used with other major projects
3. Host it on cloud 
4. make a website to showcase its demo
5. make API documentation, so others can use it easily

## Tech stack
- **Backend**: Node.js, express.js, canvas, etc
- **Frontend**: HTML, SCSS and JavaScript.
- **Cloud**: AWS or Heroku (as per need)

As a part of GSSoC'21, I would like to work on this project and contribute to this repo !

**Comment by urvashi-code1255** [comment]
@jhamadhav We are only using vanilla js. Let me know if you can do something with only vanilla js :)

**Comment by jhamadhav** [comment]
@urvashi-code1255 definitely as this - project will only need Javascript, I can make it using only vanilla Javascript too 👍

**Comment by jhamadhav** [comment]
Can I start making it ?
@urvashi-code1255

**Comment by jhamadhav** [comment]
@urvashi-code1255 and @Vishal-raj-1, please close this issue as the PR for it has been merged!

**Comment by 991rajat** [comment]
Sorry for the dealy @jhamadhav 
You can start working.
