### ISSUE TITLE
[GSSOC 21] Ludo game using javascript

### ISSUE THREAD

**Issue by vaishnavig20** [Vishal-raj-1/Awesome-JavaScript-Projects#362]
I would like to add a ludo game application to this project.
I am a GSSOC 21 participant. Please assign this project to me.

**Comment by urvashi-code1255** [comment]
@vaishnavig20 Sure go for it :)

**Comment by aditidewangan** [comment]
Please assign me for these project.  I also made a ludo game using javascript .

**Comment by 991rajat** [comment]
@vaishnavig20 Any Updates ?

**Comment by vaishnavig20** [comment]
I will send a pull request soon

**Comment by 991rajat** [comment]
No problem. Take your time.

**Comment by harshgupta20** [comment]
@vaishnavig20 Any update?, Kindly reply within 2 days or I have to close it.
