### ISSUE TITLE
Colorgame

### ISSUE THREAD

**Issue by satcasm** [Vishal-raj-1/Awesome-JavaScript-Projects#364]
Would like to add a color guessing game in the website as a GSSOC' 21 participant.
Thanks!

**Comment by urvashi-code1255** [comment]
Can you show me the preview here @satcasm ?

**Comment by satcasm** [comment]
![image](https://user-images.githubusercontent.com/56315878/111022468-f32ef100-83f8-11eb-86ac-1ea6814d6e55.png)
There will be two modes and the user just has to guess the color.
![image](https://user-images.githubusercontent.com/56315878/111022490-0cd03880-83f9-11eb-8565-92b882888f9d.png)
The user can also choose new colors anytime and upon guessing the color:
![image](https://user-images.githubusercontent.com/56315878/111022530-3d17d700-83f9-11eb-8a13-deae8a09cfdc.png)

**Comment by satcasm** [comment]
@urvashi-code1255 should I proceed with it?

**Comment by 991rajat** [comment]
Already Implemented @satcasm Let me know if you can modify or like to add new feat to this particular project.
