### ISSUE TITLE
New Project: Study Timer and  Scheduler

### ISSUE THREAD

**Issue by guruc-134** [Vishal-raj-1/Awesome-JavaScript-Projects#365]
I would like to add a Web Application which, would have the following features:
Allows you to set your session length and break length
Allows you to change your study session time, break length the effect is noticed dynamically in the session clock
It prevents you from resetting your break time  and  you can't extend your break periods
There is a single slot allocated for both session and break timers, once the session timer hits 00:00 the break timer automatically gets started and it replaces the session timer in place
The time is displayed along with the name of the current state of the session on the title bar of the webpage so that the user can keep track of his time even when he is on another page
Please assign me this issue under GSSoC 2021

**Comment by urvashi-code1255** [comment]
@guruc-134 go for it :)

**Comment by guruc-134** [comment]
@urvashi-code1255  Thank, you

**Comment by guruc-134** [comment]
@urvashi-code1255 
Current Progress:
-->completed the timer
-->added the planner
--> completed dropdown bar.

current website look:-  https://guruc-134.github.io/Pomodoro-Timer/

I'm also planning to add a local storage feature so that in that way the user will not loose his session progress if the tab is closed
Im also planning to add an alternate theme and alternate font option for the page

could you review the changes and let me know if there are any suggestions?

**Comment by guruc-134** [comment]
@urvashi-code1255  once check it out I have made a pull request once check it out
