### ISSUE TITLE
CAR AVOIDANCE GAME USING JAVASCRIPT

### ISSUE THREAD

**Issue by pushpakumari5117** [Vishal-raj-1/Awesome-JavaScript-Projects#368]
@Vishal-raj-1 @urvashi-code1255 
PLEASE GO THROUGH THIS PROJECT IDEA ONCE AND ASSIGN IT TO ME, IT WILL BE A GREAT CONTRIBUTION TO YOUR AWESOME JAVASCRIPT PROJECTS.

**DESCRIPTION**
I want to create a car avoidance game using HTML, CSS AND JAVASCRIPT. 

**FEATURES:**
1. CALCULATES SCORE.
2. HANDLE DIRECTION WITH ARROW KEYS.
3. IF CAR COLLIDES WITH ANOTHER CAR, GAME FINISHES.
4. FINAL SCORE IS DISPLAYED WHEN GAME IS OVER.
5. REPLAY BUTTON IS ALSO THERE
6. UI WILL BE SIMILAR TO RACING TRACKS

**Comment by urvashi-code1255** [comment]
@pushpakumari5117 I Loved this project idea :) go for it

**Comment by pushpakumari5117** [comment]
Thank you so much @urvashi-code1255
