### ISSUE TITLE
Scroll to Top Button

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#37]
## Is your feature request related to a problem? Please describe.

- Make a scroll to top button using html css and Javascript.

## Describe the solution you'd like

- Button should be visible at every part of the page(not only at the bottom).

**Comment by Nagsenwaghmare** [comment]
hey! @urvashi-code1255 I want to work on this issue  . should I make different structure or should I add it to main webpage  ?

**Comment by urvashi-code1255** [comment]
@Nagsenwaghmare Add it to the main webpage itself

**Comment by Nagsenwaghmare** [comment]
hey urvashi I am done with the scroll to top button , Have a look :blush:

https://user-images.githubusercontent.com/64947831/107626255-87375c80-6c83-11eb-9bc7-160ae6318ae0.mp4

**Comment by urvashi-code1255** [comment]
> hey urvashi I am done with the scroll to top button , Have a look 😊

Hey @Nagsenwaghmare Please change this top button to some up arrow and also change its color to some grey or black.
Also pull the recent changes from upstream before making a PR.

**Comment by Nagsenwaghmare** [comment]
I am unable to pull changes from upstream  urvashi  can you please help ?
when I added  remote it is showing" remote upstream already exists". but when I am fetching it ti is showing  "Repository not found".

**Comment by urvashi-code1255** [comment]
hey @Nagsenwaghmare Try to do "remote -v" 

if it gives 4 urls( 2 of origin and 2 of upstream) then you have added upstream.

But if it gives only 2 urls of origin then you have to do "git remote add upstream https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects.git"

**Comment by Nagsenwaghmare** [comment]
![Awesome JavaScript Project - Google Chrome 12-02-2021 14_59_16](https://user-images.githubusercontent.com/64947831/107751078-ec05bc00-6d42-11eb-9b59-1bab0ff10163.png)
@urvashi-code1255 does this looking good should I make PR?

**Comment by Nagsenwaghmare** [comment]
![Awesome JavaScript Project - Google Chrome 12-02-2021 14_59_16](https://user-images.githubusercontent.com/64947831/107751078-ec05bc00-6d42-11eb-9b59-1bab0ff10163.png)
@urvashi-code1255 does this looking good should I make PR?

**Comment by Vishal-raj-1** [comment]
@Nagsenwaghmare Increase the size of arrow not circle !! You can increase fontsize !!

**Comment by Nagsenwaghmare** [comment]
> @Nagsenwaghmare Increase the size of arrow not circle !! You can increase fontsize !!

done!
