### ISSUE TITLE
Particle JS project

### ISSUE THREAD

**Issue by Alik-Kumar-Ghosh** [Vishal-raj-1/Awesome-JavaScript-Projects#371]
## Particle.js JavaScript Project

I am Alik Kumar Ghosh. I would like to add a particle.js Javascript based project.
Could you please assign this to me as I am **GSSOC'21 participant**?

![image](https://user-images.githubusercontent.com/33929979/110936462-ef4a9280-8356-11eb-924f-fa829ee43c26.png)

**Comment by srija920** [comment]
hey, I am a GSSOC'21 participant , I would love to take up this task, can you please assign it to me?

**Comment by Alik-Kumar-Ghosh** [comment]
I have already completed, i am about to push my code now.

**Comment by Alik-Kumar-Ghosh** [comment]
[https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/373/#issue-591691906](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/373/#issue-591691906)

That's my PR link please have a look if possible.
