### ISSUE TITLE
Feature- download option in lets draw project

### ISSUE THREAD

**Issue by Engineervinay** [Vishal-raj-1/Awesome-JavaScript-Projects#372]
## Is your feature request related to a problem? Please describe.
hello, I want to add a download feature to the Let's Draw project so the user can download the painting he/she draws.
## Describe the solution you'd like
it will be really beneficial if the user can download the memory he created by drawing on the canvas, I can convert the canvas element into a jpeg image using javascript and then provide the functionality to download it.

## Additional context
I am one of the participants of **GSSOC'21** it would be really helpful if you can assign this issue to me so I can work on it.
@Vishal-raj-1 @urvashi-code1255

**Comment by urvashi-code1255** [comment]
@Engineervinay Sure go for it :)
