### ISSUE TITLE
[GSSOC'21 ]JAVASCRIPT BROWSER CODE EDITOR

### ISSUE THREAD

**Issue by aliya-rahmani** [Vishal-raj-1/Awesome-JavaScript-Projects#374]
## Is your feature request related to a problem? Please describe.
No, it's not a problem. I would like to work on a javascript browser code editor.
## Describe the solution you'd like
Here are a few ideas for additional features for our code editor:
- Use CSS for syntax highlighting
- Allow the user to switch between languages
- Add another screen next to our editor where the user can run the code

Please assign me this task under gssoc!

**Comment by urvashi-code1255** [comment]
@aliya-rahmani This issue has already made by some one

**Comment by aliya-rahmani** [comment]
@urvashi-code1255  but I didn't see any similar issues, please reference it. And if it isn't there, please add gssoc labels.

**Comment by aliya-rahmani** [comment]
@urvashi-code1255 should I change to another project idea?
