### ISSUE TITLE
Add github workflow for automatic build and deployment

### ISSUE THREAD

**Issue by ManasUniyal** [Vishal-raj-1/Awesome-JavaScript-Projects#376]
- Use github build action to test javascript, HTML and CSS files
- Use github build action for deployment

**Comment by urvashi-code1255** [comment]
@ManasUniyal Sure go for it :)

**Comment by ManasUniyal** [comment]
Hello, @urvashi-code1255 I am a mentor myself 😄.
Kindly assign it to someone else.

**Comment by jhasuraj01** [comment]
Hi, I am a GSSoC Participant, I would like to try solving this issue

**Comment by Vishal-raj-1** [comment]
@jhasuraj01 What do you want to try in this issue ?
