### ISSUE TITLE
Feature: Drumkit

### ISSUE THREAD

**Issue by anjali-tejasvi** [Vishal-raj-1/Awesome-JavaScript-Projects#377]
The present drum-kit doesn't have any option to change the theme. With a click, the theme will be changed. If you allow I can add this new feature to it. 
@urvashi-code1255 pls assign me this under gssoc.

**Comment by urvashi-code1255** [comment]
@anjali-tejasvi Sure go for it :)

**Comment by aditidewangan** [comment]
Please assign me this project. I am GSSOC'21 participant and wanted to work on this project.

**Comment by aditidewangan** [comment]
![image](https://user-images.githubusercontent.com/76042201/111151436-79903200-85b5-11eb-9c45-2565bd9da2a6.jpeg)
If this look good and it also make a sound by clicking.
