### ISSUE TITLE
[GSSOC'21] Lorem Ipsum Generator.

### ISSUE THREAD

**Issue by FireQueen-3010** [Vishal-raj-1/Awesome-JavaScript-Projects#378]
##New Project
A Lorem Ipsum words generator based on the number of words that the user needs.

## To Reproduce
1. Use Lorem Ipsum API's
2. DOM manipulation.
3. Use advanced CSS to properly style with modern UI themes.

## Feature: 
The user will be able to generate Lorem Ipsum words according to the input number he provides along with a great UI experience.

**Comment by FireQueen-3010** [comment]
Please assign this to me under Gssoc'21.

**Comment by urvashi-code1255** [comment]
@FireQueen-3010 We already have Text Generator which is an updation of lorem ipsum. So I think we don't need this.

Please feel free to close this issue
