### ISSUE TITLE
Gray Code to Binary Code Converter.

### ISSUE THREAD

**Issue by sejalxz** [Vishal-raj-1/Awesome-JavaScript-Projects#380]
Hey I would like to make a code converter from Gray Code to Binary Code

Please  assign me this issue under GSSOC' 21!

**Comment by urvashi-code1255** [comment]
@sejalxz Sure go for it :)

**Comment by khushi935** [comment]
Can I work on this?

**Comment by sejalxz** [comment]
@urvashi-code1255 @991rajat. Hey! It's been long time since I made a pr. Please look into it! Thank you :)
