### ISSUE TITLE
[GSSOC'21] RGB Color guessing game

### ISSUE THREAD

**Issue by AnanyaJajoo** [Vishal-raj-1/Awesome-JavaScript-Projects#382]
I would like to add a new game called RGB Color guessing game.

I am a GSSOC 21 participant. Can you please assign me this task under gssoc!
Please @urvashi-code1255 and @Vishal-raj-1 assign me this.

**Comment by urvashi-code1255** [comment]
@AnanyaJajoo This issue has already been made my some one .

**Comment by 991rajat** [comment]
Already implemented!
