### ISSUE TITLE
Recipie Finder

### ISSUE THREAD

**Issue by bitaashna** [Vishal-raj-1/Awesome-JavaScript-Projects#384]
Search and generate random meals and their recipie
#GSSOC'21
**Project Specifications:-**
Display UI with form to search and button to generate
Connect to API and get meals
Display meals in DOM with image and hover effect
By clicking on meal , details can be seen
Click on generate button and fetch & display a random meal

Hey @urvashi-code1255 ! I would like to work on it as a participant of **GSSOC'21**.Can you please assign this issue to me.

**Comment by urvashi-code1255** [comment]
@bitaashna go for it
