### ISSUE TITLE
Palindrome-Checker in Javascript

### ISSUE THREAD

**Issue by Aarti002** [Vishal-raj-1/Awesome-JavaScript-Projects#385]
This is a very basic project in javascript, for a complete beginner like me : )
Building a simple palindrome checker is great practice for working with strings and manipulating them with JavaScript. Plus, checking for palindromes can be a lot of fun!

i will be using some animation and will try to make my project  responsive and easy to deal.
Requirements: some javascript, html and css 

=>It can be apply for whole statement not only for a particular string
Thank you!

**Comment by Aarti002** [comment]
hey @urvashi-code1255 please assign this to me  will try my best .
Thank you!

**Comment by 991rajat** [comment]
@Aarti002 Pallindrome Checker Exist.
If you want to modify or add new feat to this particular project let me know I will assign it to you.

**Comment by Aarti002** [comment]
sure i would try to add some animation to it, please assign it to me

Thank you!

**Comment by harshgupta20** [comment]
@Aarti002 Any update?, Kindly reply within 2 days or I have close it.

**Comment by Aarti002** [comment]
i'm really very sorry i just forgot about this one , i will show by tonight itself @harshgupta20

**Comment by Aarti002** [comment]
can you add label tag in it @harshgupta20 ?

**Comment by Amit366** [comment]
@991rajat @ridsuteri can I work??

**Comment by ridsuteri** [comment]
sorry @Amit366 , it's resolved now :)
