### ISSUE TITLE
Image-gallery Project in Javascript 

### ISSUE THREAD

**Issue by Aarti002** [Vishal-raj-1/Awesome-JavaScript-Projects#386]
This is beginner kind project  and i would love to add some more features from my side.

Features : -
1. User can add on more photos to the gallery 
2. Each photo will have a category and photos with same category will be queue in same row
3. On clicking at particular pic user can view that pic in bigger font

---With some animations----

**Comment by Aarti002** [comment]
hey @urvashi-code1255 please assign this to me.
Thank you!

**Comment by 991rajat** [comment]
@Aarti002 It sounds good. Sure go ahead!

**Comment by 991rajat** [comment]
@Aarti002 are you still interested in this? If not I may transfer to another person.
> Let me know

**Comment by Aarti002** [comment]
ofcourse even i have started working on it already, i will show you by
tommorow. Please give me some time atleast!!

**Comment by 991rajat** [comment]
Take your time I was just confirming. Let me know if you need any help

**Comment by Aarti002** [comment]
hey @991rajat ,  i have made a PR on this issue, please review it and let me know if something is missing.
Thank you!
