### ISSUE TITLE
Want To Add Blog Website In this Project

### ISSUE THREAD

**Issue by Mrinal81** [Vishal-raj-1/Awesome-JavaScript-Projects#387]
I am a GSSOC'21 Participant. I would like to add the blog website where anyone can post his/her blogs.I want to work on this Issue.
Please assign me this issue..

**Comment by Vishal-raj-1** [comment]
@Mrinal81 You can go ahead with this issue. But make sure you use vanilla JS only

**Comment by Mrinal81** [comment]
@Vishal-raj-1  OK

**Comment by harshgupta20** [comment]
@Mrinal81 Any update?, Kindly reply within 2 days or I have to close it.

**Comment by Mrinal81** [comment]
@harshgupta20 yaa working on it. I will made PR  ASAP..

**Comment by Mrinal81** [comment]
@ridsuteri @harshgupta20 @991rajat   Kindly have a look on PR #1263 ......

Please add  Level Tag as well as GSSOC'21 Tag........

**Comment by 991rajat** [comment]
I'm closing this one. As it is merged.
