### ISSUE TITLE
Address Book Using Javascript

### ISSUE THREAD

**Issue by aliya-rahmani** [Vishal-raj-1/Awesome-JavaScript-Projects#388]
Hi ! I am Aliya Rahmani, a GSSOC'21 participant.
I would like to work on an Address Book management system developed by javascript, HTML, CSS. In this javascript project has a Name, Address, Telephone number, Email, website for the Address Book management system. If any information is incorrect, there are buttons to correct and delete. 

Please , kindly assign this task to me

**Comment by 991rajat** [comment]
@aliya-rahmani Sounds Good. Go Ahead

**Comment by aliya-rahmani** [comment]
@991rajat  thanks for assigning

**Comment by harshgupta20** [comment]
@aliya-rahmani Any update?, Kindly reply within 2 days or I have to close it.
