### ISSUE TITLE
Edit button in "Magic notes" app

### ISSUE THREAD

**Issue by frappelatte28** [Vishal-raj-1/Awesome-JavaScript-Projects#39]
## Describe the solution you'd like
There should be an edit button alongside the delete button
![jsProjcts](https://user-images.githubusercontent.com/64382399/107605909-8807c880-6c5a-11eb-9ccc-a41468080e5f.jpg)

**Comment by frappelatte28** [comment]
@Vishal-raj-1 can you assign me this issue?

**Comment by Vishal-raj-1** [comment]
@frappelatte28 Sure !! You can start.

**Comment by urvashi-code1255** [comment]
Hey @frappelatte28 Are you working on this? Any updates?

**Comment by frappelatte28** [comment]
Hey @urvashi-code1255! Actually, I am working on the other feature request that I have mentioned earlier. And I am facing some issues in that I tried my hands and did my research but that issue is not resolving. I am attaching the screenshot of the error that is showing up, let me know if you can help me with it :)
![Awesome_js_project_issue](https://user-images.githubusercontent.com/64382399/108174134-14b3fa00-7125-11eb-9e5f-d672141042f7.png)

**Comment by Vishal-raj-1** [comment]
click on source where you will see the error at line number 27 of init.js . check [this](https://stackoverflow.com/questions/10291693/cannot-read-property-getcontext-of-null-using-canvas)

**Comment by frappelatte28** [comment]
yeah I did check the source you mentioned but I dont understand what is happening and why it is happening

**Comment by Vishal-raj-1** [comment]
@frappelatte28 did you make edit features in this note app ?

**Comment by frappelatte28** [comment]
No, I didn't, if somebody else wants to work on this issue please assign them.

**Comment by khushi935** [comment]
Can I work on this?

**Comment by Vishal-raj-1** [comment]
@khushi935 sure !!

**Comment by khushi935** [comment]
https://user-images.githubusercontent.com/62712155/109026624-f2524b80-76e5-11eb-9884-cdd39f7c1cdd.mp4

Have a look at this.
