### ISSUE TITLE
[GSSOC'21] Design note app like  keep

### ISSUE THREAD

**Issue by Goheljay** [Vishal-raj-1/Awesome-JavaScript-Projects#392]
Hello, I participate in gssoc 2021.
@urvashi-code1255  and @Vishal-raj-1 I can redesign the note app. look like google keep. So can you assign me?

**Comment by syedmdsaifihassan** [comment]
@urvashi-code1255 @Vishal-raj-1 I would like to work on this issue, please let me know if it is not assigned to anyone.

**Comment by Vishal-raj-1** [comment]
@Goheljay Sure you can !! @syedmdsaifihassan Sorry You can check other issues for now

**Comment by Goheljay** [comment]
@Vishal-raj-1 thank buddy

**Comment by Goheljay** [comment]
@Vishal-raj-1 give me a Gssoc and level label to my issue

**Comment by harshgupta20** [comment]
@Goheljay Send the PR for this issue:)

**Comment by Goheljay** [comment]
In 2 to 3 days I will sending this PR.

**Comment by Goheljay** [comment]
Tomorrow i will submit my project
