### ISSUE TITLE
[GSSOC'21] Navgation bar not work in mobile view or reponsive view

### ISSUE THREAD

**Issue by Goheljay** [Vishal-raj-1/Awesome-JavaScript-Projects#393]
## Describe the bug
when I goto the mobile view than the navbar toggle not work. 
So can you assign me? I can work on this issue.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by 991rajat** [comment]
Fixed
