### ISSUE TITLE
Yoga App [gssoc'21]

### ISSUE THREAD

**Issue by sidmohanty11** [Vishal-raj-1/Awesome-JavaScript-Projects#397]
## Is your feature request related to a problem? Please describe.
No, I would like to add a yoga app . Basically, I made this according to the health issues today, its fairly simple and has a very soothing music added to it. It makes the whole pranayam yoga a breeze.
## Describe the solution you'd like
Made this yoga app and it can be further be made complex with addition of more musics and more yoga options

## Additional context
gssoc'21 participant

**Comment by harshgupta20** [comment]
@sidmohanty11 , The description you have given is not solving or adding any genuine feature. If its only about music than this issue will be closed with in 2 days, Kindly specify what more feature you can in it.

**Comment by sidmohanty11** [comment]
Sir I’ve solved the merge conflicts
