### ISSUE TITLE
New feature-- 2D breakout game

### ISSUE THREAD

**Issue by frappelatte28** [Vishal-raj-1/Awesome-JavaScript-Projects#40]
## Describe the solution you'd like
We can add a 2D breakout game, which is an intermediate javascript project

https://user-images.githubusercontent.com/64382399/107606823-59d7b800-6c5d-11eb-809d-d7cfba0d7374.mp4

**Comment by frappelatte28** [comment]
@Vishal-raj-1 let me know if you want to add this game to the projects section:-)

**Comment by Vishal-raj-1** [comment]
@frappelatte28 Yes !! You can start.

**Comment by harshgupta20** [comment]
@frappelatte28 Any update? Kindly reply within 2 days or I have to close this.

**Comment by frappelatte28** [comment]
You can close it, I am not working anymore on this issue.
