### ISSUE TITLE
Giphy Search Engine [Javascript]

### ISSUE THREAD

**Issue by ibhavikamalhotra** [Vishal-raj-1/Awesome-JavaScript-Projects#402]
## Is your feature request related to a problem? Please describe.
No
## Describe the solution you'd like
I want to add a JS Project which is a Giphy Search Engine, kindly assign me this issue so that I can do the mentioned.

@urvashi-code1255  ! I would like to work on this as I am a participant of GSSoC'21. This is going to be my first contribution to #GSSoC'21.

**Comment by 991rajat** [comment]
@ibhavikamalhotra You must ensure that it only be done in vanilla JS. Let me know how will you do it.
I will assign it to you.

**Comment by ibhavikamalhotra** [comment]
Yes it is in Vanilla JS, kindly assign me the issue so that i can work on the same.

**Comment by Vishal-raj-1** [comment]
@ibhavikamalhotra Go ahead

**Comment by ibhavikamalhotra** [comment]
@Vishal-raj-1 @991rajat I have created the PR #844  for this issue, do see to it and please merge this into the main branch, this is my first PR under GSSoC'21, let me know if there is anything missing. Also, add the required GSSoC'21 labels to this issue, so that my points get calculated.

**Comment by harshgupta20** [comment]
PR of this issue has been merged.
