### ISSUE TITLE
Play Beats [Javascript]

### ISSUE THREAD

**Issue by icoderharshit** [Vishal-raj-1/Awesome-JavaScript-Projects#403]
## Is your feature request related to a problem? Please describe.
No 
## Describe the solution you'd like
I want to add a JS Project which is a music player with an API, kindly assign me this issue so that I can do the mentioned.

@urvashi-code1255 ! I would like to work on this as I am a participant of GSSoC'21. This is going to be my first contribution to #GSSoC'21.

**Comment by 991rajat** [comment]
@icoderharshit Idea sounds very good. Currently we are accepting projects which are based on vanilla javascript.
Is your project will be able to build on this.
Do let me know if you want to work on it. I will assign it to you.

**Comment by icoderharshit** [comment]
Yes it is in Vanilla Javascript, kindly assign me the issue.

**Comment by Vishal-raj-1** [comment]
@icoderharshit GO Ahead

**Comment by icoderharshit** [comment]
@Vishal-raj-1 I have done as mentioned, and created the PR for the same with no conflicts with the base branch, please see to it and merge into the main branch. This is the first PR of me under GSSoC'21, I'm quite excited about it...Kindly see to it and close this issue by accepting the PR #832

**Comment by icoderharshit** [comment]
and please add the required gssoc labels @Vishal-raj-1 asap. I am already late for leaderboard !
