### ISSUE TITLE
Flappy Bird Game

### ISSUE THREAD

**Issue by deeptea22** [Vishal-raj-1/Awesome-JavaScript-Projects#404]
The game is a side-scroller where the player controls a bird, attempting to fly between columns of green pipes without hitting them. 
Hey @urvashi-code1255 ! I would like to work on it as a participant of GSSOC'21.Can you please assign this issue to me.

**Comment by amritakesh** [comment]
hey
I'm a GSSoC participant, may i please work on this issue?
i've made a flappy bird game with python before, so i guess i can work and contribute to this project as well

**Comment by 991rajat** [comment]
@deeptea22  Idea sounds good. Currently we are accepting projects which are based on vanilla javascript.
Is your project will be able to build on this.
Do let me know if you want to work on it. I will assign it to you.

**Comment by deeptea22** [comment]
@991rajat yes this is built on vanilla javascript. I will be able to do it. Please assign this to me. Thank you :)

**Comment by deeptea22** [comment]
hey @991rajat I have started working on the project and i can make a PR tomorrow so can you please add the gssoc and level labels. Thank you :)
