### ISSUE TITLE
Image Gallery

### ISSUE THREAD

**Issue by sneha-nitdgp** [Vishal-raj-1/Awesome-JavaScript-Projects#405]
I'd like to add a  pure JavaScript based gallery that helps you showcase your images with thumbnails and displays the image along with the description on hovering over it.
@urvashi-code1255 Can you please assign this to me?

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by 991rajat** [comment]
Everyone Someone is working on image gallery application, As soon as it merged with our current code base you can work on to add new feat or modify it. Feel free to look around, plenty of things can be added or modified within this project. Create an issue we will be happy to assign you.
I'm closing this issue for now
