### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by satcasm** [Vishal-raj-1/Awesome-JavaScript-Projects#409]
Would like to add a todo listing site as a part of GSSOC'21.
Look [here](https://tudo-list.netlify.app/) for preview.

**Comment by harshgupta20** [comment]
Hi @satcasm , the issue which you raised has already got resolved, but your project UI is bit better, i will recommed you to contribute on notes app which is already exist and update its UI.

This project already exist, same as notes app

**Comment by satcasm** [comment]
Okay
