### ISSUE TITLE
There is an issue in the footer section

### ISSUE THREAD

**Issue by kishankr7979** [Vishal-raj-1/Awesome-JavaScript-Projects#41]
## Describe the bug
The Date mentioned in the footer section is still showing 2020 instead of 2021.

## To Reproduce
1. Updation required
 
## Expected behaviour
Footer section should have the latest Year to be shown, i can do that and also afterwards there is no manual updation required for the same.

## Environment (please complete the following information):
 - OS: Mac
 - Browser: Chrome

**Comment by kishankr7979** [comment]
@Vishal-raj-1 Please assign me this issue

**Comment by urvashi-code1255** [comment]
Go for it @kishankr7979 :)
