### ISSUE TITLE
[GSSOC 21'] Add Birthday Reminder project

### ISSUE THREAD

**Issue by Vedant-Rahane** [Vishal-raj-1/Awesome-JavaScript-Projects#411]
I am Vedant Rahane, GSSOC'21 participant.
I would like to add this Javascript based project which contain people's data in array like name and birthday. It will show person if its birthdate matches current date and also automatically calculate age.

Something like this -

![birthday-reminder](https://user-images.githubusercontent.com/71424483/111030496-87647c80-8428-11eb-8609-c662841fb90a.png)

Please @urvashi-code1255 and @Vishal-raj-1 assign me this.

**Comment by 991rajat** [comment]
Hey @Vedant-Rahane are you still interested in this. I will assign it to you 
Do let me know

**Comment by Vedant-Rahane** [comment]
@991rajat Please assign me this, I am working on it.
