### ISSUE TITLE
New year crackers Firework with JS

### ISSUE THREAD

**Issue by kumarankm** [Vishal-raj-1/Awesome-JavaScript-Projects#415]
## Is your feature request related to a problem? Please describe.
No
## Describe the solution you'd like
What if we add new year wish with JS with cracking animation on background with sound?
I would like to work on it.

## Additional context
Assign me this issue under GSSOC' 21!

**Comment by kumarankm** [comment]
Can you assign me this issue? @urvashi-code1255 @Vishal-raj-1

**Comment by kumarankm** [comment]
@urvashi-code1255 Kindly assign this issue to me :)

**Comment by kumarankm** [comment]
@991rajat  Is this additional feature is okay?

**Comment by 991rajat** [comment]
@kumarankm Idea Sounds awesome. Are still interested ?
> Let me know I will assign you.

**Comment by kumarankm** [comment]
> @kumarankm Idea Sounds awesome. Are still interested ?
> 
> > Let me know I will assign you.

Yes I'm @991rajat
