### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by syedmdsaifihassan** [Vishal-raj-1/Awesome-JavaScript-Projects#416]
I want to create a timeline project in javascript.

**Comment by 991rajat** [comment]
@syedmdsaifihassan How would you do it, Explain the feature more please.
Idea sounds great.

**Comment by syedmdsaifihassan** [comment]
List of important events arranged in the order in which they happened.

I want to create this timeline project in vertical order.
I use the timeline.js to render the responsive vertical timeline.

**Comment by Vishal-raj-1** [comment]
GO Ahead @syedmdsaifihassan

**Comment by syedmdsaifihassan** [comment]
Thanks buddy, I will start working on this and get back to you ASAP.
@Vishal-raj-1

**Comment by syedmdsaifihassan** [comment]
Hi, @991rajat @Vishal-raj-1
I have created the Dynamic Timeline in Vanilla js, please review my pull request.
