### ISSUE TITLE
Digital Clock : Responsiveness

### ISSUE THREAD

**Issue by Vedant-Rahane** [Vishal-raj-1/Awesome-JavaScript-Projects#418]
Digital clock project is not well responsive, the clock is getting out off window on small screen.

**Issue -**

![digitalClock](https://user-images.githubusercontent.com/71424483/111032624-27270800-8433-11eb-995f-2e28fe141086.png)

I can fix this.
@urvashi-code1255 @Vishal-raj-1 please assign this to me as GSSOC'21 participant.

**Comment by Goheljay** [comment]
I participated in gssoc 2021. 
I can fix this problem. @Vishal-raj-1  @urvashi-code1255 please assign me this issue.

**Comment by Ankit0225** [comment]
hey @urvashi-code1255 @Vishal-raj-1 I would love to work on this project

**Comment by samar08** [comment]
Hey @urvashi-code1255  @Vishal-raj-1  I am a GSSOC participant. I would like to add an alarm feature for the digital clock. Please assign me this issue. Thanks and regards A.M.Samara simha reddy.

**Comment by Ankit0225** [comment]
Hey @Vedant-Rahane I would like to work on this project Would you like to assign this project I am good at HTML,CSS, and JS

**Comment by 991rajat** [comment]
@Vedant-Rahane Are you still interested in this ? 
Do let me know

**Comment by Ankit0225** [comment]
@991rajat I am interested please assign me this project

**Comment by 991rajat** [comment]
Hey @Ankit0225 Just let you know Some one is working on the bug of buttons don't work on that part from that fix it.

**Comment by Ankit0225** [comment]
@991rajat Ok

**Comment by Vedant-Rahane** [comment]
> @Vedant-Rahane Are you still interested in this ?
> Do let me know

@991rajat  Due to exams I was unable to respond, is this issue solved ?
I had worked on this issue should I make PR ?

**Comment by 991rajat** [comment]
@Vedant-Rahane Go Ahead Since Ankit hasn't made PR

**Comment by Vedant-Rahane** [comment]
@991rajat Can I know why you change label to `level0` ?
