### ISSUE TITLE
Bug in Project Section after recent PR

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#42]
## Describe the bug
Spacing between project section and about section is increased. Project section has bug.

## Expected behavior
- Reduce the spacing between About and project section. 
- Make all the cards as same as the cards in first row.

## Screenshots
![Capture1](https://user-images.githubusercontent.com/63122133/107612523-74fdf400-6c6c-11eb-9ab8-94c74b7e14a7.PNG)
![Capture2](https://user-images.githubusercontent.com/63122133/107612538-7a5b3e80-6c6c-11eb-8710-753fbb213929.PNG)

## Environment (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome

## Additional context
- Please check the whole website before sending a PR(including responsiveness)

**Comment by khushi935** [comment]
I correct this issue in my recent PR. Please have a look.
https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/46

**Comment by urvashi-code1255** [comment]
> I correct this issue in my recent PR. Please have a look.
> #46

Thanks @khushi935 for removing the bug from Project section 😊

**Comment by khushi935** [comment]
I want to work on this. I will remove the extra space between about us and project section.

**Comment by khushi935** [comment]
![Screenshot (57)](https://user-images.githubusercontent.com/62712155/107663075-f8413900-6cb0-11eb-9dec-9d6d5dcf1fd9.png)
Does it look good?
