### ISSUE TITLE
Survey App with Js

### ISSUE THREAD

**Issue by Tanu-priya-Roy** [Vishal-raj-1/Awesome-JavaScript-Projects#423]
I would like to contribute to GSSOC'21 by making this project. Please assign me this Project.

**Comment by Tanu-priya-Roy** [comment]
Thank u for assigning me this project.

**Comment by micksharma** [comment]
Hi I want to work on this.

**Comment by harshgupta20** [comment]
Hi @Tanu-priya-Roy, these projects have been already made, you can improve that project or if you have something specific with it then please describe in details, what will be the features of that project.

**Comment by Tanu-priya-Roy** [comment]
Ok, will do that Sir.

**Comment by Vishal-raj-1** [comment]
I am assigning this issue to you. You can go ahead @Tanu-priya-Roy

**Comment by Tanu-priya-Roy** [comment]
Thanks a lot.

**Comment by harshgupta20** [comment]
@Tanu-priya-Roy Any update?, Kindly reply within 2 days or I have to close it.

**Comment by Tanu-priya-Roy** [comment]
Yes, I am working on it.

**Comment by harshgupta20** [comment]
@Tanu-priya-Roy update??
