### ISSUE TITLE
Random quote generator

### ISSUE THREAD

**Issue by gupta31** [Vishal-raj-1/Awesome-JavaScript-Projects#424]
It will generate quotes randomly and post that quote in social media like twitter etc.

**Comment by gupta31** [comment]
I want to work on this under GSSOC21.Please assign to me

**Comment by harshgupta20** [comment]
Hi @gupta31  You can go ahead with your creation.☺☺

**Comment by gupta31** [comment]
Thanks @harshgupta20 😊

**Comment by harshgupta20** [comment]
Hi @gupta31 , We have found that this issue is already solved, Kindly raise the issue which is not present in the project and if you want to add some features then you can raise the issue on that dynamic random quote generator.

Happy Contributing.
