### ISSUE TITLE
Spock Rock Game

### ISSUE THREAD

**Issue by gupta31** [Vishal-raj-1/Awesome-JavaScript-Projects#425]

**Comment by gupta31** [comment]
I want to work on this under GSSOC21.Please assign to me

**Comment by 991rajat** [comment]
Hey @gupta31 Idea sounds awesome 
Few things to say currently there is project rock paper scissor what I would say is to contribute to that project and create a switch button in the game for difficulty mode which will change the mode of game
- Easy will remain Same Rock Paper Scissor
- Hard will be your Idea 

Any different kind of suggestions are welcome.
Let me know if you want to do it. I will assign it to you

**Comment by Vishal-raj-1** [comment]
@gupta31 Let me know are you interested ?

**Comment by gupta31** [comment]
Yes I am interested .For harder level I will include Spock and lizard apart from rock,paper and scissor.
This is inspired from Big bang theory TV series.
Soon I will create PR .Please assign to me under gssoc 2021.

**Comment by Vishal-raj-1** [comment]
@gupta31 Sure !!

**Comment by harshgupta20** [comment]
@gupta31 Any update?, Kindly reply within 2 days or I have to close it.
