### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [Vishal-raj-1/Awesome-JavaScript-Projects#427]
Hi! I would like to update contributing.md and and all the mentioned below with all the steps so that even a beginner in open source can contribute
Add the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on it as a part of GSSOC'21

**Comment by Vishal-raj-1** [comment]
@khareyash05 This would be great.

**Comment by khareyash05** [comment]
@Vishal-raj-1 could you pls also add a level label to the the same

**Comment by khareyash05** [comment]
@Vishal-raj-1 Created a PR Have a look!
