### ISSUE TITLE
[GSSoC '21] Creating Tetris game

### ISSUE THREAD

**Issue by amrzaki2000** [Vishal-raj-1/Awesome-JavaScript-Projects#428]
Hello,
I'd like to create Tetris game using javascript as part of my GSSoC contribution.
Thanks

**Comment by amrzaki2000** [comment]
@urvashi-code1255 @Vishal-raj-1

**Comment by micksharma** [comment]
Hi I want to work on this.

**Comment by amrzaki2000** [comment]
@urvashi-code1255 @Vishal-raj-1 
Can you assign this to me, please ?

**Comment by amrzaki2000** [comment]
@ridsuteri Can you assign this to me , please ?

**Comment by harshgupta20** [comment]
@amrzaki2000 Any update?, Kindly reply within 2 days or I have to close it.
