### ISSUE TITLE
Creating Word cloud using js and jquery

### ISSUE THREAD

**Issue by gupta31** [Vishal-raj-1/Awesome-JavaScript-Projects#430]
I want to work on this issue. Please assign to me

**Comment by 991rajat** [comment]
@gupta31 Explain a little more I don't get it. Since we are currently accepting project based on pure vanilla.
will you be able to do it in vanilla JS?
Do let me know!

**Comment by Vishal-raj-1** [comment]
@gupta31 If you can implement everything in vanilla JS. Then I will assign it to you

**Comment by gupta31** [comment]
This includes jQuery also apart from JavaScript.

**Comment by Vishal-raj-1** [comment]
@gupta31 Then leave this project for now !!
