### ISSUE TITLE
New Project :  Minion Translation App 

### ISSUE THREAD

**Issue by signifershrey** [Vishal-raj-1/Awesome-JavaScript-Projects#433]
I would like to add a Web Application to your project, It would have the following features:

It would translate the English conversation into minions native language.
It uses pure VanillaJs and takes the help of API to get the translated text.

Please assign me this issue under GSSoC 2021

**Comment by 991rajat** [comment]
@signifershrey  Sounds Exciting! Is there any API for this?

**Comment by signifershrey** [comment]
@991rajat  Check this one -  api.funtranslations.com

**Comment by 991rajat** [comment]
@signifershrey It's not working But Believe you will be able to do it.
Project sounds interesting too.
Shall I assign you this?

**Comment by signifershrey** [comment]
Yes, assign me!

**Comment by 991rajat** [comment]
@signifershrey Sorry for this there was some confusion Someone developed this project I will merge it today by itself what you could do is add new feature to it or a new language will assign it to. Is it Okay?
I let you know as soon as possible

**Comment by signifershrey** [comment]
Okay!

**Comment by 991rajat** [comment]
Hey @signifershrey Sorry for the Delay Minion App has been added.
Feel free to ping me the Idea you would Like to work. I'll be Happy to assign you.
And change the title also.

**Comment by harshgupta20** [comment]
@signifershrey Any update?, Kindly reply within 2 days or I have to close it.

**Comment by harshgupta20** [comment]
@signifershrey Kindly reply in 24 hours,

**Comment by 991rajat** [comment]
Minion Translation Already added. If @signifershrey Want to create a new type or modify existing project Create a new Issue.
We are closing this one.
