### ISSUE TITLE
New Project: Budget app 

### ISSUE THREAD

**Issue by rray14** [Vishal-raj-1/Awesome-JavaScript-Projects#434]
Hi my name is Ardra, participant of GSSoC'21
I'll contribute by adding a new project in JS, which is the budget calculator, which will give the total budget from the user's input of incomes and expenses 
Please assign this issue to me
Thanks!!

**Comment by micksharma** [comment]
Hi I want to work in this issue.

**Comment by ShambhaviSharma0110** [comment]
Hey, I'm interested in this project could you please allow me to work on it?
