### ISSUE TITLE
Grocery list app

### ISSUE THREAD

**Issue by rray14** [Vishal-raj-1/Awesome-JavaScript-Projects#435]
My name is Ardra, participant of GSSoC'21
Using javascript, I'll be creating a grocery list app where users can input the items and it generates a list
Please assign this issue to me
Thanks!!

**Comment by Ankit0225** [comment]
Het I would like to work on this project

**Comment by aditidewangan** [comment]
Hey I am a GSSOC'21 participant I wanted to work o this project using javascript. I also made a similar project for my resume so it is easy for me please assign this project to me.

**Comment by lakshita15** [comment]
hi , i'm gssoc'21 participant
I want to work on this issue
Can you assign issue to me ?
i'll submit before deadline

**Comment by 991rajat** [comment]
Who ever is interested comment here! Assigning will be done in FCFS
Issue creator will get the priority

**Comment by rray14** [comment]
I am interested

**Comment by 991rajat** [comment]
Great Develop it.
