### ISSUE TITLE
Javascript Bill Splitter

### ISSUE THREAD

**Issue by malavikarajeshvikraman** [Vishal-raj-1/Awesome-JavaScript-Projects#436]
Hi ! I am Malavika R Vikraman, a GSSOC'21 participant.
I will like to contribute to this project by adding a a simple bill splitter app. It will take the total amount, no of people and tip  and calculate the amount each person will pay.
Please , kindly assign this task to me

**Comment by micksharma** [comment]
Hi I want to work on this issue.

**Comment by 991rajat** [comment]
Who ever is interested comment here! Assigning will be done in FCFS
Issue creator will get the priority
@malavikarajeshvikraman

**Comment by malavikarajeshvikraman** [comment]
Hey Could you assign it to me

**Comment by 991rajat** [comment]
Great Develop it
