### ISSUE TITLE
JavaScript Tip Calculator

### ISSUE THREAD

**Issue by malavikarajeshvikraman** [Vishal-raj-1/Awesome-JavaScript-Projects#437]
Hi ! I am Malavika R Vikraman, a GSSOC'21 participant.
I will like to contribute to this project by adding a a simple tip calculating  app. It will take the total amount, and ask you haw the service was .Depending on which a tip will be calculated and displayed.
Please , kindly assign this task to me

**Comment by shahbazalam07** [comment]
I want to contribute to this please assign me

**Comment by divitagulati** [comment]
Hey, I am Divita Gulati, a participant of GSSOC'21.
I would like to contribute to this, please assign this task to me.

**Comment by 991rajat** [comment]
I'm Closing this issue as it's duplicate
Who ever is interested comment on #347
