### ISSUE TITLE
[GSSOC 21'] JavaScript Hangman game

### ISSUE THREAD

**Issue by AnanyaJajoo** [Vishal-raj-1/Awesome-JavaScript-Projects#448]
Hi! I am Ananya and I am a  GSSOC'21 participant.
I would like to contribute to this project by adding a JavaScript Hangman game.
Please assign this to me @urvashi-code1255

**Comment by haarsh01** [comment]
Hi! I am Harsh and a GSSOC 2021 participant of this time
I would like to contribute to this project. Please assign me this project and further steps.

**Comment by ridsuteri** [comment]
srry @AnanyaJajoo this project already exists

**Comment by 991rajat** [comment]
@AnanyaJajoo If you like to modify or add new feat to it let me know
I'll assign it to you.

**Comment by Vishal-raj-1** [comment]
@AnanyaJajoo or @haarsh01 if anybody of you want to improve this project then let me know other I will close this issue
