### ISSUE TITLE
[GSSOC'21] Password generator in vanilla javascript

### ISSUE THREAD

**Issue by apoorvachawda** [Vishal-raj-1/Awesome-JavaScript-Projects#450]
Hello, I am a GSSOC'21 participant and I want to create a vanilla js password generator. Here are the salient features of the project - 

1. User will be asked to enter the number of characters for the password.
2. A **strong** password will be generated using that number of characters.
3. The password will consist of special characters, uppercase and lowercase letters and numbers.

Please assign me this project under GSSOC'21 @urvashi-code1255

**Comment by ridsuteri** [comment]
srry @apoorvachawda this project similar project already exists

**Comment by apoorvachawda** [comment]
OK i will look for another project

**Comment by ridsuteri** [comment]
yes @apoorvachawda you can look for improvement in that project or add any other awesome project to the repo
