### ISSUE TITLE
Javacript Clock

### ISSUE THREAD

**Issue by poojitha2002** [Vishal-raj-1/Awesome-JavaScript-Projects#451]
Hello, I am GSSOC participant, I would like to design a real time clock by using Javascript. Please do assign it to me.
Thank you.

**Comment by mohammedjameel24** [comment]
i also want to work on this

**Comment by poojitha2002** [comment]
@mohammedjameel24 I have raised the issue as I am interested to work on this. So please assign this issue to me.

**Comment by mohammedjameel24** [comment]
Go ahead @poojitha2002  
If and only if u aren't able to deliver 
I want to work on this 
Happy

🔥

**Comment by poojitha2002** [comment]
Yeah, I will work on this:)

**Comment by poojitha2002** [comment]
Thanks for assigning.

**Comment by poojitha2002** [comment]
Please verify the project. 
https://github.com/poojitha2002/clock

**Comment by ridsuteri** [comment]
sorry @poojitha2002 similar kind of project already exists in the repo

**Comment by poojitha2002** [comment]
Oh😔
