### ISSUE TITLE
JavaScript Dragon Game 

### ISSUE THREAD

**Issue by aliya-rahmani** [Vishal-raj-1/Awesome-JavaScript-Projects#452]
Hi ! I am Aliya Rahmani, a GSSOC'21 participant.
I would like to contribute to this project by adding a simple dragon. It's a dragon game with audio effects and simple UI. Made with HTML, CSS, and Javascript.
Please , kindly assign this task to me.

**Comment by aliya-rahmani** [comment]
@ridsuteri  I' have made pull request #453  Please review it!

**Comment by 991rajat** [comment]
@aliya-rahmani Any Updates or Need any help

**Comment by aliya-rahmani** [comment]
@991rajat will work on it
