### ISSUE TITLE
auto assign, welcome bot

### ISSUE THREAD

**Issue by anjali1102** [Vishal-raj-1/Awesome-JavaScript-Projects#457]

**Comment by anjali1102** [comment]
@Vishal-raj-1  verify this issue
I want to take up this issue

**Comment by ridsuteri** [comment]
@anjali1102 can u provide a little description about the issue?

**Comment by anjali1102** [comment]
Any person can himself self assign the issue by "/assign" in the comment box 
![auto_assign_issues_banner](https://user-images.githubusercontent.com/56559378/111197952-13bb9e80-85e5-11eb-8ae7-7f3d34e55581.png) 




Whenever a person creates his/her  first PR/ Issue  it shows a welcome message by GitHub bot  and also
<img width="765" alt="71592779-d8dd6000-2b31-11ea-9337-28b9ab7cd59d" src="https://user-images.githubusercontent.com/56559378/111198185-4cf40e80-85e5-11eb-846b-09d633bb88a5.png">

**Comment by ridsuteri** [comment]
@anjali1102 Many people are coming with the projects which are already present in the repo and that auto assign bot will create a mess for us. You can work on welcome bot .

**Comment by harshgupta20** [comment]
@anjali1102 Any update?, Kindly reply within 2 days or I have to close it.
