### ISSUE TITLE
adding a button in Animated Counter js project

### ISSUE THREAD

**Issue by mahesh-11102** [Vishal-raj-1/Awesome-JavaScript-Projects#460]
**_Feature that I would like to add on Animated counter?_**

=>I would like to add a button on left side of the page, on clicking that button the counter should start.
### **_What's my solution?_**
=> I will add an onclick function to the button in that function I will add the counter function , So that on clicking the button the 
      counter should start.

@Vishal-raj-1 @urvashi-code1255  please assign me this issue , I would like to work on it

**Comment by mahesh-11102** [comment]
thank you @ridsuteri sir for assigning this issue

**Comment by ridsuteri** [comment]
@mahesh-11102 :)
