### ISSUE TITLE
Card image cap image not working

### ISSUE THREAD

**Issue by akshay1027** [Vishal-raj-1/Awesome-JavaScript-Projects#462]
## Describe the bug
The image of project Card image cap is not loading properly.

**Comment by ridsuteri** [comment]
@akshay1027 can u explain the issue with the relavent screenshot/gifs

**Comment by SiddhantChadha** [comment]
Hey There!
The GIF linked to Text to Voice generator project is not getting displayed on the card. Please assign this issue to me. I am a GSSOC '21 participant. Looking forward to contribute.
![image](https://user-images.githubusercontent.com/63542625/111176678-8faaec00-85cf-11eb-9450-24c1ca731d9d.png)

**Comment by ridsuteri** [comment]
sorry @SiddhantChadha but this issue is corrected in a PR recently...You can try for other improvements or can add other more awesome projects to repo :)

**Comment by 991rajat** [comment]
As mentioned Issue is resolved So I'm closing this issue for now.
Create a new one for improvements or features.
