### ISSUE TITLE
A custom video player.

### ISSUE THREAD

**Issue by FireQueen-3010** [Vishal-raj-1/Awesome-JavaScript-Projects#463]
I would like to make a custom video player using javascript.

**Comment by FireQueen-3010** [comment]
Please assign me this.

**Comment by FireQueen-3010** [comment]
May I know the level under which I am assigned this issue? (As it is an advanced project) @ridsuteri

**Comment by ridsuteri** [comment]
@FireQueen-3010 it will be counted under level 3

**Comment by FireQueen-3010** [comment]
Ok thanks!
