### ISSUE TITLE
 [GSSOC 21] Adding a CGPA calculator built using JavaScript.

### ISSUE THREAD

**Issue by Abhikr-git** [Vishal-raj-1/Awesome-JavaScript-Projects#465]
Hello, I'm Abhishek Kumar, a participant in GSSOC 21. I went through this project and found it really innovative.
I want to add a new custom CGPA calculator which is built using JavaScript. As most of us here are college students and we know that calculating and maintaining your CGPA is quite important. So, I want to build and add a CGPA calculator which would be really helpful. 
So, I request you to please assign me this as a part of my GSSOC project. I would really love to work on this project.

**Comment by Abhikr-git** [comment]
#489

**Comment by harshgupta20** [comment]
@Abhikr-git Any update?, Kindly reply within 2 days or I have to close it.

**Comment by Amit366** [comment]
@harshgupta20 can I work??

**Comment by Abhikr-git** [comment]
> @Abhikr-git Any update?, Kindly reply within 2 days or I have to close it.

Sir, my end-semester examinations are going on. Please give me a couple of days, I'll resolve the issue as soon as possible.

**Comment by harshgupta20** [comment]
@Abhikr-git Any update about the issue?

**Comment by Abhikr-git** [comment]
Sir, I have resolved the issue, will create the PR today
