### ISSUE TITLE
Extra space between about us para and projects

### ISSUE THREAD

**Issue by khushi935** [Vishal-raj-1/Awesome-JavaScript-Projects#47]
## Describe the bug
![bug](https://user-images.githubusercontent.com/62712155/107659301-03926580-6cad-11eb-9b9a-d839cfbbf013.png)

In the browser, there is extra space seen between about us and project details. Please have a look.

**Comment by urvashi-code1255** [comment]
@khushi935 This is the same issue as #42 . Please see its description. You can work on it if you are interested. Also, Please feel free to close this issue

**Comment by khushi935** [comment]
Okay, thanks.
