### ISSUE TITLE
A piano app 

### ISSUE THREAD

**Issue by barsha119** [Vishal-raj-1/Awesome-JavaScript-Projects#471]
Using javascript I want to make a piano app , Where the user would be able to play  7 piano note's sounds by pressing the keys of their computer's keyboard.

**Comment by haarsh01** [comment]
Hi, I am a Gssoc'21 participant, I want to contribute to this issue.
Please assign it to me.
Thank you

**Comment by 991rajat** [comment]
@barsha119 Great Idea Go for it.

**Comment by barsha119** [comment]
I have created the app but how do I add?

**Comment by 991rajat** [comment]
Add your files to respective folders like html in public and js in assets so onn and add project to script.js.
 Look at one of any project you will know.
Let me know if need any help.

**Comment by barsha119** [comment]
I have made a pull request...but it's showing some error
