### ISSUE TITLE
Http Cats App

### ISSUE THREAD

**Issue by SandeepKrSuman** [Vishal-raj-1/Awesome-JavaScript-Projects#473]
## Example

If the http code entered by the user is 300 then it will display this image :-

![300](https://user-images.githubusercontent.com/54541515/111144010-80ff0d80-85ac-11eb-8f61-dc95a94f7afc.jpg)
---
Please assign this project to me under GSSOC21.

**Comment by 991rajat** [comment]
@SandeepKrSuman Sound Awesome Go Ahead!
