### ISSUE TITLE
Creating a Whack a mole game for website

### ISSUE THREAD

**Issue by ayush461** [Vishal-raj-1/Awesome-JavaScript-Projects#475]
@harshgupta20  @ridsuteri @991rajat 
I am GSSOC21 participant.
I want to add whack a mole game using js 
please assign it to me.

**Comment by ridsuteri** [comment]
Sorry @ayush461 that game already exists in the repo, try improving that game Or try to add any other project
:)

**Comment by ayush461** [comment]
okk
