### ISSUE TITLE
Tic Tac Toe game 

### ISSUE THREAD

**Issue by guptaa98** [Vishal-raj-1/Awesome-JavaScript-Projects#477]
Hi 
As a Gssoc'21 participant, I would like to contribute to this issue.
Hey @urvashi-code1255  Kindly assign it to me.

**Comment by haarsh01** [comment]
Hi, I am a Gssoc'21 participant, I want to contribute to this issue.
Please assign it to me.
Thansk you

**Comment by amritakesh** [comment]
hey
I'm a GSSoC participant, may i please work on this issue?

**Comment by lakshita15** [comment]
hi , i'm gssoc'21 participant
I want to work on this issue
Can you assign issue to me ?
i'll submit before deadline

**Comment by harshgupta20** [comment]
Hi @guptaa98 , Kindly specify what is issue in it, and or what more you want to add in it.

**Comment by guptaa98** [comment]
Hi @harshgupta20 .
I'm planning to build a 2-player tic-tac toe game from scratch.

**Comment by guptaa98** [comment]
Hi @harshgupta20 .
Sorry my bad! 
I thought this game wasn't present so was planning to build it from scratch and add it here.

**Comment by 991rajat** [comment]
This Game Already exist would you like to add new feat or modify it
Like Add Difficulty mode 
Any suggestions are welcome.

**Comment by Vishal-raj-1** [comment]
IF anybody you are interested then Let me know otherwise I will close this duplicate issue

**Comment by harshgupta20** [comment]
Since we got reply from contributor side, we are closing it.
