### ISSUE TITLE
Dice Game

### ISSUE THREAD

**Issue by rohansharma4050** [Vishal-raj-1/Awesome-JavaScript-Projects#480]
I would like to develop a dice game using JavaScript in which every time the user refreshes the page different number pops up on die and accordingly the winner is declared.

I would like to work on this issue under GSSOC21 @ridsuteri can you please assign this issue to me

Sample
![Screenshot (695)](https://user-images.githubusercontent.com/69635604/111179421-12cd4180-85d2-11eb-8935-82147b344e84.png)

**Comment by ridsuteri** [comment]
srry @rohansharma4050 but this issue is already taken so try to improve the issue or add any other awesome js project
