### ISSUE TITLE
Bubble Particle Text project 

### ISSUE THREAD

**Issue by ishita-sehgal** [Vishal-raj-1/Awesome-JavaScript-Projects#481]
I would like to add a 'Bubble Particle Text' project using canvas and vanilla JS. In this project the text is in bubble form and bubbles move on moving mouse over it and then text re-gains its form automatically.

 @urvashi-code1255 , Can you please assign this issue to me as a gssoc'21 participant.

Sample:
![Screenshot (657)](https://user-images.githubusercontent.com/78426468/111192588-3d71c700-85df-11eb-89dc-95f92d401513.png)
![Screenshot (658)](https://user-images.githubusercontent.com/78426468/111192608-42cf1180-85df-11eb-9d27-436fa50c3032.png)

**Comment by 991rajat** [comment]
Hey @ishita-sehgal Looks Intersting Go Ahead!
