### ISSUE TITLE
digital clock button bug

### ISSUE THREAD

**Issue by Astrodevil** [Vishal-raj-1/Awesome-JavaScript-Projects#482]
In digital clock project the **start** button & **Stop** button hides when clicked on one button, this is not looking good . So i want to work on this.
I am Amitesh, a GSSoC 2021participant. Please assign this task to me.

![start](https://user-images.githubusercontent.com/73425223/111192561-33e85f00-85df-11eb-8f6e-4ba5af89aab6.png)

**Comment by amritakesh** [comment]
hey
I'm a GSSoC participant, may i please work on this issue?
I have some experience working with java script. I also took part in She Hacks 2021.

**Comment by 991rajat** [comment]
@Astrodevil Are still interested?

**Comment by Astrodevil** [comment]
yes @991rajat

**Comment by 991rajat** [comment]
@Astrodevil  Some is working on responsiveness part so don't change that, apart from that fix it
Thank You
