### ISSUE TITLE
Number Converter by using Vanilla JS 

### ISSUE THREAD

**Issue by amangupta37** [Vishal-raj-1/Awesome-JavaScript-Projects#483]
want to add a new web application for number conversion. assign this issue to me under GSSOC

**Comment by shahbazalam07** [comment]
I want to contribute to this issue

**Comment by 991rajat** [comment]
Someone is working on this.
I'm making this on hold As soon as Older is merged I will open this to add new feat or modify existing project

**Comment by 991rajat** [comment]
Everyone this type of project is underdevelopment. Once it's developed you can create new issue for modification or new features
I'm closing this issue for now
