### ISSUE TITLE
Snake game

### ISSUE THREAD

**Issue by apoorvachawda** [Vishal-raj-1/Awesome-JavaScript-Projects#484]
[GSSOC'21]  Hi there, I am Apoorva Chawda, a GSSOC participant.

I would like to make the classic snake game using vanilla JS. Please assign this project to me.

**Comment by amritakesh** [comment]
hey
I'm a GSSoC participant, may i please work on this issue?

**Comment by 991rajat** [comment]
@apoorvachawda Are you interested in working on this?
Let me know

**Comment by Vishal-raj-1** [comment]
@apoorvachawda You have one week for solve this issue otherwise I will assign this issue to @amritakesh

**Comment by Amit366** [comment]
@ridsuteri is this open??

**Comment by ridsuteri** [comment]
@Amit366 nopes :( another PR has already added this game
