### ISSUE TITLE
Meditation Web APP

### ISSUE THREAD

**Issue by apoorvachawda** [Vishal-raj-1/Awesome-JavaScript-Projects#485]
[GSSOC'21] Hi, I am Apoorva, a GSSOC'21 participant. 

I wanted to make a simple meditation app having different sounds, images and timer options.

Please assign this project to me under GSSOC'21.

**Comment by amritakesh** [comment]
hey
I'm a GSSoC participant, may i please work on this issue?
i've already made a meditation aap(its in my github repo for She Hacks 2021) So i think i can work on this project effectively

**Comment by 991rajat** [comment]
@apoorvachawda Currently someone is doing this type of project once it is merged,
Also same type of issue is being created before so I'm closing it.
Issue #438 
Comment on that
I'm closing this.
