### ISSUE TITLE
JavaScript drum Kit

### ISSUE THREAD

**Issue by mrunalvilas** [Vishal-raj-1/Awesome-JavaScript-Projects#487]
hey!
I am a GSSoC'21 participant and would wish to work on a  **JavaScript Drum Kit project** under _Awesome JavaScript Projects_. Please Assign this to me.

**Comment by amritakesh** [comment]
hey
I'm a GSSoC participant, may i please work on this issue?

**Comment by harshgupta20** [comment]
> hey!
> I am a GSSoC'21 participant and would wish to work on a **JavaScript Drum Kit project** under _Awesome JavaScript Projects_. Please Assign this to me.

Kindly specify what are the changes you gonna make in this.

**Comment by mrunalvilas** [comment]
@harshgupta20  I would wish to change the current UI and key set up from the current DrumKit.

**Comment by 991rajat** [comment]
Everyone this type of issue is underdevelopment. Once it's developed you can create new issue for modification or new features
I'm closing this issue for now
