### ISSUE TITLE
2D game - Space Invaders in javascript

### ISSUE THREAD

**Issue by aliya-rahmani** [Vishal-raj-1/Awesome-JavaScript-Projects#491]
Space Invaders game is an arcade video game that was first released in 1978. Here, a player basically controls a cannon. The basic concept is that the player is about to save the Earth from the invasion of evil space invaders. This system is a remake of the space invader phaser that is built on HTML. It is also built on JavaScript (i.e. require.js) for the desktops.  Besides, require.js breaks up the code into modules. 

Please assign me this task under GSSOC

**Comment by 991rajat** [comment]
@aliya-rahmani  Idea sounds great! Would it be feasible to do it in pure vanilla javascript?
let me know I'll assign it to you

**Comment by Vishal-raj-1** [comment]
@aliya-rahmani If you can do this in Vanilla JS then I will assign it to you otherwise close this issue

**Comment by aliya-rahmani** [comment]
@Vishal-raj-1  @991rajat  sure I can, please assign me the issue

**Comment by Vishal-raj-1** [comment]
@aliya-rahmani done

**Comment by harshgupta20** [comment]
@aliya-rahmani Any update? , kindly reply within  2 days else I have to close this issue.

**Comment by anushree71199** [comment]
Since there hasn't been any reply from 10 days on this issue, can I work on it? If I can please assign it to me under GSSOC'21 participation. I will make it using pure vanilla JavaScript. @ridsuteri @991rajat @harshgupta20
