### ISSUE TITLE
Adding Progress Bar in QuizApp Project

### ISSUE THREAD

**Issue by SiddhantChadha** [Vishal-raj-1/Awesome-JavaScript-Projects#493]
Hello! I am Siddhant Chadha and currently a participant of GSSOC'21. I was going through the QuizApp project and want to add a progress bar made using CSS and javascript which would indicate the current progress of the user. It would look something like this.
![image](https://user-images.githubusercontent.com/63542625/111308209-66966400-8680-11eb-96a5-70ea1f053de7.png)
Please assign this issue to me. Looking forward to contribute.
Thanks!

**Comment by ridsuteri** [comment]
yea @SiddhantChadha go ahead :)

**Comment by SiddhantChadha** [comment]
@ridsuteri @harshgupta20 please check my PR and let me know if it is merged or not.
