### ISSUE TITLE
Add speech recognition

### ISSUE THREAD

**Issue by Goheljay** [Vishal-raj-1/Awesome-JavaScript-Projects#494]
## Is your feature request related to a problem? Please describe.
Hello, I am Jay Gohel. a GSSOC'21 participant.
## Describe the solution you'd like
Can I add the speech recognition feature to this website? I have already made this feature. if you watch this feature then [click here](https://angry-wiles-f22f92.netlify.app/) So can you assign me this issue so I can contribute?
## Additional context
this feature made in HTML, CSS, JavaScript. not use any external API, and external library. 

So can you Assign me this issue?

**Comment by Goheljay** [comment]
@Vishal-raj-1 assign me this issue... Please....

**Comment by 991rajat** [comment]
@Goheljay Idea sounds awesome! Go Ahead

**Comment by Goheljay** [comment]
@991rajat thanks buddy

**Comment by Goheljay** [comment]
I will pr this feature in 1 to 2 days. Okey buddy.

**Comment by Goheljay** [comment]
@991rajat Hello Buddy, I submitted pull request. So Review it.
