### ISSUE TITLE
Flappy ball using javascript

### ISSUE THREAD

**Issue by manognyaa** [Vishal-raj-1/Awesome-JavaScript-Projects#498]
Inspired from `Flappy bird` game, I have created a small `flappy ball` game using  **HTML**, **CSS** and **Javascript**. 
Here am providing a glimpse of the game.

![image](https://user-images.githubusercontent.com/77045147/111267898-9c245880-8652-11eb-85c5-b06da21dfbf9.png)

![image](https://user-images.githubusercontent.com/77045147/111267989-b52d0980-8652-11eb-8a1f-6cdc73f84e0e.png)

@991rajat @urvashi-code1255 @Vishal-raj-1 @ridsuteri  please assign me this issue

**Comment by ridsuteri** [comment]
Sorry @manognyaa similar project already exists, try to improve that project or add any other awesome js project to the repo

**Comment by manognyaa** [comment]
Sure sir, thank you. @ridsuteri
