### ISSUE TITLE
ON/OFF bulb using javaScript

### ISSUE THREAD

**Issue by mahesh-11102** [Vishal-raj-1/Awesome-JavaScript-Projects#499]
I have created a `ON/OFF` bulb project using `JavaScript` . Here on **_clicking_** the **bulb image** or on the **switch** the bulb will be in on/off position .

Here I have shared a glimpse of the project
@ridsuteri  @Vishal-raj-1  @urvashi-code1255  @991rajat  please assign me the project

> ### `ON` position

![image](https://user-images.githubusercontent.com/77436328/111270321-b90e5b00-8655-11eb-8b6e-d081f57bc43b.png)

> ### `OFF` position

![image](https://user-images.githubusercontent.com/77436328/111270378-c9bed100-8655-11eb-8b5e-a65b1aa2bec8.png)

**Comment by mahesh-11102** [comment]
@ridsuteri  sir assigning me the issue :)

**Comment by ridsuteri** [comment]
:) go ahead with it
