### ISSUE TITLE
Pomodoro Timer

### ISSUE THREAD

**Issue by HelenEH0** [Vishal-raj-1/Awesome-JavaScript-Projects#502]
Hey @urvashi-code1255 @Vishal-raj-1,
I would like to add a Pomodoro timer as a project to the website.
I am a GSSOC'21 participant and I would like to contribute to the project. Please assign me this project.

**Comment by 991rajat** [comment]
@HelenEH0  Any Updates?

**Comment by HelenEH0** [comment]
I'm having semester exams now which was again postponed, can I work on this after that?

**Comment by 991rajat** [comment]
Sure No Problem

**Comment by Ankita297** [comment]
Can i work on this @ridsuteri  @991rajat @Vishal-raj-1 @urvashi-code1255 ?

**Comment by 991rajat** [comment]
@HelenEH0 Any Updates? If not respond in 2days will be transfered to @Ankita297

**Comment by Ankita297** [comment]
can i work on this @991rajat  ?

**Comment by ridsuteri** [comment]
yes you can go ahead with it @Ankita297 :)
