### ISSUE TITLE
PIN code search

### ISSUE THREAD

**Issue by TidbitsJS** [Vishal-raj-1/Awesome-JavaScript-Projects#505]
## PIN code search 

An application based on real postal data, when given a pin code, will provide the info of the location.

## Describe the solution you'd like
Use of fetch to get data from postalpincode API

## Event

GSSOC'21

## Demo
![](https://s4.gifyu.com/images/cinnamon-20210314-42872b42c4ec8f5b6.gif)

**Comment by TidbitsJS** [comment]
I will like to create PR for this. 
Do assign @urvashi-code1255 :)

**Comment by harshgupta20** [comment]
Hi @TidbitsJS , You an start working on this.☺
