### ISSUE TITLE
Expanding card[GSsoc 21)

### ISSUE THREAD

**Issue by Deeksha-Rawat** [Vishal-raj-1/Awesome-JavaScript-Projects#507]
![Expanding card](https://user-images.githubusercontent.com/50552823/111342806-ce5ca700-86a0-11eb-9e83-3def1ae83fed.gif)

**Comment by Deeksha-Rawat** [comment]
I want to add this project as my GSSOC 21 program.
please assign it to me.
Thanks

**Comment by harshgupta20** [comment]
Hi @Deeksha-Rawat  , This has been assigned to you. ☺☺

**Comment by Deeksha-Rawat** [comment]
I have made the PR . Please look into that.
Thank you
