### ISSUE TITLE
Improve the contact us form in the website

### ISSUE THREAD

**Issue by gayatri517** [Vishal-raj-1/Awesome-JavaScript-Projects#508]
I want to improve the contact page by -
1)Aligning the text heading to the centre and making it bigger in size.
2)I want to add a submit button with hover effect.

I want to work on this issue as a participant of GSSOC'21. Please assign it to me.

**Comment by Ankkkitt** [comment]
Hey, I would love to improve to Contact Us form and work on this issue. I will ad
1. Form validation in Name, email section
2. reduce the width and make everything to the center
3. Add some hover effects on Submit Button
4. Increase the size of the header section and give some styling

**Comment by jaypatel31** [comment]
Hey I want to add the back button in contact us form to improve the accessibility of the user can you assign it to me .

I am participant of GSSoc' 21

**Comment by harshgupta20** [comment]
Hello, @jaypatel31 , You are good to go with your idea.

**Comment by harshgupta20** [comment]
@jaypatel31 You have 2 days left for the PR or else i will assign it to other participant.

**Comment by jaypatel31** [comment]
@harshgupta20 I will complete it within two days

**Comment by gayatri517** [comment]
@harshgupta20 I am willing to do this within 2 days. Please assign it to me.

**Comment by jaypatel31** [comment]
@harshgupta20 I have opened a pull request #972 with the necessary changes please review it.
