### ISSUE TITLE
Dark Theme Toggler

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#51]
## Describe the solution you'd like
Make dark theme for this project using Javascript.

**Comment by anjali1102** [comment]
hey, I am taking up this issue!  assign me

**Comment by urvashi-code1255** [comment]
> hey, I am taking up this issue! assign me

Go for it @anjali1102

**Comment by Vishal-raj-1** [comment]
@anjali1102 any update ?

**Comment by anjali1102** [comment]
I will give PR by today. Can you add [ crossWoc, difficulty level ]  labels on this issue?

> @anjali1102 any update ?

**Comment by anjali1102** [comment]
Dark theme mode is to be only on main page only or it should be applicable on project pages too? @urvashi-code1255

**Comment by urvashi-code1255** [comment]
> Dark theme mode is to be only on main page only or it should be applicable on project pages too? @urvashi-code1255

Hi @anjali just make it for main website for now!
