### ISSUE TITLE
COVID-19 Live Stats Responsive Website

### ISSUE THREAD

**Issue by sejalxz** [Vishal-raj-1/Awesome-JavaScript-Projects#510]
I would like to contribute to this project by adding a COVID-19 Live Stats Responsive Website. It's a website which will show COVID-19 live statistics by country. Made with HTML, CSS, and JavaScript.

Please , kindly assign this task to me under GSSoC 21'

**Comment by haarsh01** [comment]
Hi, I am a Gssoc'21 participant, I want to contribute to this issue.
I would like to contribute to this project. Please assign it to me.
Thank you

**Comment by sejalxz** [comment]
@harshgupta20 could you please assign this to me?

**Comment by sejalxz** [comment]
@urvashi-code1255 could you please assign me this?

**Comment by 991rajat** [comment]
who ever interested comment! FCFS assigning will be done
Issue creator will get priority

**Comment by sejalxz** [comment]
@991rajat Sure! Please assign me thank you :)

**Comment by harshgupta20** [comment]
@sejalxz Any update? , kindly reply within  2 days else I have to close this issue.

**Comment by sejalxz** [comment]
@harshgupta20 Hi! Currently my semester exams and practical's are going on that's I am going slow. Hope you'll consider that. I'll get back to it as soon as my exams end.
Thanks!

**Comment by harshgupta20** [comment]
@sejalxz no problem, take your time buddy:)

**Comment by harshgupta20** [comment]
@sejalxz Any update about the issue?

**Comment by Ankita297** [comment]
Can i work on this @harshgupta20 @ridsuteri ?

**Comment by Ankita297** [comment]
@harshgupta20 @ridsuteri @urvashi-code1255 Can i work on this ?

**Comment by Ankita297** [comment]
@ridsuteri  ?

**Comment by ridsuteri** [comment]
@haarsh01 you want to work on this?

**Comment by ridsuteri** [comment]
> Can i work on this @harshgupta20 @ridsuteri ?

@Ankita297 since it's fcfs , so let's wait for 2-3 till @haarsh01 responds

**Comment by Ankita297** [comment]
@991rajat ?

**Comment by Ankita297** [comment]
@harshgupta20 ?

**Comment by harshgupta20** [comment]
hello @Ankita297, why you mentioned me here ?

**Comment by Ankita297** [comment]
Sir Can i work on this ?

**Comment by harshgupta20** [comment]
@Ankita297 Go ahead : )
