### ISSUE TITLE
Improvement in BMI Calculator (GSSoC'21)

### ISSUE THREAD

**Issue by yashikabhargava** [Vishal-raj-1/Awesome-JavaScript-Projects#511]
**Is your feature request related to a problem? Please describe.**
BMI Calculator

**Describe the solution you'd like**

1. Alignment of text to the center, change in size and font of the text.
2. Change in shape of button and addition of hover effect.
3. Change in the background color.
4. Alignment of BMI Calculator to the Center.

I want to work on this issue, can you please assign this issue to me as a part of Gssoc'21.

**Comment by yashikabhargava** [comment]
I want to work on this issue, can you please assign this issue to me as a part of Gssoc'21.

**Comment by shahbazalam07** [comment]
i want to work on this issue

**Comment by SilverGraph** [comment]
I would like to work on this issue as well.

**Comment by yashikabhargava** [comment]
@harshgupta20 Hello, I have created a new issue can u please review and assigned it to me issue no. #511

**Comment by yashikabhargava** [comment]
These are the improvements that I have done , also updated GIF in script.js.
![bmi changes](https://user-images.githubusercontent.com/76060661/115267470-d6ec4580-a156-11eb-891a-9bfab3dcefa7.PNG)

**Comment by yashikabhargava** [comment]
Is it okay? Can I make a PR?

**Comment by SilverGraph** [comment]
@yashikabhargava @urvashi-code1255 That looks like my design.
