### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Riya764** [Vishal-raj-1/Awesome-JavaScript-Projects#512]

**Comment by shahbazalam07** [comment]
I want to work on this issue

**Comment by Riya764** [comment]
@shahbazalam07 this issue is created by me

**Comment by Riya764** [comment]
I am working on it

**Comment by shahbazalam07** [comment]
ok fine

**Comment by Vishal-raj-1** [comment]
@Riya764 Raise the PR in one week  otherwise it will be assigned to @shahbazalam07

**Comment by harshgupta20** [comment]
@Riya764 Any update? , kindly reply within  2 days else I have to close this issue.
