### ISSUE TITLE
KeyEvent Code[GSsoc 21]

### ISSUE THREAD

**Issue by Deeksha-Rawat** [Vishal-raj-1/Awesome-JavaScript-Projects#514]
HI! I want to add my this project as a part of GGSOc.
Please assign this to me.
Thanku

![KeyEventCode](https://user-images.githubusercontent.com/50552823/111408850-e31a5880-86fb-11eb-97db-9bb7ad1a86f2.gif)

**Comment by 991rajat** [comment]
@Deeksha-Rawat This Project Already exist in our current codebase for Improvements or new features you can create a new issue .
I'm closing this for now.
