### ISSUE TITLE
Beautify Contact us form

### ISSUE THREAD

**Issue by fatma-sia27** [Vishal-raj-1/Awesome-JavaScript-Projects#515]
Hey, I had seen this  website and I thought it would be great if we beautify the "Contact us" page by using CSS . We can change background color, fonts and many more changes. 
SZo please assign me this issue so that I can beautify this page.
Thank you.

**Comment by harshgupta20** [comment]
Hi @fatma-sia27  its good make the contact page awesome, but could you plz tell us what are changes you going to make on that issue.

**Comment by fatma-sia27** [comment]
> Hi @fatma-sia27 its good make the contact page awesome, but could you plz tell us what are changes you going to make on that issue.

Yes we can make "Delhi tourism " logo at the top and can beutify its font,  we can change its background colour , also we can change its font color , we can change color of submit button on hover. Also we can make that name box smaller so that it looks clean . 
Thank you

**Comment by fatma-sia27** [comment]
> Hi @fatma-sia27 its good make the contact page awesome, but could you plz tell us what are changes you going to make on that issue.

Please allow me to work on this  project, it would love  to work  on this.

**Comment by fatma-sia27** [comment]
@harshgupta20  Thank you for assigning this issue to me and I want to ask should I send a pull request for this issue.??

**Comment by harshgupta20** [comment]
Yes @fatma-sia27 , if you have resolve the issue then surly you are allowed to send us PR. But it would be helpful for us if you can host it as well via github pages so that we can review it faster to merge it.😉😉

**Comment by fatma-sia27** [comment]
> Yes @fatma-sia27 , if you have resolve the issue then surly you are allowed to send us PR. But it would be helpful for us if you can host it as well via github pages so that we can review it faster to merge it.😉😉

Ook thank you

**Comment by harshgupta20** [comment]
@fatma-sia27 any update?
Kindly reply within 2 days or i have to close it.

**Comment by fatma-sia27** [comment]
> @fatma-sia27 any update?
> Kindly reply within 2 days or i have to close it.

Yes Yes Iam doing .

**Comment by harshgupta20** [comment]
Good @fatma-sia27 , Whats the update?

**Comment by fatma-sia27** [comment]
> Good @fatma-sia27 , Whats the update?

I had made changes in PR#784 please review it. 
Thank you

**Comment by harshgupta20** [comment]
Kindly link your PR with this issue.

**Comment by fatma-sia27** [comment]
https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/784

**Comment by fatma-sia27** [comment]
> #784

@harshgupta20
