### ISSUE TITLE
I would like to add "Happy Bouncing Balls :) " project 

### ISSUE THREAD

**Issue by Raj142** [Vishal-raj-1/Awesome-JavaScript-Projects#517]
please assign it me under GSSoC label . i am a participant of GSSoC'21.

**Comment by 991rajat** [comment]
@Raj142 Bouncing Ball Type project exist if you want to improve or modify
Or your idea is totally different please let me know

**Comment by Vishal-raj-1** [comment]
@Raj142 If you want to modify then reply here, otherwise you can close this issue
