### ISSUE TITLE
Add To-do list project

### ISSUE THREAD

**Issue by Raj142** [Vishal-raj-1/Awesome-JavaScript-Projects#518]
Please assign it me under GSSoC label. i am A participant of GSSoc'21

**Comment by PrathmeshSadake** [comment]
As a GSSoC participant please assign this task to me under gssoc label.

**Comment by Raj142** [comment]
i already generate a pull request you can check please assign it to me. @Vishal-raj-1

**Comment by divitagulati** [comment]
Hey, I am Divita Gulati, a participant of GSSOC'21.
I would like to contribute to this, please assign this task to me.

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant. could you please assign me this?

**Comment by pragati-kumar** [comment]
I'm a GSSOC'21 participant. I would like to contribute to this issue and can get started ASAP. Could you assign this to me?

**Comment by harshgupta20** [comment]
@991rajat Any Update ?
Kindly reply within 2 days or i have to assign it to someone else.

**Comment by Raj142** [comment]
@harshgupta20 i found same project on project list. However i will add to do list app with CRUD operation . Additionally user is allow to search tasks. 
I will add this project by tonight. @991rajat
