### ISSUE TITLE
Palindrome check

### ISSUE THREAD

**Issue by sejalshri** [Vishal-raj-1/Awesome-JavaScript-Projects#526]
I would like to add a Js project that will check if a given string or a number is palindrome or not.
Please assign me under GSSOC'21 . 
@ridsuteri @urvashi-code1255 @Vishal-raj-1

**Comment by Upasana1216** [comment]
I would like to work on this issue. Please assign this to me

**Comment by ridsuteri** [comment]
@sejalshri go ahead with it :)

**Comment by ridsuteri** [comment]
@Upasana1216 issues are alloted on first come first served basis ,kindly look for any other open issue
or wait for few days, if @sejalshri doesn't come up with a PR then it will be alloted to you
