### ISSUE TITLE
JavaScript Chess App

### ISSUE THREAD

**Issue by Subhampreet** [Vishal-raj-1/Awesome-JavaScript-Projects#527]
App Description :
- A Two-Player Chess Game Developed using JavaScript.

App Features:
- Show possible moves when a piece is selected
- Pieces can only make valid moves
- Pieces can only take opponent pieces
- Toggle turns after each move (white being the first

**Comment by 991rajat** [comment]
Hey @Subhampreet Idea sounds great. Currently we are accepting vanilla JS based projects. Will you be able to do it?
Let me know I'll assign it to you

**Comment by Subhampreet** [comment]
Yeah Sure!!! I will be developing the complete project in vanilla JavaScript.

**Comment by Subhampreet** [comment]
Kindly assign me the issue to work on it, as I am eager to contribute to this project!!!!

**Comment by Amit366** [comment]
@harshgupta20 can I work??

**Comment by Amit366** [comment]
@991rajat is this open??
