### ISSUE TITLE
Spotify finder

### ISSUE THREAD

**Issue by Ayushjain2205** [Vishal-raj-1/Awesome-JavaScript-Projects#529]
## Spotify finder 

Build a web app which helps users find tracks and playlists from spotify

I am a GSSoC participant please assign this task to me under gssoc21 label. gssoc'21

**Comment by Ayushjain2205** [comment]
@harshgupta20 Can you please assign this issue to me under GSSOC' 21

**Comment by Ayushjain2205** [comment]
@urvashi-code1255 Can you please assign this to me?

**Comment by 991rajat** [comment]
Hey @Ayushjain2205  Idea sounds awesome. Currently we are accepting vanilla JS based projects. Will you be able to do it?
Let me know I'll assign it to you

**Comment by Ayushjain2205** [comment]
@991rajat Yes I will be able to implement it with vanilla JS. Please assign it to me.
