### ISSUE TITLE
Replace absolute measurements with fluid measurements in digitalClock 

### ISSUE THREAD

**Issue by guptaa98** [Vishal-raj-1/Awesome-JavaScript-Projects#530]
I am a Gssoc'21 participant.
I want to change the styling of this project such that the position of the clock gets adjusted accordingly when the browser's size is changed. 
Hey @urvashi-code1255 @Vishal-raj-1  kindly assign this issue to me.

**Comment by 991rajat** [comment]
This type of issue is underdevelopment. Once it's developed you can create new issue for modification or new features
I'm closing this issue for now
