### ISSUE TITLE
Budget-App

### ISSUE THREAD

**Issue by sejalxz** [Vishal-raj-1/Awesome-JavaScript-Projects#537]
Hi, I am Sejal Dahake. I would like to contribute to this project by making a Budget App using JavaScript under GSSOC'21.

## Features
* The app shows, the balance, the income and the outcome
* It also has a dashboard where the user can add a new entry (an income or an expense)
* The user can toggle between the income list (that show only all income entries) and the expenses list (that shows only the outcome entries) and all list that shows all the entries.
* The user can edit or delete an entry.
* The app has a chart, so the user can easily compare the income and outcome.
* The user's income and expense entry list is stored in the local storage, so when he refreshes the page, or reboot his machine, he can always find  his data there.

Please assign this issue to me. Thank you :)

**Comment by 991rajat** [comment]
Hey @sejalxz Idea sounds great! Nice features.
Are you still interested ? Let me know I'll assign it to you

**Comment by sejalxz** [comment]
Yes, do assign me. :) Would love to work :)

**Comment by harshgupta20** [comment]
@sejalxz Any update? , kindly reply within  2 days else I have to close this issue.

**Comment by sejalxz** [comment]
@harshgupta20 Hi! Currently my semester exams and practical's are going on that's I am going slow. Hope you'll consider that. I'll get back to it as soon as my exams end.
Thanks!

**Comment by 991rajat** [comment]
@sejalxz  Okay No problem

**Comment by harshgupta20** [comment]
Since this project already exist with more features already. I have to close it, you can look upto another issue : )
