### ISSUE TITLE
Replace the card images of the project section with GIFs

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#54]
Replace the card images of the project section with GIFs like the animated counter project

**Comment by TidbitsJS** [comment]
Well, can I do this with GIF zoom on hover?

**Comment by Devenkapoor7303** [comment]
Can I work on this issue?

**Comment by Vishal-raj-1** [comment]
@TidbitsJS Yes !! @Devenkapoor7303 It is assigned to @TidbitsJS for Now !! You can check other issues for Now !!

**Comment by ChitvanRamani22** [comment]
@Vishal-raj-1 Can i work on this issue.

**Comment by Vishal-raj-1** [comment]
@TidbitsJS Any update or shall i assign this to @ChitvanRamani22 ?

**Comment by TidbitsJS** [comment]
> @TidbitsJS Any update or shall i assign this to @ChitvanRamani22 ?

So sorry for the delayed work ... I will create PR by today itself
