### ISSUE TITLE
Javascript Roadmap

### ISSUE THREAD

**Issue by Anupreetadas** [Vishal-raj-1/Awesome-JavaScript-Projects#540]
Hi,I am Anupreeta Das.I would like to contribute to this project by making a Roadmap using JavaScript under GSSOC'21.

## Features
- The app will show the roadmap which will help the user for easy navigation.
-  The user can give the source and destination address and can follow the map.
-  It also consists of the nearby important food stores,hospitals.

Please assign this issue to me.Thankyou

**Comment by 991rajat** [comment]
Hey @Anupreetadas  Idea sounds great and Nice features too. Currently we are accepting vanilla JS based projects. Will you be able to do it?
Let me know I'll assign it to you

**Comment by Vishal-raj-1** [comment]
@Anupreetadas You can raise PR now

**Comment by harshgupta20** [comment]
@Anupreetadas Any update? , kindly reply within  2 days else I have to close this issue.
