### ISSUE TITLE
Connect Four

### ISSUE THREAD

**Issue by TidbitsJS** [Vishal-raj-1/Awesome-JavaScript-Projects#546]
## Connect Four Game

Connect Four is a two-player connection board game, in which the players choose a color and then take turns dropping colored discs into a seven-column, six-row vertically suspended grid.

The pieces fall straight down, occupying the lowest available space within the column. The objective of the game is to be the first to form a horizontal, vertical, or diagonal line of four of one's own discs.

## Event

GSSOC'21

## Demo
![demo](https://s4.gifyu.com/images/cinnamon-20210319-2.gif)

**Comment by TidbitsJS** [comment]
Kindly assign this to me @urvashi-code1255 :)

**Comment by urvashi-code1255** [comment]
Go ahead @TidbitsJS :)
