### ISSUE TITLE
Currency Converter

### ISSUE THREAD

**Issue by AryaPatel1111** [Vishal-raj-1/Awesome-JavaScript-Projects#549]
I had like to add currency converter in js using vanilla js.

**Comment by AryaPatel1111** [comment]
Please can one of the mentor assign me this issue. I am waiting for the approval.

**Comment by AryaPatel1111** [comment]
@ridsuteri Can you please assign me this issue.

**Comment by ridsuteri** [comment]
@AryaPatel1111 similar project is added to the repo ,try to improve it or make another one different from existing one

**Comment by 991rajat** [comment]
Hey @AryaPatel1111 this Type of project already exist in our current codebase. If you want to modify or add new features create a new issue regarding that. I'm closing this for now
