### ISSUE TITLE
CSS JS files not linked properly [Device info]

### ISSUE THREAD

**Issue by mohammedjameel24** [Vishal-raj-1/Awesome-JavaScript-Projects#551]
## Describe the bug
The style and javascript files are not properly linked to **Device info** project 

## To Reproduce
Scroll down to device info project
Cluck to open project 

## Expected behavior
Loads the styles and javascript files

## Logs
No logs
Improperly linked js css files

## Environment (please complete the following information):
 Browser

## Additional context
Fix : just add the files from root directory of Awesome-javascript-projects

**Comment by mohammedjameel24** [comment]
Please assign me this issue

**Comment by 991rajat** [comment]
Hey @mohammedjameel24 Good catch I'm assigning it to you.

**Comment by mohammedjameel24** [comment]
pull req #687

**Comment by 991rajat** [comment]
Wrong PR

**Comment by harshgupta20** [comment]
This issue has been solved.
