### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by aastha621** [Vishal-raj-1/Awesome-JavaScript-Projects#553]
No its not a problem. I want to enhance the look of the navbar by adding on hover effects and making it more attractive and responsive.
Pls assign this issue to me!

**Comment by 991rajat** [comment]
Hey @aastha621 Since the UI of the application has been changed Please take a look and let me know what things you want to add or modify. I'll assign it to you

**Comment by aastha621** [comment]
I can 
1) Add shadow on hover effect on 'Awesome Javascript' title on navbar.
2) Animate the text 'The great collection of JavaScript projects,
just for you!!!' by giving it a typewriter effect.

Pls assign this to me!

**Comment by 991rajat** [comment]
@aastha621 Idea sounds cool. Please work on it.

**Comment by aastha621** [comment]
@991rajat I have made necessary changes and made a PR. Kindly review it! PR #765

**Comment by aastha621** [comment]
@991rajat pls review PR #765 , have made the necessary changes
