### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by Sloth-Panda** [Vishal-raj-1/Awesome-JavaScript-Projects#56]
## Is your feature request related to a problem? Please describe.
Yes
## Describe the solution you'd like
Would like to make a javascript music player game made using html, css, js

## Additional context
Add any other context about the feature request here.
It wiil be having a good background animation

**Comment by Sloth-Panda** [comment]
Would like  to work on this as part of crossWOC

**Comment by urvashi-code1255** [comment]
Go for it @Sloth-Panda

**Comment by Sloth-Panda** [comment]
@urvashi-code1255, this issue should contain crossWoc and a level tag right? for it to be counted for score?
