### ISSUE TITLE
Adding styles to the BMI Calculator page

### ISSUE THREAD

**Issue by SilverGraph** [Vishal-raj-1/Awesome-JavaScript-Projects#563]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried enhancing the look of the BMI Calculator page.
## Describe the solution you'd like
I would like to add styles to the "BMI Calculator" page.

## Additional context
@Vishal-raj-1  @urvashi-code1255 
Greetings! I am a participant in GSSOC'21 and I request you to assign me the task of adding styles to the "BMI Calculator" page.
This is how I have imagined the design:

- Before:
![before](https://user-images.githubusercontent.com/74287708/111805392-f9403880-88f6-11eb-9c2d-fde5e62a048e.png)

- After
![after](https://user-images.githubusercontent.com/74287708/111805437-078e5480-88f7-11eb-95d3-935de24e19e7.png)

**Comment by Ayushgup85** [comment]
is this issue still open?

**Comment by 991rajat** [comment]
@SilverGraph Wait for a while someone is working on it As soon as it frees I'll let you know.
By the way Cool UI. Do not worry we will merge that.
Ping me after 2 Days

**Comment by SilverGraph** [comment]
@991rajat Greetings! You asked me to remind you about this issue.

**Comment by Vishal-raj-1** [comment]
@SilverGraph You can work on that issue

**Comment by SilverGraph** [comment]
I have pushed the changes successfully.
