### ISSUE TITLE
URL Shortener not Working

### ISSUE THREAD

**Issue by AnandBIT** [Vishal-raj-1/Awesome-JavaScript-Projects#571]
## To Reproduce
1.  Type in any url in (https://vishal-raj-1.github.io/Awesome-JavaScript-Projects/public/url-shortner.html)
2.  You'll get the source code for that particular website instead of the shorted url.

## Expected behavior
A shorted url should be there as a result.

## Logs
In Network tab of Developer Tools, after submitting the url, I'm getting a 404 Error

## Environment (please complete the following information):
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by 991rajat** [comment]
Nice Catch @AnandBIT I'm Assgining it to you fix it

**Comment by AnandBIT** [comment]
@991rajat can I also change the UI, as it is not responsive now?

**Comment by AnandBIT** [comment]
@991rajat please review this and sorry for the mistake :)
