### ISSUE TITLE
Auto close tooltip in password generator

### ISSUE THREAD

**Issue by ishani02** [Vishal-raj-1/Awesome-JavaScript-Projects#574]
I would like to add the feature of auto closing to the tooltip in password generator. This feature will automatically hide the tooltip few seconds after the copy button is clicked.I would be implementing this using JavaScript .
@urvashi-code1255 Please assign this issue to me under GSSoC'21.

**Comment by 991rajat** [comment]
Hey @ishani02 Go Ahead
