### ISSUE TITLE
Navbar Brand and Home page link

### ISSUE THREAD

**Issue by alkatrivedi** [Vishal-raj-1/Awesome-JavaScript-Projects#575]
## Describe the bug
On clicking the 'Home' link in the navbar after clicking any other link like the 'Projects' link. The image on the home page is touching the navbar.

## To Reproduce
1. Open index.html and click on 'Projects' in the navbar
2. Now click on either 'Home' or 'Awesome Javascript' in the navbar
3. We can see an error that the home page image is touching the navbar which is not good-looking.

## Expected behavior
On clicking on either the 'Home' or 'Awesome Javascript' link =, the page should be the same as it is while opening the first-time index.html.

## Logs
![bug](https://user-images.githubusercontent.com/58396306/111833899-d3c42680-8918-11eb-9f96-262cc42e1b9d.PNG)

Error: Home page image is touching navbar.

![prev](https://user-images.githubusercontent.com/58396306/111833953-e8082380-8918-11eb-8a7c-decbefa5507d.PNG)

On clicking either the 'Home' or Awesome Javascript' link, it should be like the above image.

## Environment (please complete the following information):
 - OS: Windows
 - Browser: Chrome

## Additional context
I am a participant in GSSoC'21. I would like to work on this issue. May I work on it under GSSoC'21?

**Comment by alkatrivedi** [comment]
@urvashi-code1255 Kindly assign me this issue.

**Comment by 991rajat** [comment]
Everyone UI of the website has been updated. Feel free to find bug there and create a new issue for that will be happy to assign.
As this is old I'm closing this issue for now
