### ISSUE TITLE
Password strength checker 

### ISSUE THREAD

**Issue by pranabprohit** [Vishal-raj-1/Awesome-JavaScript-Projects#577]
To check whether the password are weak, strong or medium type.

**Comment by pranabprohit** [comment]
hello @urvashi-code1255 @Vishal-raj-1, I would like to work on this issue as a part of GSSOC. Can you please assign this issue to me.

**Comment by 991rajat** [comment]
Hey @pranabprohit Nice feat Please add it.

**Comment by Vedant-Rahane** [comment]
@991rajat Should I work on this.

**Comment by 991rajat** [comment]
@pranabprohit Please resopond if you are working on this. If not responded within 2 days it will be transferred to vedant

**Comment by pranabprohit** [comment]
> @pranabprohit Please resopond if you are working on this. If not responded within 2 days it will be transferred to vedant

I will make the PR today

**Comment by 991rajat** [comment]
@pranabprohit Okay

**Comment by pranabprohit** [comment]
@991rajat made a PR for this issue please review it. Can you change the label to level 2 I have added some other funcationality too.
