### ISSUE TITLE
Added DarkMode File

### ISSUE THREAD

**Issue by vasanthgk02** [Vishal-raj-1/Awesome-JavaScript-Projects#578]
## Is your feature request related to a problem? Please describe.
No its not a problem. I have created a new DarkMode File.
## Describe the solution you'd like
The DarkMode has a toggle button. When we click on it it changes from white mode to dark mode and vice versa

## Screenshot

White Mode
![DarkMode 1](https://user-images.githubusercontent.com/74846250/111857540-3ab50000-8958-11eb-89c8-cbd9b899a494.jpeg)

Dark Mode
![DarkMode 2](https://user-images.githubusercontent.com/74846250/111857552-4ef8fd00-8958-11eb-8425-cdd1acf3d09f.jpeg)

Issue number #560 .
I am a participant of GSSOC'21

**Comment by haarsh01** [comment]
Hey, I am a GGSOC'21 participant. Can I work on this issue, please? Please assign it to me.

**Comment by vasanthgk02** [comment]
Hii @urvashi-code1255 I have made this project. Please assign this issue to me so that I can improve my code!

**Comment by harshgupta20** [comment]
@vasanthgk02 Any update? , kindly reply within 2 days else I will assign it to other participants.
