### ISSUE TITLE
Adding a action game "Dragonfly"

### ISSUE THREAD

**Issue by Sweeti-Gupta** [Vishal-raj-1/Awesome-JavaScript-Projects#582]
I want to add an action game in this project in which there would be a dragon and an obstacle. The dragon has to defend itself from the obstacle which would be coming in front of him with an increasing speed. The dragon could defend itself by jumping. The game would have various features like it will have background sound while playing and a different sound while losing. It will show score as well.

Hey @Vishal-raj-1 , I want to contribute this as a part of GSSOC. Please assign this issue to me.

**Comment by 991rajat** [comment]
@Sweeti-Gupta Idea Sounds Great. Do work on it.

**Comment by priyanka001tech** [comment]
I would also like to contribute in this project..

**Comment by priyanka001tech** [comment]
By adding some new things

**Comment by priyanka001tech** [comment]
![Uploading Screenshot (271).png…]()
@991rajat I'm already started to working on this
can u please assign me

**Comment by priyanka001tech** [comment]
![Screenshot (271)](https://user-images.githubusercontent.com/70838173/113502813-2bcf6f80-954c-11eb-840c-8a2fea15df36.png)

**Comment by 991rajat** [comment]
@Sweeti-Gupta Anyupdates ?
Let me know if you are not able to work will assign to different contributor?

**Comment by 991rajat** [comment]
@priyanka001tech Let me know if you want to work on it?

**Comment by Sweeti-Gupta** [comment]
> @Sweeti-Gupta Anyupdates ?
> Let me know if you are not able to work will assign to different contributor?

Working on it. It's about to complete.

**Comment by 991rajat** [comment]
Okay No problem just checking. Take your time

**Comment by priyanka001tech** [comment]
@991rajat yes I want to do it.

**Comment by priyanka001tech** [comment]
![Screenshot (271)](https://user-images.githubusercontent.com/70838173/114214538-0d210c80-9982-11eb-97c2-34c054ef28e6.png)
only functions are needed to be done..

**Comment by priyanka001tech** [comment]
@Sweeti-Gupta she takes to much time..Can't we both work on this project together? So it will be done in less time.

**Comment by 991rajat** [comment]
I believe your game will be different from hers
So you should create a new issue attaching with this image I'll assign it to you.

**Comment by priyanka001tech** [comment]
@991rajat  issue #821 
please assign me

**Comment by Sweeti-Gupta** [comment]
@991rajat  When I have done all the changes in the cloned folder, I tried to run the html file in chrome but the audio is not playing in the chrome and all the things are working. I have added the audio files in the sound folder and also provided the path for them in .js file but it is not working. When I am trying it with the original folder in which I have worked, the audio is working.

Please check it and guide me.

![Screenshot (2759)_LI](https://user-images.githubusercontent.com/79096136/114277586-61db8a80-9a49-11eb-9d81-3a0d48b46130.jpg)
