### ISSUE TITLE
Github User Finder

### ISSUE THREAD

**Issue by bitaashna** [Vishal-raj-1/Awesome-JavaScript-Projects#583]
An app which will find the gtihub user and we can keep track of name,company,bio,pubic repos,etc
There will be a button directing to the github profile of user
I would like to work on the issue as a participant of **GSSOC'21**
@urvashi-code1255 Please assign me this issue.

**Comment by harshgupta20** [comment]
Hello @bitaashna , You can start work on it.😉

**Comment by bitaashna** [comment]
@urvashi-code1255 I have created a PR #615 .Please check it.
