### ISSUE TITLE
Responsive Navbar in mobile view 

### ISSUE THREAD

**Issue by abhijeet141** [Vishal-raj-1/Awesome-JavaScript-Projects#585]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to enhancing the look of Navbar.
## Describe the solution you'd like
I would like to make the navbar more responsive when it is in mobile view some animation in the collapsed section.

**Comment by abhijeet141** [comment]
Hey, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by 991rajat** [comment]
Currently UI has been changed please look into it feel free to find bugs and raise issue Will be happy to assign you all.
For now I'm closing this one
