### ISSUE TITLE
Background Slider

### ISSUE THREAD

**Issue by Deeksha-Rawat** [Vishal-raj-1/Awesome-JavaScript-Projects#589]
Hi I want to contribute this project to your repository as a part of GGSOC 21.
please assign this to me.
![BackgroundSlider](https://user-images.githubusercontent.com/50552823/111894605-204f5500-8a32-11eb-968c-291a507cec3b.gif)

**Comment by 991rajat** [comment]
@Deeksha-Rawat Nice Concept Go Ahead
