### ISSUE TITLE
Add Memory Game

### ISSUE THREAD

**Issue by shitesh2607** [Vishal-raj-1/Awesome-JavaScript-Projects#591]
Memory game is grid-based game in JavaScript, HTML and CSS. It's simple card game where you need to match pairs by turn over 2 cards at a same time.
Rules for Memory Game:
 1. You will start by flipping over one card
 2. The next card that you going to flip if matches, you get +1 to your score. then these card 
 will be disappear.
 3. If the next card you flip does not match, a pop up alert notifies you and card flip back.
 4. The game continues until  you match all the cards on the board
 I want add this game. I'm already done by half of game. 
So, please @Vishal-raj-1 & @urvashi-code1255 assigned it to me as a part of gssoc21.

**Comment by 991rajat** [comment]
@shitesh2607 Game sounds very  addictive Will be fun to play. Go Ahead develop it

**Comment by shitesh2607** [comment]
sure

**Comment by 991rajat** [comment]
Do not worry about these linked issues your's one will be accepted as per FCFS
Just confirming other people about similar idea.

**Comment by shitesh2607** [comment]
Thanks @991rajat.

**Comment by Amit366** [comment]
@ridsuteri can I work??

**Comment by 991rajat** [comment]
@shitesh2607 Any updates. If not will be transfered to someone else

**Comment by harshgupta20** [comment]
@Amit366 You can work on it :)
