### ISSUE TITLE
Adding Form_Wave_Animation Project

### ISSUE THREAD

**Issue by gaurav24072002** [Vishal-raj-1/Awesome-JavaScript-Projects#592]
I am contributing and would like to add a new Awesome JavaScript Project to this Repository That is very useful to create Login Forms. Have a look at it -
![Screenshot (115)](https://user-images.githubusercontent.com/77109758/111910600-080a2500-8a88-11eb-9f1e-246359311b22.png)

![Screenshot (117)](https://user-images.githubusercontent.com/77109758/111910582-f88adc00-8a87-11eb-98e1-e527abe6f099.png)

![Form_Wave_Animation](https://user-images.githubusercontent.com/77109758/111910624-25d78a00-8a88-11eb-87de-de79c128729d.gif)

**Comment by gaurav24072002** [comment]
@Vishal-raj-1 @urvashi-code1255 @  Any Update ??

**Comment by gaurav24072002** [comment]
Any Update @Vishal-raj-1 and @urvashi-code1255 ???

**Comment by gaurav24072002** [comment]
@Vishal-raj-1 and @urvashi-code1255  can you please reply on the updates??

**Comment by Vishal-raj-1** [comment]
done

**Comment by gaurav24072002** [comment]
Can you Please gave the label of GSSOC '21 and add label of Level also to it.
Thank you !!
