### ISSUE TITLE
to-do list with deletion and adding option

### ISSUE THREAD

**Issue by priyanka001tech** [Vishal-raj-1/Awesome-JavaScript-Projects#595]
To-do list with pictures and marking sign

any one can add the new thing as well as strike the thing when it is done

I want to do it as gssoc particiapnt

**Comment by 991rajat** [comment]
This type of issue is under development and someone has made PR too. Raise a issue for modifying or adding new features to it after it is merged. Will be happy to assign you.
I'm closing this for now.
