### ISSUE TITLE
Modify and make more attractive contact page

### ISSUE THREAD

**Issue by RoliGautam** [Vishal-raj-1/Awesome-JavaScript-Projects#598]
I would like to make the the contact page more attractive and beautiful by adding some font styles, background color and changing the style of the button.
Please assign for it . I am newbie and I would like to contribute in this projects.

**Comment by RoliGautam** [comment]
Thanks for assign me. I will make a pull request soon.

**Comment by RoliGautam** [comment]
Hello sir..
I just make a  pull request related to contact us page (issue #598).
Please review it, It is my first pull request and first time contribution
in open source project .

Link of pull request:
https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/633

Thank you!!

**Comment by 991rajat** [comment]
@RoliGautam We are sorry for not able to merge your request due to changes in the project. Feel free to look around there are plenty of things can be added, modified in this project Create a issue, We will be happy to assign you

I'm closing this issue for now
