### ISSUE TITLE
Beautify the navigation bar

### ISSUE THREAD

**Issue by RoliGautam** [Vishal-raj-1/Awesome-JavaScript-Projects#599]
I would like to give some hover and style in the menu bar .  Give some styling using css in the 'home', 'about', 'projects', 'contact us',  'Awesome JavaScript' headings. It would be look more attractive , If we give some color and hover effect.
Please assign me for this, I would really like to contribute in this section.

**Comment by RoliGautam** [comment]
Thanks  for assigning me. I will make a pull request soon.

**Comment by harshgupta20** [comment]
@RoliGautam Any update? , kindly reply within  2 days else I have to close this issue.
