### ISSUE TITLE
Redesign the contact us page.

### ISSUE THREAD

**Issue by manasivaraiya** [Vishal-raj-1/Awesome-JavaScript-Projects#606]
I am a GSSOC'21 participant. I would love to change the contact us page. Pls assign me this with a gssoc tag.

**Comment by Nishayadav-bit** [comment]
I would like to work on this issue . Please assign to me .
I'm a participant in GSSOC'21

**Comment by satwik16** [comment]
I would like to work on this issue .I am familiar to all the tech stack required to complete this project. I am a participant of GSSOC,21 .

**Comment by harshgupta20** [comment]
@manasivaraiya Any update? , kindly reply within  2 days else I have to close this issue.
