### ISSUE TITLE
No button to get back to home page from contact us page.

### ISSUE THREAD

**Issue by Aman-kumar001** [Vishal-raj-1/Awesome-JavaScript-Projects#607]
As there is no button to get back to the home page from the contact us page. Would be glad to contribute under gssoc21.

**Comment by Aman-kumar001** [comment]
Created a PR regarding this issue.

**Comment by raks924** [comment]
can i work on this issue?

**Comment by Aman-kumar001** [comment]
It has been resolved now. So i don't think it is required.
