### ISSUE TITLE
Dynamic quote generator

### ISSUE THREAD

**Issue by Archna29** [Vishal-raj-1/Awesome-JavaScript-Projects#61]
## Additional context
Add any other context about the feature request here.

**Comment by Archna29** [comment]
I would like to work on this issue

**Comment by Archna29** [comment]
this issue will count in crosswoc?

**Comment by urvashi-code1255** [comment]
> this issue will count in crosswoc?

Yes, But everytime specify the programs!! So that I can add the label

**Comment by Archna29** [comment]
What level this project will be of?

**Comment by harshgupta20** [comment]
This PR has been merged.
