### ISSUE TITLE
ChatBot

### ISSUE THREAD

**Issue by aastha0507** [Vishal-raj-1/Awesome-JavaScript-Projects#613]
Can I add a chat bot app?

**Comment by 991rajat** [comment]
Hi @aastha0507 Could you describe more how would you implement it. For now we are currently accepting only Vanilla JS based project. Will you be able to develop it in vanilla js?

**Comment by harshgupta20** [comment]
Hi @aastha0507 , since you have not replied for so long, we will be closing this issue in 2 days.

**Comment by ridsuteri** [comment]
sorry @aastha0507 i am closing this issue now :(
