### ISSUE TITLE
Lyrics Search 

### ISSUE THREAD

**Issue by TidbitsJS** [Vishal-raj-1/Awesome-JavaScript-Projects#614]
## Lyrics Search App

A project created using an API to fetch lyrics of any songs. Enter the respective details, & related searches with their lyrics will appear.

### Event
GSSOC'21

## Demo
![demo](https://s4.gifyu.com/images/cinnamon-20210321-8-1.gif)

**Comment by TidbitsJS** [comment]
Kindly assign this to me @harshgupta20 or @urvashi-code1255  :)

**Comment by TidbitsJS** [comment]
Can you assign this to me so that I can make PR for this @urvashi-code1255?

**Comment by 991rajat** [comment]
Great Idea @TidbitsJS Please go ahead!
