### ISSUE TITLE
Quote Generator App

### ISSUE THREAD

**Issue by bitaashna** [Vishal-raj-1/Awesome-JavaScript-Projects#617]
Using an API to build a random quote generator

**Comment by bitaashna** [comment]
I would like to work on this issue.Please assign it to me @urvashi-code1255 @harshgupta20 :)

**Comment by VishwaRaj-21** [comment]
I would like to work on it

**Comment by khushi-naik** [comment]
I would like to work on this issue for GSSOC 2021. I would implement this idea using an API wherein a user could choose a category and the quote would be generated accordingly.
