### ISSUE TITLE
Creation of url shortener

### ISSUE THREAD

**Issue by Sloth-Panda** [Vishal-raj-1/Awesome-JavaScript-Projects#62]
## Is your feature request related to a problem? Please describe.
Creation of url shortener
## Describe the solution you'd like
This js code will be able to make shorter the provided link
## Additional context
Add any other context about the feature request here.

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 do assign it to me and kindly add the tags too

**Comment by Vishal-raj-1** [comment]
@Sloth-Panda Sure !!

**Comment by abhinav5481** [comment]
Hi,
I would like to work on it. Could you please assign it to me?
