### ISSUE TITLE
Request for Editing Drum Kit Project-Add Click Event Functionality

### ISSUE THREAD

**Issue by anjujoseph555** [Vishal-raj-1/Awesome-JavaScript-Projects#621]
I am GSSOC 21 participant and would love to edit the drum kit project which is a very fun and interesting project. Currently the project offers only keypress. I would like to add a click functionality as well. Would really love to contribute and showcase my JS skills.
Dear mentors, please do assign me.

**Comment by Vishal-raj-1** [comment]
That would be great idea !!

**Comment by anjujoseph555** [comment]
@Vishal-raj-1 sir, please do review my pull request.
Thanks and regards.

**Comment by anjujoseph555** [comment]
hello @ridsuteri @Vishal-raj-1 @Alik-Kumar-Ghosh @urvashi-code1255 please review my pull request, it'll be my first PR under GSSOC'21
