### ISSUE TITLE
Update the Search Bar

### ISSUE THREAD

**Issue by Fab-Gaurav** [Vishal-raj-1/Awesome-JavaScript-Projects#624]
Hello @Vishal-raj-1 
As a participant of GSSoc'21 kindly assign me this issue.
## Have a look :-
Present 
![Before](https://user-images.githubusercontent.com/71934708/112126713-baf29400-8bea-11eb-8614-57abdf407309.PNG)

After update
![After](https://user-images.githubusercontent.com/71934708/112126846-da89bc80-8bea-11eb-92a8-bc9edda7a426.PNG)

## Environment (please complete the following information):
 - OS: Windows
 - Browser: Chrome

**Comment by Fab-Gaurav** [comment]
Assign this to me so that I can make PR.

**Comment by Vishal-raj-1** [comment]
sure !!

**Comment by Fab-Gaurav** [comment]
@Vishal-raj-1 
Please have a look on the PR https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/627

**Comment by 991rajat** [comment]
@Fab-Gaurav Since the UI has been updated this feature has become obsolete. We are sorry to inform you that.
Feel free to look around, there are plenty of things that can be added or modified within this project. Create an Issue we will be happy to assign you that.

**Comment by Fab-Gaurav** [comment]
@991rajat Please have a look on issue https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/issues/651
Should I work upon it.
