### ISSUE TITLE
Stop Watch only working buttons should be visible

### ISSUE THREAD

**Issue by EkjotKaur** [Vishal-raj-1/Awesome-JavaScript-Projects#628]
Reset Lap Reset Lap button are not needed when stop watch is not on.
Start button is not required during the running stopwatch.

Can I contribute on this issue?
Please assign me this issue. 
[GSSOC'21]

@Vishal-raj-1 @urvashi-code1255

**Comment by EkjotKaur** [comment]
@urvashi-code1255 @Vishal-raj-1 @991rajat please view this

**Comment by 991rajat** [comment]
Good catch. Feel free to change UI as well if you like.
