### ISSUE TITLE
Resposive Website

### ISSUE THREAD

**Issue by EkjotKaur** [Vishal-raj-1/Awesome-JavaScript-Projects#629]
Pages like Netflix, password generator, new year count down any many others are not responsive .
Can I make them responsive 
[GSSOC'21]

Please assign me this issue
@urvashi-code1255 @Vishal-raj-1

**Comment by agamjotsingh18** [comment]
I can take this issue and make it perfectly responsive?   Regards!

**Comment by EkjotKaur** [comment]
@urvashi-code1255 @Vishal-raj-1 @991rajat  please view this

**Comment by 991rajat** [comment]
Hey @EkjotKaur For Now You create a list of project which you feel like the code is breaking
As there are other people who maybe working on same project may cause conflict in future so I would suggest You create a list and I will tell you for now to work on certain projects and keep you updated as soon as other projects are free to work upon.

**Comment by EkjotKaur** [comment]
I want to responsiveness of the following projects:

- [ ] Netflix Clone
- [ ] Pinpad
- [ ] Calculator
- [ ] New year count down
- [ ] Image slide
- [ ] Local Storage
- [ ] Analog Clock
- [ ] Password Generator
- [ ] Pixel Game

**Comment by EkjotKaur** [comment]
@991rajat  Please assign me this issue and tell on which of these can I work right now.

**Comment by EkjotKaur** [comment]
@991rajat Please tell me in which of these I can work.

**Comment by Vishal-raj-1** [comment]
@EkjotKaur For now you can contribute to first four project. Do one thing raise separate PRs for every issue it will be easy for US to review and It will be help you to gain more points

**Comment by Vishal-raj-1** [comment]
@agamjotsingh18 You can work on next 2 project for now. !!

**Comment by EkjotKaur** [comment]
> @EkjotKaur For now you can contribute to first four project. Do one thing raise separate PRs for every issue it will be easy for US to review and It will be help you to gain more points

Okayy

**Comment by agamjotsingh18** [comment]
> @agamjotsingh18 You can work on next 2 project for now. !!

Okay

**Comment by Bhavya-Sehgal** [comment]
Can I make analog clock and password generator responsive
[GSSOC'21]

Please assign me this issue
@urvashi-code1255 @Vishal-raj-1 @991rajat  @harshgupta20 @ridsuteri

**Comment by ridsuteri** [comment]
@Bhavya-Sehgal yeah you can go ahead with them

**Comment by Bhavya-Sehgal** [comment]
> @Bhavya-Sehgal yeah you can go ahead with them

okayy :)

**Comment by agamjotsingh18** [comment]
#Image slide made responsive

![Screenshot (36)](https://user-images.githubusercontent.com/70067726/113898322-63a71300-97e9-11eb-9203-70e36be45fab.png)
![Screenshot (37)](https://user-images.githubusercontent.com/70067726/113898326-6570d680-97e9-11eb-9600-6cd87e613e0a.png)

**Comment by agamjotsingh18** [comment]
#881

**Comment by agamjotsingh18** [comment]
#854 made responsive local storage

**Comment by ridsuteri** [comment]
@agamjotsingh18 i am unable to find the local storage made responsive PR ,
please tag me/other mentors in the PR

**Comment by agamjotsingh18** [comment]
> @agamjotsingh18 i am unable to find the local storage made responsive PR ,
> please tag me/other mentors in the PR

Okay sir
