### ISSUE TITLE
Add Cross WOC Banner or Poster

### ISSUE THREAD

**Issue by Ayush7614** [Vishal-raj-1/Awesome-JavaScript-Projects#63]
## Is your feature request related to a problem? Please describe.
Add Cross WOC Banner or Poster

## Describe the solution you'd like
Add Cross WOC to  Banner or Poster

**Comment by Vishal-raj-1** [comment]
@Ayush7614 Go for it and Please add GSSOC banner as well.

**Comment by Ayush7614** [comment]
@Vishal-raj-1 you can also add crosswoc level because I can do it under crosswoc
