### ISSUE TITLE
Redesign the Contact Us page

### ISSUE THREAD

**Issue by avinashjha1320** [Vishal-raj-1/Awesome-JavaScript-Projects#632]
@synox @Alik-Kumar-Ghosh @michysantillan @tinchods93 @chaitanyashimpi 
Hey, I want to rebuild the contact us page with some animation and features. Can you please assign this task to me.

**Comment by nikhv** [comment]
Hey @synox @Alik-Kumar-Ghosh @michysantillan @tinchods93 @chaitanyashimpi
I am a GSSOC 2021 participant. I would like to work on the issue.
Could you please assign me this issue?

**Comment by 991rajat** [comment]
Everyone rightnow this issue is under development. Once it's developed you can create new issue for modification or new features
Feel free to look around, plenty of things can be added or modified within this project. Create an issue will be happy to assign you.
I'm closing this issue for now
