### ISSUE TITLE
search option is not working

### ISSUE THREAD

**Issue by mdatif796** [Vishal-raj-1/Awesome-JavaScript-Projects#634]
## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by 991rajat** [comment]
UI has been updated which makes this issue obsolete we are sorry to inform you that. Feel free to look around, plenty of things can be added or modified within this project. Create an issue will be happy to assign you.
I'm closing this issue for now
