### ISSUE TITLE
Memory Game 

### ISSUE THREAD

**Issue by Akansha-Bhandari** [Vishal-raj-1/Awesome-JavaScript-Projects#635]
Hii !!
I am a participant and i would like to **add a Memory game using javascript** in the recent project collection of "Awesome-Javascript Projects"  ...
Please assign this issue to me ....

**Comment by 991rajat** [comment]
Hey @Akansha-Bhandari Please can you elaborate more how will it work, As I feel there is similar type of project under development, so please clarify.
There is issue #591
Is it similar?

**Comment by Akansha-Bhandari** [comment]
yes its similar to the above mentioned issue ...
so i guess there is no need to re-create the game again ....

**Comment by 991rajat** [comment]
Once it's developed you can create new issue for modification or new features.
Feel free to look around, plenty of things can be added or modified within this project. Create an issue we will be happy to assign you.
I'm closing this issue for now
