### ISSUE TITLE
for updating the navbar brand.

### ISSUE THREAD

**Issue by mdatif796** [Vishal-raj-1/Awesome-JavaScript-Projects#636]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to enhancing the look of sidenav.
## Describe the solution you'd like
I have updated sidenav.html and added sidenav.css for changing current sidenav project into animated sidenav

## Additional context
Add any other context about the feature request here.

**Comment by 991rajat** [comment]
@mdatif796 Please refer any design or something?
How will it look after modifications

**Comment by Vishal-raj-1** [comment]
@mdatif796 You can raise the PR or show the design here itself

**Comment by harshgupta20** [comment]
@mdatif796 Whats the update,
Reply within 2 days on we have to close this issue.

**Comment by mdatif796** [comment]
I'm working on it.

**Comment by harshgupta20** [comment]
@mdatif796 It's been a month that you haven't sent the PR, you have to send the PR within a week.

**Comment by mdatif796** [comment]
I will send it soon.

**Comment by harshgupta20** [comment]
@mdatif796 What's the update? Since it will been 2 months for this issue, we can't give you more time on this, Kindly send PR within a week or I have to close the issue.

**Comment by harshgupta20** [comment]
@mdatif796 Any update?

**Comment by harshgupta20** [comment]
@mdatif796 no problem, you can just give updates about the project, so that we can keep a record of your issue.

**Comment by harshgupta20** [comment]
@mdatif796 Its been a long time you didn't sent the PR till now, Kindly respond within a week.
