### ISSUE TITLE
back to top button

### ISSUE THREAD

**Issue by oneknucklehead** [Vishal-raj-1/Awesome-JavaScript-Projects#639]
## Describe the bug
a "Go back to top" button should be added so that the users do not have to undergo the hard work of scrolling to the top

## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by oneknucklehead** [comment]
Can I get assigned to this issue as a GSSoC'21 participant?

**Comment by 991rajat** [comment]
Hey @oneknucklehead this feature is already been implemented. Feel free to look around, plenty of things can be added or modified within this project. Create an issue will be happy to assign you.
I'm closing this issue for now
