### ISSUE TITLE
Whack-a-mole

### ISSUE THREAD

**Issue by Meghag5** [Vishal-raj-1/Awesome-JavaScript-Projects#64]
## Describe the solution you'd like
It is a game in which moles will pop up and when we will select it our points will increase.

**Comment by Meghag5** [comment]
@urvashi-code1255 pls assign it to me and kindly add the tags too

**Comment by urvashi-code1255** [comment]
@Meghag5 Add the description of your project in the pr template you have used!!

**Comment by Vishal-raj-1** [comment]
@Meghag5 That will be great project !! Go for it and Try to complete one issue then ask for next issue !!
