### ISSUE TITLE
Github logo bottom left

### ISSUE THREAD

**Issue by oneknucklehead** [Vishal-raj-1/Awesome-JavaScript-Projects#640]
## Describe the bug
The Github logo on the bottom left should have a hover effect that changes its color and not its size. changing its size is affecting the footer section.

**Comment by oneknucklehead** [comment]
Can I work on this issue under GSSoC'21?

**Comment by iamabhii1** [comment]
Can ,I also work on this issue?

**Comment by 991rajat** [comment]
Hey @oneknucklehead this feature is already been implemented. Feel free to look around, plenty of things can be added or modified within this project. Create an issue we will be happy to assign you.
I'm closing this issue for now
