### ISSUE TITLE
want to add digital fancy clock in this project.

### ISSUE THREAD

**Issue by iamabhii1** [Vishal-raj-1/Awesome-JavaScript-Projects#641]
Hi , I want to add a fancy digital clock which is build using html, css , javascript .
please assign me  and allow me to go forward with this.

**Comment by 991rajat** [comment]
This project already exist. You can create issue for modification or adding new feat.
Feel free to look around, plenty of things can be added or modified within this project. Create an issue we will be happy to assign you.
I'm closing this issue for now
