### ISSUE TITLE
Add To-Do List Project

### ISSUE THREAD

**Issue by AB-san** [Vishal-raj-1/Awesome-JavaScript-Projects#643]
## Is your feature request related to a problem? Please describe.
No its not a problem. I want to add a new project which is a To-Do List
## Describe the solution you'd like
I will add js code which is required to make a new project on To-Do List webapp
## Additional context
In the To-Do List webapps we can add tasks /remove tasks.

**Comment by AB-san** [comment]
Please assign me this issue .

**Comment by 991rajat** [comment]
this type of project is underdevelopment and PR is requested. Once it's merged you can create new issue for modification or new features
Ping me here 2-3 days later.
