### ISSUE TITLE
Mapping Earthquake Data

### ISSUE THREAD

**Issue by iamabhii1** [Vishal-raj-1/Awesome-JavaScript-Projects#645]
Hi, i want to add   a project in public section in this repository regarding **_Mapping earthquake data_** .
mapping earthquakes  using government data on the world map _**using API's and world data feed**_.
this contribution is for GSSOC 21.

please assign me the permission to work on that .

**Comment by 991rajat** [comment]
Sounds Interesting Please Go Ahead Develop it.
