### ISSUE TITLE
[GSSOC'21] Reduce animation in Calculator project

### ISSUE THREAD

**Issue by shonali2600** [Vishal-raj-1/Awesome-JavaScript-Projects#646]
## Is your feature request related to a problem? Please describe.
Yes, While clicking on any number or operator in the calculator, it moves a lot(a lot of animation is there) which is irritating.
## Describe the solution you'd like
I would like to reduce its animation.

**Comment by shonali2600** [comment]
I'm a GSSOC participant and would like to work on it, Please assign this issue to me.

**Comment by 991rajat** [comment]
Sure Go Ahead!
