### ISSUE TITLE
Tetris game

### ISSUE THREAD

**Issue by Amit366** [Vishal-raj-1/Awesome-JavaScript-Projects#647]
## Is your feature request related to a problem? Please describe.
No its not a problem. I just want to add tetris game
## Describe the solution you'd like

Greetings! I am a GSSOC'21 participant and I would like to work on this issue.
I will make Tetris game in javascript

**Comment by Amit366** [comment]
Greetings! I am a GSSOC'21 participant and I would like to work on this issue.

**Comment by Amit366** [comment]
@ridsuteri please assign this issue to me. I am a GSSOC participant

**Comment by ridsuteri** [comment]
@Amit366 this issue is  already assigned ,please try any other one :)

**Comment by Amit366** [comment]
@ridsuteri but I opened it 6 days ago. How is it assigned.

**Comment by ridsuteri** [comment]
@Amit366 there is another issue which was opened 26 and 17 days earlier
