### ISSUE TITLE
Add To-do list app project

### ISSUE THREAD

**Issue by shonali2600** [Vishal-raj-1/Awesome-JavaScript-Projects#648]
## Is your feature request related to a problem? Please describe.
No its not a problem. I would like to add a to-do list app
## Describe the solution you'd like
Will add to-do app using Javascript.

I'm a GSSOC participant Please assign this issue to me

**Comment by AB-san** [comment]
Kindly check issue #643 I have already created this issue !!

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant. could you please assign me this?

**Comment by shonali2600** [comment]
@AB-san I'm so sorry, I've not seen that, I'll close this issue.

**Comment by AB-san** [comment]
> @AB-san I'm so sorry, I've not seen that, I'll close this issue.

It's okay it happens!
