### ISSUE TITLE
Adding styles to "Exchange Rate Calculator"

### ISSUE THREAD

**Issue by SilverGraph** [Vishal-raj-1/Awesome-JavaScript-Projects#650]
Greetings! I am a GSSOC'21 participant and I would like to add some styles to the "Exchange Rate Calculator" page as well as make it responsive.
I would request @Vishal-raj-1 @urvashi-code1255 to assign me this issue.

**Comment by 991rajat** [comment]
Please Go Ahead! Exchange Rate Calculator definitely needs an upgrade

**Comment by SilverGraph** [comment]
@991rajat 
I have successfully added styles to the page. Please review my pull request #719
