### ISSUE TITLE
Falling Bullets

### ISSUE THREAD

**Issue by Fab-Gaurav** [Vishal-raj-1/Awesome-JavaScript-Projects#651]
Hello @Vishal-raj-1 , @urvashi-code1255 
### Want to add Falling Bullets Animation JS to the projects

 [Have a look](https://drive.google.com/file/d/1Ezl0WykdAiVZQ0SWXk_xZHPcilLHFf15/view?usp=sharing)

As a participant of GSSoc'21 I would request you to assign me this issue.

**Comment by 991rajat** [comment]
@Fab-Gaurav Good One Develop it with pure vanilla JS.

**Comment by Fab-Gaurav** [comment]
@991rajat Please Review my PR : https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/727
