### ISSUE TITLE
Add a memory based game to projects

### ISSUE THREAD

**Issue by oneknucklehead** [Vishal-raj-1/Awesome-JavaScript-Projects#652]
## Is your feature request related to a problem? Please describe.
No, it's not a problem. I just want to add my project to the list of projects.

**Comment by 991rajat** [comment]
@oneknucklehead This project is already been under development.Once it's developed you can create new issue for modification or new features
Feel free to look around, plenty of things can be added or modified within this project. Create an issue we will be happy to assign you.
I'm closing this issue for now
