### ISSUE TITLE
Harry Potter characters using Vanila js

### ISSUE THREAD

**Issue by pritamkr1** [Vishal-raj-1/Awesome-JavaScript-Projects#653]
Please assign me to this project.

**Comment by 991rajat** [comment]
Hey @pritamkr1  Describe it more, reference anything so that I'm able to get the proper idea

**Comment by pritamkr1** [comment]
Basically! I'll use API to show all characters of herry Potter with vanilajs

**Comment by pritamkr1** [comment]
Done from my side @991rajat   please have a look at Harry potter #748
