### ISSUE TITLE
Password Genetator using js

### ISSUE THREAD

**Issue by Archna29** [Vishal-raj-1/Awesome-JavaScript-Projects#657]
## Is your feature request related to a problem? Please describe.
No its not a problem. I want to add it in project list.

**Comment by Archna29** [comment]
I am a gssoc participant. Please assign this project to me

**Comment by 991rajat** [comment]
@Archna29  This project is already been implemented.
Feel free to look around, plenty of things can be added or modified within this project. Create an issue we will be happy to assign you.
I'm closing this issue for now
