### ISSUE TITLE
Booklist Application using JavaScript

### ISSUE THREAD

**Issue by vanshikapandey** [Vishal-raj-1/Awesome-JavaScript-Projects#658]
An application that helps users manage the booklist  by adding deleting and updating the list. I am good with javascript and would like to work on this issue under GSSOC'21. Please **/assign** this issue to me admin.

**Comment by amedi-stephen** [comment]
This sounds cool. We can partner on this

**Comment by 991rajat** [comment]
@vanshikapandey  Is it similar to TODO List?

**Comment by vanshikapandey** [comment]
No sir this isn't similar to to-do list.I will be implementing it bit
differently.Kindly assign it to me

**Comment by vanshikapandey** [comment]
Thank you for assigning this issue sir.will get back asap:)

**Comment by harshgupta20** [comment]
@vanshikapandey Whats the update ?
Reply within 2 days or else we have to close it.

**Comment by vanshikapandey** [comment]
Hello sir it's almost done I will make the pr by tomorrow

**Comment by harshgupta20** [comment]
@vanshikapandey It's been a long time, you haven't sent the PR till now.

**Comment by harshgupta20** [comment]
@vanshikapandey Any update? Kindly reply within 2 days or else i have to close this issue.

**Comment by vanshikapandey** [comment]
I will send by today evening

**Comment by harshgupta20** [comment]
@vanshikapandey What's the update?
