### ISSUE TITLE
spelling correction

### ISSUE THREAD

**Issue by lakshita15** [Vishal-raj-1/Awesome-JavaScript-Projects#661]
I want to correct the spellings in rock paper scissor project and add animations to buttons and hover effects. I would add some box shadows to make ui clean.

**Comment by kusu356** [comment]
@ridsuteri @urvashi-code1255 Please assign me this issue under GSSOC21 label.

**Comment by lakshita15** [comment]
I think i raised the issue. So, it would be great if you try and work on some other issues. 
Regards Lakshita..

**Comment by ridsuteri** [comment]
@kusu356 issues are assigned on first come and first serve basis

**Comment by lakshita15** [comment]
@ridsuteri @991rajat please check this i have already completed it....
