### ISSUE TITLE
Add project titles to various projects.

### ISSUE THREAD

**Issue by lakshita15** [Vishal-raj-1/Awesome-JavaScript-Projects#662]
I noticed that various projects lack title. I would like to add title to them all .

**Comment by lakshita15** [comment]
@ridsuteri please see to it

**Comment by ridsuteri** [comment]
@lakshita15 can you share screenshots/gifs of them?

**Comment by lakshita15** [comment]
Sure I’ll work and send it to you.

**Comment by Vishal-raj-1** [comment]
@lakshita15 ??

**Comment by lakshita15** [comment]
Okay I’ll share today

**Comment by ridsuteri** [comment]
@lakshita15 kindly come up with proper screenshots/gifs else we have to close/transfer this issue

**Comment by lakshita15** [comment]
Like these there are various projects that lack a title on their actual
implemented page. I would like to add a nav bar having the name of the
project.
If it’s a game I’ll add heading of that project to the project.

**Comment by ridsuteri** [comment]
@ridsuteri please support the issue with proper screenshots/gifs

**Comment by lakshita15** [comment]
I have added the screenshots..

**Comment by lakshita15** [comment]
Plss check this on gmail.

**Comment by ridsuteri** [comment]
@lakshita15 srry unable to see any screenshots..

**Comment by lakshita15** [comment]
Please see discord🙂🙂

**Comment by ridsuteri** [comment]
ok great @lakshita15 go ahead

**Comment by harshgupta20** [comment]
@lakshita15 Whats the update ?

**Comment by lakshita15** [comment]
I'll Start working was suffering from covid , will start in day or two.
Sorry for the delay🙂

**Comment by ridsuteri** [comment]
take care @lakshita15 , and get well soon :)

**Comment by lakshita15** [comment]
Plss check discord for the changes I’m not able to upload ss here

**Comment by lakshita15** [comment]
@ridsuteri

**Comment by ridsuteri** [comment]
go ahead @lakshita15
