### ISSUE TITLE
Add Hospital registration form validation in the project collection

### ISSUE THREAD

**Issue by AyushPradhan9** [Vishal-raj-1/Awesome-JavaScript-Projects#663]
## Introduction
Hey! I want to add a form registration through javascript in project collection as a participant of GSSoC. Please assign it to me!
Thanks and regards.

## Screenshot:
![bandicam 2021-03-25 19-58-02-732](https://user-images.githubusercontent.com/52281409/112489462-76aaf380-8da4-11eb-9bfc-41deefe76caf.jpg)

**Comment by Suhanii1214** [comment]
Hello!! I would like to work on this issue as a part of GSSOC 2021 . I have already worked with forms so I would be able to design well.
Thankyou!

**Comment by AyushPradhan9** [comment]
@Suhanii1214 Sorry, but I have already done with the form just need a green flag to start to develop a PR. You may raise your own issue or develop the form for better once merged. Thank you!

**Comment by Suhanii1214** [comment]
ok @AyushPradhan9 no prblm.

**Comment by AyushPradhan9** [comment]
@urvashi-code1255 @Vishal-raj-1 @991rajat please view this.
