### ISSUE TITLE
Simon Game Javascript

### ISSUE THREAD

**Issue by srishti-13** [Vishal-raj-1/Awesome-JavaScript-Projects#665]
Hello.....I want to add Simon Game javascript project as a part of GSSoC'21. I have already made this project beforehand while learning. Could you please assign this issue to me?

**Comment by 991rajat** [comment]
this type of project is underdevelopment. Once it's developed you can create new issue for modification or new features
 Feel free to look around, plenty of things can be added or modified within this project. Create an issue we will be happy to assign you.
I'm closing this issue for now
