### ISSUE TITLE
Rearrange the Project In Alphabetical Order

### ISSUE THREAD

**Issue by Bhavyal9** [Vishal-raj-1/Awesome-JavaScript-Projects#667]
As you can see the projects are in random order. I would like to rearrange them in alphabetical order so that it will be easy for the user to navigate through them.

@ridsuteri @urvashi-code1255  Please assign me this issue under GSSOC21 label.

**Comment by kusu356** [comment]
@ridsuteri @urvashi-code1255 Please assign me this issue under GSSOC21 label.

**Comment by Bhavyal9** [comment]
@kusu356 Hi, This issue is raised by me because I want to work on it.

**Comment by Ankita297** [comment]
Can i work on this @ridsuteri @Vishal-raj-1 @urvashi-code1255 ?

**Comment by ridsuteri** [comment]
@Ankita297 you want to do it manually or by writing a sort function or so?, if you are doing it manually ,i don't think it is of any use..,  as it will  break when other project will get added.

**Comment by Ankita297** [comment]
@ridsuteri I want to do it by adding sort function  not manually .
So can i work on t this @Vishal-raj-1 @urvashi-code1255 @harshgupta20

**Comment by Ankita297** [comment]
@ridsuteri I want to do it by adding sort function not manually .
So can i work on t this @Vishal-raj-1 @urvashi-code1255 @harshgupta20
