### ISSUE TITLE
Add a sticky sidebar consisting social media icons in home page

### ISSUE THREAD

**Issue by gayatri517** [Vishal-raj-1/Awesome-JavaScript-Projects#669]
I want to add a sticky social media side bar in the homepage of the website. 
Preview-
![sidebar](https://user-images.githubusercontent.com/70585276/112584535-080a7c00-8e1e-11eb-8afe-1bbd3a100c4e.png)

@Vishal-raj-1 I want to work on this issue as a participant of GSSOC'21. Please assign it to me.

**Comment by affan880** [comment]
I'm a beginner  . i want to contribute in this project by adding sidebar consisting of social media icons .
![sidebar](https://user-images.githubusercontent.com/60839175/112587538-bd8bfe00-8e23-11eb-8a37-0d879033c206.png)

**Comment by gayatri517** [comment]
@ridsuteri please look in to the issue.
