### ISSUE TITLE
Memes Generator

### ISSUE THREAD

**Issue by affan880** [Vishal-raj-1/Awesome-JavaScript-Projects#674]
Want to add a meme generator  by which you can make a meme and you can see current popular memes.

@Vishal-raj-1  please assign me this to do.

**Comment by affan880** [comment]
@Vishal-raj-1  please assign me this issue

**Comment by Vishal-raj-1** [comment]
@affan880 Go ahead !!

**Comment by affan880** [comment]
Thanks🤩
