### ISSUE TITLE
Add Document to Handwritting Website

### ISSUE THREAD

**Issue by Priyadarshan2000** [Vishal-raj-1/Awesome-JavaScript-Projects#679]
Hello 👋🏻  @Vishal-raj-1 

I would like to add a Document to  Handwriting javascript app . This application helps convert document to handwriting. 
this is made with the help of **Google Font API**

Functionalities:
-  Convert to Document to the handwriting
- 10 different type of font
- Dark mode
- Download your work in png Format.
- change font size, font width.

@Vishal-raj-1  I am a GSSoC'21 participant and I think this is an interesting javascript project. Kindly allow me to work on this issue and contribute to this project!

**Comment by Vishal-raj-1** [comment]
@Priyadarshan2000 That would be great project. Waiting for the PR

**Comment by Priyadarshan2000** [comment]
Ok sir plz.. assign me this project.i would PR in 2 days..
