### ISSUE TITLE
Click-And-Drag

### ISSUE THREAD

**Issue by Meghag5** [Vishal-raj-1/Awesome-JavaScript-Projects#68]
## Describe the solution you'd like
in this project when we drag sideways it will show more pictures and no.s like in netflix when we click and drag it shows more movies. 

## Additional context
Add any other context about the feature request here.
It is very useful in many places

**Comment by Meghag5** [comment]
@urvashi-code1255 pls assign it to me and kindly add the tags too.

**Comment by urvashi-code1255** [comment]
@Meghag5 Go for it!!

Do follow the PR template and make a seperate branch!!

**Comment by Meghag5** [comment]
> @Meghag5 Go for it!!
> 
> Do follow the PR template and make a seperate branch!!

yes sure
