### ISSUE TITLE
Adding a placeholder for the name, email, etc.

### ISSUE THREAD

**Issue by RubenFalcao14** [Vishal-raj-1/Awesome-JavaScript-Projects#688]
The text boxes do not have a placeholder . I'm a GSSOC'21 participant and I  would love to add the placeholder.
Thank You.

**Comment by dikshitaiyer** [comment]
I would like to work on this issue , I am Gssoc participant. If no one is working on this issue then please assign it to me.Thanks!

**Comment by pyash99** [comment]
I'm a GSSOC'21 participant and I would like to work on this issue.

**Comment by shruti-mayank** [comment]
I am a GSSoC'21 participant and would like to work on the issue.
Could you please assign me the issue?

**Comment by Vishal-raj-1** [comment]
@RubenFalcao14 You can raise the PR for the same !! Rest of you can check the other issue
