### ISSUE TITLE
[Enhancement]: Mole-game-project

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#69]
## Is your feature request related to a problem? Please describe.
- Overflow in horizontal direction.
- Start button is too small and don't have any designs.

## Describe the solution you'd like
- Remove the Overflow(scroll bar) in horizontal direction.
- Give styling to the start button.

**Comment by Meghag5** [comment]
i will work on this . pls assign it to me @urvashi-code1255

**Comment by urvashi-code1255** [comment]
Sure @Meghag5
