### ISSUE TITLE
Add A todo list project

### ISSUE THREAD

**Issue by Priya19999** [Vishal-raj-1/Awesome-JavaScript-Projects#690]
Hey! I want to add A to-do list to the project collection ---as a participant of GSSOC'21. Please assign it to me!

**Comment by Shivangi-ch** [comment]
I want to add  to-do list to the  collection as a participant of GSSOC'21. 
Please assign it  to me.

**Comment by Vishal-raj-1** [comment]
@Priya19999 You can raise the PR now. Meanwhile @Shivangi-ch You can check other issues

**Comment by Priya19999** [comment]
Okay Sending  a PR now

**Comment by harshgupta20** [comment]
This project already exist :)
