### ISSUE TITLE
Add a temp_finder project

### ISSUE THREAD

**Issue by Anubhav7298** [Vishal-raj-1/Awesome-JavaScript-Projects#692]
I want to add a temperature finder project.

This project aim to provide real time temperature of a city.

**Comment by affan880** [comment]
?? @Anubhav7298

**Comment by Vishal-raj-1** [comment]
@Anubhav7298 Atleast Before raising the issue check the Project is already there or not. And if some issues are open then until its assigned to you, don't raise the PRs. It is a duplicate issue you can contribute to other issues.
