### ISSUE TITLE
UI modification of Contact-Us Form 

### ISSUE THREAD

**Issue by Tanya933** [Vishal-raj-1/Awesome-JavaScript-Projects#706]
I would like to add   icons   ,placeholder ,    contact-form button effects  improvement and other css stuffs to  enhance the 
    UI of  Contact Us form as a GSSOC'21 participant . @ridsuteri @991rajat @urvashi-code1255 @harshgupta20 please assign 
    this issue to me. Thankyou .

**Comment by Tanya933** [comment]
@ridsuteri @991rajat @urvashi-code1255 @harshgupta20.Please assign this issue to me.Thankyou

**Comment by Vishal-raj-1** [comment]
@Tanya933 It is already assigned to someone. You can check other issues
