### ISSUE TITLE
Create a signup and login form

### ISSUE THREAD

**Issue by Muskan-creator** [Vishal-raj-1/Awesome-JavaScript-Projects#707]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to include a new feature.
## Describe the solution you'd like
I  want to create a signup and login form page in this project .
please assign this issue to me @urvashi-code1255

**Comment by shruti-mayank** [comment]
I can make a perfectly responsible login and signup page for the website. 
I request @Vishal-raj-1 and @urvashi-code1255 to assign me the issue.

**Comment by Vishal-raj-1** [comment]
@Muskan-creator This issue assigned to you for next one week, IF you are not able to raise PR in one week then It would be assigned to @shruti-mayank. Meanwhile shruti you can check other issues
