### ISSUE TITLE
Html validation

### ISSUE THREAD

**Issue by Muskan-creator** [Vishal-raj-1/Awesome-JavaScript-Projects#708]
## Describe the bug
The lists are not valid according to html along with some other issues. Please assign me this issue.
You can check for yourself by uploading the index.html here.
https://validator.w3.org/#validate_by_input

## Expected behavior
I want to validate html according w3c standards.

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).
![image](https://user-images.githubusercontent.com/59757988/112791618-916cb900-907f-11eb-97a8-96117d067134.png)

## Additional context
Also projects.html and contact.html are not validated
![image](https://user-images.githubusercontent.com/59757988/112791838-f0cac900-907f-11eb-8858-a3fa6dc9a910.png)
![image](https://user-images.githubusercontent.com/59757988/112791894-093ae380-9080-11eb-9135-e48e143ef8d1.png)

**Comment by Vishal-raj-1** [comment]
@Muskan-creator You can do one thing. This issue is assigned to you. and sign up page assigned to someone else. is it okay ?

**Comment by Muskan-creator** [comment]
I have already started working on both issues.I have a idea for signup form.I have created issues 1 week ago ,half work is already done.
