### ISSUE TITLE
Pagination in Vanilla JS

### ISSUE THREAD

**Issue by shubhamjha25** [Vishal-raj-1/Awesome-JavaScript-Projects#709]
## Is your feature request related to a problem?
No, It's not a problem. I am trying to include a new feature.

## Describe your feature 
Pagination is the process of separating print or digital content into discrete pages. 
For print documents and some online content, pagination also refers to the automated process of adding consecutive numbers to identify the sequential order of pages.
Online articles are sometimes paginated to break up content. There is some justification to organizing long articles into multiple pages to aid the reader.

Therefore, I would like to add a simple project called "Pagination" using HTML, CSS and vanilla JS.

![paginationnnn](https://user-images.githubusercontent.com/63443481/112793250-91ba8380-9082-11eb-82ba-00f089432836.png)

Would be delighted if you consider my submission for this issue @Vishal-raj-1  @urvashi-code1255 @991rajat.
Thank You _:)_

**Comment by 991rajat** [comment]
@shubhamjha25  Always get assigned first before making PR, It helps us to manage easily.

**Comment by shubhamjha25** [comment]
Thanks, I will keep this in mind for sure.
