### ISSUE TITLE
Carousel using Vanilla JS

### ISSUE THREAD

**Issue by shubhamjha25** [Vishal-raj-1/Awesome-JavaScript-Projects#716]
Hi There! 
I am Shubham Jha. Currently Open Sourcing.

This issue is not related to any problem. Rather, I would like to add a new feature.

## Description
I would like to make a **Carousel** using the primitive tools i.e., HTML5, CSS3 and Vanilla JS. 
A carousel is a list of cards that can be shuffled to display different content. Ideally, each card contains a different item that the user can browse from left and right. Carousel is an effective way of displaying images or content cards. They can add visual interest and reduce clutter.

### Why **Carousel** ? 
Though, there are plenty of CSS frameworks and libraries available that enables you to create a carousel in a couple of minutes. 
The reason I chose this because building a functioning carousel in browser readable code requires architectural thinking, management of data and elements, DOM manipulation and the consideration for user interaction.

No _libraries_, no _frameworks_, no _build tools_. Just **HTML5**, **CSS3** and **JavaScript** from _scratch_.

Humble request to the maintainers of this awesome project @Vishal-raj-1 @urvashi-code1255 @991rajat, Kindly assign me to this issue so that I can start working on it.

Thank You _:)_

**Comment by 991rajat** [comment]
@shubhamjha25  I believe this issue is similar to this one #589 ?

**Comment by shubhamjha25** [comment]
Ah! Yes yes.

**Comment by 991rajat** [comment]
Once it's developed you can create new issue for modification or new features.
Feel free to look around, plenty of things can be added or modified within this project. Create an issue we will be happy to assign you.
I'm closing this issue for now

**Comment by shubhamjha25** [comment]
Okay, Thank You.
