### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by NehaK745** [Vishal-raj-1/Awesome-JavaScript-Projects#729]
## Describe the bug
I was going through this project and I found this error. the spelling of contact is not grammatically correct.
Please assign this issue to me I want to fix this as a participant of gssoc21.
## Additional context
![Screenshot (12)_LI](https://user-images.githubusercontent.com/64440607/112937053-96e00700-9144-11eb-916b-463a51fa3bfb.jpg)

**Comment by Vishal-raj-1** [comment]
@NehaK745 You can raise the PR for the same and check other mistakes as well

**Comment by harshgupta20** [comment]
Issue Already resolved :)
