### ISSUE TITLE
PR template is not in place

### ISSUE THREAD

**Issue by Sloth-Panda** [Vishal-raj-1/Awesome-JavaScript-Projects#73]
## Is your feature request related to a problem? Please describe.
Yes
## Describe the solution you'd like
When I try to make a pr it does not show me the pr template
## Additional context
Add any other context about the feature request here.

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda Do you want to solve this issue?

**Comment by Sloth-Panda** [comment]
Yes, can make this asap @urvashi-code1255

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda Make a PR for this one first!! Then only I can merge any PR!!

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 I have already made the pr for the other two You can check them its just basically a set of checklists and nothing else is there in a pr template else I have to again close both the prs for no reason

**Comment by Sloth-Panda** [comment]
Assign me this and add the tags then but doing this wont affect already made prs but the ones that will be coming after this gets merged @urvashi-code1255

**Comment by urvashi-code1255** [comment]
> Assign me this and add the tags then but doing this wont affect already made prs but the ones that will be coming after this gets merged @urvashi-code1255



> @urvashi-code1255 I have already made the pr for the other two You can check them its just basically a set of checklists and nothing else is there in a pr template else I have to again close both the prs for no reason

Hey @Sloth-Panda You can always edit your PR or issue from here..

![Capture](https://user-images.githubusercontent.com/63122133/107881986-e956c280-6f0c-11eb-8640-2e38cb88eb27.PNG)

I am only saying you to send its PR and then copy this template and edit your current PR!!

**Comment by urvashi-code1255** [comment]
For your current PRs you can copy the format from [here](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/blob/main/.github/PR_template.md) and fill it accordingly!!
