### ISSUE TITLE
Project Idea : John Conway's game of life

### ISSUE THREAD

**Issue by jhamadhav** [Vishal-raj-1/Awesome-JavaScript-Projects#730]
# Game-of-life
A project inspired by John Conway's game of life. 
The Game of Life, also known simply as Life, is a cellular automaton devised by the British mathematician John Horton Conway in 1970. It is a zero-player game, meaning that its evolution is determined by its initial state, requiring no further input. One interacts with the Game of Life by creating an initial configuration and observing how it evolves.
*Source - wikipedia*

## Main goal
1. Make a simulator to simulate the rules in the game of life
2. Let the user make or change the patterns
3. Add different preloaded and known patterns
4. Add info regarding the concept
5. Add slider to increase and see each individual steps

## Tech stack
- **Frontend**: HTML, SCSS/CSS and JavaScript.

## Examples :
![image](https://user-images.githubusercontent.com/37475140/112936575-b296dd80-9143-11eb-8dbc-c3307bad3275.png)

**Comment by jhamadhav** [comment]
As part of #GSSoC'21, I would love to develop it and contribute to this project.
@Vishal-raj-1  @urvashi-code1255 please assign me this !

**Comment by Vishal-raj-1** [comment]
@jhamadhav are you using html, css and vanilla js only ??

**Comment by jhamadhav** [comment]
Yes definitely.
It more complex towards mathematics but tools are enough
