### ISSUE TITLE
Armstrong Number Checker using Javascript

### ISSUE THREAD

**Issue by tk315** [Vishal-raj-1/Awesome-JavaScript-Projects#731]
## Is your feature request related to a problem? Please describe.
No its not a problem. I just want to add a new project to check whether a number is Armstrong or not using JavaScript under GSSOC2021

## Describe the solution you'd like
When the user click on Check Button after entering the Number ,this project will find out whether the Entered Number is Armstrong or Not and give the results.
Armstrong No: the sum of cubes of each digit is equal to the number itself

**Comment by tk315** [comment]
@991rajat @Vishal-raj-1 @urvashi-code1255 Please assign me this issue

[GSSOC'21]

**Comment by Vishal-raj-1** [comment]
@tk315 You can go ahead with this issue. Looking forward to your PR
