### ISSUE TITLE
Create License

### ISSUE THREAD

**Issue by tushartiwari7** [Vishal-raj-1/Awesome-JavaScript-Projects#732]
## To Reproduce
1. we have many free licenses to choose from eg. Apache v2.0, MIT, GNU etc.
2. i can add any as per your preferences.
3. A License is a must for a repo like this as this repo remains active almost everytime so having a icense is a good idea.

## Expected behavior
it will make [this ](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/i) a more legitimate repo 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: any 
 - Browser: any

## Additional context
please add gssoc21 and level2 labels for this issue, thanks.

**Comment by Vishal-raj-1** [comment]
@tushartiwari7 sure !!

**Comment by tushartiwari7** [comment]
please have a look at this @Vishal-raj-1
