### ISSUE TITLE
Infix to postfix and prefix converter using JavaScript

### ISSUE THREAD

**Issue by shivammahajancse** [Vishal-raj-1/Awesome-JavaScript-Projects#733]
## Is your feature request related to a problem? Please describe.
No its not a problem. I just want to add a new project that converts Infix to postfix/prefix using JavaScript under GSSOC 2021.
## Describe the solution you'd like
I will make an converter which convert infix expression to postfix and prefix. When user enters a infix expression and click on convert button then it convert into postfix and prefix expression.

**Comment by Vishal-raj-1** [comment]
@shivammahajancse GO Ahead with this issue
