### ISSUE TITLE
Infix, Postfix & Prefix expression evaluator using JavaScript

### ISSUE THREAD

**Issue by shivammahajancse** [Vishal-raj-1/Awesome-JavaScript-Projects#734]
## Is your feature request related to a problem? Please describe.
No its not a problem. I just want to add a new project which evaluate the infix, postfix & prefix expression using JavaScript under GSSOC 2021.
## Describe the solution you'd like
I will make an evaluator which evaluate infix, postfix & prefix expression. When user enters a infix/prefix/postfix expression and click on evaluate button then it evaluate the expression.

**Comment by headphone-rachit** [comment]
Hey, @shivammahajancse I would Like to work on it would you assign me this and tell me where to add it.
Thanks

**Comment by Vishal-raj-1** [comment]
@shivammahajancse how is it different from #733 . If it is different then I would assigned this issue to @headphone-rachit
