### ISSUE TITLE
Factorial Calculator

### ISSUE THREAD

**Issue by tk315** [Vishal-raj-1/Awesome-JavaScript-Projects#735]
Is your feature request related to a problem? Please describe.
No its not a problem. I just want to add a new project to calculate the Factorial of the entered Number using JavaScript under GSSOC2021

Describe the solution you'd like
When the user click on Calculate Button after entering the Number ,this project will print the Factorial of the entered number on the screen

Factorial:  is the product of all positive integers less than or equal to n

**Comment by tk315** [comment]
gssoc

**Comment by AnshikaAgrawal5501** [comment]
Hey, I am a GSSOC'21 participant and I would like to work on this issue.

@Vishal-raj-1  @urvashi-code1255  @ridsuteri 
Please assign this issue to me.

**Comment by Malvika18** [comment]
I would want to work on this.

**Comment by tk315** [comment]
@991rajat @Vishal-raj-1 @urvashi-code1255 Please assign me this issue

[GSSOC'21]

**Comment by tk315** [comment]
assign

**Comment by Vishal-raj-1** [comment]
@tk315 I have already assigned one issue to you. Do one issue at a time. For now I am assigning this issue to @AnshikaAgrawal5501

**Comment by AnshikaAgrawal5501** [comment]
Thank you @Vishal-raj-1  for assigning me the issue.
