### ISSUE TITLE
Add a profile card generator.

### ISSUE THREAD

**Issue by janvi01** [Vishal-raj-1/Awesome-JavaScript-Projects#736]
I would like to add a new javascript project.

### Description
Like enter your personal details like name, dob, profession, photo, etc.
and then it will display a beautiful card displaying your identity.
Something like I-Card.

Please review this issue...

**Comment by janvi01** [comment]
@991rajat

**Comment by Vishal-raj-1** [comment]
@janvi01 Sure you can go ahead with that issue

**Comment by janvi01** [comment]
Thanks for assigning.

**Comment by janvi01** [comment]
labels won't be added? @Vishal-raj-1

**Comment by janvi01** [comment]
Please review my PR.
