### ISSUE TITLE
Quiz App

### ISSUE THREAD

**Issue by Amit366** [Vishal-raj-1/Awesome-JavaScript-Projects#737]
## Is your feature request related to a problem? Please describe.
No its not a problem. I am a GSSOC participant and would like to make a quiz app
## Describe the solution you'd like
I would use javascript and html to make the app.

**Comment by Amit366** [comment]
@ridsuteri please assign it to me

**Comment by Amit366** [comment]
@991rajat can I start working??

**Comment by Vishal-raj-1** [comment]
@Amit366 Quiz App is already there, if you wan to modify already existing project then let me know
