### ISSUE TITLE
Valentine Special 

### ISSUE THREAD

**Issue by TidbitsJS** [Vishal-raj-1/Awesome-JavaScript-Projects#74]
## Heart It
Many many hearts to all people who are trying to code & want to become a better version of oneself

## JS developer's Valentine
Simple yet elegant creative application using JS. The project is about to create multiple hearts with different timeouts + a single heart creation on every click anywhere in the window ( Drizzle of Hearts )

## Demo ( Keep an eye on cursor )
![demo](https://s2.gifyu.com/images/cinnamon-20210214-1606227f16cbc62d0.gif)

**Comment by TidbitsJS** [comment]
Assign this to me & I will make PR by today itself. Do add GSSOC labels to all of my contributions to help me achieve my goal ( Contributing as a participant of GSSOC event )

**Comment by urvashi-code1255** [comment]
@TidbitsJS I love this project!! You can go for it!

**Comment by TidbitsJS** [comment]
Thank you so much @urvashi-code1255
