### ISSUE TITLE
Grocery bud

### ISSUE THREAD

**Issue by Amit366** [Vishal-raj-1/Awesome-JavaScript-Projects#740]
## Is your feature request related to a problem? Please describe.
No its not a problem. I am a GSSOC participant and would like a web app in which user can add the grocery items which are to be bought
## Describe the solution you'd like
I will be using JavaScript and HTML

**Comment by Amit366** [comment]
@ridsuteri please assign me this issue

**Comment by Amit366** [comment]
@991rajat can I start working on it??

**Comment by Vishal-raj-1** [comment]
@Amit366 There is already one project Name Local Storage . You can improve that project. And dont raise the PR until issue is assigned to you

**Comment by Amit366** [comment]
@Vishal-raj-1 once see the image of the website.

**Comment by Amit366** [comment]
If you like that then ok or else I will close the PR.
