### ISSUE TITLE
Fotter section is not allign in desktop view

### ISSUE THREAD

**Issue by abhijeet141** [Vishal-raj-1/Awesome-JavaScript-Projects#745]
## Describe the bug
Fotter section is not allign in desktop view

## To Reproduce
1. click on website link
2. scroll down
Please assign me this issue
![image](https://user-images.githubusercontent.com/67696867/113006981-71c6b500-9193-11eb-8293-6c2b5d9a0bd1.png)

**Comment by Bhavya-Sehgal** [comment]
I want to work on this issue  as GSSOC'21 participant. Please assign me this issue. @Vishal-raj-1 @urvashi-code1255  @991rajat

**Comment by Vishal-raj-1** [comment]
@abhijeet141 You can work on that issue. @Bhavya-Sehgal Check other issue for now, or if @abhijeet141 doesn't raise PR in next 5 days then I will assign this issue to you

**Comment by abhijeet141** [comment]
@Vishal-raj-1 Please check this and also please check on main website that there is no project visible in project section
