### ISSUE TITLE
Image Editor 

### ISSUE THREAD

**Issue by AnshikaAgrawal5501** [Vishal-raj-1/Awesome-JavaScript-Projects#754]
## Is your feature request related to a problem? Please describe.
No, it's not a problem. I would like to add a new project called **Image Editor**.

## Describe the solution you'd like
In this project, multiple filters are provided and we can apply them to the image and edit it.

## Additional context
There is a range to decide the intensity of each and every filter. The frame can also be added with the desirable color.

## Screenshot
![cover](https://user-images.githubusercontent.com/56653257/113134821-f15d8e00-923e-11eb-8497-8da95734b698.png)

@Vishal-raj-1 @urvashi-code1255  @ridsuteri 
I am a GSSOC'21 participant, please assign this issue to me.

**Comment by ridsuteri** [comment]
@AnshikaAgrawal5501 this issue is already assigned to someone,please come up with any other issue or try to improve any existing project
