### ISSUE TITLE
Adding functional links in contact us section

### ISSUE THREAD

**Issue by abhijeet141** [Vishal-raj-1/Awesome-JavaScript-Projects#756]
## Describe the bug
Currently, the contact us section links are non-clickable  they are not functional.

![image](https://user-images.githubusercontent.com/67696867/113184671-1966e480-9273-11eb-8764-2a8c8b222bd9.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by abhijeet141** [comment]
> Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
> @991rajat  Kindly assign this issue to me!
> Discord Username : Abhijeet Sinha(P)
> Discord Tag: #4018

**Comment by urvashi-code1255** [comment]
@abhijeet141 Links are not clickable because we haven't added any URL in them.
