### ISSUE TITLE
JavaScript Grocery List Project 

### ISSUE THREAD

**Issue by bishalshaw-164** [Vishal-raj-1/Awesome-JavaScript-Projects#761]
## Additional context
If the user tries to submit a blank item, the top container in the project alerts the user to add an item with an “alert” message. If the user successfully adds an item, the top container alerts the user with a “success” message.
Every time an item is added, the item is displayed in the DOM and is also saved to the user's local storage.
If the user clicks the “Clear items” button, all items will be removed from the DOM and local storage.
If the user clicks just one of the delete item icons, only that item will be removed.

**Comment by 991rajat** [comment]
Hey @bishalshaw-164 It is similar to local storage. Please checkout. If you want to improve upon it comment here, will assign it to you.

**Comment by 991rajat** [comment]
Groccery App has been added. If you want to improve upon it create a issue will be happy to assign you.
