### ISSUE TITLE
Add the LIGHT-DARK mode 

### ISSUE THREAD

**Issue by K-jais** [Vishal-raj-1/Awesome-JavaScript-Projects#762]
I can Add Light Dark Mode to all of the pages which adds another feature to this website and which just gives two choices to the user as whats its preferable UI is either light or dark.

**Comment by K-jais** [comment]
Thank you for assigning me this issue.

**Comment by K-jais** [comment]
Hello @urvashi-code1255  , this feature has already been added in the project. Is it allowed to do that if some other person has been assigned the issue and some other person has done that?

**Comment by harshgupta20** [comment]
@K-jais Yes, but you have to ask to the project admin first and wait for it, if participant will not respond then it will be assigned to you.
Since this issue has been solved, I have to close it.
