### ISSUE TITLE
Add Pronunciation web project

### ISSUE THREAD

**Issue by K-jais** [Vishal-raj-1/Awesome-JavaScript-Projects#764]
In this project, I will have one pronunciator who pronounces each and everything a person or a user writes.

**Comment by urvashi-code1255** [comment]
@K-jais I think its similar to "text to speech project" which is already present on the website. Do have  a look on it. Let me know if you want to do something different

**Comment by K-jais** [comment]
Yes, ma'am, it is quite similar to that only. I haven't seen that project before creating this issue. Sorry for the inconvenience.

**Comment by 991rajat** [comment]
I'm closing this issue as it is already present.
If you want to improve on it. Create a new issue. Will be happy to assign you.
