### ISSUE TITLE
Calendar using VanillaJs

### ISSUE THREAD

**Issue by Soham2020** [Vishal-raj-1/Awesome-JavaScript-Projects#771]
### Hi there, myself Soham Das, wants to add a new simple project, called “Calendar”, using HTML, CSS and VanillaJs.  

**Description:** 

Calendar is a system of organizing days. This is done giving names to period of times, days, weeks, months and years. As we all know how days are valuable for us, so if we add calendar, we will navigate our progress of each day and also good for setting short- or long-term goals. 

 

Therefore, I would like to add a simple project “Calendar” 

 

Would be delighted if you consider my submission for this        issue @Vishal-raj-1 @urvashi-code1255 @991rajat. 

Dear project maintainers, please assigned me to this issue, so that I can work on it, as early as possible. 
Thank You

**Comment by urvashi-code1255** [comment]
@Soham2020 Calender is already present in the project. If you want to improve it then I can assign it to you.

**Comment by 991rajat** [comment]
I'm closing this. If you want to improve upon this project create a new issue for improvement.
