### ISSUE TITLE
Palindrome check -  Improvement in UI.

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [Vishal-raj-1/Awesome-JavaScript-Projects#774]
## Describe the bug
Both check and reset buttons  are displayed despite of its dependence on text being added.

## Expected behavior
Initially there should  only be the check button and after that if the word is checked then only reset button should be there. 

![palindrome-ss](https://user-images.githubusercontent.com/66208607/113411975-c4db7a80-93d4-11eb-9450-326a14a3614e.png)

**Comment by Bhavya-Sehgal** [comment]
I want to work on this issue as GSSOC'21 participant. Please assign me this issue. @Vishal-raj-1 @urvashi-code1255 @991rajat

**Comment by 991rajat** [comment]
@Bhavya-Sehgal Reset button is required when someone is typing and want to erase all.
Would you like to modify or change the layout of current palindrome checker?

**Comment by Bhavya-Sehgal** [comment]
> @Bhavya-Sehgal Reset button is required when someone is typing and want to erase all.
> Would you like to modify or change the layout of current palindrome checker?

Okay sure!!
