### ISSUE TITLE
Auto-type project

### ISSUE THREAD

**Issue by mahesh-11102** [Vishal-raj-1/Awesome-JavaScript-Projects#778]
## Here I'm sharing a glimpse of the project

https://user-images.githubusercontent.com/77436328/113427539-d6337f80-93f2-11eb-8490-bab22d3316df.mp4

@ridsuteri  @991rajat  @urvashi-code1255  @harshgupta20 ,As  a part of  GSSOC'21 I would like to work on this project .
 please assign this issue to me .

**Comment by Vishal-raj-1** [comment]
Sure @mahesh-11102 go ahead

**Comment by mahesh-11102** [comment]
thank youy @Vishal-raj-1 sir , for assiging me the issue :)
