### ISSUE TITLE
Make calculator project response in mobile view  

### ISSUE THREAD

**Issue by Marim99** [Vishal-raj-1/Awesome-JavaScript-Projects#783]
the calculator project isn't response in small screen so I want to make this project response ..as a participant of GSOC 21. Please assign it to me
![Screenshot (167)](https://user-images.githubusercontent.com/78925756/113451483-5ca38d80-9402-11eb-88f6-ca3aae3897fb.png)

**Comment by Vishal-raj-1** [comment]
Sure @Marim99 Go ahead

**Comment by Marim99** [comment]
thank you for assigned me , please can you make label for this issue
