### ISSUE TITLE
Wrong Word Count In Word Counter Project

### ISSUE THREAD

**Issue by swapnilbhakare** [Vishal-raj-1/Awesome-JavaScript-Projects#786]
## Describe the bug
**There is wrong count of words in Word counter project** . I want to hands on this issue @urvashi-code1255 mam please assign this issue to me ,Under the gssoc label :)
![word counter error](https://user-images.githubusercontent.com/67636219/113470697-e6476100-93ea-11eb-979f-aeec833ed697.png)

 
## Expected behavior
If We type Four Words it should display that you written 4 words

## Environment (please complete the following information):
 - OS: Windows 
 - Browser: chrome

**Comment by prayas7102** [comment]
Please assign this issue to me i want to work on resolving this issue.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by AnandBIT** [comment]
Please assign this issue to me, I'll resolve this issue ASAP

**Comment by swapnilbhakare** [comment]
@prayas7102 ,@AshuKV ,@AnandBIT I created this issue first so, on the basis of first come first serve this issue will assign to me,If I am unable to solve this you guys can go for it , but let mentors assign this issue to me first :)
