### ISSUE TITLE
Chat app

### ISSUE THREAD

**Issue by bug-debug-done** [Vishal-raj-1/Awesome-JavaScript-Projects#787]
I would like to add a Chat app to the website .

**Comment by ridsuteri** [comment]
@bug-debug-done similar issue #613  is already raised ..since the applicant is not responding i am assigning it to you now

**Comment by harshgupta20** [comment]
@bug-debug-done Any update? Kindly reply within 2 days or else i have to close this issue.

**Comment by bug-debug-done** [comment]
@Harshal0902 I'll make pr within 2 days

**Comment by harshgupta20** [comment]
Any update?
