### ISSUE TITLE
RETURN to HOME PAGE BUTTON

### ISSUE THREAD

**Issue by bug-debug-done** [Vishal-raj-1/Awesome-JavaScript-Projects#789]
## Describe the bug
Once we click on a particular project it opens in new tab and there is no option to get back to home page

## To Reproduce
1. Create a RETURN TO HOME PAGE button
2. Link it to the home page
 

## Additional context
It would be better if the project page opens in  the same tab.

**Comment by bug-debug-done** [comment]
Please assign this to me.

**Comment by ridsuteri** [comment]
@bug-debug-done you want to add home button on each project page?

**Comment by bug-debug-done** [comment]
@ridsuteri yes

**Comment by ridsuteri** [comment]
@bug-debug-done in my opinion it is making more sense now..but let me ask other mentors about it
please wait

**Comment by bug-debug-done** [comment]
Ok

**Comment by ridsuteri** [comment]
@bug-debug-done ok go ahead

**Comment by harshgupta20** [comment]
Since the project structure has been changed this issue has been solved.
