### ISSUE TITLE
8 Ball Pool game

### ISSUE THREAD

**Issue by bug-debug-done** [Vishal-raj-1/Awesome-JavaScript-Projects#790]
I would like to add a 8 ball pool game. I will make it using HTML 5 , CSS and JavaScript. Please assign this to me under GSSOC'21.

**Comment by harshgupta20** [comment]
@bug-debug-done Any update? Kindly reply within 2 days or else i have to close this issue.

**Comment by bug-debug-done** [comment]
@harshgupta20 I will make PR within 3-4 days

**Comment by harshgupta20** [comment]
@bug-debug-done Any update?

**Comment by ridsuteri** [comment]
@bug-debug-done progress?

**Comment by Amit366** [comment]
@ridsuteri @Vishal-raj-1 can I work?

**Comment by ridsuteri** [comment]
ok @Amit366 go ahead :)

**Comment by Amit366** [comment]
@ridsuteri any other issue which is open and no one is working??

**Comment by ridsuteri** [comment]
@Amit366 try looking in issues sections for issues which are open/ not addressed for a while..
i will also let you know , if i came across any such issues :)
