### ISSUE TITLE
Shopping Cart

### ISSUE THREAD

**Issue by bug-debug-done** [Vishal-raj-1/Awesome-JavaScript-Projects#792]
I am a GSSOC'21 Participant. 
I will make a E-Commerce Shopping Cart using HTML,CSS and JavaScript.

**Comment by Amit366** [comment]
@ridsuteri can I work??

**Comment by bug-debug-done** [comment]
working on it

**Comment by Amit366** [comment]
@bug-debug-done you r working on 6 projects and I don't think you have sent Aby PR yet. So I asked @ridsuteri to check whether this is open or not.

**Comment by bug-debug-done** [comment]
@Amit366 Don't worry I am working Work on it work in progress :)

**Comment by ridsuteri** [comment]
@bug-debug-done any progress on this issue?

**Comment by bug-debug-done** [comment]
@ridsuteri 60% done. I am also working on other issues so it is taking timr

**Comment by ridsuteri** [comment]
@bug-debug-done it's been 13 days since you are assigned to this issue! 
please try to come up with a PR as soon as possible, and same applies to the other issues assigned to you as well :)

**Comment by bug-debug-done** [comment]
@ridsuteri will complete it by tomorrow

**Comment by ridsuteri** [comment]
ok @bug-debug-done ! thanks for the update :)

**Comment by bug-debug-done** [comment]
@ridsuteri  hey I am done with the code but there is some problem with the photos some photos do not load

**Comment by bug-debug-done** [comment]
@ridsuteri I am getting this error "failed to push some refs to 'https://github.com/bug-debug-done/Awesome-JavaScript-Projects.git'
" not able to update

**Comment by bug-debug-done** [comment]
@ridsuteri hey can please check the pr #1135
