### ISSUE TITLE
Text To Speech is shown twice on the website

### ISSUE THREAD

**Issue by bug-debug-done** [Vishal-raj-1/Awesome-JavaScript-Projects#793]
## Describe the bug
Same project is mentioned twice

## To Reproduce
1. I'll remove the repetition

**Comment by bug-debug-done** [comment]
Please assign this to me.

**Comment by harshgupta20** [comment]
@bug-debug-done you can start working on this issue.

**Comment by bug-debug-done** [comment]
@harshgupta20 sorry for delay was busy with something will do it asap

**Comment by 991rajat** [comment]
Already fixed.
