### ISSUE TITLE
Text to Voice Generator is shown twice on website

### ISSUE THREAD

**Issue by Mrinal81** [Vishal-raj-1/Awesome-JavaScript-Projects#794]
I am a GSSOC'21 Participant.I want to work on this Issue.
Please assign me this issue..

**Comment by harshgupta20** [comment]
@Mrinal81  Can you please describe more about this issue??

Kindly reply within 2 days or else we need to close it.

**Comment by Mrinal81** [comment]
![text to voice](https://user-images.githubusercontent.com/76482022/114364421-028b9080-9b97-11eb-900e-9447abe8250e.jpeg)
![text to voice generator](https://user-images.githubusercontent.com/76482022/114364431-04edea80-9b97-11eb-8cde-cb28df8d91a8.jpeg)


@harshgupta20 I have attached the photo in which text to voice generator shown twice.....

**Comment by Mrinal81** [comment]
@harshgupta20 there is many projects which has shown twice.......

**Comment by harshgupta20** [comment]
@Mrinal81 go ahead buddy.

**Comment by Mrinal81** [comment]
@harshgupta20 Please have a look on PR #1008..

**Comment by ridsuteri** [comment]
@Mrinal81 i guess this comes under issue #957 !
and that's assigned to you ,so it would be better if you could close this and the PR made to it :)
