### ISSUE TITLE
Blank space at the end of the Home page

### ISSUE THREAD

**Issue by bug-debug-done** [Vishal-raj-1/Awesome-JavaScript-Projects#796]
![Screenshot from 2021-04-03 15-03-00](https://user-images.githubusercontent.com/75927761/113474474-c61cae00-948d-11eb-9c09-2cc11173b74b.png)
I will remove the blank space as it does not look good.Please assign this to me.

**Comment by harshgupta20** [comment]
@bug-debug-done since this issue has been resolved, i am closing that issue.
