### ISSUE TITLE
The Layout of the page is not same

### ISSUE THREAD

**Issue by bug-debug-done** [Vishal-raj-1/Awesome-JavaScript-Projects#799]
![Screenshot from 2021-04-03 15-05-47](https://user-images.githubusercontent.com/75927761/113474542-2ad80880-948e-11eb-83ab-76e2e7b63f05.png)
two projects are shown in same line which does not look good. It is different from the rest of the page I'll correct that.

**Comment by harshgupta20** [comment]
@bug-debug-done since this issue has been resolved, so i am closing that issue.
