### ISSUE TITLE
In some of the project the CSS not linked correctly

### ISSUE THREAD

**Issue by bug-debug-done** [Vishal-raj-1/Awesome-JavaScript-Projects#801]
I am a GSSOC'21 Participant. 

![Screenshot from 2021-04-03 15-16-16](https://user-images.githubusercontent.com/75927761/113474762-95d60f00-948f-11eb-80f3-050968437c0c.png)
![Screenshot from 2021-04-03 15-16-23](https://user-images.githubusercontent.com/75927761/113474763-966ea580-948f-11eb-9fa8-fc108ad77f70.png)
I will link the CSS correctly.
Please assign this to me.

**Comment by ridsuteri** [comment]
@bug-debug-done sorry both the issues are resolved in some other PRs ..kindly look for this issue in any other project or add any new project

**Comment by bug-debug-done** [comment]
Please check these projects @ridsuteri 
![Screenshot from 2021-04-07 11-16-49](https://user-images.githubusercontent.com/75927761/113818298-3597e380-9795-11eb-8992-a5ec8007ee98.png)
![Screenshot from 2021-04-07 11-18-22](https://user-images.githubusercontent.com/75927761/113818306-3761a700-9795-11eb-9f4e-8a25b25671e8.png)
![Screenshot from 2021-04-07 11-25-50](https://user-images.githubusercontent.com/75927761/113818309-37fa3d80-9795-11eb-91ff-f62092c6e865.png)
![Screenshot from 2021-04-07 11-28-09](https://user-images.githubusercontent.com/75927761/113818311-3892d400-9795-11eb-9ae0-1d2c3734b09a.png)
![Screenshot from 2021-04-07 11-31-33](https://user-images.githubusercontent.com/75927761/113818315-392b6a80-9795-11eb-9931-dc97267b09bf.png)
![Screenshot from 2021-04-07 11-33-11](https://user-images.githubusercontent.com/75927761/113818317-39c40100-9795-11eb-89fc-1fb3b827d67c.png)

**Comment by bug-debug-done** [comment]
@ridsuteri can yo please also have a look at these issues also  #787 #789 #790 and #792

**Comment by ridsuteri** [comment]
@bug-debug-done some of the projects from the above list are working properly,kindly check once again from the deployed site
and i guess there is issue with notes app hence i am assigning you the issue.

**Comment by ridsuteri** [comment]
> @ridsuteri can yo please also have a look at these issues also #787 #789 #790 and #792

done :)

**Comment by harshgupta20** [comment]
@bug-debug-done Any update? Kindly reply within 2 days or else i have to close this issue.

**Comment by bug-debug-done** [comment]
@harshgupta20 working on other PR for this repo

**Comment by harshgupta20** [comment]
@bug-debug-done Kindly link that PR with this issue.
