### ISSUE TITLE
Addition of SEARCH OPTION

### ISSUE THREAD

**Issue by bug-debug-done** [Vishal-raj-1/Awesome-JavaScript-Projects#802]
I am a GSSOC'21 Participant. 
I will add search option to the project page so that it will make it easy to find a project.

**Comment by harshgupta20** [comment]
Its a great thing to add. @bug-debug-done you can start working on that issue.

**Comment by Ankita297** [comment]
Can i work on this @harshgupta20 @ridsuteri @urvashi-code1255 @Vishal-raj-1 ?

**Comment by bug-debug-done** [comment]
@Ankita297 I am currently working on it there is some issue with my repo so it's taking time :)

**Comment by ridsuteri** [comment]
@bug-debug-done please try to come up with PR as soon as possible :)

**Comment by bug-debug-done** [comment]
@ridsuteri yes can you also check pr #1135

**Comment by bug-debug-done** [comment]
because I am not able to make multiple PRs on same project

**Comment by harshgupta20** [comment]
@bug-debug-done Thanks for contributing, your PR has been merged.

**Comment by Ankita297** [comment]
@harshgupta20  is search option is added ?

**Comment by bug-debug-done** [comment]
@harshgupta20 I did not made the pr merged yet
