### ISSUE TITLE
Add a  Chess Game Project

### ISSUE THREAD

**Issue by Mrinal81** [Vishal-raj-1/Awesome-JavaScript-Projects#803]
I am a GSSOC'21 Participant. I want to make Chess game .
Please assign me this issue..

**Comment by harshgupta20** [comment]
@Mrinal81 you can start working on that issue.
Kindly give the PR within a week or else we need assign it to some other participant.

**Comment by Mrinal81** [comment]
@harshgupta20 Please review the PR #1032 ..

Please review it..

**Comment by harshgupta20** [comment]
Merged :)
