### ISSUE TITLE
JS file not linked for some of the Project

### ISSUE THREAD

**Issue by bug-debug-done** [Vishal-raj-1/Awesome-JavaScript-Projects#804]
I am a GSSOC'21 Participant. 
I will link the js file for each of the projects. So that all the project will function properly. Please assign this to me.

**Comment by ridsuteri** [comment]
@bug-debug-done can you please share the screenshots/gifs of any such projects..

**Comment by bug-debug-done** [comment]
yes I'll share

**Comment by harshgupta20** [comment]
@bug-debug-done kindly reply within 2 days or else we need to close this issue.
