### ISSUE TITLE
Add a Motorcyle Game Project using Javascript

### ISSUE THREAD

**Issue by Mrinal81** [Vishal-raj-1/Awesome-JavaScript-Projects#805]
I am a GSSOC'21 Participant. I want to make motorcycle game.
Please assign me this issue..

**Comment by ridsuteri** [comment]
@Mrinal81 can you share the gif/screenshot of the project?

**Comment by harshgupta20** [comment]
@Mrinal81 kindly reply in 2 days or else we will to close this issue.

**Comment by Mrinal81** [comment]
@harshgupta20 @ridsuteri  please check the video whch i have attached.....


https://user-images.githubusercontent.com/76482022/114360060-3e702700-9b92-11eb-8acb-b81004c4e9d4.mp4

**Comment by harshgupta20** [comment]
@Mrinal81 you can start working on it.

**Comment by Mrinal81** [comment]
@harshgupta20  ok

**Comment by Mrinal81** [comment]
@harshgupta20 @ridsuteri kindly review the PR #1166 ....
