### ISSUE TITLE
Content of footer can be aligned at the center.

### ISSUE THREAD

**Issue by Fpj-11** [Vishal-raj-1/Awesome-JavaScript-Projects#810]
## Describe the bug
Content of footer can be aligned at the center to make it look more professional.
Kindly assign this issue to me.

**Comment by ridsuteri** [comment]
@Fpj-11 can you please share a screenshot/gif of how the site will look after your modifications

**Comment by Fpj-11** [comment]
Before
![Screenshot (2103)](https://user-images.githubusercontent.com/76908206/113972379-29288f00-9858-11eb-9854-83c2ad12bb82.png)

After
![Screenshot (2101)](https://user-images.githubusercontent.com/76908206/113972398-30e83380-9858-11eb-8b9a-dd77faaf7eac.png)

**Comment by ridsuteri** [comment]
@Fpj-11 PR #681 is adding some changes to footer let's wait for 2-3 days

**Comment by ridsuteri** [comment]
also @Fpj-11 PR #835 has already resolved the issue, and i think this issue is not available to work now 
so i am closing this issue :(

**Comment by Fpj-11** [comment]
Np :)
