### ISSUE TITLE
Exchange Rate Claculator Not Working

### ISSUE THREAD

**Issue by AnandBIT** [Vishal-raj-1/Awesome-JavaScript-Projects#811]
## Describe the bug
Excahnge Rate Calculator Not Working as Expected!

## To Reproduce
1.  Put in any value to exchange
2. After submitting, no value comes out as output.

## Expected behavior
Exchange value should come as the user presses **Enter ** key

## Environment (please complete the following information):
 - OS: Ubuntu 20.04.1
 - Browser: Brave Browser v89.1.22.70

**Comment by SilverGraph** [comment]
I have already addressed this in issue #650 
The bug was that the CSS and JS files were not linked properly.

**Comment by AnandBIT** [comment]
Ok, then I'm closing this issue!
