### ISSUE TITLE
Bug in handling Click event of LocalStorage webpage

### ISSUE THREAD

**Issue by AnandBIT** [Vishal-raj-1/Awesome-JavaScript-Projects#812]
## Describe the bug
Click event is not properly handled, due to which checkbox is also not working

## To Reproduce
1. Just input an item to be stored in LocalStorage
2. After pressing enter, try to mark the checkbox, you'll find that it is not working as expected.
3. Also, if we click anywhere on screen, the fish logo vibrates, which leads to a bad UX

## Expected behavior
Checkbox should work as it should be and clicking anywhere on screen vibrates the fish logo, which needs to be changed.
There should be a delete option, which is not present now!

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Ubuntu 20.04.1
 - Browser: Brave Browser v89.1.22.70

**Comment by harshgupta20** [comment]
@AnandBIT can you please give some more info about it, by putting the screenshot or video so that we can see it. Kindly reply within 2 days or I have to close this.
