### ISSUE TITLE
adding a todo app using javascript

### ISSUE THREAD

**Issue by anshika208** [Vishal-raj-1/Awesome-JavaScript-Projects#815]
adding a todo app using javascript in which users can add the work along with the deadline and they will recieve reminder of the deadlines and medicine timetables with appropriate notifications.
cotibution regarding  **gssoc21**.
@harshgupta20 can i work on this?

**Comment by vedant-jain03** [comment]
I have already did this project I want to work on this issue.

**Comment by 991rajat** [comment]
It's already present in the Awesome JS. If you want to improve upon it please create a issue regarding that. Will be to happy to assign you.
