### ISSUE TITLE
symbols visibility in tic tac toe game

### ISSUE THREAD

**Issue by lakshita15** [Vishal-raj-1/Awesome-JavaScript-Projects#816]
## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by lakshita15** [comment]
the O & X symbols are not visible on clicking . Please assign me this issue.

**Comment by lakshita15** [comment]
@ridsuteri @991rajat @Vishal-raj-1

**Comment by lakshita15** [comment]
@ridsuteri @harshgupta20 @Vishal-raj-1  plss aasign this to me🙂🙂

**Comment by ridsuteri** [comment]
@lakshita15 i guess the symbols are pretty visible... , can you support your issue with any screenshot/gifs..?

**Comment by lakshita15** [comment]
I checked it now . It’s working now When i tested maybe  there was issue at
that time. The thing is that the symbols are coming after few seconds ....

**Comment by ridsuteri** [comment]
ok @lakshita15 ,so i am closing this issue now :)
