### ISSUE TITLE
wanted to updated the look of digital clock of issue #105

### ISSUE THREAD

**Issue by iamabhii1** [Vishal-raj-1/Awesome-JavaScript-Projects#820]
Hi , i wanted to update the design look of digital clock of isssue(closed) #105 
I think the CSS part is not correctly done .so, i just wanted to update that part.
kindly assign this me .
contribution regarding _**_gssoc21_**_

**Comment by 991rajat** [comment]
Hey @iamabhii1 You can work it. Update us within 2 days. If not will be assigned to someone else.

**Comment by iamabhii1** [comment]
ok
