### ISSUE TITLE
Tortoise and pokemon collision game in javascript

### ISSUE THREAD

**Issue by priyanka001tech** [Vishal-raj-1/Awesome-JavaScript-Projects#821]
It is a very simple game where the tortoise and a pokemon character is running towards each other and one have to jump high to save from collision to each other.

Good quality of graphics and animation is there

I would like to code it as a gssoc participant

It is the base structure. Animation is going to be added 

![Screenshot (271)](https://user-images.githubusercontent.com/70838173/113503447-88805980-954f-11eb-8eb9-2138c5889867.png)

**Comment by priyanka001tech** [comment]
http://127.0.0.1:5500/

@991rajat this is not yet completed .The work is still going on.

**Comment by harshgupta20** [comment]
@priyanka001tech Similar game already exist in the projects.
