### ISSUE TITLE
Enhancement of Calendar

### ISSUE THREAD

**Issue by AnshikaAgrawal5501** [Vishal-raj-1/Awesome-JavaScript-Projects#834]
## Is your feature request related to a problem? Please describe.
No, it's not a problem. I would like to enhance the look of the calendar project.
## Describe the solution you'd like
- Add bootstrap to the input fields and button.
- Make page navigation arrows small.
- Vertically align the content to the center.
- Enhance the look of the calendar.

Right now it looks like this.
![Untitled](https://user-images.githubusercontent.com/56653257/113520308-c1501b00-95af-11eb-96cc-74e2917cfb17.png)

## Additional context
I am a GSSOC'21 participant, please assign this issue to me.

@Vishal-raj-1 @urvashi-code1255 @ridsuteri @991rajat @harshgupta20

**Comment by AnshikaAgrawal5501** [comment]
Thank you so much @ridsuteri for assigning me the issue. I will work on it and raise the pr very soon.

**Comment by ridsuteri** [comment]
great @AnshikaAgrawal5501 go ahead :)
