### ISSUE TITLE
Add Typing Speed project/game

### ISSUE THREAD

**Issue by nidhivanjare** [Vishal-raj-1/Awesome-JavaScript-Projects#839]
I want to add a new js project where the player will type the text that is generated randomly on the screen. 
This will test his typing skills and speed. 

Something like this :

<img width="1440" alt="Screenshot 2021-04-04 at 8 16 39 PM" src="https://user-images.githubusercontent.com/55665104/113512532-b29f3f00-9582-11eb-8c28-029c20d462db.png">

I am a GSSOC'21 Participant, I would like to work on this issue.

**Comment by ridsuteri** [comment]
sorry @nidhivanjare similar issue is already assigned :(
so you can't work on the same now
i am also closing your PR #877 corrosponding to it :(

**Comment by nidhivanjare** [comment]
Hey 
The project is still not visible on the page 
Because the script.js code was not added 
I need to add that in for the code to be visible.
