### ISSUE TITLE
JavaScript drum-kit

### ISSUE THREAD

**Issue by Abhijay007** [Vishal-raj-1/Awesome-JavaScript-Projects#84]
vanilla javascript project:  'javascript drum kit'

![drum kit](https://user-images.githubusercontent.com/64387054/107920977-cc190700-6f93-11eb-80c6-8de7dcfff681.gif)

I made this project during 30 days of vanilla javascript challenge by WES BOS. 

live preview link: https://agitated-mccarthy-b9d840.netlify.app/

**Comment by urvashi-code1255** [comment]
Its Looking great!! @Abhijay007 You can go for it!!

**Comment by Abhijay007** [comment]
> Its Looking great!! @Abhijay007 You can go for it!!
> 
> Are you participating in crosswoc or gssoc?

Gssoc.
