### ISSUE TITLE
Website Logo

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#85]
Design logos for the website!!

Show the samples here before making a PR!!

**Comment by Aayushi-Mittal** [comment]
Can I work on this issue?

**Comment by urvashi-code1255** [comment]
Sure @Aayushi-Mittal Go for it!!

**Comment by Aayushi-Mittal** [comment]
These are some samples. Hope you like it!
## Design-1
<img src="https://user-images.githubusercontent.com/60853067/107980677-b2ed7600-6fe6-11eb-8fda-ead88fa5de2c.png" height=40% width=40%>

## Design-2
<img src="https://user-images.githubusercontent.com/60853067/107980692-b7199380-6fe6-11eb-916d-f23e72125cfd.png" height=40% width=40%>

**Comment by kanishkaa24** [comment]
Hey, Can I work on this?

**Comment by urvashi-code1255** [comment]
Hey @kanishkaa24 you can go for it!

**Comment by urvashi-code1255** [comment]
> These are some samples. Hope you like it!

Hey @Aayushi-Mittal I like them! Could you please try them out on navbar?

**Comment by kanishkaa24** [comment]
![Logo (3)](https://user-images.githubusercontent.com/71253790/108318554-07127900-71e6-11eb-98a5-5126e5faf499.png)
![Logo (4)](https://user-images.githubusercontent.com/71253790/108318558-08dc3c80-71e6-11eb-8709-068b18f1bfbb.png)
Mam these are a few samples.

**Comment by urvashi-code1255** [comment]
Hey @kanishkaa24 I like the second one very much!! You can try it out on website navbar!

**Comment by Vishal-raj-1** [comment]
Hey @Aayushi-Mittal I think Design - 3 would look nice without that background at about section. What do you say ? We can replace about section image with design-3. And on scrolling we can give this effect as shown here.

![about](https://user-images.githubusercontent.com/59874304/108335527-13540180-71f9-11eb-9319-734587fa465e.JPG)


@kanishkaa24 As logo We should focus on `Awesome JavaScript Projects` not only on javascript, isn't it ? If we replace JavaScript to Awesome JavaScript Projects in second image and change the background according to navbar. Then it would be better. You can try it out !!

**Comment by kanishkaa24** [comment]
Sure @urvashi-code1255 Mam and @Vishal-raj-1 Sir. I will change the title and adjust the background and try it on navbar.

**Comment by kanishkaa24** [comment]
It is not visible on the header because of the small size.

**Comment by kanishkaa24** [comment]
![Logo (7)](https://user-images.githubusercontent.com/71253790/108531180-6bbff780-72fc-11eb-8fd9-233b630ac33d.png)

**Comment by Aayushi-Mittal** [comment]
Agree @Vishal-raj-1. It is a good idea.

**Comment by Vishal-raj-1** [comment]
@kanishkaa24 LGTM !!

**Comment by kanishkaa24** [comment]
> @kanishkaa24 LGTM !!

Shall I make a PR?

**Comment by kanishkaa24** [comment]
@Vishal-raj-1 @urvashi-code1255 
Shall I make a PR?

**Comment by harshgupta20** [comment]
@kanishkaa24 Yes you can send the PR :)

**Comment by harshgupta20** [comment]
@kanishkaa24 Kindly reply within 2 days or I have to close this.

**Comment by kanishkaa24** [comment]
@harshgupta20 
I will make the PR today. I was not well so I could not respond.
