### ISSUE TITLE
Update Paint Clone Project

### ISSUE THREAD

**Issue by K-jais** [Vishal-raj-1/Awesome-JavaScript-Projects#852]
This Paint clone will be similar to the Paint 3d which is there on the desktop. Adding the functionality of the brush, eraser, file save, color change, etc.

**Comment by K-jais** [comment]
Sir, please look into this.

**Comment by K-jais** [comment]
Please @ridsuteri review this issue.

**Comment by ridsuteri** [comment]
@K-jais there is already a similar project in the repo with the name of Drawing app.
is your project different from that one?
and if possible kindly share screenshot/gif of your project

**Comment by K-jais** [comment]
Its working video,


https://user-images.githubusercontent.com/75881393/113969601-e44e2980-9852-11eb-904a-a8c1f1e180ce.mp4

**Comment by K-jais** [comment]
Once see this @ridsuteri

**Comment by ridsuteri** [comment]
@K-jais looks great ! but since a drawing app already exists , it would be better if you do the improvements to existing project rather than adding a similar one

**Comment by K-jais** [comment]
> @K-jais looks great ! but since a drawing app already exists , it would be better if you do the improvements to existing project rather than adding a similar one

Ok sir I will add the necessary things in the existence project.

**Comment by ridsuteri** [comment]
@K-jais ok great ,i am assigning you the issue now.
also update the issue heading
