### ISSUE TITLE
Add Drag Drop To-Do List Project

### ISSUE THREAD

**Issue by K-jais** [Vishal-raj-1/Awesome-JavaScript-Projects#853]
This will be a to-do list project which has the functionality to save the person's work and he can drag and drop the particular work from one table of things to another.

**Comment by sumitaccess007** [comment]
I am okay to pick this project, if you can assign this to me.

**Comment by K-jais** [comment]
Sir, please look into this.

**Comment by K-jais** [comment]
Please @ridsuteri review this issue.

**Comment by ridsuteri** [comment]
sounds good @K-jais ! go ahead with it

**Comment by ridsuteri** [comment]
@sumitaccess007 the projects are assigned on first come first served basis, wait for few days if @K-jais doesn't comes up with a PR, we will transfer the issue to you
