### ISSUE TITLE
Responsive Projects

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [Vishal-raj-1/Awesome-JavaScript-Projects#854]
Can I make the following projects responsive
Analog clock 
Password generator
Flip cards
Study timer
Progress Bar

[GSSOC'21]

Please assign me this issue
@urvashi-code1255 @Vishal-raj-1 @991rajat @harshgupta20 @ridsuteri

**Comment by ridsuteri** [comment]
@Bhavya-Sehgal all the issues are resolved now , i am closing this issue now :)

**Comment by Bhavya-Sehgal** [comment]
> @Bhavya-Sehgal all the issues are resolved now , i am closing this issue now :)

Please keep it open as I am working on one more project i.e Image Editor , after that you may close.

**Comment by ridsuteri** [comment]
ohk @Bhavya-Sehgal :)
