### ISSUE TITLE
Adding a Memory Game.

### ISSUE THREAD

**Issue by riasenpai** [Vishal-raj-1/Awesome-JavaScript-Projects#859]
I am making a Memory Game which will help to improve your memory in a fun way using JS!

Please Assign me under GSSOC '21.

Please assign me @ridsuteri  @harshgupta20  @urvashi-code1255  @Vishal-raj-1

**Comment by ridsuteri** [comment]
sorry @riasenpai ,this project is already assigned to someone.., so try to add any other awesome project or improve any existing one
