### ISSUE TITLE
Website Favicon

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#86]
Design favicons for the website and show the demo here before making  a PR!!

**Comment by khushi935** [comment]
I want to work on this.

**Comment by urvashi-code1255** [comment]
@khushi935 go for it!

**Comment by kanishkaa24** [comment]
Hey, Can I work on this ?

**Comment by urvashi-code1255** [comment]
@kanishkaa24 Sure go for it!

**Comment by kanishkaa24** [comment]
![9](https://user-images.githubusercontent.com/71253790/108326349-24e4db80-71f0-11eb-92f9-5d21bbb11d15.png)
![10](https://user-images.githubusercontent.com/71253790/108326357-26ae9f00-71f0-11eb-8802-bd4dc6c62cc9.png)
![11](https://user-images.githubusercontent.com/71253790/108326361-26ae9f00-71f0-11eb-84b8-b0f066699e0e.png)
![12](https://user-images.githubusercontent.com/71253790/108326364-27473580-71f0-11eb-8dfc-c9e119565ead.png)
![13](https://user-images.githubusercontent.com/71253790/108326366-27dfcc00-71f0-11eb-8568-0073c00ef76f.png)
![14](https://user-images.githubusercontent.com/71253790/108326369-28786280-71f0-11eb-9aed-7605ea419475.png)
@urvashi-code1255 Mam please review these. These are all transparent.

**Comment by Vishal-raj-1** [comment]
@kanishkaa24 I am not sure, but for now we can use third one !! You raise the PR for it.
