### ISSUE TITLE
Footer Updation

### ISSUE THREAD

**Issue by urvashi-code1255** [Vishal-raj-1/Awesome-JavaScript-Projects#87]
Add github repo link to the footer using github icon.

**Comment by nilisha-jais** [comment]
I want to work on it

**Comment by urvashi-code1255** [comment]
Sure @nilisha-jais Go for it!! Also, tell about the programs you are participating in

**Comment by nilisha-jais** [comment]
I would like to work on it as a part of cwoc

**Comment by asimaries** [comment]
I would like to work on it

**Comment by urvashi-code1255** [comment]
> I would like to work on it

Hi @

**Comment by supzi-del** [comment]
Can I work on this even if I'm not assigned?

**Comment by asimaries** [comment]
> > I would like to work on it
> 
> Hi @asimaries This issue is already assigned so please look at other issues in this repository!

I have completed the issue  please just check it once

**Comment by asimaries** [comment]
> Add github repo link to the footer using github icon.
I have completed it just checkout
Ma'am thank you

**Comment by urvashi-code1255** [comment]
> Can I work on this even if I'm not assigned?

No @supzi-del Find a issue which is not assigned to anyone!

**Comment by raveena69** [comment]
I would like to work on this issue.

**Comment by ambivert-sam** [comment]
Hey!!
@urvashi-code1255  I am participate at GSSoC'21 I would like to work with this issue
Would you please assign it to me?
