### ISSUE TITLE
Styling Problems in mobile-sized devices.

### ISSUE THREAD

**Issue by AshishRajIITI** [Vishal-raj-1/Awesome-JavaScript-Projects#870]
## Describe the bug

https://user-images.githubusercontent.com/67483270/113777881-4f133e00-9749-11eb-8dad-aed5bd17f659.mp4

![WhatsApp Image 2021-04-07 at 02 24 40 (1)](https://user-images.githubusercontent.com/67483270/113777894-520e2e80-9749-11eb-8f87-bf443d620a4f.jpeg)
![WhatsApp Image 2021-04-07 at 02 24 40](https://user-images.githubusercontent.com/67483270/113777895-520e2e80-9749-11eb-9e71-8c3c1d351faf.jpeg)

## To Reproduce
1. Open the hosted website on a smartphone-sized device.

## Expected behavior
The sidebar that includes social-media icons has problems in the styling part. The vertical bar hides out the content present behind it making the website contents unreadable at times. One solution is to dynamically change the opacity of the social media icon bar(make its opacity larger on focussing) etc. A proper margin between the Header and the main content should be present. Same thing with the footer. The top button should be better placed.

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Android 10
 - Browser: Google Chrome

## Additional context
I have attached two screenshots and a video to explain the issue.

**Comment by ridsuteri** [comment]
@AshishRajIITI go ahead with it :)

**Comment by harshgupta20** [comment]
@AshishRajIITI Any update? Kindly reply within 2 days or else i have to close this issue.

**Comment by harshgupta20** [comment]
Issue has been resolved : )
