### ISSUE TITLE
Links are not connected to the social media handles on the homepage.[ggsoc21]

### ISSUE THREAD

**Issue by Deeksha-Rawat** [Vishal-raj-1/Awesome-JavaScript-Projects#871]

**Comment by Deeksha-Rawat** [comment]
Thank you for assigning me this issue.
But I need your help regarding this. I don't know to which accounts or links I need to link those social media handles
Likewise the twitter, youtube, google whose account I need to link.
Can you please provide me with the links so that I can use them and raise the PR for the same.
Thank you

**Comment by harshgupta20** [comment]
@Deeksha-Rawat Right now, you can give the link of home pages of these social media website like youtube.com, but make sure it should be open in new tab when user clicks on it.

**Comment by Deeksha-Rawat** [comment]
ok sure !!
