### ISSUE TITLE
Speech to text

### ISSUE THREAD

**Issue by Amit366** [Vishal-raj-1/Awesome-JavaScript-Projects#872]
## Is your feature request related to a problem? Please describe.
No its not a problem. I am a GSSOC participant and would like to add speech to text converter using JavaScript. 
## Describe the solution you'd like
I will be using Js and HTML.

**Comment by ridsuteri** [comment]
@Amit366 image to speech or text to speech?

**Comment by Amit366** [comment]
Text to speech @ridsuteri

**Comment by Amit366** [comment]
@ridsuteri since a similar project is present so I will do speech to text

**Comment by ridsuteri** [comment]
great @Amit366 go ahead
