### ISSUE TITLE
Car Running Project using Html,Css,Javascript 

### ISSUE THREAD

**Issue by Mrinal81** [Vishal-raj-1/Awesome-JavaScript-Projects#874]
I am a GSSOC'21 Participant. I want to make car running project.
@ridsuteri please have a look on this issue.
Please assign me this issue.

**Comment by ridsuteri** [comment]
@Mrinal81 similar PR #554 is open ,is your project different from this one?
and if  you can share a gif/screenshot of your project ?

**Comment by Mrinal81** [comment]
@ridsuteri  
![Screenshot from 2021-04-07 14-37-12](https://user-images.githubusercontent.com/76482022/113841011-ec548d80-97ae-11eb-8dd2-6a740496c33e.png)
Please have a look.........

https://user-images.githubusercontent.com/76482022/113840924-d646cd00-97ae-11eb-9ec2-42a3550fb7d9.mp4

**Comment by ridsuteri** [comment]
@Mrinal81 ok go ahead with it :)

**Comment by Mrinal81** [comment]
@ridsuteri  Thanks  for assign..

**Comment by Mrinal81** [comment]
@ridsuteri please have a look on issue#888..

**Comment by Mrinal81** [comment]
@ridsuteri  i made a pull request #953 . Please review it....
