### ISSUE TITLE
[BUG] [GSSOC' 21] Footer not fixed at the bottom

### ISSUE THREAD

**Issue by Aditya201551** [Vishal-raj-1/Awesome-JavaScript-Projects#882]
## Describe the bug
- In the index page the footer is not fixed at the bottom of the page i.e the footer is scrollable along with the page

## To Reproduce
1.  Go to the index.page
2.  Scroll down
3.  See the footer

## Expected behavior
- Fixed footer at the bottom of the site

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Windows 10 pro
 - Browser: Google Chrome, Edge, Tor, FireFox

![Screenshot (73)](https://user-images.githubusercontent.com/32588231/113902572-a9fe7100-97ed-11eb-8023-363196cd375b.png)

## Additional context
@Vishal-raj-1 @ridsuteri

**Comment by ridsuteri** [comment]
@Aditya201551 PR #681 is about to fix the issue.
kindly wait for 2-3 days..

**Comment by Aditya201551** [comment]
@ridsuteri sure!

**Comment by Aditya201551** [comment]
@ridsuteri ig its been 4 days now 😅

**Comment by ridsuteri** [comment]
@Aditya201551 ok go ahead with it :)
