### ISSUE TITLE
[BUG] [GSSOC' 21] Message area expanding more than its parent box

### ISSUE THREAD

**Issue by Aditya201551** [Vishal-raj-1/Awesome-JavaScript-Projects#883]
## Describe the bug
- In contact us section the message(textarea) expands more than the size of its parent box making it look not great

## To Reproduce
1.  Goto the site
2.  Click on contact us button
3.  Goto the message area
4. Expand the message area the see the bug

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS: Windows 10 pro
 - Browser: Google Chrome, Tor, Edge, FireFox

![Screenshot (74)](https://user-images.githubusercontent.com/32588231/113903969-2b0a3800-97ef-11eb-8eff-4b346ffa8260.png)

## Additional context
@Vishal-raj-1 @ridsuteri

**Comment by ridsuteri** [comment]
@Aditya201551 message box is looking fine 
![Screenshot (19)](https://user-images.githubusercontent.com/59795822/113971091-b8807300-9855-11eb-9d0d-d4c2d5072315.png)

check once again please :)

**Comment by Aditya201551** [comment]
@ridsuteri sir the box is expandable so if you expand the textarea more than the parent div the textarea gets out of the  parent div, the video is provided below for reference: 


https://user-images.githubusercontent.com/32588231/113972082-a1428500-9857-11eb-8a6f-347c58f25281.mp4

**Comment by ridsuteri** [comment]
oh ohk @Aditya201551 go ahead with it

**Comment by Aditya201551** [comment]
Sure starting the work now!
