### ISSUE TITLE
Meme Soundboard using html, css and javascript

### ISSUE THREAD

**Issue by akshay399** [Vishal-raj-1/Awesome-JavaScript-Projects#885]
I will make a meme soundboard that will play various meme sounds on keyboard key press.

![IMG-20210407-WA0024.jpg](https://user-images.githubusercontent.com/55823965/113910673-baffb000-97f6-11eb-9358-f31c555ee86c.jpg)

**Comment by akshay399** [comment]
I am a gssoc member, please assign me this issue @ridsuteri

**Comment by ridsuteri** [comment]
seems great @akshay399 go ahead

**Comment by akshay399** [comment]
> seems great @akshay399 go ahead

i made a [PR](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/904) please review it, thank you :)
