### ISSUE TITLE
Create a Music App with JavaScript

### ISSUE THREAD

**Issue by WebVishal** [Vishal-raj-1/Awesome-JavaScript-Projects#887]
I have developed a Music app like JioSaavn
Please @991rajat  and @ Vishal-raj-1 assign me for this project.
I'm a GSSOC'21 participant and wants to contribute to this project

**Comment by harshgupta20** [comment]
@WebVishal Any update? Kindly reply within 2 days or else i have to close this issue.

**Comment by WebVishal** [comment]
@harshgupta20 hi, It is almost done, I just have to add some CSS. I will be creating PR by tomorrow.

**Comment by harshgupta20** [comment]
Thanks for contributing, PR has been merged : )
