### ISSUE TITLE
Restaurant Website with html,css,Javascript 

### ISSUE THREAD

**Issue by Mrinal81** [Vishal-raj-1/Awesome-JavaScript-Projects#888]
I am GSSOC'21 Participant. I will make a restaurant website with html,css,Javascript. 

Please assign me this issue..

**Comment by ridsuteri** [comment]
sounds great! @Mrinal81 go ahead with it

**Comment by anushka-srivastava22** [comment]
I am a gssoc participant Anushka. I have a good experience in html css and js  of  11 months. I will surely able to complete it within few days. Therefore I request you to kindly assign me this issue.

**Comment by Mrinal81** [comment]
@ridsuteri  @harshgupta20 Kindly review the PR #1254 .....

**Comment by ridsuteri** [comment]
sorry @anushka-srivastava22 , @Mrinal81 has submitted her PR and it got merged ! hence i am closing the issue :)
