### ISSUE TITLE
Some projects have been added twice on the website

### ISSUE THREAD

**Issue by prachibansal2000** [Vishal-raj-1/Awesome-JavaScript-Projects#889]
## Describe the bug
Some projects have been added twice on the website

## To Reproduce
1. Changes in script.js file

## Environment (please complete the following information):
 - OS: Windows
 - Browser: Google Chrome

## Additional context
Here the particle js project is shown twice
![image](https://user-images.githubusercontent.com/56162563/113983877-161dbb00-9868-11eb-8ade-8548b1245c61.png)

The same is with the animated minion eye project.

**Comment by prachibansal2000** [comment]
Pls assign so that i can start working :)

**Comment by harshgupta20** [comment]
@prachibansal2000 you can work on this issue.
