### ISSUE TITLE
Flash Card Generator 

### ISSUE THREAD

**Issue by nidhivanjare** [Vishal-raj-1/Awesome-JavaScript-Projects#890]
I am a GSSOC'21 participant and I want to work on this issue. 

## Describe the solution you'd like
I want to add to the project to generate flashcards that are used for memorizing things. 
I will be done using HTML, CSS, and JS.

**Comment by harshgupta20** [comment]
Hi @nidhivanjare This project already exist you can improve that project if you want to, but please tell what are changes you are gonna make?

(Note: Reply within 2 days else we need to close this issue. )

**Comment by nidhivanjare** [comment]
yes, I just reviewed that project. 
Looks like everything I had to do.
I try and make another issue.

**Comment by harshgupta20** [comment]
Since this issue already exist,I am closing that issue.
