### ISSUE TITLE
No error page 

### ISSUE THREAD

**Issue by anjali1102** [Vishal-raj-1/Awesome-JavaScript-Projects#891]
This is the current displayed weird page if the some error in URL
![Page-not-found-·-GitHub-Pages](https://user-images.githubusercontent.com/56559378/114010834-2cd10b80-9882-11eb-916c-dc7ea08a1f21.png)

Need to create beautiful error page.

**Comment by anjali1102** [comment]
I will complete this task. Assign to me

**Comment by anjali1102** [comment]
I am participant of gssoc . Kindly label

**Comment by harshgupta20** [comment]
Hi @anjali1102 can you give the detail about the tech you are gonna use, Because you have to use JS only.

(Note: Reply within 2 days else we need to close this issue. )

**Comment by anjali1102** [comment]
Yes , sure I will

**Comment by anjali1102** [comment]
@harshgupta20  kindly add gssoc label , level

**Comment by harshgupta20** [comment]
Hi @anjali1102, you are good to go.

**Comment by harshgupta20** [comment]
Kindly give PR within a week.
