### ISSUE TITLE
Rotating 3D Cube using Html Css

### ISSUE THREAD

**Issue by micky2001** [Vishal-raj-1/Awesome-JavaScript-Projects#898]

**Comment by supriyagahoi** [comment]
Hi, I want to work on this issue. I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : supriya gahoi
Discord Tag: #2406

**Comment by harshgupta20** [comment]
@micky2001 Kindly specify what changes you gonna make in this issue, is it only about html and css  ?? , since it doesn't have any codebase with JS so if you didn't reply within two day then we need to close this issue.

**Comment by harshgupta20** [comment]
@supriyagahoi Please give us some details about it, if you are willing to work on this.
