### ISSUE TITLE
Text Generator

### ISSUE THREAD

**Issue by TidbitsJS** [Vishal-raj-1/Awesome-JavaScript-Projects#90]
## Tired of boring lorem ipsum?
Ever ran out of words or tired enough of having same lorem ipsum all over the website. Yess??

## Proposal
Here is a thing for you, a text generator in JS to help you generate random text paragraphs

## Event 
Participating as a part of GSSOC

## Demo
![demo](https://s2.gifyu.com/images/cinnamon-20210215-4.gif)

**Comment by TidbitsJS** [comment]
Assign this to me & I will get it done!

**Comment by urvashi-code1255** [comment]
@TidbitsJS I like it!! Go for it :)
