### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [Vishal-raj-1/Awesome-JavaScript-Projects#92]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

Please assign it to me as a part of Cross Woc.

**Comment by urvashi-code1255** [comment]
@muthuannamalai12 Sure go for it!!

**Comment by muthuannamalai12** [comment]
@urvashi-code1255  We need a code of conduct file for the custom message shown by the welcome bot. So I have created a new issue for it. Kindly assign me that issue.
