### ISSUE TITLE
Armstrong Number check - Improvement in UI.

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [Vishal-raj-1/Awesome-JavaScript-Projects#925]
I want to improve the UI and make this projects responsive.

Screenshot:

![an-x](https://user-images.githubusercontent.com/66208607/114262411-75f99a80-99fd-11eb-84b4-316c51e58ecd.png)

[GSSOC'21]

Please assign me this issue
@urvashi-code1255 @Vishal-raj-1 @991rajat @harshgupta20 @ridsuteri

**Comment by Shivangi-ch** [comment]
Please assign this to me.

**Comment by harshgupta20** [comment]
Hi @Shivangi-ch you can start working on that issue.
