### ISSUE TITLE
Add flipping cards project

### ISSUE THREAD

**Issue by Vedant-Rahane** [Vishal-raj-1/Awesome-JavaScript-Projects#931]
I am Vedant Rahane, GSSOC'21 participant.
I would like to add this Javascript based flipping cards project.

Something like this -

![flip-card](https://user-images.githubusercontent.com/71424483/114266042-b19e5f80-9a11-11eb-82dd-9c185ac9fabe.gif)

Please @ridsuteri @991rajat @urvashi-code1255 assign me this.

**Comment by harshgupta20** [comment]
Hi @Vedant-Rahane you can start working on that issue, Kindly give the PR within 7 days or we will assign it to some else.

**Comment by harshgupta20** [comment]
Hi @Vedant-Rahane i saw that this project already exist. Since it already exist i need to close this issue. If want to improve the existing project then plz let me know and change the "issue title". 

Kindly reply within 2 days or else we need to close this issue.

**Comment by Vedant-Rahane** [comment]
@harshgupta20 This project is not repeated, I have checked all projects there is one project in which card get flipped on click. That is for question and answers. In this project cards get automatically flipped.

**Comment by harshgupta20** [comment]
@Vedant-Rahane Since this project already existed and by just changing the onClick method to auto doesn't make it different.
You can improve the existing one.

**Comment by Vedant-Rahane** [comment]
Okay @harshgupta20 , I am closing this issue.
