### ISSUE TITLE
Upgradation in Movie app Project

### ISSUE THREAD

**Issue by Panic100** [Vishal-raj-1/Awesome-JavaScript-Projects#938]
## Is your feature request related to a problem? Please describe.
No its not a problem. I will enhance the look of welcome page, orientation of search bar.

## Additional context
I want to change its position and make it attractive.
![Screenshot (253)_LI](https://user-images.githubusercontent.com/73658735/114282532-200b0e00-9a62-11eb-8643-d188ed28e51b.jpg)

**Comment by harshgupta20** [comment]
This issue already has been solved, by other participant, you can check and work for more issues on issue panel.
