### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by muthuannamalai12** [Vishal-raj-1/Awesome-JavaScript-Projects#94]
I would like to add code of conduct file as code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Cross-woc. Kindly assign it to me.

**Comment by urvashi-code1255** [comment]
@muthuannamalai12 There was an existing assigned issue for code_of_conduct file. which I have merged just now! you can check that!

And feel free to close this issue

**Comment by muthuannamalai12** [comment]
> @muthuannamalai12 There was an existing assigned issue for code_of_conduct file. which I have merged just now! you can check that!
> 
> And feel free to close this issue

Ok Thank You I will close it.
