### ISSUE TITLE
Add github actions to auto-comment after successful merge of the pr.

### ISSUE THREAD

**Issue by AB-san** [Vishal-raj-1/Awesome-JavaScript-Projects#941]
![image](https://user-images.githubusercontent.com/71064674/114289764-0e445d80-9a98-11eb-86e9-16ae4e87bf5c.png)

I noticed @ridsuteri commenting this after every successful approval of the changes of a pr . Would you like to have a bot to auto-comment after you approve the changes or merge the pr in order to save time?

**Comment by ridsuteri** [comment]
sounds great @AB-san ! go ahead with it :)

**Comment by AB-san** [comment]
> sounds great @AB-san ! go ahead with it :)

Hello @ridsuteri done with coding part , I wanted a small favour-
Can you please mention the username of all the mentors for this project , who dont want a thank you message after their pr is merged.

**Comment by ridsuteri** [comment]
@AB-san consider all of us i.e @ridsuteri @991rajat @harshgupta20 @urvashi-code1255 @Vishal-raj-1

**Comment by AB-san** [comment]
> @AB-san consider all of us i.e @ridsuteri @991rajat @harshgupta20 @urvashi-code1255 @Vishal-raj-1

Okay got it

**Comment by AB-san** [comment]
Sorry to say but i found that the resources that i was trying to use isnt working well so , I needed some more time!! is there any deadline?

**Comment by ridsuteri** [comment]
@AB-san oh ohk ! try to get this issue done as soon as possible

**Comment by AB-san** [comment]
> @AB-san oh ohk ! try to get this issue done as soon as possible 

Sure!!!
