### ISSUE TITLE
Guess the word game in js 

### ISSUE THREAD

**Issue by Archna29** [Vishal-raj-1/Awesome-JavaScript-Projects#95]

**Comment by Archna29** [comment]
I would like to work on this issue please assign it toe

**Comment by Archna29** [comment]
I want to work on this issue please assign it to me.

**Comment by urvashi-code1255** [comment]
@Archna29 go for it!!

**Comment by LazySukanta** [comment]
I would like to contribute, Assign me for this project as I am GSSOC (participate)2021.

**Comment by urvashi-code1255** [comment]
Go for it @LazySukanta

**Comment by harshgupta20** [comment]
@Archna29 Any Update ? Kindly reply within 2 days or I have to close this.
