### ISSUE TITLE
Footer Arrangement 

### ISSUE THREAD

**Issue by anhushree** [Vishal-raj-1/Awesome-JavaScript-Projects#952]
## Describe the bug
There is no space between the human image and the footer. And there is extra space after the footer 

## To Reproduce
1.Visit the website 

 

## Expected behavior
The Footer should be aligned in such a way that 
Space before the footer should be equal to space after the footer and there should be no extra space after the footer.

![image](https://user-images.githubusercontent.com/56672958/114342845-42904a80-9b7a-11eb-9b7c-df23a0d61d63.png)

**Comment by anhushree** [comment]
@Ayushjain2205 Could you please look into this issue? May I work on this issue?

**Comment by harshgupta20** [comment]
This issue has been resolved : )
