### ISSUE TITLE
expense tracker

### ISSUE THREAD

**Issue by Amit366** [Vishal-raj-1/Awesome-JavaScript-Projects#954]
## Is your feature request related to a problem? Please describe.
No its not a problem. I want to add an expense tracker feature. I am a GSSOC participant. 
## Describe the solution you'd like
I will work using Javascript and html

## Additional context
Add any other context about the feature request here.

**Comment by Amit366** [comment]
@ridsuteri please assign it to me

**Comment by Amit366** [comment]
@ridsuteri please assign this to me

**Comment by ridsuteri** [comment]
@Amit366 this project is already present in the repository :(

**Comment by Amit366** [comment]
@ridsuteri there are 178 issues opened and there are some participants who have 6 to 7 issues but aren't able to send a PR. Now from where can I work on a new project. Can you suggest any idea on which I can work.

**Comment by ridsuteri** [comment]
see @Amit366 participants are coming up with new issues daily !
that clearly means there are still lots of project to be added in the repo .. also about participants having 6-6 issues , we will be asking them about their progress after certain days  and if they are unable to get the projects done in certain time ..those project will be assigned to anyone else ...
