### ISSUE TITLE
Want to make header/banner full size 

### ISSUE THREAD

**Issue by vedant-jain03** [Vishal-raj-1/Awesome-JavaScript-Projects#955]
## Describe the bug
Want to make header/banner full size 

## To Reproduce
1. I will make banner 100vh
2. Will align header according to that
3. Will also give this features to other page as well

![bandicam 2021-04-12 14-14-15-899](https://user-images.githubusercontent.com/76901313/114367074-b0983a00-9b99-11eb-8a1f-11c34cdc1eb9.jpg)

## Environment (please complete the following information):
 - Browser:

**Comment by vedant-jain03** [comment]
@ridsuteri Please assign me if valid

**Comment by ridsuteri** [comment]
@vedant-jain03 go ahead with it :)
also please insure that it's responsiveness and other features won't break

**Comment by vedant-jain03** [comment]
> @vedant-jain03 go ahead with it :)
> also please insure that it's responsiveness and other features won't break

Sure
