### ISSUE TITLE
There is many projects which has shown twice or thrice

### ISSUE THREAD

**Issue by Mrinal81** [Vishal-raj-1/Awesome-JavaScript-Projects#957]
![WhatsApp Image 2021-04-12 at 3 18 02 PM](https://user-images.githubusercontent.com/76482022/114375901-c6f6c380-9ba2-11eb-947c-cd039153c3e5.jpeg)
![WhatsApp Image 2021-04-12 at 3 18 02 PM (1)](https://user-images.githubusercontent.com/76482022/114375907-c9591d80-9ba2-11eb-9a1e-96fc20b84fe8.jpeg)
![WhatsApp Image 2021-04-12 at 3 18 02 PM (2)](https://user-images.githubusercontent.com/76482022/114375912-ca8a4a80-9ba2-11eb-8fa7-9503b69dc6a2.jpeg)
![WhatsApp Image 2021-04-12 at 3 18 02 PM (3)](https://user-images.githubusercontent.com/76482022/114375916-cb22e100-9ba2-11eb-861b-cf2eca2fb0ab.jpeg)
![WhatsApp Image 2021-04-12 at 3 18 02 PM (4)](https://user-images.githubusercontent.com/76482022/114375920-cc540e00-9ba2-11eb-867a-8d7657901605.jpeg)
![WhatsApp Image 2021-04-12 at 3 18 03 PM](https://user-images.githubusercontent.com/76482022/114375926-cceca480-9ba2-11eb-9df7-c67a8965249d.jpeg)

@ridsuteri @harshgupta20 @Vishal-raj-1  I am a GSSOC'21 participant.  I will solve all the bugs.....

Please assign me this issue......

**Comment by ridsuteri** [comment]
@Mrinal81 go ahead with it :)
also please correct the missing gifs/images issue of the projects too

**Comment by Mrinal81** [comment]
@ridsuteri ok

**Comment by Mrinal81** [comment]
@ridsuteri can you please have a look on PR #1008 ..

**Comment by ridsuteri** [comment]
any progress @Mrinal81 ?

**Comment by Mrinal81** [comment]
@ridsuteri yaa today I will made PR

**Comment by Mrinal81** [comment]
@ridsuteri Please have a look on PR #1077 .

Kindly review it...

**Comment by Mrinal81** [comment]
@ridsuteri kindly review the PR #1077 ...
