### ISSUE TITLE
Moving Dark mode toggling option to navbar

### ISSUE THREAD

**Issue by kanishka8276** [Vishal-raj-1/Awesome-JavaScript-Projects#960]
The dark mode toggling option is available only when the user has not scroll the page once it's scrolled go to top button is visible there due to which if the user wants to toggle to dark mode he will have to go back to top. It would be better of the toggle button is in the navbar on the right of the GitHub Button.
Please assign this to me.

**Comment by harshgupta20** [comment]
Since this thing is not needed and not necessary, so we have to close it.
