### ISSUE TITLE
Image Editor - New features

### ISSUE THREAD

**Issue by AnshikaAgrawal5501** [Vishal-raj-1/Awesome-JavaScript-Projects#964]
## Is your feature request related to a problem? Please describe.
No its not a problem. I want to update the **Image Editor** project.
## Describe the solution you'd like
- Currently there are only five filters present in the Image Editor project, I would like to add few more, like saturate, invert, brightness, etc.
- Also, I would like to add bootstrap to the input field and the buttons.
## Additional context
@Vishal-raj-1 @urvashi-code1255 @ridsuteri 
I am a GSSOC'21 participant, please assign this issue to me.

**Comment by AnshikaAgrawal5501** [comment]
@Vishal-raj-1  @urvashi-code1255  @ridsuteri 
Please assign me this issue.

**Comment by AnshikaAgrawal5501** [comment]
Hey @harshgupta20,
Please view this issue as well.
Thanks

**Comment by harshgupta20** [comment]
@AnshikaAgrawal5501 Go ahead with your idea:)
