### ISSUE TITLE
Enhancing project page background.

### ISSUE THREAD

**Issue by aastha621** [Vishal-raj-1/Awesome-JavaScript-Projects#966]
## Is your feature request related to a problem? Please describe.
No its not a problem. The background where the projects are listed looks very dull and simple. I am trying to improve the UI of the background of the project page.

## Describe the solution you'd like
I will make use of a css and javascript animated background which will enhance the look of the project page.

@991rajat @urvashi-code1255 pls assign the same to me!

**Comment by 991rajat** [comment]
@Vishal-raj-1 Is this required?

**Comment by harshgupta20** [comment]
@aastha621 Kindly reply within 2days or else we have to close it.

**Comment by aastha621** [comment]
I think the page looks fine without it as well. This will cause problems in dark mode. We can close this!
