### ISSUE TITLE
Pacman Game using html, css and vanilla js

### ISSUE THREAD

**Issue by SanskaarPatni** [Vishal-raj-1/Awesome-JavaScript-Projects#968]
I would love to work on a pacman game using Vanilla JS.
Kindly assign me the issue as a part of GSSOC' 21!
@Vishal-raj-1 @urvashi-code1255 
Thank you

**Comment by harshgupta20** [comment]
Any update? kindly reply within 2 days or else I have to close it.

**Comment by SanskaarPatni** [comment]
Hey, Sorry I'm caught up with something else! 
You may close it

**Comment by harshgupta20** [comment]
@Amit366 Yes. You can start working on it : )
