### ISSUE TITLE
netflix clone using vanilla javascript

### ISSUE THREAD

**Issue by Abhijay007** [Vishal-raj-1/Awesome-JavaScript-Projects#97]
Netflix clone using vanilla javascript:

![netflix](https://user-images.githubusercontent.com/64387054/107990722-0b2e7300-6ffb-11eb-9ff2-467d8f3de5f2.gif)

It is not exactly like Netflix but I use the same color contrast as the original Netflix website to depict something like that.

This project also has search functionality and also I use some APIs (for images, loading movies, rating, etc) in this project which may help a beginner to start with APIs.

**Comment by urvashi-code1255** [comment]
Great @Abhijay007 go for it!

**Comment by Abhijay007** [comment]
ok
