### ISSUE TITLE
Musical Instrument sound generator

### ISSUE THREAD

**Issue by SrishtiArya07** [Vishal-raj-1/Awesome-JavaScript-Projects#976]
## Is your feature request related to a problem? Please describe.
No its not a problem. I tried to add a musical instrument sound generator feature.
## Describe the solution you'd like
It produces different instrumental sounds like drums, harp, gong, bell, etc by using html.

## Additional context
I am a GSSOC'21 participant, please assign this issue to me.

**Comment by 991rajat** [comment]
@SrishtiArya07 Which musical instrument.
Piano and Drum are already present?

**Comment by harshgupta20** [comment]
@SrishtiArya07 Kindly reply in 2 days or else we need to close this issue.

**Comment by SrishtiArya07** [comment]
> @SrishtiArya07 Which musical instrument.
> Piano and Drum are already present?

The soundboard will have sound effects of Harp, Bass Drum, Drumroll, Chinese Gong, Military Drum, and Bugle call. I will also add rotating buttons.
