### ISSUE TITLE
Update the yoga /meditation project using html , bootstrap and vanilla js

### ISSUE THREAD

**Issue by anshika208** [Vishal-raj-1/Awesome-JavaScript-Projects#978]
##Is your feature request related to a problem? Please describe.
No its not a problem. I tried to add a meditation app

Describe the solution you'd like
It is a meditation app which will allow users to choose the time limit and type of music they want for meditating. 

Additional context
I am a GSSOC'21 participant, please assign this issue to me. @Vishal-raj-1 @harshgupta20 @urvashi-code1255 @991rajat

**Comment by anshika208** [comment]
@Vishal-raj-1 @harshgupta20 can i start working on it?

**Comment by 991rajat** [comment]
I think the project exist. Named yoga app.
Please checkout. If you want to improve upon it comment here. Will be happy to assign you.

**Comment by anshika208** [comment]
yes @991rajat i would like to improve the yoga app by adding more music options along with different time limits to do meditation and also a days wise calendar to check that the user doesnt forget to do mediation any day.

**Comment by harshgupta20** [comment]
@anshika208 Its great project, but since this project already exist we can't make another one with same concept but you can improve the existing project.

**Comment by anshika208** [comment]
yes I will improve the existing one @harshgupta20

**Comment by anshika208** [comment]
hey! @991rajat i have made a pr regarding this issue 5 days ago ... pls do have a look. thanku!!
