### ISSUE TITLE
Adding Hovering effect on GitHub button

### ISSUE THREAD

**Issue by 4kashyadav** [Vishal-raj-1/Awesome-JavaScript-Projects#982]
I will add a hovering effect on the GitHub button to make it more attractive! So please assign this to me
![Screenshot (523)](https://user-images.githubusercontent.com/78416508/114558152-03e8b600-9c88-11eb-934c-1dcd1764a9a6.png)

**Comment by harshgupta20** [comment]
Any update? kindly reply within 2 days or else I have to close it.
