### ISSUE TITLE
Removing the excessive blank space below contact us

### ISSUE THREAD

**Issue by Priyanshujha11** [Vishal-raj-1/Awesome-JavaScript-Projects#983]
Removing the excessive blank space below contact us which is making making contact us bigger and too spacious

**Comment by harshgupta20** [comment]
@Priyanshujha11 you can send the PR

**Comment by ambivert-sam** [comment]
I'm a participant of gssoc'21 want to contribute to this issue can I work on it?

**Comment by harshgupta20** [comment]
@ambivert-sam You can start working on this issue : )

**Comment by harshgupta20** [comment]
@ambivert-sam Any update? Kindly reply within 2 days or else we have to close this issue due to inactivity.

**Comment by ambivert-sam** [comment]
Would please describe to me exactly from where do I have to remove excessive blank space in contact us

**Comment by harshgupta20** [comment]
@ambivert-sam Its too late to respond because someone has already resolved this issue, you need to be active so that you can track about this project, but dont worry here are more to learn, you can find another bug, resolve it, as fast as speed of light ; ).
But till then take and good bye
