### ISSUE TITLE
Adding placeholder in contact us section

### ISSUE THREAD

**Issue by 4kashyadav** [Vishal-raj-1/Awesome-JavaScript-Projects#984]
I will add a placeholder in the contact us section and then it will look more professional and attractive.
Contact us section now!!
![Screenshot (524)](https://user-images.githubusercontent.com/78416508/114559577-8160f600-9c89-11eb-8f75-e724df6afcbc.png)
What I want to do!!
![Screenshot (525)](https://user-images.githubusercontent.com/78416508/114559652-976eb680-9c89-11eb-853c-5987a0c9c706.png)

**Comment by 4kashyadav** [comment]
@nidhivanjare please assign this to me!

**Comment by harshgupta20** [comment]
The issue has been resolved already
