### ISSUE TITLE
Adding animation in social media buttons

### ISSUE THREAD

**Issue by Priyanshujha11** [Vishal-raj-1/Awesome-JavaScript-Projects#985]
Adding animation in social media buttons to make them more attractive and catchy.

**Comment by Priyanshujha11** [comment]
![Screenshot (28)](https://user-images.githubusercontent.com/78751081/114560342-3abfcb80-9c8a-11eb-975f-edcfc166f92e.png)

**Comment by 991rajat** [comment]
What type of animation.

**Comment by Priyanshujha11** [comment]
pop up effect

**Comment by 991rajat** [comment]
@urvashi-code1255 Is this okay?

**Comment by harshgupta20** [comment]
@Priyanshujha11 Any update? kindly reply within 2 days or else I have to close it.
