### ISSUE TITLE
Removing GIFs from readme files

### ISSUE THREAD

**Issue by kmryashasvi** [Vishal-raj-1/Awesome-JavaScript-Projects#99]
As we know that,
A readme file lets you know about the repo as well as attracting contributors to contribute in it.
But, readme file included in your repo is loosing grip in both of the roles, because of the GIFs mentioned in it,
They create an informal image of your repo, which is not good,
In order to maintain formality of your readme file,
Let me remove the gifs and insert some catching sentences instead.
This is under crosswoc,

**Comment by urvashi-code1255** [comment]
Hey @kmryashasvi I don't want to remove GIFs!!

**Comment by kmryashasvi** [comment]
okay
