### ISSUE TITLE
Removing all the extra copies of projects [GSSOC'21]

### ISSUE THREAD

**Issue by anushree71199** [Vishal-raj-1/Awesome-JavaScript-Projects#994]
I will remove all those projects that are getting doubled up. I would like to remove the projects that are copy of one project. Please assign this issue to me under GSSOC'21 participation. I will be helping the website in improvising it's performance by removing all the extra projects so please assign this task to me.

**Comment by harshgupta20** [comment]
Hi @anushree71199 there are not extra copies but there some repeated code issue which has been considered already. Thanks for raising that issue but someone is already working on it.
