### ISSUE TITLE
Footer should be improvised

### ISSUE THREAD

**Issue by tanya070820** [Vishal-raj-1/Awesome-JavaScript-Projects#997]
## Is your feature request related to a problem? Please describe.
Yes as by improving footer home page will look more attractive as  we will add some details also in it like name of mentor who is handling it and many more.
Please assign this issue to me @Vishal-raj-1

**Comment by harshgupta20** [comment]
@tanya070820 You can send the PR for it.

**Comment by tanya070820** [comment]
@tanya070820 ok Sir

**Comment by harshgupta20** [comment]
@tanya070820 Since its been a month and we haven't got any update from your side, kindly reply within 2 days or else I have to close it.

**Comment by tanya070820** [comment]
@harshgupta20 sir I have already created its pr

**Comment by Ankita297** [comment]
Can i work on this  @ridsuteri @harshgupta20 @991rajat @urvashi-code1255 ?

**Comment by harshgupta20** [comment]
@tanya070820 Kindly link that PR with this issue.

**Comment by Ankita297** [comment]
Can i work on this now @harshgupta20 @ridsuteri ?

**Comment by harshgupta20** [comment]
@Ankita297 I have already assigned you the task of other issue, and since the @tanya070820 has already made PR so if her PR got closed then after that it would allowed to you to work on it : )

**Comment by harshgupta20** [comment]
@tanya070820 kindly link your PR with this issue, if you didn't do that then it could cause the point error in gssoc for you, since its a rule that participants should have to link PR with issue so that we can track their point. 
So Link you PR with this Fast.
